### ISSUE TITLE
Hardcoded Session Secret

### ISSUE THREAD

**Issue by TimWolla** [datarhei/restreamer#1]
I noticed that you use the example session secret of `express-session`: https://github.com/datarhei/restreamer/blob/5252445ec9c0f0383fcc7bd5cbb3b4b316a6d860/src/webserver/app.js#L44

You should generate a random secret during the first run, otherwise it is possible to tamper with the session information.

**Comment by christophjohannsdotter** [comment]
Hi,

i created a branch with the modification you suggested: https://github.com/datarhei/restreamer/commit/a05e2bf1636ce41e4d98361b8251ac51a906b368

Would you solve it the same way?

Chris

**Comment by TimWolla** [comment]
> Would you solve it the same way?

This will destroy every session on a server restart. Depends on whether you want that. Apart from that it looks fine to me (but I am not entirely sure whether 512 bit is too much, you should be fine with 128 bit, but don't quote me on that).

**Comment by TimWolla** [comment]
Also: The issue ID in your commit message is wrong.

**Comment by christophjohannsdotter** [comment]
yes just noticed that :smiley_cat: 
thanks for your help.
