### ISSUE TITLE
RTSP > RTMP

### ISSUE THREAD

**Issue by unmanagedtn** [datarhei/restreamer#10]
RTSP > RTMP to youtube is not working is there anyway to check the format, youtube has strict requirements.

**Comment by jstabenow** [comment]
We need more informations about your setup:
* Runs the optional target stable (is green)
* What's your image resolution, bitrate and fps (the UI will displays the fps and the bandwidth if the stream is running)
* what says Youtube?

Most of our test cameras have 720p and 500-800 Kb/s and this works without problems.
