### ISSUE TITLE
Maximum simultaneous viewers limit

### ISSUE THREAD

**Issue by costasjf** [datarhei/restreamer#101]
In documentation it states that the number of simultaneous viewers is limited. I can't find more details about this limit. How many users can simultaneously watch a stream with no external stream service? Is this limit related to my hardware capacity?

**Comment by ioppermann** [comment]
The number of simultaneous viewers is purely limited by your available upload bandwidth. The more users watch the stream, the more data is sent from your Restreamer to the users. To have a rough estimate where the limit is you can divide your upload bandwidth with the bitrate of your stream (make sure that you use the same units, i.e. bytes vs. bits).

**Comment by costasjf** [comment]
Thanks for your reply @ioppermann! I have another question, when this users limit is achieved and a new one tries to watch the stream, what happens? Are all the users affected (lost connection, lower quality video, freezing...) or just the new ones can't watch the stream? Thanks again! :-)

**Comment by ioppermann** [comment]
In this case all users would be affected because they all share your upload bandwidth.

**Comment by jstabenow** [comment]
Hey @costasjf,
Your problem should be solved with the latest release:

- Current viewers and bandwidths
- Bandwidth limitation
- Viewer/Session limitation

More informations:
- https://docs.datarhei.com/restreamer/knowledge-base/manual/system-settings/network#bandwidth-control
- https://demo.datarhei.com/api/swagger/index.html#/default/session-3-current
- https://demo.datarhei.com/api/swagger/index.html#/default/restream-3-get-all

 Check it out and post if you have any questions.
