### ISSUE TITLE
rpi zero w

### ISSUE THREAD

**Issue by federicobalm** [datarhei/restreamer#102]
Is it possible to run reatreamer on an rpi zero w, and use raspicam?

**Comment by ioppermann** [comment]
Theoretically it should be possible, however I didn't try it myself. The Raspberry Pi Zero W has camera support and allows encoding the video to h.264 on its GPU. This stream is then used by the Restreamer.

Once you made sure, that the connected camera is working properly (e.g. by taking snapshots with the `raspivid` tool), you can follow these instructions: https://datarhei.github.io/restreamer/docs/guides-raspicam.html

**Comment by federicobalm** [comment]
I followed all the steps as I did with rpi3. but after installing restreamer in docker the container does not appear. Try it on many occasions and the same thing keeps happening.

in rpi3 I can do it perfectly, but in rpi zero I can not.

some help? someone who could?

**Comment by federicobalm** [comment]
this is the problem https://www.youtube.com/watch?v=YJZKNbv_1YY

throws the error: 
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

some help?

**Comment by federicobalm** [comment]
is it possible that it is ARMv6 the RPI Zero W?

I see that the architecture for restreamer must be ARMV7l.

Is it possible that this is the drawback?

**Comment by federicobalm** [comment]
I tried to install using the following code:

docker run -d --restart always \
      --name restreamer \
      -e "RS_USERNAME = admin" -e "RS_PASSWORD = datarhei" \
      -p 8080: 8080 -v / mnt / restreamer / db: / restreamer / db \
      --tmpfs / tmp / hls \
      datarhei / restreamer-armv6l: latest

but the error remains the same ..


I also try with the distribution of dietpi. but do not run restreamer in this distribution.

apparently the problem is with docker.

Is there any way to install restreamer without using docker?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.
