### ISSUE TITLE
Pre requirement

### ISSUE THREAD

**Issue by fullstackdev-star** [datarhei/restreamer#103]
Hello, how are you?
I installed restreamer on my ubuntu 18.04
I think installed and running on port 8080.
but I can not see the page on the url.
Please advise me.
![Screenshot_1](https://user-images.githubusercontent.com/13324891/60306573-3d491800-9973-11e9-97e1-3bb8944b902e.png)
![Screenshot_2](https://user-images.githubusercontent.com/13324891/60306574-3de1ae80-9973-11e9-95a8-04fdc1a9747a.png)

**Comment by ioppermann** [comment]
Do you try to access it via the IPv6 address of your ubuntu machine?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
