### ISSUE TITLE
Auto restart stream so that Youtube will archive video

### ISSUE THREAD

**Issue by Scotty775** [datarhei/restreamer#105]
Hi,
I'm using Restreamer to stream a webcam to Youtube using a raspberry Pi.

I would like Youtube to archive the stream into hourly videos.
I can stop and restart the stream every hour using the Restreamer GUI, and this triggers Youtube to archive the video as i want,

Is there a way to configure Restreamer to restart the stream automatically?

Or could somebody help me with a script that would have the same effect?

Thanks, Scott

**Comment by ioppermann** [comment]
Hi Scott

A similar feature where it will be possible to start/stop the restreaming via the API was already requested. As soon as this will be available, it will be possible to call it by a script. Alternatively I can think of some kind of scheduler option in the UI.

**Comment by Scotty775** [comment]
Hi, thanks for replying. 
I will have a look at scheduling the UI, and I'll keep an eye on restreamer updates.

Thanks, Scott

**Comment by greycoding** [comment]
Hello,

I also need the possibility to start and stop the restreamer via the API.
Is this now possible?

**Comment by ioppermann** [comment]
@greycoding This will be possible in the upcoming version of Restreamer.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
