### ISSUE TITLE
Security vulnerability: Stream token exposed via API

### ISSUE THREAD

**Issue by philipptrenz** [datarhei/restreamer#107]
**Setup:** 
- Restreamer as cloud instance
- Open port 1935, secured via token
- Webcam behind NAT, streaming via RTMP to cloud instance

**Vulnerability:** 

API endpoint `v1/states` exposes the token in cleartext in case of an error within the `message` value:

```json
{
    "repeat_to_local_nginx": {
        "type": "error",
        "message": "rtmp://localhost/live/external.stream?token=XXXXXXX: Operation not permitted"
    },
    "repeat_to_optional_output": {
        "type": "disconnected"
    }
}
```

Even if it is the internal RTMP streaming url of the cloud instance, the token is the same as of the publicly streaming url.

**Comment by ioppermann** [comment]
@philipptrenz Thanks for the hint. I will fix this ASAP.

**Comment by ioppermann** [comment]
@philipptrenz This has been fixed in b784b8a4d99f5f6d24ef426a9136457d88c9a207. In case you want to use it now, you have to build your own Docker image from the sources.

**Comment by philipptrenz** [comment]
Thanks for the quick fix! When do you plan to push it to Docker Hub?

**Comment by jstabenow** [comment]
Jobs done ;-)
