### ISSUE TITLE
integrate my system to Restream dynamically 

### ISSUE THREAD

**Issue by ahmad-alansari** [datarhei/restreamer#109]
how i can use Restreamer pragmatically ?

**Comment by ioppermann** [comment]
@ahmad-alansari Do you mean programmatic? The Restreamer has an API (https://datarhei.github.io/restreamer/docs/references-http-api.html), however it only allows you to read properties, but not to control the Restreamer. This is planned and will be available in the future.

**Comment by ahmad-alansari** [comment]
1. we are getting bytes from MDVR devices where we want to encode their data, can we use restreamer in this scenario and distinguish between their streams
2. If so, will we use single RTSP for all of them or there is a way for dynamic RTSP?

**Comment by ioppermann** [comment]
One Restreamer instance can only pull one stream at a time. If you want to pull several streams, then create a new Restreamer instance for each stream.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by jstabenow** [comment]
Hey @ahmad-alansari 
This ticket is closed due to inactivity. If you still have questions, please open a new issue or reopen this case.
Thanks.
