### ISSUE TITLE
Question: In which interval gets the /images/live.jpg updated?

### ISSUE THREAD

**Issue by philipptrenz** [datarhei/restreamer#110]
Hey,

I'm about to build a digital image frame based on a Raspberry Pi Zero to display a live feed streamed via Restreamer. As the Pi Zero is a bit underpowered to run the HLS stream in Chromium, I thought about displaying the images of the `/images/live.jpg` endpoint. Therefore I'd like to know the frequency, in which the image gets updated. 

Thanks!

**Comment by jellykells** [comment]
The interval is configurable. https://datarhei.github.io/restreamer/docs/references-environment-vars.html#rs_snapshot_interval

**Comment by philipptrenz** [comment]
awesome!
