### ISSUE TITLE
Feature to add Image Overlay

### ISSUE THREAD

**Issue by ssamjh** [datarhei/restreamer#113]
It would be cool to be able to embed an image in the stream, example below.
It was created in OBS, but this shouldn't be too hard to implement in the ffmpeg process.

![Sponsor Example](https://i.imgur.com/1XBOhzs.png)

**Comment by matigumma** [comment]
Hello ssamjh!
i had test this recently and works perfect:
ffmpeg -y -rtsp_transport tcp -i inputVideo -i /tmp/hls/Logo.png \
-filter_complex "[0:v][1:v] overlay=15:15" -c:v libx264 -an -f flv outputVideoWithLogo

i take it from here: https://superuser.com/a/683696

**Comment by ioppermann** [comment]
This is a feature we're currently working on. In a first step, you'll be able to add the logo to the player (this doen't require re-encoding the stream). As @matigumma suggested, this would encode the logo into the stream, i.e. it requires re-encoding of the stream.

**Comment by ssamjh** [comment]
I wonder if a better approach to this would be allowing people to specify their own ffmpeg commands, while still using restreamer to detect drops and handle stream re-starting if the connection is lost.

**Comment by advantix78** [comment]
Is it possible to add a video in pre roll in css?

**Comment by ioppermann** [comment]
@advantix78 If you want to display some pre-roll (or ads), you can use any player that supports this and HLS streaming instead of the player that comes with Restreamer. The URL of the stream is `http://[address and port of your restreamer]/hls/live.stream.m3u8` (or `https://` if configured accordingly) that you need to add to the player's playlist.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
