### ISSUE TITLE
RTMP only way to watch or can you use a http HLS?

### ISSUE THREAD

**Issue by icepicknz** [datarhei/restreamer#118]
Hi,

Wanting to stream to my TV which requires something like http://192.168.33.225:2236 or another example http://192.168.33.3:8001/1:0:19:48D:8:A9:6400000:0:0:0: but won't accept a RTMP:// address.

I can get it working by running VLC on 'stream' mode, leaving the video and audio in original format but with encapsulation MPEG-TS

is there any way to get a HLS without RTMP and rather using the NGIX to deliver it somehow?

**Comment by icepicknz** [comment]
Found the path 8080/hls/live.stream.m3u8 however doesn't seem to work

**Comment by br0kenlink** [comment]
What about http://192.168.33.225:2236/player.html

**Comment by ioppermann** [comment]
@icepicknz What brand and model is your TV and what kind of protocol is it expecting on that port? Restreamer currently only supports pushing a stream via RTMP. Which settings to you use in VLC?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
