### ISSUE TITLE
RTSP to WebRTC

### ISSUE THREAD

**Issue by OmarAttia** [datarhei/restreamer#119]
To beat shinobi, webrtc implantation would be a knockout!

**Comment by ioppermann** [comment]
@OmarAttia Thanks for the suggestion.

**Comment by svenerbeck** [comment]
@OmarAttia 
This function is now an official feature request. WebRTC.
You find the list here: https://github.com/datarhei/restreamer/discussions/345

cheerio
Sven

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
