### ISSUE TITLE
Error with source recompiling

### ISSUE THREAD

**Issue by advantix78** [datarhei/restreamer#120]
When i try to recompile restreamer from the source code i get this error, can anyone help me to fix? i found a possible solution on web, i need a 64 bit device? beacuse i'm on 32-bit raspberry
![Immagine](https://user-images.githubusercontent.com/40419553/65820501-4a9fc800-e22a-11e9-9b98-66438d0fbed2.png)

**Comment by ioppermann** [comment]
If you are using a 32-bit Pi, then you should build the Docker image with one of the 32bit Dockerfiles: `Dockerfile-arm32v6` or `Dockerfile-arm32v7`. Please try first the `Dockerfile-arm32v7`. This for newe the Pi 3 series.

The command would look like: `docker build -t restreamer -f Dockerfile-arm32v7 .`

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
