### ISSUE TITLE
Ie/Edge not working

### ISSUE THREAD

**Issue by kosa7** [datarhei/restreamer#123]
Hello,
We're having trouble playing in Edge and IE.
when I try to access LAN from 1 of 10 attempts to start stream. in other cases only 3 dots in progress.
IE does not work at all, only white screen.
access from the public site for nat will never run the video.
Firefox, Chrome, Opera without a problem.
I tried docker with both native iptables and routed, on debian, centos, windows hyper-v, always behaves the same way.
Any insights on how to make it work in Edge?
eventually is there any instructions how to start restreamer native directly to hw instead of in the docker? I tried myself according to the configuration files but failed.
Thanks

**Comment by ioppermann** [comment]
The playback should work in Edge and IE10+. I will have a look into this.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
