### ISSUE TITLE
Lets Encrypt?

### ISSUE THREAD

**Issue by koljasagorski** [datarhei/restreamer#125]
Hey how can I add a subdomain with lets encrypt? Need help pleassseee!!

**Comment by matigumma** [comment]
Hello i used Caddyserver... i think you can use traefik (https://github.com/containous/traefik) too..

link
https://hub.docker.com/r/abiosoft/caddy/ 

caddyfile its simple:

subdomain.mydomain.com
tls user@host.com
proxy / path/to/your/service { 
  transparent
}

remmember to point your subdomain dns to the Caddyserver host

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
