### ISSUE TITLE
Your stream wasn't accessible.

### ISSUE THREAD

**Issue by LunarstarPony** [datarhei/restreamer#126]
![Screenshot (30)](https://user-images.githubusercontent.com/36251959/70283062-cd309f00-17fa-11ea-85a4-80cd2b4ae3ac.png)

It shows up Streaming is successfully initiated.
And then shows up Your stream wasn't accessible.
Error: ffmpeg exited with code 1:

**Comment by melbguy** [comment]
I have the same issue

**Comment by 11wickets** [comment]
same here
