### ISSUE TITLE
Streaming problem with Dahua IP camera

### ISSUE THREAD

**Issue by Saulianas** [datarhei/restreamer#13]
I have an issue wit IP/Network Camera, model: DH-SD59230T-HN

Restreamer (on raspberry) doesn't accept given RTSP address.

Tested on VLC,  all links below, works well:
rtsp://rtsp:rtsp@v.raido.lt:554

rtsp://rtsp:rtsp@v.raido.lt:554/cam/realmonitor?channel=1&subtype=0
rtsp://rtsp:rtsp@v.raido.lt:554/cam/realmonitor?channel=1&subtype=1
rtsp://rtsp:rtsp@v.raido.lt:554/cam/realmonitor?channel=1&subtype=2

The camera  H.264 supported. 

Maybe you have the clue what can be the problem?

Thank's

**Comment by svenerbeck** [comment]
Hello Saulianas
Better late than never!
Testing hardware is difficult, as we usually do not have it on site. We promise you better.
Cheerio
Sven
