### ISSUE TITLE
nal_unit_type

### ISSUE THREAD

**Issue by a93h** [datarhei/restreamer#131]
ffprobe started on 2019-12-26 at 23:39:59
Report written to "/restreamer/src/webserver/public/debug/ffprobe-20191226-233959.log"
Command line:
/usr/local/bin/ffprobe -show_streams -show_format rtmp://localhost/live/external.stream
ffprobe version 4.1.3 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --bindir=/usr/local//bin --extra-cflags=-I/usr/local//include --extra-ldflags=-L/usr/local//lib --prefix=/usr/local/ --enable-nonfree --enable-gpl --enable-version3 --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-openssl --enable-postproc --enable-small --enable-static --disable-debug --disable-doc --disable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[NULL @ 0x55c66fcfca40] Opening 'rtmp://localhost/live/external.stream' for reading
[rtmp @ 0x55c66fcfd380] No default whitelist set
[tcp @ 0x55c66fcfd880] No default whitelist set
[tcp @ 0x55c66fcfd880] Original list of addresses:
[tcp @ 0x55c66fcfd880] Address 127.0.0.1 port 1935
[tcp @ 0x55c66fcfd880] Address ::1 port 1935
[tcp @ 0x55c66fcfd880] Interleaved list of addresses:
[tcp @ 0x55c66fcfd880] Address 127.0.0.1 port 1935
[tcp @ 0x55c66fcfd880] Address ::1 port 1935
[tcp @ 0x55c66fcfd880] Starting connection attempt to 127.0.0.1 port 1935
[tcp @ 0x55c66fcfd880] Successfully connected to 127.0.0.1 port 1935
[rtmp @ 0x55c66fcfd380] Handshaking...
[rtmp @ 0x55c66fcfd380] Type answer 3
[rtmp @ 0x55c66fcfd380] Server version 13.14.10.13
[rtmp @ 0x55c66fcfd380] Proto = rtmp, path = /live/external.stream, app = live, fname = external.stream
[rtmp @ 0x55c66fcfd380] Window acknowledgement size = 5000000
[rtmp @ 0x55c66fcfd380] Max sent, unacked = 5000000
[rtmp @ 0x55c66fcfd380] New incoming chunk size = 4000
[rtmp @ 0x55c66fcfd380] Creating stream...
[rtmp @ 0x55c66fcfd380] Sending play command for 'external.stream'
[flv @ 0x55c66fcfca40] Format flv probed with size=2048 and score=100
[flv @ 0x55c66fcfca40] Before avformat_find_stream_info() pos: 13 bytes read:2439 seeks:0 nb_streams:0
[flv @ 0x55c66fcfca40] Unknown type |RtmpSampleAccess
[NULL @ 0x55c66fd2b400] nal_unit_type: 7(SPS), nal_ref_idc: 3
[NULL @ 0x55c66fd2b400] nal_unit_type: 8(PPS), nal_ref_idc: 3
[NULL @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] nal_unit_type: 8(PPS), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 5(IDR), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] Format yuv420p chosen by get_format().
[h264 @ 0x55c66fd2b400] Reinit context to 1280x720, pix_fmt: yuv420p
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] Increasing reorder buffer to 1
[h264 @ 0x55c66fd2b400] no picture
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] nal_unit_type: 6(SEI), nal_ref_idc: 0
[h264 @ 0x55c66fd2b400] nal_unit_type: 1(Coded slice of a non-IDR picture), nal_ref_idc: 3
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[h264 @ 0x55c66fd2b400] ct_type:0 pic_struct:0
[flv @ 0x55c66fcfca40] All info found
[flv @ 0x55c66fcfca40] rfps: 60.000000 0.000260
[flv @ 0x55c66fcfca40] rfps: 60.000000 0.000260
[flv @ 0x55c66fcfca40] rfps: 120.000000 0.001040
[flv @ 0x55c66fcfca40] rfps: 120.000000 0.001040
[flv @ 0x55c66fcfca40] rfps: 240.000000 0.004160
[flv @ 0x55c66fcfca40] rfps: 240.000000 0.004160
[flv @ 0x55c66fcfca40] rfps: 59.940060 0.000405
[flv @ 0x55c66fcfca40] rfps: 59.940060 0.000405
[flv @ 0x55c66fcfca40] After avformat_find_stream_info() pos: 548237 bytes read:548237 seeks:0 frames:83
Input #0, flv, from 'rtmp://localhost/live/external.stream':
  Metadata:
    Server          : NGINX RTMP (github.com/arut/nginx-rtmp-module)
    displayWidth    : 1280
    displayHeight   : 720
    fps             : 60
    profile         :
    level           :
  Duration: 00:00:00.00, start: 158.027000, bitrate: N/A
    Stream #0:0, 42, 1/1000: Audio: aac, 44100 Hz, stereo, fltp, 163 kb/s
    Stream #0:1, 41, 1/1000: Video: h264, yuv420p(tv, bt470bg/bt709/bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 6144 kb/s, 60 fps, 60 tbr, 1k tbn, 120 tbc
[h264 @ 0x55c66fd8e800] nal_unit_type: 7(SPS), nal_ref_idc: 3
[h264 @ 0x55c66fd8e800] nal_unit_type: 8(PPS), nal_ref_idc: 3
[AVIOContext @ 0x55c66fcff280] Statistics: 548237 bytes read, 0 seeks
[rtmp @ 0x55c66fcfd380] Deleting stream...

**Comment by a93h** [comment]
I believe this issue is to do with OBS not emitting the SPS PPS frequently enough.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
