### ISSUE TITLE
Secure HLS Token?

### ISSUE THREAD

**Issue by inat-tv** [datarhei/restreamer#133]
Hello. Can protection markers be added to publications? If that happens, it'll be beautiful.

For example

`<?php

$url = 'http://IP-ADDRESS'; // restreamer address
$key = 'SECRETKEY'; // key from conf file. KEEP IT IN SECRET
$lifetime = 3600 * 3; // 3 hours after link will be invalid

$stream = $_GET['stream']; // this script get streamname from a query string (script.php?stream=bbc)

$ipaddr = $_SERVER['REMOTE_ADDR'];
$desync = 300; // allowed time desync between restreamer and hosting servers in seconds
$starttime = time() - $desync;
$endtime = $starttime + $lifetime;
$salt = bin2hex(openssl_random_pseudo_bytes(16));

$hashsrt = $stream.$ipaddr.$starttime.$endtime.$key.$salt;
$hash = sha1($hashsrt);

$token = $hash.'-'.$salt.'-'.$endtime.'-'.$starttime;
$link = $url.'/'.$stream.'/embed.html?token='.$token;
$embed = '<iframe allowfullscreen style="width:640px; height:480px;" src="'.$link.'"></iframe>';

echo $embed;
?>`

**Comment by ioppermann** [comment]
@inat-tv This is a vey custom implementation of such a token. One solution would be to proxy the requests to the HLS stream through e.g. nginx with LUA (https://github.com/openresty/lua-nginx-module) where you can check the validity of the token in an `access_by_lua_block { ... }`.

**Comment by inat-tv** [comment]
> @inat-tv This is a vey custom implementation of such a token. One solution would be to proxy the requests to the HLS stream through e.g. nginx with LUA (https://github.com/openresty/lua-nginx-module) where you can check the validity of the token in an `access_by_lua_block { ... }`.

**Comment by inat-tv** [comment]
> @inat-tv This is a vey custom implementation of such a token. One solution would be to proxy the requests to the HLS stream through e.g. nginx with LUA (https://github.com/openresty/lua-nginx-module) where you can check the validity of the token in an `access_by_lua_block { ... }`.

Such a module already exists by default. I think it would be better to integrate this into your project.
http://nginx.org/en/docs/http/ngx_http_secure_link_module.html
