### ISSUE TITLE
Raspicam  rotate  video

### ISSUE THREAD

**Issue by rychmar** [datarhei/restreamer#14]
Raspberry Pi 2
How do  rotate an image from the camera ?
-e "RS_RASPICAM_ROTATE=180" does not work!

My command line:
`docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=xxx" -e "RESTREAMER_PASSWORD=xxx" -e "MODE=RASPICAM" -e "RS_RASPICAM_WIDTH=1280" -e "RS_RASPICAM_HEIGHT=720" -e "RS_RASPICAM_FPS=25" -e "RS_RASPICAM_BITRATE=1500000" -e "RS_RASPICAM_ROT=180" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db -v /opt/vc:/opt/vc --privileged datarhei/restreamer-armv7l:latest`

Greetings from Poland

**Comment by mim-Armand** [comment]
Hey rychmar,
Where did you get the "`RS_RASPICAM_ROT`" from? it doesn't exist in the source code as I see..

,m
