### ISSUE TITLE
Custom bitrate for encoding

### ISSUE THREAD

**Issue by ariselseng** [datarhei/restreamer#141]
I want a bitrate for the video that is not in the <select> in the web interface. Is there a way to specify one?

**Comment by ioppermann** [comment]
@ariselseng In order to add more options for the bitrate you can edit the HTML for the UI (see https://github.com/datarhei/restreamer/blob/master/src/webserver/public/views/main.html#L79) and then building your own Docker image.

**Comment by ioppermann** [comment]
Or, a bit more hacky, use the inspector of the browser in order to edit the option values in the `<select>` tag. However, this you have to do every time you reload the Restreamer UI.

**Comment by ariselseng** [comment]
@ioppermann Thanks!
