### ISSUE TITLE
Value 5000.000000 for parameter 'timeout' out of range

### ISSUE THREAD

**Issue by tritone11** [datarhei/restreamer#142]
While trying to stream to a HLS output, it couldn't start the stream.
Executing the ffmpeg standalone, this error came out on the timeout value. I set 2000 and it worked correctly after it.

```
Value 5000.000000 for parameter 'timeout' out of range  
(1e06 / 2147.48)
Error setting option timeout to value 5000.  
Could not write header for output file #0 (incorrect codec parameters ?): Numerical result out of range```

**Comment by tritone11** [comment]
https://github.com/datarhei/restreamer/pull/143

**Comment by ioppermann** [comment]
@tritone11 Thanks for pointing this out. This is indeed a bug which will be fixed soon.
