### ISSUE TITLE
Master M3U8

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer#146]
Any plans to automatically restream all bitrates included in a master m3u8?

**Comment by ioppermann** [comment]
We didn't look into this, yet.

**Comment by jstabenow** [comment]
Hey @badincite 
The `master.m3u8` is now available. However, without multibitrate support. This is a big race, but is on our roadmap.

**Comment by svenerbeck** [comment]
💙💚🧡💜 Help datarhei with a rating or review on Google. #feelsgoodtobeloved [https://t.co/ZT9pRX1gG7](https://t.co/ZT9pRX1gG7)
