### ISSUE TITLE
how to set defaults

### ISSUE THREAD

**Issue by matigumma** [datarhei/restreamer#147]
is possible to set a default true External RTMP-Streaming-transmision ? 
ty

**Comment by ioppermann** [comment]
No, currently not. But the logic when to default it to `true` could be improved, i.e. to set it to `true` if the input field for the external address is not empty. Currently Restreamer sets it only to `true` if it is connected to the external address.

**Comment by jstabenow** [comment]
The Release 2 includes many additional functions and keeps the processes running.
Have fun with it 👍
