### ISSUE TITLE
Cannnot access web interface

### ISSUE THREAD

**Issue by H4kt** [datarhei/restreamer#149]
Contents of web page: https://pastebin.com/1uCg4r7x
Errors reported: https://pastebin.com/bFzRgfpN

Everything was set up correctly and errors only appear when I attempt to open web interface.

**Comment by scottgrobinson** [comment]
Can you provide docker-compose or docker command you are using to run this instance please.

**Comment by H4kt** [comment]
I am actually just running the image from docker hub
