### ISSUE TITLE
login problem in a VPS

### ISSUE THREAD

**Issue by maxlinux2000** [datarhei/restreamer#15]
HI,
I have installed resteamer in a ubuntu 14.04 in a vps with public IP, but I can't login to the resteramer web interface, with "admin/datarhei"

I have just installed  the v0.1.0-rc.7.1

 any tips?

**Comment by mim-Armand** [comment]
I hope it's not too late but it could be because you have set those (and change them from their default values) when you ran the docker start script, if you notice there are two options:
```bash
-e "RESTREAMER_USERNAME=<NewUserName>" -e "RESTREAMER_PASSWORD=<NewPassword>"
```
,m
