### ISSUE TITLE
Restreamer Poor sound quality on RTMP

### ISSUE THREAD

**Issue by arni7** [datarhei/restreamer#153]
Good day.
I have recently been a raspberry pi 3 b + user. I really liked your program, which I installed as described at https://datarhei.github.io/restreamer/
My problem is that I type "RTSP video source" and everything is fine.
And when I stream to "the optimal source for Youtube RTMP, the sound quality is very bad. Please help. Regards, Oscar

I have exactly the same problem, it seems to me that the reason is the camera stream I have Dahua and you Oscar?

Interestingly, as the material will be recorded by youtube, then when playing the sound is correct

Arek

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
