### ISSUE TITLE
Server returned 5XX Server Error reply

### ISSUE THREAD

**Issue by wojtekca** [datarhei/restreamer#157]
I have error:
Your stream wasn't accessible.
rtsp://admin:password@193.xxx.xxx.xxx:554/media/video1: Server returned 5XX Server Error reply 

On VLC this link works. Where is the problem?

**Comment by ioppermann** [comment]
@wojtekca What is the brand and model of the camera? It looks like the camera was having trouble if ffmpeg tries to connect to it.

**Comment by wojtekca** [comment]
The IP camera is BCS-P-444RSA. In ffmpeg works fine.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
