### ISSUE TITLE
ip cam with rtsp url not start streaming

### ISSUE THREAD

**Issue by sminodonte** [datarhei/restreamer#158]
I use an ip cam with a rtsp  url:
rtsp://user:password@IP:554/onvif1
I don't select anything and I click on start button. 

Rrastremer view this:
"Streaming process is initiating. Please wait..."

but the streaming never started

**Comment by ioppermann** [comment]
@sminodonte What brand and model is your camera? Did you tick the TCP transport checkbox?

**Comment by cultura4** [comment]
Model: sricam SP012 
TCP transport: YES

**Comment by sminodonte** [comment]
Model: sricam SP012
TCP transport: YES

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
