### ISSUE TITLE
Start/Stop with API call for on-demand integration with home-assistant

### ISSUE THREAD

**Issue by ElleshaHackett** [datarhei/restreamer#159]
In addition to this issue: https://github.com/datarhei/restreamer/issues/98

I would love to start/stop the stream using the Restreamer API and the default or last used settings. The encoding is quite resource heavy for an older machine and I want to intergrate it with Home-Assistant.io. If works perfectly fine, just I don't want it to be enabled constantly. In home-assistant I would be able to make a switch to turn the camera on or off and then show the livestream. Can we introduce a simple "start" / "stop" command to the restreamer API?

*I have restreamer instance constantly running in a Docker container so the API should be available all the time just not encoding/streaming*.

**Comment by bschuele** [comment]
This would be really great. I want to use the restreamer for forwarding a webcam stream of my 3d printer to be able to use octoprint from the internet with the stream. But I do not want to have the streaming enabled all the time.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
