### ISSUE TITLE
ip camera streming quality

### ISSUE THREAD

**Issue by shimin** [datarhei/restreamer#16]
Hey! Thanks for the really good job, it seems you offer the best solution to display rtsp stream with any browser for today. But I have an issue)
I have access to my h.264 rtsp stream (rtsp://<ip>:554/play.sdp) from any browser but it has delay more than 1 minute and pretty much artifacts when something changes in camera view.
My CPU usage is about 1-1.5%.
When I tried to do the same with ffmpeg and ffserver (ffmpeg -i rtsp://<ip>:554/play.sdp -map 0 http://localhost:8090/feed.ffm) I had CPU usage about 30-40 percents and less time delay but plenty of errors like "RTP: missed xx packets" and same artifacts when movement in front of camera.
But if I use vlc to access rtsp stream directly without changing anything with camera connection I get perfect stream quality.
So could you please point me what to adjust to achive better stream quality (may be by increasing CPU quota somehow).
I use rspi3 with raspbian and docker 1.11.1
p.s. --cpu-quota constraint produces warning "Your kernel does not support CPU cfs quota. Quota discarded."

**Comment by svenerbeck** [comment]
Hello shimin 
the reastreamer does not change the stream.
You have to touch the input. If you have a network camera, change the settings. 
Play with the settings:
FPS 18 - 30
iFrame/GOV/GOP: 24-61
Video resolution 
Often you will find a compression setting in the camera. Turn on those knobs.

Good luch
Sven
