### ISSUE TITLE
Feature request: indication of number of simultaneous viewers

### ISSUE THREAD

**Issue by JulienLB** [datarhei/restreamer#163]
Hello,

thank you first for your great work.
To evaluate the load on the server running the restreamer container, and the interest for the stream itself, I think it would be nice to be able to know the number of simultaneous viewers for a given restreamer instance.

Would it be possible to implement such a feature?

**Comment by mike9011** [comment]
This has been requested before: https://github.com/datarhei/restreamer/issues/100
