### ISSUE TITLE
hls: force fragment split error after [x] hours

### ISSUE THREAD

**Issue by mike9011** [datarhei/restreamer#164]
Hi,

First of all; thanks for this great tool!
I'm having some issues with my RTSP camera/stream. After a couple of hours I'm getting a lot of errors:

`[04-05-2020 21:26:22.721] [ERROR] [                 NGINX] 41#0: *46 hls: force fragment split: 466.155 sec, , client: 127.0.0.1, server: 0.0.0.0:1935`

I need to restart the stream to temporarily resolve the issue.

System: Intel Nuc
Platform: Ubuntu Server
CPU Usage during stream: ~25%

**Comment by mike9011** [comment]
Issue seems to be resolved after downgrading to `Restreamer v0.6.0`. 
I don't see major changes from 0.6.0 to 0.6.4 that could cause these issue?

**Comment by ioppermann** [comment]
@mike9011 Can you reproduce this error and what brand is your camera? This usually happens when the stream gets out of sync or the camera might issue some weird timestamps.

**Comment by mike9011** [comment]
@ioppermann Yes, every time I start the stream it works for ~20-40 minutes, then the issue starts. I'm running the same RTSP stream in Home Assistant without any issues.. or is this caused by the conversion from RTSP to RTMP? 

It's a bird box camera; green-backyard.com

**Comment by mike9011** [comment]
Issue seems to be resolved by unchecking TCP. Strange, because it's running fine with TCP enabled with ffmpeg on my other server. 

Thanks again!

**Comment by mike9011** [comment]
Issue back again after 8 > hours.. have no clue..

**Comment by ioppermann** [comment]
@mike9011 It might be a problem with the nginx-rtmp module that is receiving the RTMP stream. What is the brand of your camera and what are the encoding settings, e.g. video codec options, audio codec options, and do copy or encode the audio/video on the Restreamer.

**Comment by therumbler** [comment]
i'm also seeing this issue . I'm streaming from a Wyze cam.

H264 MPEG-4 AVC (part 10)
Resolution 1920x1080
Frame Rate: 20
Format: Planar 4:2:0 YUV

**Comment by ioppermann** [comment]
This really looks like, there's some problem with the nginx rtmp module. In an upcoming version of Restreamer, we're going to move away from nginx. This will probably solve this issue.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
