### ISSUE TITLE
Troubles with multirestream

### ISSUE THREAD

**Issue by PetrCZE** [datarhei/restreamer#165]
Hello,
I have some troubles.
Can I run more than one restream? If I use this tut https://datarhei.github.io/restreamer/docs/guides-multiple-restreamer.html I get everytime connection refused.

Please help me

Kind regards

**Comment by ioppermann** [comment]
@PetrCZE Please make sure that you expose the port 8080 from inside the container to different ports outside of the container (e.g. 8091 to 8094 as in the docs). If you want to connect to one of these Restreamer you have to use the port number as seen from outside of the container, e.g. http://localhost:8091/ to http://localhost:8094/

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
