### ISSUE TITLE
Restreaming video files doesn't work as supposed

### ISSUE THREAD

**Issue by StevoLopata** [datarhei/restreamer#166]
Hi!

When I try to restream a video file from online HLS link (copy/copy options on encoder), it doesn't restream it at it's native framerate, but instead restreams 1500FPS in one second, like it was simply locally encoding the file. That results in a video that skips each frame 5 minutes forward. Is there any way to edit the ffmpeg configuration to add -re option (native frame rate)?

Any response appreciated

**Comment by ioppermann** [comment]
@StevoLopata Restreamer is intended to restream live content. With live content, the `-re` option is not recommended. If you want to add it, edit https://github.com/datarhei/restreamer/blob/master/conf/live.json#L76 and add "-re" to the "inputOptions". Then you need to build your own Docker image with this modification or you mount a modified `live.json` to `/restreamer/conf/live.json`.

**Comment by StevoLopata** [comment]
Thanks for the clarification! I'm having a issue locating restreamer master folder on my Ubuntu server though, is there any chance you could help me find it?

**Comment by ioppermann** [comment]
If you want to modify the `live.json` you can clone the Restreamer repository to your machine and make the modifications. Alternatively, you can simply download only the `live.json` from the Restreamer repository by navigation to the file on github and once there, click on "Raw". This will display only the file and then you can save or copy paste it and store it to your machine.

**Comment by istoutjesdijk** [comment]
Works like a charm, it looks like the -re is mandatory for all HLS streams. Performance also seems to be better for RTMP streams (less skipping). Maybe it should be default again? It looks like you removed it before: https://github.com/datarhei/restreamer/issues/132

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
