### ISSUE TITLE
RTSP Video is not playing

### ISSUE THREAD

**Issue by vishnusaxena-globallogic** [datarhei/restreamer#17]
Hi All,

I am very new to the video. In fact this is first time I am doing something in this field.
I want to show an RTSP video on web page + mobiles, I am using Restreamer for this.
I can as of now can see live Images only (when i select the player it displays a static image, which gets refreshed after some time ... but not the live video feed.)

Can any one help w.r.t.

Many thanks in advance !

Thanks & Regards,
Vishnu N Saxena

**Comment by IzmaylovAndrey** [comment]
@vishnusaxena-globallogic attach logs from container
docker logs ${CONTAINER_NAME}
And show command for running container
