### ISSUE TITLE
Feature request -  implement nginx-rtmp-backup

### ISSUE THREAD

**Issue by wallopthecat** [datarhei/restreamer#171]
Goal: backup stream source for always available stream if main goes down

https://github.com/ngoral/nginx-rtmp-backup allows you to have a secondary backup stream (could be an always available loop "offline coming back soon" or whatever you want)

**Comment by RockNRollGeek** [comment]
Another great example of this, with a newer codebase, is: [https://github.com/Hakkin/streamRIP](https://github.com/Hakkin/streamRIP), which also will instantaneously without delay switchover to a video file you choose of similar stream bitrate, works pretty well for having not been touched in some time, though I have seen some issues on recent (18.04/20.04) builds of ubuntu and recent debian builds for reasons im unsure of. 

Would LOVE to see this functionality though, 10x more than anything else I've seen in the FRQ's or backlog, absolute game changer, especially for IRL streams where sometimes cellular/mobile bandwidth can disappear or come back at a moments notice.

**Comment by ioppermann** [comment]
We're working on a similar, more integrated, solution on this, which doesn't involve scripting.

**Comment by RockNRollGeek** [comment]
rad! As long as it supports secondary streams -or- a local file, that will be amazing.

**Comment by RockNRollGeek** [comment]
Curious if there's been any movement on this?

**Comment by ioppermann** [comment]
Yes, there's movement. It will be included in one of the upcoming versions.

**Comment by RockNRollGeek** [comment]
Is this dead? It's now Aug 2021.

**Comment by ioppermann** [comment]
No, it's not dead, but a bit delayed. Unfortunately we can't dedicate all of our time to this project.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
