### ISSUE TITLE
Use URL instead of IP for player URL (Docker deployments)

### ISSUE THREAD

**Issue by bkraul** [datarhei/restreamer#172]
In **docker** instances where restreamer is running behind a web proxy such as nginx-proxy, using an IP for the external player URL embed does not work, due to the fact that the proxy routes communication to each container by virtual host.

Therefore, if we could have an environment variable for the public host rather than it detecting it and using IP, it would be awesome.

For example:
- RS_PUBLIC_URL=livestream.mydomain.com

And have the player use this address to generate the embed code:
```
<iframe src="https://livestream.mydomain.com/player.html" name="restreamer-player" width="800" height="450" scrolling="no" frameborder="0" webkitallowfullscreen="true" mozallowfullscreen="true" allowfullscreen="true"></iframe>
```

**Comment by wallopthecat** [comment]
I can knock this out when I get some time

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
