### ISSUE TITLE
Audio delayed, overlapping and restarting

### ISSUE THREAD

**Issue by jxs714** [datarhei/restreamer#177]
Hey guys,

Just tested the platform and when streaming in obs, the audio from my microphone is delayed by 8-10 seconds, overlaps after about 20 seconds and repeats until it becomes jumbled audio. Its pretty weird. How can I fix this? Are any issues being consistently fixed?

Keep up the great work, looking forward to hearing back.

**Comment by ioppermann** [comment]
This is really weird. This might be a problem with OBS. Did you try to record to disk and see/here the same?

Does OBS have enough resources available for encoding the video stream?

Restreamer usually just copies the video and audio data while changing the container format from RTMP to HLS. Do you use any encoding settings in Restreamer?

**Comment by jxs714** [comment]
Hey there

Thanks for the update. Yes, I have a completely new and fresh installed PC more than able to run anything thrown at it, so thats not the case lol.

**Comment by jxs714** [comment]
Hey guys,

I figured out the issue. It was because I was test playing the video in a browser window on the same computer as I was streaming. SMH. Sorry about that guys. Hope this fixes it for someone else.
