### ISSUE TITLE
Feature Request - Add third streaming output

### ISSUE THREAD

**Issue by BShurilla** [datarhei/restreamer#178]
Currently you can do 2 simultaneous streams, which is awesome, but it would be nice if we could get 3 - that would allow one to our website, one to youtube, and one to facebook all from one control panel.

**Comment by ioppermann** [comment]
We are working on that 😃

**Comment by Yuvi-App** [comment]
I'll add and state it be great if we could have more then 1 external streaming server 👍 
Thanks

**Comment by jxs714** [comment]
Hey guys,

I'm confused. I am currently on 0.6.5 and I only see one output option for external streaming. How are you guys seeing two? Am I supposed to modify the default setup in Docker?

**Comment by BShurilla** [comment]
> Hey guys,
> 
> I'm confused. I am currently on 0.6.5 and I only see one output option for external streaming. How are you guys seeing two? Am I supposed to modify the default setup in Docker?

When you are looking at the web page, you should have an "Optional:" section with a checkbox for "External Streaming-Server" select that checkbox and it will allow to add a second output.

**Comment by jxs714** [comment]
> 
> 
> > Hey guys,
> > I'm confused. I am currently on 0.6.5 and I only see one output option for external streaming. How are you guys seeing two? Am I supposed to modify the default setup in Docker?
> 
> When you are looking at the web page, you should have an "Optional:" section with a checkbox for "External Streaming-Server" select that checkbox and it will allow to add a second output.

Hey bud,

Thanks for reaching back. Yes, I know of this option. When you check this option there is only one output option. From my understanding multistream documentation states that you have to create a docker for each stream. You originally mentioned there was an option for 2, but you would like 3. When I check the optional box, it only shows stream link for YouTube/Twitch etc.

**Comment by BShurilla** [comment]
> > > Hey guys,
> > > I'm confused. I am currently on 0.6.5 and I only see one output option for external streaming. How are you guys seeing two? Am I supposed to modify the default setup in Docker?
> > 
> > 
> > When you are looking at the web page, you should have an "Optional:" section with a checkbox for "External Streaming-Server" select that checkbox and it will allow to add a second output.
> 
> Hey bud,
> 
> Thanks for reaching back. Yes, I know of this option. When you check this option there is only one output option. From my understanding multistream documentation states that you have to create a docker for each stream to output to such as YouTube, Twitch, etc. You originally mentioned there was an option for 2, but you would like 3. When I check the optional box, it only shows one stream link for YouTube/Twitch etc. Im trying to understand howd you get two on one page lol

ah, gotchya, yes. There is only the one option including that to _push_ your stream. In my case my final website _pulls_ the player and embeds it giving me output #1 then I use the external option to push to youtube giving me output #2

**Comment by jxs714** [comment]
> 
> 
> > > > Hey guys,
> > > > I'm confused. I am currently on 0.6.5 and I only see one output option for external streaming. How are you guys seeing two? Am I supposed to modify the default setup in Docker?
> > > 
> > > 
> > > When you are looking at the web page, you should have an "Optional:" section with a checkbox for "External Streaming-Server" select that checkbox and it will allow to add a second output.
> > 
> > 
> > Hey bud,
> > Thanks for reaching back. Yes, I know of this option. When you check this option there is only one output option. From my understanding multistream documentation states that you have to create a docker for each stream to output to such as YouTube, Twitch, etc. You originally mentioned there was an option for 2, but you would like 3. When I check the optional box, it only shows one stream link for YouTube/Twitch etc. Im trying to understand howd you get two on one page lol
> 
> ah, gotchya, yes. There is only the one option including that to _push_ your stream. In my case my final website _pulls_ the player and embeds it giving me output #1 then I use the external option to push to youtube giving me output #2

Oh ok. I thought you meant there was an option for one rtmp setup to dish out to 2 streams. I jumped out of my seat for a sec lol. Thanks for the replies

**Comment by Yuvi-App** [comment]
Yeah what I’m needing is 1 incoming rtmp stream to push to two or more external streams

**Comment by wallopthecat** [comment]
Restreamerception - set up one instance to pull from the feed of the main instance and rebroadcast :P

**Comment by Yuvi-App** [comment]
> Restreamerception - set up one instance to pull from the feed of the main instance and rebroadcast :P

You say that, but that's what I'm doing now.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by jstabenow** [comment]
Hey @BShurilla 
This ticket is closed due to inactivity. If you still have questions, please open a new issue or reopen this case.
Thanks.
