### ISSUE TITLE
External 'External RTMP-Streaming-Server' not restarting properly for Youtube Live

### ISSUE THREAD

**Issue by Viatrak** [datarhei/restreamer#18]
**Environment:** 
Restreamer running on a Raspberry Pi 3 with Hypriot image and the Arm7 :latest docker container. P1357-E Axis camera locally streaming to external Youtube live. The RasPi and Axis camera are on the same local network. 

Source setting: rtsp://USER:PASS@ip/axis-media/media.amp?videocodec=h264&resolution=1920x1080&fps=20&audio=0&compression=30&clock=0&audio=0

External server setting: rtmp://a.rtmp.youtube.com/live2/channelid

The container is being run via:
docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=user" -e "RESTREAMER_PASSWORD=password" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer-armv7l:latest

**Problem:**
After configuring the video source and the external stream everything works great. Upon rebooting the RPi the docker container and video source resume properly. The external streaming attempts to start but never does. After manually hitting 'stop' and then 'start' for the external streaming server it resumes streaming properly.

**Comment by stepanstipl** [comment]
I've been seeing the same issue, on Raspberry Pi Zero with camera module.
