### ISSUE TITLE
webcam video sync between containers

### ISSUE THREAD

**Issue by cskonopka** [datarhei/restreamer#181]
Is it possible to synchronize webcam streams between 2 individual Restreamer containers? i.e. each instance has it's own webcam

**Comment by ioppermann** [comment]
Can you please describe what exactly you want to synchronize? What do you want to achieve?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
