### ISSUE TITLE
Is there anyone using Datarhei/Restreamer? 

### ISSUE THREAD

**Issue by svenerbeck** [datarhei/restreamer#19]
Is there anyone using Datarhei/Restreamer? 

We try to find a list of products/companies/people using it 24/7? 

Everyone is invited to post in comments 👍 

(electronic hand5)
Sven

**Comment by hosenmatz** [comment]
yupp, i want to use restreamer on Pi 3 for lots of ip-cams (rtsp, evtl. RaspiCam) in the near future (over the next year)
our project is to do gardening/harvesting vegetables 24/7 for people without a garden mixed with the possibility to run it as a game
for this we need 4 cams per Pi to stream to 4 different html-pages (in 25 different gardens, together 100 cams)

dirk

**Comment by svenerbeck** [comment]
Hallo, Moin Moin hostenmatz
Any news about your gardening/harvesting project?

Cheerio 
Sven
