### ISSUE TITLE
https-portal issue

### ISSUE THREAD

**Issue by kbysfm** [datarhei/restreamer#192]
@wdalmijn @ioppermann Following the Docker Compose guide here https://datarhei.github.io/restreamer/docs/guides-https.html and whenever I execute docker-compose up I receive the following error:

"ERROR: for https-portal Cannot start service https-portal: Ports are not available: port is already allocated."

I've restarted docker and checked docker-compose.yml file, yet I'm not sure what ports are already allocated.

Thoughts?

**Comment by scottgrobinson** [comment]
It means another docker container on your system OR another application on your system is using the port specified in the docker-compose file. Try changing the port in the docker-compose file, you'll then have to access it via https://IPHERE:NEWPORT

**Comment by wallopthecat** [comment]
`sudo netstat -tulnp | grep 80`

**Comment by kbysfm** [comment]
Had to use sudo lsof -i -P -n | grep LISTEN to figure out what ports were being used. Turns out (MacOS) had a ton of httpd protocols for a proxy service that was using 80/443
