### ISSUE TITLE
documentation : add example using docker compose

### ISSUE THREAD

**Issue by otivedani** [datarhei/restreamer#193]
Hi, 
I think maybe it's better to add documentation using docker-compose at [references / environment variables section](https://datarhei.github.io/restreamer/docs/references-environment-vars.html), for those especially who running local everytime.
and if it's possible, I want to make a PR about it. 
cheers.

**Comment by ioppermann** [comment]
@otivedani You can contribute to the documentation by changing to the `gh-pages` branch and submitting a PR on this branch.
