### ISSUE TITLE
data.streams is not iterable

### ISSUE THREAD

**Issue by ofadam** [datarhei/restreamer#200]
I'm at a loss as to why I'm getting this error log within a second of launching Restreamer (I pulled the latest version, as mine was out of date): 

/restreamer/src/classes/Restreamer.js:326
                for(let s of data.streams) {
                                  ^

TypeError: data.streams is not iterable
    at /restreamer/src/classes/Restreamer.js:326:35
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:310:20)
    at Pipe.<anonymous> (net.js:672:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Restreamer@0.6.6 start: `node ./src/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Restreamer@0.6.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ofadam** [comment]
Just as an FYI, it only became an issue in 0.6.6 – 0.6.5 works fine still.

**Comment by ioppermann** [comment]
This should be fixed in 0.6.7
