### ISSUE TITLE
install on Jetson Nano

### ISSUE THREAD

**Issue by kalashnikov2** [datarhei/restreamer#202]
its posible to install / Use restreamer  on ARM devices ?  like jetson nano
:D

**Comment by ioppermann** [comment]
Yes, it is possible. You can use the ARM Docker images. You can follow the directions on https://datarhei.github.io/restreamer/docs/installation-linux-arm.html

- arm32v7: docker pull datarhei/restreamer-armv7l:latest
- arm64v8: docker pull datarhei/restreamer-aarch64:latest

**Comment by kalashnikov2** [comment]
it works using   restreamer-aarch64

`docker run -d --restart always      --name restreamer      -e "RS_USERNAME=admin" -e "RS_PASSWORD=XXXxXxXXX"      -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db      --tmpfs /tmp/hls      datarhei/restreamer-aarch64:latest`
 

Thanks for the help
