### ISSUE TITLE
Automatic start streamming

### ISSUE THREAD

**Issue by Bosutike** [datarhei/restreamer#203]
Hello,

I am trying to make restreamer start streaming automatically after a reboot.
To deploy docker I have used
`docker run -d --restart always -e "RS_USERNAME=admin" -e "RS_PASSWORD=passsword" -e "RS_INPUTSTREAM=rtmp://localhost/live/external.stream?token=secret" -p 1935:1935 -p 8080:8080 -e RS_TOKEN=xxxxxxx -v /mnt/restreamer/db:/restreamer/db restreamer`

After a reboot, the button on the UI is "start" instead of "stop" (basically not streaming).

**Comment by ioppermann** [comment]
@Bosutike The command looks correct, however the automatic start of the stream with `RS_INPUTSTREAM` will only work if you have a fresh Restreamer without an existing `v1.json` in `/mnt/restreamer/db`.

Afterwards, if the stream is connected and the docker container has to be restarted, then Restreamer should automatically reconnect to the stream in order to recreate the same state as before the reboot.

**Comment by PJSFilms** [comment]
Hi.
I have a very similar issue but one which requires Restreamer to start when a remote stream is received, without creating a very long error log before (while it is waiting) and after (until I get back home). Is there a 'trigger' setting possible for this? I'm not a developer but a videographer using Restreamer for live streaming remotely to my own website. My set up is working but has to be started from home each time. Sorry if I've missed something simple in the user guide.

**Comment by Bosutike** [comment]
Hi. 
I forgot I had this issue open.
I started using docker-compose.yml and its working. I will share my file.

`version: "3"
services:
  restreamer:
    image: restreamer_nazarewaves:latest
    container_name: restreamer_nazarewaves
    ports:
      - 1935:1935
      - 8080:8080
    networks:
      - frontend
    volumes:
      - "/home/restreamer/db/:/home/restreamer/db"
    environment:
      - RS_USERNAME=admin
      - RS_PASSWORD=admin
      - RS_LOGLEVEL=4
      - RS_TIMEZONE=Europe/Berlin
      - RS_SNAPSHOT_INTERVAL=1m
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
`

I suspect that if you want you can recreate this as a command.

**Comment by darvin** [comment]
> Hi.
> I forgot I had this issue open.
> I started using docker-compose.yml and its working. I will share my file.
> 
> `version: "3" services: restreamer: image: restreamer_nazarewaves:latest container_name: restreamer_nazarewaves ports: - 1935:1935 - 8080:8080 networks: - frontend volumes: - "/home/restreamer/db/:/home/restreamer/db" environment: - RS_USERNAME=admin - RS_PASSWORD=admin - RS_LOGLEVEL=4 - RS_TIMEZONE=Europe/Berlin - RS_SNAPSHOT_INTERVAL=1m restart: always deploy: replicas: 1 restart_policy: condition: any delay: 5s window: 10s `
> 
> I suspect that if you want you can recreate this as a command.

CAN YOU SHARE YOUR FILE

**Comment by Bosutike** [comment]
I am sorry but I am not using this solution anymore.
