### ISSUE TITLE
Your stream wasn't accessible. failed to execute ffprobe: Command failed: ffprobe...

### ISSUE THREAD

**Issue by Wisbell** [datarhei/restreamer#204]
```
Your stream wasn't accessible.
failed to execute ffprobe: Command failed: ffprobe -of json -v error -show_streams -show_format rtsp://user:pass@192.168.1.123/live/ch1
```

Followed basic docker installation with Kitematic.  The IP camera's rtsp url works when viewing from VLC on host computer.  Any ideas on how to debug this?  First time docker user.

EDIT: I tried using just the cli, but that didn't work.  I also tried opening all necessary ports just to make sure that wasn't the issue either.  I tried increasing the debug logging level to see if it would give me any more information, but I didn't see anything new to help track down the issue.

Camera: Wansview 1080p k3 -> Video Compression H.264/MJPEG per manual
OS: Windows 10

**Comment by Wisbell** [comment]
Just got restreamer to work on my raspberry pi with the rpi camera.  There is a 7 or 8 second delay, but it does work on that device.  Still have to try to pinpoint the issue with the wansview camera/windows combination.

**Comment by ioppermann** [comment]
@Wisbell Did you also try to connect from the Restreamer on your Pi to the Wansview camera? Checking the failed ffprobe command, it might be that a case is not covered that prevents some RTSP streams to be properly detected. Let me investigate this.

**Comment by ioppermann** [comment]
This should be fixed now in master.

**Comment by Wisbell** [comment]
Thank you!  I pulled down the repository, built the docker image locally, and everything seems to work at intended.  For Windows users who build locally, make sure you update your git config before cloning the repository.  ``` git config --global core.autocrlf false ```  Otherwise you will receive this error: ``` Err: standard_init_linux.go:211: exec user process caused “no such file or directory” ``` -> https://discourse.openstates.org/t/file-missing-from-docker-image-err-standard-init-linux-go-exec-user-process-caused-no-such-file-or-directory/440
