### ISSUE TITLE
How do I send the HLS stream to another server?

### ISSUE THREAD

**Issue by Thiagobhmg** [datarhei/restreamer#206]
How do I send the HLS stream to another server? Is there a configuration manual for this?

Is it possible to get a stream on the server where the restreamer is?

Would anyone recommend a CDN that accepts this flow? Prefer not to be AWS.

**Comment by ioppermann** [comment]
Some CDNs accept HLS as input, but it is not very common yet. Usually using RTMP is the better option.

It is described in the documentation: https://datarhei.github.io/restreamer/docs/guides-external-rtmp.html or https://datarhei.github.io/restreamer/docs/guides-external-hls.html

If you have enough upload bandwidth available, your Restreamer is the streaming server. The player can be embedded in any page.

**Comment by Thiagobhmg** [comment]
http://ip:port/hls/live.stream.m3u8

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
