### ISSUE TITLE
Encoding Stream Output 1080p to 240p

### ISSUE THREAD

**Issue by python-911** [datarhei/restreamer#207]
Hello.

Input stream is 1080x720 - its a HD stream i want to restream in low quality i.e 360p or 420x360 or any custom values.

Currently i can change bitrate preset etc - but an option to choose vide resolution is required.

i checked main.html file but i couldn't find way to add soutput sream resolution -_ 

Thanks

**Comment by python-911** [comment]
for now i added v-  live.json 
"-s 240x160", it worked for stream is buffering as it was buffering in 1080p.

in next update please add options to choose from.
so we can choose video resolution / quality .
from minimum 144p to max.

Regards

**Comment by Inzombie** [comment]
> for now i added v- live.json
> "-s 240x160", it worked for stream is buffering as it was buffering in 1080p.
> 
> in next update please add options to choose from.
> so we can choose video resolution / quality .
> from minimum 144p to max.
> 
> Regards

Where I can find the live.json file?

**Comment by ioppermann** [comment]
The live.json file is in the /conf directory of the repository.

**Comment by Inzombie** [comment]
> The live.json file is in the /conf directory of the repository.
> […](#)
> Am 08.07.2021 um 23:21 schrieb Inzombie ***@***.***>: ﻿ for now i added v- live.json "-s 240x160", it worked for stream is buffering as it was buffering in 1080p. in next update please add options to choose from. so we can choose video resolution / quality . from minimum 144p to max. Regards Where I can find the live.json file? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I can't find the directory, i installed via docker.

**Comment by ioppermann** [comment]
You have to download it from the repository: https://github.com/datarhei/restreamer/blob/master/conf/live.json and then you can mount your modified version into the docker container with `-v /path/to/modified/live.json:/restreamer/conf/live.json`.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
