### ISSUE TITLE
No audio after ingesting RTMP

### ISSUE THREAD

**Issue by hsully03** [datarhei/restreamer#208]
Hi everyone, I'm using Restreamer's RTMP server to ingest an OBS stream into Restreamer. The RTMP stream itself has no audio issues, but the player itself has no audio. Why would that be?

**Comment by ioppermann** [comment]
By default the player is on mute. And you have to set the audio codec to "auto". If the audio is encoded in a supported format, it will be simply copyied or transcoded to AAC.

What are the audio settings you use in OBS?

**Comment by hsully03** [comment]
> By default the player is on mute. And you have to set the audio codec to "auto". If the audio is encoded in a supported format, it will be simply copyied or transcoded to AAC.
> 
> What are the audio settings you use in OBS?

Taking the audio off of mute to auto resulted in FFMPEG retuning error code 1. This was on macOS, I switched to windows and had no issues.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
