### ISSUE TITLE
Stream stopped after few hours

### ISSUE THREAD

**Issue by kayo77** [datarhei/restreamer#212]
I have two streams to YouTube. Both stops after few hours - YT don't see stream despite being restreamer-side. How can i debug this issue?

**Comment by fruvous** [comment]
I'm seeing this issue on my YT stream as well with v0.6.8.  OBS continues to show green but with 0kbps.  Only fix I've been successful with is to reboot the restreamer box.

I'm using the old studio key.  Let me know what logs you would like to see.

**Comment by kayo77** [comment]
This is Yt issue or restreamer issue?

**Comment by fruvous** [comment]
My problem is a Restreamer issue.  If it's YT, the other stream would continue and OBS wouldn't drop down to 0kbps

**Comment by ioppermann** [comment]
Did you see any error messages in the console?

**Comment by kayo77** [comment]
No, there is nothing special in console

**Comment by fruvous** [comment]
I rolled back my version to 0.66 and haven't experienced the issue since.

**Comment by robinostlund** [comment]
i also have the same issue with latest version, will try to use 0.66 as @fruvous said was working now.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
