### ISSUE TITLE
Clarify Auto resume or auto start?

### ISSUE THREAD

**Issue by RaymiiOrg** [datarhei/restreamer#214]
I was not able to find it in the docs or wiki but I have a question. 

After configuring a stream and an external youtube one, including OBS setup, it works well. Both the html player and youtube (Damm the new live control room, forcing you to open the page otherwise nothing happens) are showing the stream (from obs).

But, what if I stop the stream, then after a few days do another stream?

Do I have to configure all the urls in the webui again? Do I have to click start in the webui again? Or is it all saved and is pressing start in OBS enough to start restreamer including youtube? (Except for opening live control room...)

And, if the server with the docker container reboots, does the above also apply?

Could you please clarify the above things?

**Comment by ioppermann** [comment]
The streams in Restreamer that are currently connected will try to reconnect on loss of connection. Restreamer stores the wanted state ("connected" or "disconnected") such that it can reconstruct them after a reboot.

In your case, you are pulling the stream from the local RTMP. This is the stream you send to Restreamer from OBS. If you stop OBS, Restreamer gets disconnected from the RTMP and will try to reconnect every few seconds. As soon as you start OBS again, it will be able to connect to the local RTMP.

The same happens for the stream that you send to Youtube. This one also pulls the stream from the local RTMP and forwards it to Youtube. This will also try to reconnect if the incoming stream stops.

**Comment by RaymiiOrg** [comment]
Thank you for clarifying. Is there any way I can help the documentation, via a pull request with this information? I wasn't able to find the github . io site here.

**Comment by ioppermann** [comment]
@RaymiiOrg Very much appreciated. You can find the source for the documentation in the `gh-pages` branch of the Restreamer repository.

**Comment by RaymiiOrg** [comment]
I made a pull request which adds it to the FAQ: https://github.com/datarhei/restreamer/pull/217
