### ISSUE TITLE
Your stream wasn't accessible on Dahua camera

### ISSUE THREAD

**Issue by rolfikr1** [datarhei/restreamer#215]
I have problem with restream Dahua camera. Restreamer shows: failed to execute ffprobe: Command failed: ffprobe -of json -v error -show_streams -show_format rtsp://login:pass@A.B.C.D:554. What can I do to make it work?

**Comment by ioppermann** [comment]
You should tick the `RTSP over TCP` option. Otherwise it tries to connect to the camera via UDP which is usually leading to errors.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
