### ISSUE TITLE
Streaming stays on stopping please wait

### ISSUE THREAD

**Issue by ohopecam** [datarhei/restreamer#216]
I need help my streaming on my website wont start again I stopped it at night a while ago and it just says streaming stopping please wait so I cant start it again if you know anything please help.

**Comment by ioppermann** [comment]
This looks like the ffmpeg is not stopping completely. Please try to restart the Docker container.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
