### ISSUE TITLE
rtmps not working

### ISSUE THREAD

**Issue by ssdeol84** [datarhei/restreamer#218]
Dear Sir, 

Docker is working properly with rtmp and hls. as you know facebook have updated the server and now it takes in put as rtmps. i request you to update the docker as now its not working with facebook.

**Comment by ioppermann** [comment]
@ssdeol84 I just tried it out and it works with RTMPS as well. Simply enter the `rtmps://...` URL in the field for the "External Streaming-Server" and select "RTMP".

**Comment by ssdeol84** [comment]
Sir I've tried but it's not working...may be Facebook have changed the server parameters which doesn't match with the current encoding settings of restreamer ?


Can u add multiple restreaming option in same docker ?
Does this have marquee or logo feature in push stream ?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
