### ISSUE TITLE
Stream from MP4 video file

### ISSUE THREAD

**Issue by Adam-Oudaimah-SCASE** [datarhei/restreamer#221]
Hello,
Is there any way to stream a video file directly?
The video file may be stored anywhere (On the local files' system or on AmazonS3 bucket).
Thanks a lot.

**Comment by ioppermann** [comment]
It will not work for non-live streams, because reads the data as fast as it gets delivered. This will have a "very fast-forward" effect on the video if you read a local file or via HTTP.

**Comment by alex9099** [comment]
maybe ffmpeg could be run internally like this example https://write.corbpie.com/how-to-stream-mp4-video-to-youtube-with-ffmpeg/ ?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket is closed.
