### ISSUE TITLE
Able to set resolution

### ISSUE THREAD

**Issue by internetxs** [datarhei/restreamer#223]
Hey 
Very nice tool / frontend. But it would be nice if you can set the output resolution. Facebook for example demands 1280x720 but if your source is higher they kick the stream

**Comment by DachsbauTV** [comment]
This would actuallybe amazing

However, I think the main limit is the bitrate.
As far as i know fb allows a maximum of 6000kbps and Twitch about 9000kbps.

The option to have a custom bitrate and resolution per output would be a game changer. Not even paid services like restream offer this.

**Comment by internetxs** [comment]
In ffmpeg it’s not difficult to define

Op ma 23 nov. 2020 om 16:41 schreef DachsbauTV <notifications@github.com>

**Comment by ioppermann** [comment]
This feature is already on the list and will eventually find its way into Restreamer.

**Comment by Yuvi-App** [comment]
Just adding this to the list of great to haves!

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
