### ISSUE TITLE
Add chromecast support 

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer#224]
I've actual already got a chromecast player working with it but thought it would be nice to have it builtin to the docker container. And cleaned up a bit by someone who knows more than I.

https://codepen.io/badincite/pen/MWjgYRw

![Chromecast](https://user-images.githubusercontent.com/7386290/100107435-a1595f80-2e37-11eb-9e3e-4dd3ff091c75.PNG)

**Comment by badincite** [comment]
I'll build it into my own branch working on learning how to now.

**Comment by badincite** [comment]
Figured it out quickly if anyone else wants it https://hub.docker.com/r/badincite/restreamer

**Comment by ioppermann** [comment]
@badincite Do you mind to make a pull request with your changes? So we might adopt it for the official version or even allow the user to chose a player they prefer.

**Comment by badincite** [comment]
Done hopefully I did it correctly, please excuse my inexperience.
