### ISSUE TITLE
No audio with docker

### ISSUE THREAD

**Issue by j-atoms** [datarhei/restreamer#227]
If I set RS_USBCAM_AUDIO=false I get perfect video streaming without audio. If set to true, Restreamer will not start. Am I missing anything in my docker-compose.yaml? Thanks.
[https://github.com/j-atoms/docker-compose/blob/master/yamls/restreamer/docker-compose.yaml](https://github.com/j-atoms/docker-compose/blob/master/yamls/restreamer/docker-compose.yaml)

**Comment by ioppermann** [comment]
@j-atoms You also have to set the appropriate values for your audio device. Please check the manual: https://datarhei.github.io/restreamer/docs/guides-usb-camera.html#audio-support

Also in your YAML, the path to the `snd`  device should not have the `/` at the end.

**Comment by j-atoms** [comment]
I overlooked the audio specifics and have added them to my yaml. Thank you.
