### ISSUE TITLE
Video Grid using multiple inputs

### ISSUE THREAD

**Issue by BGarber42** [datarhei/restreamer#229]
It would be nice to be able to grid multiple stream inputs with the hstack/vstack ffmpeg filter.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
