### ISSUE TITLE
Make logo bigger

### ISSUE THREAD

**Issue by electrodog10** [datarhei/restreamer#231]
How can I make the logo bigger? I don't think it's based on the image's size unless I'm doing something wrong. 
Thanks!

**Comment by ioppermann** [comment]
The logo size is limited to 12% of the width of the player but not more than 200 pixel. The builtin "watermark" plugin from the clappr player is used for this (https://github.com/clappr/clappr-plugins/tree/master/src/plugins/watermark). It has limited capabilities regarding the positioning and resizing of the logo.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. We close this ticket.
