### ISSUE TITLE
Stream going not Out to youtube.

### ISSUE THREAD

**Issue by Lordcybertracker** [datarhei/restreamer#232]
I have the problem. That the stream does not arrive on Youtube.
In Restream it says:
Streaming is successfully initiated.

Youtube link everything is correct too.

rtmp: //a.rtmp.youtube.com/live2/tpkg-XXXX-XXXX-XXXX-1tu4

With Yutube, however, the following remains: Send us your video via the streaming software to start a live stream

**Comment by ioppermann** [comment]
@Lordcybertracker Is streaming to YT still not working. Could have been a temporary issue on YTs side

**Comment by Lordcybertracker** [comment]
Yes its Working. Was an Error in the Settings.
Youtube go not wenn Stream is Mute.

**Comment by ioppermann** [comment]
👍 

Yes, YT requires an audio track for the streams.
