### ISSUE TITLE
Get RTSP output  from Restreamer 

### ISSUE THREAD

**Issue by ithouse98** [datarhei/restreamer#233]
hi dear restreamer team.
firstly thanks to your for this useful platform .
i have a questions about the restreamer , is it possible that this server relay a rtsp stream ?
my mean is we can input a rtsp url from a device ( ip cam ) and get more connection on RTSP from the server ?

**Comment by ioppermann** [comment]
If you just want to relay a RTSP stream, you can use the "rtsp-simple-server": https://github.com/aler9/rtsp-simple-server

**Comment by ithouse98** [comment]
ok. thanks to your suggestion .i will be try this .

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven

**Comment by ithouse98** [comment]
Ok, sounds great.
Thanks to you .
