### ISSUE TITLE
Restreamer YouTube problem

### ISSUE THREAD

**Issue by MacCase** [datarhei/restreamer#234]
I have been using restreamer for 10 months pushing stream to Youtube. But it doesn't work anymore. Something happened 4 days ago. Facebook stream work fine but YT not. Any suggestions?

**Comment by ioppermann** [comment]
Did you do an update of Restreamer or do you use the same version for the last 10 months? It also might be that YT changed/restricted something.

**Comment by MacCase** [comment]
no updates. What is interesting I cannot push stream to YT from nginx as well. OBS works ok.

**Comment by MacCase** [comment]
it works. Internal router problem.

**Comment by MacCase** [comment]
it works. Internal router problem.
