### ISSUE TITLE
Schedule live events on YOUTUBE or others 

### ISSUE THREAD

**Issue by CrashOv62** [datarhei/restreamer#237]
Hello,

Would it be possible in future versions of the program to set up a system for programming video streams?
For example, to be able to schedule the live broadcast of one-off events (at a start and end date and time, etc.) or recurring events?
and be able to schedule one-off or other events per week ...?
Youtube allows you to do this, I don't know if with other platforms this is also possible ... So that restreamer starts by itself according to the schedule and stops the broadcast at the scheduled end time and not have to broadcast 24/7.

**Comment by svenerbeck** [comment]
The feature request has been included as a feature request. https://github.com/datarhei/restreamer/discussions/345

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
