### ISSUE TITLE
MJPEG stream as input?

### ISSUE THREAD

**Issue by eisengrau** [datarhei/restreamer#239]
Hello,

I have just deployed a restreamer docker container. Even though on the Wiki, it is mentioned that rstreamer supports MJPEG, when I add my rtsp stream url from the camera, I get the message that "video stream must be h264, found mjpeg".

Unforutnately my old tp-link IP camera does not support h264 as it seems. It is possible to "trick" the output url to be like for example: rtsp://172.50.1.5/video.h264 but the stream itself is still mjpeg and audio is g726 according to VLC.

My goal was to restream it into h264 any way if it would have benn possible. Is it possible to somehow "override" the configuration so restreamer can accept this stream as is, or should I throw away the (back in the day expensive) camera?

**Comment by ioppermann** [comment]
Does your camera do MJPEG via RSTP, or do you have "direkt" MJPEG stream? In any case you need to enable encoding such that the MJPEG data gets encoded to h264. In the upcoming release, there will be a finer grained control on how to process MJPEG streams.

**Comment by eisengrau** [comment]
Ufortunately, the case is the latter, the camera's hardware is only capable to output MJPG, no matter what protocol (it supports RTP, RTSP, HTTP stream) is used.

The thing is, that I can't really enable encoding in restreamer, as it won't accept the camera's stream url, the error is, what I mentioned above. I can vary the camera's output URL to have extensions like video.mp4, video.h256, ... but the CODEC is still MJPG. This is what restreamer does not like. There is no way to alter anything else from the camera's control panel.

**Comment by ioppermann** [comment]
To ingest MJPEG streams will be supported in the upcoming release. In the meantime I can offer you a workaround, if you are familiar with the command line. The idea is to use ffmpeg for converting the MJPEG stream to something Restreamer can process. This will then be send to the RTMP endpoint of the Restreamer (https://datarhei.github.io/restreamer/docs/guides-ingest-rtmp.html).

Use this command to convert the MJPEG stream to a h264 stream:
```
ffmpeg -re -r [framerate of MJPEG stream] -i [URL to MJPEG stream] -codec:v libx264 -preset:v ultrafast -r 25 -g 50 -tune:v zerolatency -pix_fmt yuv420p -b:v 1000k -bufsize:v 1000k -f flv rtmp://[address of your box]/live/external.stream?token=...
```

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by eisengrau** [comment]
Wow! Thank you very muck for the effort. I'll definately eould try this out!

Ps. is it possible to run restreamer (as a binary) under an Alpine or Debian LXC (instead of docker?.)

**Comment by svenerbeck** [comment]
LXC can OCI = docker images

Take a look at: [https://www.buzzwrd.me/index.php/2021/03/10/creating-lxc-containers-from-docker-and-oci-images/](https://www.buzzwrd.me/index.php/2021/03/10/creating-lxc-containers-from-docker-and-oci-images/)

Greetings from Switzerland
Sven
