### ISSUE TITLE
Background Music

### ISSUE THREAD

**Issue by AtomicLaser** [datarhei/restreamer#240]
Is there a way to add in a music loop to the stream?

I run a CCTV camera to YouTube, but would like to have a background music that loops

**Comment by matigumma** [comment]
interesting, ¨_¨ 
anyway, i think youtube have a lot of resttrictions about authors, if you wish to use registered audio tracks

ffmpeg is able to mix video and audio inputs like this
`ffmpeg -i video.mp4 -i audio.wav -c:v copy -c:a aac output.mp4`

but i dont know about loop,,

**Comment by AtomicLaser** [comment]
Yeah I'd be using some royalty free music for this, but its tagging it into Restreamer so that ffmpeg sends the music too

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket is closed.
