### ISSUE TITLE
how to play in vlc

### ISSUE THREAD

**Issue by wesswhite** [datarhei/restreamer#241]
how in the world do you get thi to out put or play on vlc like http://ipaddress/xxx i cannot figure it out

**Comment by ioppermann** [comment]
The address to use in VLC to watch the stream from the Restreamer is: http://ipaddress:port/hls/live.stream.m3u8

**Comment by wesswhite** [comment]
Was this in the fax or docs anywhere on the site I looked everywhere, if not please add it … 😝

And thank you 


Sent from Mail for Windows 10

**Comment by ioppermann** [comment]
You had to send three copies of the signed form RS42-11 by mail to us in order to get this information 😜

It was nowhere to find the docs. I added it: https://datarhei.github.io/restreamer/docs/guides-embedding.html#external-player

**Comment by wesswhite** [comment]
Well if you’re the app creator good job, I would like to ask if there can ever be a way to change the password from inside program or a variable to do it while installing on docker 

Sent from Mail for Windows 10

**Comment by ioppermann** [comment]
You can change the password by setting the environment variable `RS_PASSWORD` (`docker run ... -e RS_PASSWORD=foobar ...`) to the desired value before starting Restreamer (https://datarhei.github.io/restreamer/docs/references-environment-vars.html). However, it is not possible to change the password while the Restreamer is running and without restarting it.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
