### ISSUE TITLE
Build docker image on RPi 4: ffprobe error

### ISSUE THREAD

**Issue by greycoding** [datarhei/restreamer#242]
I created a Docker image of restreamer on my Raspberry Pi 4 (4GB) using the following command:

`docker build -f dockerfile-rpi -t restreamer .`

I then created a container from it:

`docker run -d --restart always --name restreamer -e "RS_USERNAME=admin" -e "RS_PASSWORD=*****" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db --tmpfs /tmp/hls restreamer:latest`

The web interface is displayed correctly, but when I try to start the stream, I get the following message:

**Your stream was not accessible.
ffprobe: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or directory**

Is this a known issue? Do I need to set any additional parameters?

**Comment by ioppermann** [comment]
You have to mount the directory `/opt/vc` into the container.

```
docker run -d --restart always --name restreamer -e "RS_USERNAME=admin" -e "RS_PASSWORD=*****" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db -v /opt/vc:/opt/vc --tmpfs /tmp/hls restreamer:latest
```

Please also check this thread: https://github.com/datarhei/restreamer/issues/148

**Comment by greycoding** [comment]
Hi @ioppermann ,

thank you! The `/opt/vc` parameter in conjunction with the `--privileged` parameter (as described in the thread you mentioned) helped to get the stream starting.
