### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by DrEzequiel** [datarhei/restreamer#243]
Would it be possible to add Chromecast support to player.html?

**Comment by RaymiiOrg** [comment]
There is a pull request open: #226  - but not much is happening on that part. You could try to build your own docker container with that specific branch and see if Chromecast works.

**Comment by badincite** [comment]
I had it working with .0.6.8 circling back on that now. I ended up just running a player in in nginx site separate. Let me see if I can get it working with this sweet new 2.1 version.

Looks like the new ones using the videojs player. Thinking it should be pretty easy its just using the plug to get chromecast
https://github.com/silvermine/videojs-chromecast

**Comment by badincite** [comment]
Almost there just needs the plugin script added to the player,html 

```
<script src='https://cdn.jsdelivr.net/npm/@silvermine/videojs-chromecast@latest/dist/silvermine-videojs-chromecast.min.js'></script>
<script src='https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1'></script>
```

Having and coding issue here with the license: playerConfig.license doesn't like the chromecast: {} in front.

```

	plugins: {
			chromecast: {}	
			license: playerConfig.license
		}
	};
```


Link works just no image yet that will need to be added to the css. 

![image](https://user-images.githubusercontent.com/7386290/176813051-641a16e5-ca43-4ef5-afeb-a35e5fe6f8ed.png)

**Comment by badincite** [comment]
Update: I have it working just need to refine it. Been testing the changes in the docker by editing the volume. I'll have to figure out how to compile it or submit a pull request and have them pull the changes into the main repository.


![image](https://user-images.githubusercontent.com/7386290/177051601-e8da9a1c-30ef-40a9-b836-3f11ba5e955f.png)

**Comment by svenerbeck** [comment]
Mega. Well done! 
🚀

**Comment by jstabenow** [comment]
Hey @badincite 
Thanks again :grinning: Great work! 

@DrEzequiel is built in and released in v2.2.0.

**Comment by badincite** [comment]
Happy I could contribute! Also might want to add something to the documentation stating Chromecast support requires https.

**Comment by svenerbeck** [comment]
The docs are currently under revision. 💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**.
