### ISSUE TITLE
Streaming to YT via RTMP doesn't work

### ISSUE THREAD

**Issue by Pioxis** [datarhei/restreamer#245]
Hello,

I have IP camera, and I'm getting that camera from rtsp protocol.
After that I want to stream it to YT via RTMP. But I'm getting information: _Your stream wasn't accessible.
no video stream detected_
From OBS stream is working fine, but from restreamer I can't stream it.
When I'm trying to stream via HLS then when I'm pressing to start, nothing happens.

**Comment by matigumma** [comment]
I dont know your cam brand but
In some cases u have to get an addition to the path of stream 
Lile this in dahua or ipc cams:
`rtsp://x.x.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif `

a lot of cams have their cuatom paths
I just find this for my model

**Comment by Pioxis** [comment]
> I dont know your cam brand but
> In some cases u have to get an addition to the path of stream
> Lile this in dahua or ipc cams:
> `rtsp://x.x.x.x:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif `
> 
> a lot of cams have their cuatom paths
> I just find this for my model

I can get via RTSP the stream video from camera. I can't stream it to YT via RTMP.
