### ISSUE TITLE
External streaming server gets black image after a while.

### ISSUE THREAD

**Issue by tiptop96** [datarhei/restreamer#246]
I have been atempting to run restreamer for a few months now with youtbe as the external streaming service. Sadly I have had some problems. I suspect that they have nothing to do with `resteramer`, but I need to be sure.

The stream works fine at first and then drops out after some random amount of time. Youtube says the connection is "excellent" and restreamer is reporting that the stream is running at it's normal speed of about 3500kbps, however the image is just black.

I am lost in this realm but one thing that I thought of is if the fact that I have a dynamic IP address could mess up the RTMP stream?

Any input is welcome. 😃

**Comment by ioppermann** [comment]
@tiptop96 The dynamic IP may be really the reason for this. If you connect to YT with one IP and then at some point YT receives the data from another IP, it will abort the stream with the old IP.

**Comment by tiptop96** [comment]
Thanks, thats great to know.

However I it happend again and I could verify the IP has not changed. Usually it is just a matter of pressing stop and start to fix it.

Any ideas?

**Comment by fruvous** [comment]
https://github.com/datarhei/restreamer/issues/212

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
