### ISSUE TITLE
Streaming bitrate suddenly collapses

### ISSUE THREAD

**Issue by giuseppegambino92** [datarhei/restreamer#247]
Hi, I noticed that a few times during the day, the detected incoming bitrate collapses to values ​​close to 0. Restarting the container several times, the bitrate returns to the original value of the incoming stream (2500kbps). Why?

**Comment by ioppermann** [comment]
Might there be a connection issue with the incoming stream?

**Comment by giuseppegambino92** [comment]
Thanks for the reply. The webcam is local, and with the ffmpeg command (without container), it doesn't happen. Except if the cam restarts. In this way, however, during the day, perhaps even after 12 hours, it suddenly goes down. I had to create a script that kills the container and re-launches it when it happens. But it seems strange to me..

**Comment by giuseppegambino92** [comment]
![restreamer](https://user-images.githubusercontent.com/17169769/109789099-44c4c800-7c10-11eb-9d58-87e0e33c40d9.png)

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
