### ISSUE TITLE
Illegal instruction (core dumped) on Raspberry pi 3

### ISSUE THREAD

**Issue by mogupta** [datarhei/restreamer#25]
Does it support raspberry pi 3 ? I was assuming that the docker image would be upward compatible to ARMv8 ?  I tried it anyways. I get the following error

Illegal instruction (core dumped) on `npm start`

**Comment by IzmaylovAndrey** [comment]
It's compatible to Rpi3. There is a problem with nginx-rtmp-module
Change nginx-rtmp-module installation in DockerFile like this:

```
curl -LOks "https://github.com/arut/nginx-rtmp-module/archive/v1.1.9.tar.gz" && \
tar -xzvf "v1.1.9.tar.gz" && \

```
And then build your docker image

**Comment by mitchhh22** [comment]
Is this compatible with the raspberry pi zero?

I updated the Dockerfile_armv7l as recommended, but still get the following error:

`./run.sh: line 65:    10 Illegal instruction     (core dumped) npm start`
