### ISSUE TITLE
Username or Password is invalid

### ISSUE THREAD

**Issue by Webranger2** [datarhei/restreamer#251]
Completely new installed system. Docker installed new. when I want to log in I always get "Username or Password is invalid" The data is 100% correct.

Raspberry zero w with Raspberry Pi OS Lite
![Bildschirmfoto 2021-03-13 um 11 40 27](https://user-images.githubusercontent.com/44174579/111027484-f1f9c600-83f0-11eb-8951-b62b0d6c07b2.png)

**Comment by ioppermann** [comment]
Did you set the environment variables `RS_USERNAME` and `RS_PASSWORD` to values that may need escaping? It could happen that the shell is changing the contents of the values if they contain some special characters (e.g. `$`).

**Comment by apofis1969** [comment]
hi, it worked with me with this code:
docker run -dit --restart unless-stopped --name restreamer --env RS_USERNAME=xxxxx --env RS_PASSWORD=xxxxx  -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db  datarhei/restreamer:latest

**Comment by ChienDesEnfers** [comment]
I have the exact same issue when I set environment variable (using Kubernetes secret).
When I launch the docker image, I display these variables with `echo $RS_USERNAME` and `echo $RS_PASSWORD`, that shows me the correct username and password. But if I use them to login, I have the error about credentials.

**Comment by ioppermann** [comment]
@ChienDesEnfers Do you use any special characters for your username or password? Also try to login with the default username (`admin`) and password (`datarhei`). This should not work.

**Comment by ChienDesEnfers** [comment]
> @ChienDesEnfers Do you use any special characters for your username or password? Also try to login with the default username (`admin`) and password (`datarhei`). This should not work.

I don't have any special characters for both of them. If I remove these environment variables and I use the default `admin`/`datarhei` it's ok.
And if I use `echo $RS_USERNAME` the login et password are correct, so I suppose the issue doesn't come from the variable but maybe how it's managed into the system.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
