### ISSUE TITLE
Automatically streaming to youtube

### ISSUE THREAD

**Issue by SarahDal** [datarhei/restreamer#253]
Is there any way to set streaming to youtube from the command line? I am hoping to just livestream between set hours of the day over 1 month, so I was hoping to set up a cron or timer job for this.

I see the RS_INPUTSTREAM and RS_OUTPUTSTREAM environmental variables, but I also see from a previous question that these can only be set on a fresh install, so I'm not sure if that is what I am looking for?

**Comment by ioppermann** [comment]
@SarahDal You can use the `RS_INPUTSTREAM` and `RS_OUTPUTSTREAM` environment variables to instruct Restreamer to start pulling from a source and sending to an external destination. You just have to make sure to have a fresh install every time.

The installation is considered to be "fresh" if there's no state database available (`/restreamer/db/v1.json`). You can achieve this by **not mounting** a local directory as `/restreamer/db` inside the container. This means the state database will not be persisted across restarts of the Docker container.

Your command line might look like this:

```
docker run -d --restart always --name restreamer -e "RS_USERNAME=admin" -e "RS_PASSWORD=datarhei" -e "RS_INPUTSTREAM=..." -e "RS_OUTPUTSTREAM=rtmp://..."  -p 8080:8080 datarhei/restreamer:latest
```

**Comment by SarahDal** [comment]
(apologies for the late reply) - thank you for this! That's really helpful
