### ISSUE TITLE
cannot find the "web preview" button to start

### ISSUE THREAD

**Issue by forgetmenot2020kenting** [datarhei/restreamer#254]
I am a new user to the restreamer, 
I cannot find the "web preview" button to start restreamer, 
can anyone help plz? thanks

![image](https://user-images.githubusercontent.com/81156695/111970694-81f8e780-8b36-11eb-9640-1011f9c5a398.png)

**Comment by ioppermann** [comment]
@forgetmenot2020kenting Did you configure the port in the "Hostname / Ports" settings?

**Comment by forgetmenot2020kenting** [comment]
![image](https://user-images.githubusercontent.com/81156695/112082065-aa78f400-8bbf-11eb-8429-e416e2cc1e62.png)
this part?

**Comment by ioppermann** [comment]
Yes. If you define a published port, you should see the web preview.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
