### ISSUE TITLE
Your stream wasn't accessible.  Invalid data found when processing input

### ISSUE THREAD

**Issue by thephoton** [datarhei/restreamer#255]
Hi

I have setup restreamer in a Windows Server 2019 docker host and it will happily connect to other CCTV devices that use H264, but I am having trouble connecting to one of our devices - it is an electronic gate camera that outputs its stream as H263.

The message in the UI states: 
Your stream wasn't accessible.
rtsp://10.12.15.8:554/stream: Invalid data found when processing input

I've tried both TCP and UDP transports, but neither work. 

Here are debug logs from TCP/UDP transport modes:
[ffprobe-20210325-131702.log.txt](https://github.com/datarhei/restreamer/files/6204937/ffprobe-20210325-131702.log.txt)
[ffprobe-20210325-130756.log.txt](https://github.com/datarhei/restreamer/files/6204939/ffprobe-20210325-130756.log.txt)

Connecting via VLC works fine, as does ffmpeg on a different host, converting the stream to an H264 mp4 file.

Any ideas would be appreciated!

Thanks
Matt

**Comment by thephoton** [comment]
Following the instructions for an external RTMP stream here: https://datarhei.github.io/restreamer/docs/guides-ingest-rtmp.html
I tried running the command
`ffmpeg -re -i rtsp://10.12.15.8:554/ -f flv rtmp://10.50.0.1/live/external.stream?token=abc` 
on a different host.

Restreamer then picks up the stream quite happily. Not entirely sure what's going on!

**Comment by ioppermann** [comment]
@thephoton This is indeed a bit strange. In your first post you use `rtsp://10.12.15.8:554/stream` as input, in the second post you use `rtsp://10.12.15.8:554/` as input. Might this be the difference? Also the `-re` option shouldn't be necessary with RTSP.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
