### ISSUE TITLE
Error Your encoder is sending data faster than realtime (multipleseconds of video each second). You must rate limit your livevideo upload to approximately 1 second of video each second.

### ISSUE THREAD

**Issue by feuersee** [datarhei/restreamer#256]
Hello,
i use restreamer with pi3 an get the following error message:
Error:
Your encoder is sending data faster than realtime (multipleseconds of video each second). You must rate limit your livevideo upload to approximately 1 second of video each second.

Stephan

**Comment by ioppermann** [comment]
What is your setup in more detail? Do you stream a camera? What is the type of camera? If you try to stream a MJPEG stream, it will likely fail because there's no framerate control with it.

**Comment by feuersee** [comment]
Stream is now working!
I use a Golbong Wireless Bird Box Camera (rtsp://192.168.xxx.xxx:554/user=xxx&password=xxx&channel=1&stream=0.sdp?real_stream).  In Stream settings, i changend the i frame interval to 2.
Thanks Stephan
