### ISSUE TITLE
How to start streaming

### ISSUE THREAD

**Issue by cFlour** [datarhei/restreamer#258]
I installed everything according to the code. Now I open restreamer, and I really don't know what to do. Can anyone explain please?

**Comment by Inzombie** [comment]
First you need a source in my case i use a m3u8 source then i restream to a rtmp server.

**Comment by ioppermann** [comment]
Yes, you need a source, which can be an IP camera, encoder, ... that provides a stream as RTSP, RTMP, or HLS (m3u8). E.g. you have an IP camera in your network, put its RTSP URL into to the input field and press "Start". After a few seconds you can watch the stream in your browser with the player that is provided with Restreamer and/or you can send the stream to an RTMP server (Wowza, Youtube, Facebook, ...).

**Comment by cFlour** [comment]
@ioppermann I don't know what is an IP camera, but I have an internal camera built-in my device, so what should I do?

**Comment by ioppermann** [comment]
To restream a built-in device is currently only possible if you're running on Linux and the built-in device is exposed as video4linux device (https://datarhei.github.io/restreamer/docs/guides-usb-camera.html). In a later version we add support for macOS and Windows.

For your case, I would recommend OBS (https://obsproject.com/).

**Comment by cFlour** [comment]
@ioppermann I tried OBS before, and it doesn't work. So I currently use [streamyard](https://streamyard.com/broadcasts).

**Comment by makr76** [comment]
My raspberry cam works well, the stream was started and now I wanted to push it to YT. Added the stream key to it and the external stream was successfully started, but the stream in YT did not appear. Its still waiting for the streaming signal..!?! any thoughts about it?
also there´s often an error in the external streaming window "Your stream wasn't accessible.
Error: ffmpeg was killed with signal SIGKILL" what could this be?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
