### ISSUE TITLE
Cpu low usage

### ISSUE THREAD

**Issue by Inzombie** [datarhei/restreamer#260]
Hi, is it possible to set a low cpu usage or something because when i use a transcoder the cpu usage is too high. Or what is the best configuration for this task?

Im new on this and i search some solution with a thread setting.

**Comment by ioppermann** [comment]
The best settings for low CPU usage is the `ultrafast` preset combined with `zerolatency` tuning. The encoder will use multiple threads if it's appropriate.

If the stream you're transcoding has a high resolution, it will use a lot CPU.

The lowest CPU usage is with just stream copying, given that you input stream is compatible.

In one of the next versions we will provide GPU encoding, if available.

**Comment by jstabenow** [comment]
Thank you very much for your comment. We have implemented the encoding options in the Restreamer v2 🚀
Have fun with it.
