### ISSUE TITLE
Youtube excellent connection but no image

### ISSUE THREAD

**Issue by SarahDal** [datarhei/restreamer#263]
When starting the stream automatically from the command line, I get the "Send us your video via the streaming software to start a live stream" and no image, but a green light and "excellent" connection

docker run -d --restart always --name restreamer -e "RS_LOGLEVEL=4" -e "RS_USERNAME=[admin]" -e "RS_PASSWORD=[password]" -e "RS_MODE=RASPICAM" -e "RS_RASPICAM_VFLIP=true" -e "RS_RASPICAM_WIDTH=852" -e "RS_RASPICAM_HEIGHT=480" -e  "RS_RASPICAM_BITRATE=640000" -p 8080:8080 -e "RS_INPUTSTREAM=rtmp://127.0.0.1/live/raspicam.stream" -e "RS_OUTPUTSTREAM=rtmp://a.rtmp.youtube.com/live2/[key]" -v /opt/vc:/opt/vc --privileged datarhei/restreamer-armv7l:latest

If I go to the web interface, stopping and restarting the stream there works. I can't see anything in the log that looks like an error

**Comment by ioppermann** [comment]
This might be an YT issue. YT wont automatically start streaming if you are not on the streaming inferface with your browser. This is a known quirk of YT. The issue #259 could be interesting for you.

The width of your stream is also unusual. It's possible be that YT doesn't like it.

**Comment by SarahDal** [comment]
I had seen that #259 and was looking into that too. Thank you for the response - frustrating that YT is so picky about streams. I will keep trying though!

**Comment by SarahDal** [comment]
I tried streaming through Twitch instead of Youtube, and found it much more reliable and an all-round better solution for me than youtube, with the stream easily embedded into a webpage.

**Comment by JakeShirley** [comment]
I am also seeing something similar.  I am trying to set up a 24/7 stream of my aquarium and it blips too hard at some point each night and goes down, requiring manual intervention.

This is what I am seeing on YouTube's side:

![image](https://github.com/datarhei/restreamer/assets/1000311/5194081f-fe1b-4bf6-935c-bd8fb1a71715)

**Comment by JakeShirley** [comment]
It looks like #587 is the same situation (or more closely to what I am seeing).
