### ISSUE TITLE
Stress Test

### ISSUE THREAD

**Issue by BigRedProductions** [datarhei/restreamer#265]
Is there a way to stress test the RTMP Server? I would like to be able to know if it will handle what I want to use it for before I use it. I plan to use this for my Church’s Live Stream. Thank you for any help!

**Comment by badincite** [comment]
Your upload bandwidth is pretty much gonna be your limit.

**Comment by ioppermann** [comment]
The RTMP server is usually not stressed at all. If send a stream via RTMP to Restreamer, then the RTMP server transformes the stream into a HLS stream which is then served as simple HTTP from the internal nginx.

If you pull in a stream from an IP camera (no matter what protocol), it will be send to the internal RTMP which will also transform the stream to HLS.

The stream for the player is always served via HTTP/HLS by nginx. nginx is quite powerfull and can handle some load. As @badincite was mentioning, the limiting factor is probably your upload bandwidth. If you have an upload bandwidth of 100 Mbit/s and your stream has a bandwidth of 2 Mbit/s, then you will only be able to server up to 50 simultaneous viewers.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
