### ISSUE TITLE
Start Stream & Adjust URL via API 

### ISSUE THREAD

**Issue by Yuvi-App** [datarhei/restreamer#269]
As a feature request, could we get away to Start/Stop streaming for both inbound & outbound streams. Then a way to modify the URL for both would be excellent.

Looking to integrate the API into a frontend app for ease of managing 10+ restreamers.

**Comment by ioppermann** [comment]
With the next Restreamer release there will be an API which allows full control of the streaming processes. Additionaly, you will be able to forward the input stream to more than one destination (e.g. Youtube, Twitch, ...). The release after that will allow you to have multiple input streams with one Restreamer instance. Both releases will have an UI for easily managing all the streams.

Please be patient.

**Comment by Yuvi-App** [comment]
Great to Hear Sir! 
Can Close out this Feature Request then

**Comment by Dielee** [comment]
Hello guys,
is there something new with this issue ?

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
