### ISSUE TITLE
Audio codec 'adpcm_g726' not compatible with FLV

### ISSUE THREAD

**Issue by mrhell69** [datarhei/restreamer#27]
Hi,

my cam has an audio format that is blocker for ffmpeg:
-----------------------------------------------------------
root@82c9991b9bac:/restreamer# ffmpeg -i rtsp://192.168.178.31:554/12 -c copy -f flv rtmp://127.0.0.1:1935/live/test.stream
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
  configuration: --prefix=/usr/local --bindir=/usr/local/bin --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib --extra-libs=-ldl --enable-nonfree --enable-gpl --enable-version3 --enable-avresample --enable-libmp3lame --enable-libx264 --enable-openssl --enable-postproc --enable-small --disable-debug --disable-doc --disable-ffserver
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[rtsp @ 0x34d84c0] UDP timeout, retrying with TCP
[rtsp @ 0x34d84c0] CSeq 6 expected, 5 received.
[rtsp @ 0x34d84c0] Could not find codec parameters for stream 0 (Video: h264, none, 640x352): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, rtsp, from 'rtsp://192.168.178.31:554/12':
  Metadata:
    title           : 11
  Duration: N/A, bitrate: 16 kb/s
    Stream #0:0: Video: h264, none, 640x352, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1: Audio: adpcm_g726, 8000 Hz, mono, s16, 16 kb/s
[flv @ 0x3530f20] Codec for stream 0 does not use global headers but container format requires global headers
[flv @ 0x3530f20] Codec for stream 1 does not use global headers but container format requires global headers
**[flv @ 0x3530f20] Audio codec 'adpcm_g726' not compatible with FLV
[flv @ 0x3530f20] Audio codec adpcm_g726 not compatible with flv**
Output #0, flv, to 'rtmp://127.0.0.1:1935/live/test.stream':
  Metadata:
    title           : 11
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), none, 640x352, q=2-31, 90k tbr, 1k tbn, 90k tbc
    Stream #0:1: Audio: adpcm_g726, 8000 Hz, mono, 16 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Could not write header for output file #0 (incorrect codec parameters ?): Function not implemented
-----------------------------------------------------------

Is there a newer Version that can handle?
Or a parameter to omit audio?

Kind regards

Gerd

**Comment by svenerbeck** [comment]
Sorry mrhell69,
please try streaming without sound to check if it working.
If there are no more problems I would close the issue.

Cheerio
Sven
