### ISSUE TITLE
From YouTube or Facebook Live to multi stream to other Facebook, YouTube, Twitch Live

### ISSUE THREAD

**Issue by yashodhank** [datarhei/restreamer#270]
Greetings,

I really appreciate all those who worked hard work and shared restreamer..
I am looking into setup streaming server for going live with three youtube, facebook and Twitch channels at the same time as soon as my primary YouTube channel live feed starts.

Any suggestions and feedback is welcome. Thank you

**Comment by CrashOv62** [comment]
Hello !

I am also a restreamer user and to multi-stream with this version 0.6.8, I don't think I have the choice to launch several instances of restreamer (one for each server ...).
look over here: https://datarhei.github.io/restreamer/docs/guides-multiple-restreamer.html

You will be able to retrieve the camera stream in rtps on each of the instances and redirect them one to YouTube, one to Twitch and another to FB ...
To redirect to YT: https://datarhei.github.io/restreamer/docs/guides-youtube.html
For Twitch: https://datarhei.github.io/restreamer/docs/guides-twitch.html
And for FB I don't really know but it must be the same principle: an RTMP: // address from the server to FB as well as a stream key ...

Looking forward to version 2.0 of restreamer with more possibilities ... (it will be possible to do a multi-stream from a single instance I believe!)

;)

**Comment by yashodhank** [comment]
Thank you for your kind reply. I found one very interesting implementation and I just need to solve some other aspects of this puzzle..
This docker container image monitors channel for live (some other possibilities also available) checkout: https://github.com/sparanoid/live-dl
If I able to mix this with restreamer in someway or another, it will be legendary.

**Comment by jstabenow** [comment]
Thank you very much for your comment. Restreamer v2 enables multi-streaming to e. g. Facebook and YouTube 👍 
Have fun with it.

**Comment by yashodhank** [comment]
Youtube or Facebook live URL can be used as source?

**Comment by varunsridharan** [comment]
> Youtube or Facebook live URL can be used as source?

I am also looking for the same
