### ISSUE TITLE
Reduce delay RTMP

### ISSUE THREAD

**Issue by apofis1969** [datarhei/restreamer#272]
Hi, I am restreaming from wowza to Dacast.
Unfortunately the delay of the rtmp stream also inside the restreamer, testing with the player, is 8-11s
How can I reduce the delay of the incoming rtmp stream and also reduce the delay of the stream to the external platform.
Any help would be great!
Thank you
Johannes

**Comment by ioppermann** [comment]
Hi Johannes, please have a look at the discussion in the issue https://github.com/datarhei/restreamer/issues/132

**Comment by apofis1969** [comment]
Hi, I tried all the possibilities. The mentioned link with adapting the live.json does not work with ubuntu 20.04+
the reducing of the time intervals in the nginx.conf  do not create a lot of result. The delay if I open the player directly at the encoder is 8-10s and sometimes more. If I implement in a website I need to add more 2s
Is there any other configuration within the code to reduce the delay? The system is great but the delay of the incoming rtmp live stream from wowza after encoding with h264 and aac is the problem. The encoding process is too slow. Unfortunately wowza does not support sorenson spark wich is a big mess.. 
any suggestion would be appreciated. Thanks a lot

**Comment by fluential** [comment]
@apofis1969 try running this for a test https://github.com/fluential/ant-media-server-docker

**Comment by apofis1969** [comment]
Hi, I tried to run the live stream to the website with ant media enterprise. Absolutely no delay. Max delay 1,57 seconds. The problem is Dacast. Hopefully they will do the refund.
