### ISSUE TITLE
new feature?  RTMP destination server needs authentication 

### ISSUE THREAD

**Issue by LeonardoBagella** [datarhei/restreamer#274]
Hello,
compliments for the work done ! 👍 

I have to redirect the streaming to a rtmp server that necessarily asks for authentication.
The feature is similar to the one OBS or other softwares already do ( see [image](https://support.wim.tv/wp-content/uploads/2021/02/Support-wimtv-impostazioni-diretta-OBS.png) )

Are there chances to have it ? :)

thank you.
Leonardo

**Comment by ioppermann** [comment]
We will look into it.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by LeonardoBagella** [comment]
Awesome! Thank you!

**Comment by svenerbeck** [comment]
Hey Ho LeonardoBagella
This is probably what you need: [Quick guide on YouTube for the use](https://youtu.be/6D5Dl6GR-hc.)
We close this issue.
Cheerio
Sven
