### ISSUE TITLE
player on different port?

### ISSUE THREAD

**Issue by kolet** [datarhei/restreamer#275]
hi there,
i've read the doc but could not find this information .

i have downloaded the docker and ran it,
i was wondering , is that possible to change the player port ?

what happen is , when i ran the docker with -p8080:8080 it forwarded the login page and the player itself .
i'd like  for the "player" to be on port 9000 for example , and the login page on 8080
or keep the login page behind nat localy and gives forward the player outside.

**Comment by ioppermann** [comment]
Such a setup will be possible with the upcoming release, where you'll have the option not to expose the login page.

**Comment by kolet** [comment]
thanks !
any eta for the new release ?

**Comment by MrCoala** [comment]
You might want to have a look at Caddy which can act as a middleware. you could define different subdomains for the panel or the player

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
