### ISSUE TITLE
add multiple input with multiple outputs

### ISSUE THREAD

**Issue by kolet** [datarhei/restreamer#276]
hi there ,
i have multiple streaming input , is that possible to add multiple input within one docker ? (and ofc have multiple output players for each streaming input) 
or i have to open multiple dockers for the number of streaming input 

thanks

**Comment by ioppermann** [comment]
Currently you have to run multiple docker container for each input (https://datarhei.github.io/restreamer/docs/guides-multiple-restreamer.html).

In the upcomping release you will be able to have multiple outputs for one stream. In the release after that we will give the possibility to have multiple inputs as well with only one docker container.

**Comment by kolet** [comment]
hurrayy !

thanks
