### ISSUE TITLE
Securing player?

### ISSUE THREAD

**Issue by kolet** [datarhei/restreamer#277]
hi !

would that be possible to add an authentication page before the player page

for example if a given person will want to hit (reach) player.html he will need to enter a username and password that were given to him. 

(that mean in the login page the "admin" will be able to create such username and password manually and randomly)

**Comment by ioppermann** [comment]
Currently this is not possible out-of-the-box. You could modify the `conf/nginx.conf` such that it asks for a password if the player.html is accessed. You could either build your own docker image with the modification or mount the modified `conf/nginx.conf` into the container.

**Comment by privatesam** [comment]
Whereabouts in the container should the nginx.conf be mounted?

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
