### ISSUE TITLE
How to restream multiple rtmp live streams at the same time?

### ISSUE THREAD

**Issue by pidzvnese** [datarhei/restreamer#278]
Dear team,

I really appreciate all those who worked hard work and shared this project,
I use software to live stream, can I customize more than 1 external rtmp live stream at config?
And is there a way to generate tokens or stream keys for separate accounts?

Thanks you!

**Comment by matigumma** [comment]
use 2 cointainers 
with first  ingest the main source and push where u want
with second ingest main playlist.m3u8 and push other where u want...

**Comment by pidzvnese** [comment]
> use 2 cointainers
> with first ingest the main source and push where u want
> with second ingest main playlist.m3u8 and push other where u want...

But if 3 or more rtmp live streams need 3 or more containers?

**Comment by RaymiiOrg** [comment]
> But if 3 or more rtmp live streams need 3 or more containers?

Yes, the number of containers scales up with the amount of destinations you want to re-stream to.

**Comment by solarkraft** [comment]
Can we turn this into an FR for supporting multiple streams?

**Comment by jstabenow** [comment]
Thank you very much for your comment. Restreamer v2 includes the multi-streaming function 🚀
Have fun with it.

**Comment by Zucka** [comment]
So just to understand.

Is there now the possibility to have multiple RTMP/RTMPS/SRT servers running in the same container?
Or is the recommended way still multiple containers?

**Comment by jstabenow** [comment]
Per container:
- multiple channels (e. g., network device to build-in http/rtmp/srt server)
- multiple targets (e. g. YouTube-Live)

Demo: 
- URL: https://demo.datarhei.com/ui
- User: admin
- Password: demo
