### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by citrusweb** [datarhei/restreamer#28]
How to enable autoplay?

Best regards,
Jaron

**Comment by MinChanSike** [comment]
It's embedded clappr player.
You can try ` autoPlay: true` by clappr player's embed parameters.
Extract from `iframe` , player.html, you can use by the following without _iframe_.

```
<script src="js/clappr.min.js"></script> //in <head>
<div id="player" style="position:absolute;top:0;right:0;bottom:0;left:0"></div>
    <script>
        var videoPath = "http://10.1.2.192:8080/hls/live.stream.m3u8";
        var posterPath = "http://10.1.2.192:8080/images/live.jpg";

        var player = new window.Clappr.Player({
            'source': videoPath,
            'parentId': '#player',            
            'poster': posterPath + '?t=' + String(new Date().getTime()),
            'mediacontrol': {
                'seekbar': '#3daa48',
                'buttons': '#3daa48'
            },
            'autoPlay': 'true',
            'height': '100%',
            'width': '100%'
        });
        var posterPlugin = player.core.mediaControl.container.getPlugin('poster');
        player.on(window.Clappr.Events.PLAYER_STOP, function updatePoster() {
            posterPlugin.options.poster = posterPath + '?t=' + String(new Date().getTime());
            posterPlugin.render();
        });
    </script>
```

**Comment by christophjohannsdotter** [comment]
correct answer, you have to rebuild the image afterwards.
Maybe we should introdruce an env for autoplay, to define it on container start.
Thanks @MinChanSike .

**Comment by sh-si** [comment]
The problem for me is to rebuild the image. I wasn't able to do it in march 2017 because of outdated dependencies.

**Comment by flybelgium** [comment]
Hello, i'm not an expert but, how to modify player.html ? I can download with Navigator like Firefox but after ? How i can overwrite player.html with autoplay ? Thank you

**Comment by christophjohannsdotter** [comment]
This Bug has already been closed, please create a new issue.
