### ISSUE TITLE
starting restreamer docker raspberry pi

### ISSUE THREAD

**Issue by mickopla** [datarhei/restreamer#281]
I followed all the steps to install Docker on my Raspberry pi 4 and it is installed properly. When i use the command 
docker run -d --restart always \
     --name restreamer \
     -e "RS_USERNAME=admin" -e "RS_PASSWORD=datarhei" \
     -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db \
     --tmpfs /tmp/hls \
     datarhei/restreamer-armv7l:latest

I get commands not found errors and restreamer won't run. 

Am i doing something wrong or using the wrong commands??

Thanks for great software

**Comment by mickopla** [comment]
Fixed this issue

**Comment by ioppermann** [comment]
@mickopla Great! Could elaborate what the issue was?
