### ISSUE TITLE
Stream Buffering after a day

### ISSUE THREAD

**Issue by mickopla** [datarhei/restreamer#285]
I've been running my webcam stream for a few weeks now. The issue i'm having is after a day or so the stream is slow to load with buffering issues. If i stop the stream and restart it fixes the problem. Would it be a limitation of running restreamer on a raspberry pi 4?? My network is all ethernet so don't think speed would be the problem. Any ideas would be appreciated.

**Comment by ioppermann** [comment]
This might be a problem with the nginx-rtmp module. What are the specs of the stream from your camera? If the camera is not delivering a constant or high enough framerate or has high variations in the bitrate is might cause these problems.

**Comment by mickopla** [comment]
I have changed the stream to H.264 with a bitrate of 1mb and 25 fps. Seems to have solved the buffering problem even though its streaming at a higher bit than the previous default

**Comment by mickopla** [comment]
Unfortunately my issues continue even with a 512k stream. I need to stop and restart the stream daily. Not the hardest thing in the world to do but still not ideal when the stream is running 24/7

**Comment by ioppermann** [comment]
The Pi 4 is more than capable to handle this. I still suspect the nginx-rtmp module, that is used to convert the incoming stream to HLS might have some issues. With the upcoming release this problem will probably disappear because this nginx module will not be part of it anymore.

**Comment by mickopla** [comment]
I look forward to the update

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
