### ISSUE TITLE
Replace comboboxes with text/number fields.

### ISSUE THREAD

**Issue by xDololow** [datarhei/restreamer#288]
I think it's worth changing these two fields to just text fields because еhere are not enough options.

![image](https://user-images.githubusercontent.com/26763912/132526827-8ac0d7a1-fcc3-492b-b280-2b2c1cd1b7b7.png)

**Comment by ioppermann** [comment]
This will be available in the next release. You will have some common suggestions and the option to give a custom value.

**Comment by jstabenow** [comment]
Jobs done ;-)
