### ISSUE TITLE
Activate / Deactivate Restreamer remote?

### ISSUE THREAD

**Issue by apofis1969** [datarhei/restreamer#291]
Hi, 
is it possible to Start and Stop the RTMP/RTSP/HLS Video Source and the External Streaming-Server remote?
The reason for the question is, that the camera is not always on. But the Restreamer asks the streaming server continuously, if the stream is online or not. 
I would like to activate and deactivate the query remote.
Is this possible?

**Comment by ioppermann** [comment]
With the upcoming release this will be possible. It'll offer a fully fledged API with which you can control all the streams.

**Comment by apofis1969** [comment]
Great! Do you know when you will release the new version?

**Comment by nikhil96widhani** [comment]
Hello. I am interested to when is the new API version launching, Great product BTW

> With the upcoming release this will be possible. It'll offer a fully fledged API with which you can control all the streams.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
