### ISSUE TITLE
Auto start streams after rpi reboot

### ISSUE THREAD

**Issue by arcangeltech** [datarhei/restreamer#293]
Each time I reboot the rpi I have to manually start the camera stream linked to the restreamer instance while the docker restreamer launches properly. Any help please.

**Comment by Baenwort** [comment]
Would be nice.

**Comment by Baenwort** [comment]
Seems you can do it with: https://datarhei.github.io/restreamer/docs/references-state.html by moding the json and putting in your targets

**Comment by ioppermann** [comment]
If the stream was connected before rebooting the rpi, then it should automatically reconnect the stream after the container is up again. This might be a bug.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
