### ISSUE TITLE
Your stream wasn't accessible. failed to execute ffprobe

### ISSUE THREAD

**Issue by mconfortino** [datarhei/restreamer#295]
Hi everybody, and thank you for such a fine product.
When a try to start this stream in the web interface, I get this message:

Your stream wasn't accessible.
failed to execute ffprobe: Command failed: ffprobe -of json -v error -show_streams -show_format rtsp://root:axis@172.19.50.37/axis-media/media.amp 

However, if I paste the command 

ffprobe -of json -v error -show_streams -show_format rtsp://root:axis@172.19.50.37/axis-media/media.amp

in a console in the same server, it works and I get this:

{
    "streams": [
        {
            "index": 0,
            "codec_name": "h264",
            "codec_long_name": "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
            "profile": "Main",
            "codec_type": "video",
            ................
            ................
        "format": {
        "filename": "rtsp://root:axis@172.19.50.37/axis-media/media.amp",
        "nb_streams": 1,
        "nb_programs": 0,
        "format_name": "rtsp",
        "format_long_name": "RTSP input",
        "start_time": "0.080022",
        "probe_score": 100,
        "tags": {
            "title": "Session streamed with GStreamer",
            "comment": "rtsp-server"
        }
    }
}

Any idea about what is going on here?
Thank you very much.

**Comment by mconfortino** [comment]
Hi. Where can I found the output of the command as executed from eht web interface, or a log file?

**Comment by ioppermann** [comment]
You can set the environment variable `RS_DEBUG` to `true`. Here are some details: https://datarhei.github.io/restreamer/docs/references-environment-vars.html#rs_debug

**Comment by mconfortino** [comment]
Something weird is happening. If I execute the ffprobe command from the host console, it runs ok as the host sees the camera. If I execute it from the container console, it fails, as the container can't see the camera. When I first installed this, it worked fine, and no changes where made to the host network configuration. I'll keep studying this.

**Comment by giovanniquarantadue** [comment]
Same problem:
 failed: ffprobe -of json -v error -show_streams -show_format -rtsp_transport tcp rtsp://user:password@xxx.xxx.xxx.xxx:554/cam/realmonitor?channel=1&subtype=0 
 Can be related to the user and password?

**Comment by ioppermann** [comment]
@giovanniquarantadue This might be. If the username and password contain special characters, the should be URL encoded. E.g. to have a `#` in the username or password will make the ffmpeg URL parser think that URL ends there. So it should be encoded as `%23`.

**Comment by giovanniquarantadue** [comment]
> @giovanniquarantadue This might be. If the username and password contain special characters, the should be URL encoded. E.g. to have a `#` in the username or password will make the ffmpeg URL parser think that URL ends there. So it should be encoded as `%23`.
Hi @ioppermann i've fixed changing the password even with encoded characters not working

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
