### ISSUE TITLE
Question to error code 1

### ISSUE THREAD

**Issue by apofis1969** [datarhei/restreamer#296]
Hi, how can I avoid the error code 1 if I take  a stream from wowza to encode with the restreamer with rtmp using spark Sorensen and speex together? Is there anything I can do?

**Comment by ioppermann** [comment]
This might be a problem with the used audio codecs. Restreamer is transforming the stream to HLS. The Sorensen and speex audio codecs are not supported by HLS.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
