### ISSUE TITLE
Mute sound on Youtube Stream

### ISSUE THREAD

**Issue by mickopla** [datarhei/restreamer#297]
I've been testing a stream to Youtube and its working well. I don't want audio on the stream. Is there a way to mute sound to the Youtube stream like the option in the player?? I have tried switching off the mic on the ipcam but i still get sound.

**Comment by ioppermann** [comment]
Youtube requires that the stream has an audio track. If you don't want the original audio track to be pushed to Youtube, you can use the audio encoding and replace the audio track with silence. Select `aac` as audio codec and `silence` as preset and adjust the other parameter to your liking. Leave the video codec to `copy`.

**Comment by mickopla** [comment]
Thanks a lot, very much appreciated

**Comment by jstabenow** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
