### ISSUE TITLE
Disk is full up

### ISSUE THREAD

**Issue by arcadiush** [datarhei/restreamer#298]
The disk fills up.
what could be causing the disk to be full to 100%?
I see it creates /var/lib/docker/overlay2/........./diff/tmp/hls/live.stream -....... ts files with very large sizes. What are they needed for, can they be removed?

```
Filesystem                        1K-blocks     Used Available Use% Mounted on
udev                                4030500        0   4030500   0% /dev
tmpfs                                710240     1356    708884   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  20511312 13904556   5541796  100% /
tmpfs                               3540428        0   3540428   0% /dev/shm
tmpfs                                  5120        0      5120   0% /run/lock
tmpfs                               3540428        0   3540428   0% /sys/fs/cgroup
/dev/sda2                            999320   305040    625468  33% /boot
/dev/loop0                            43264    43264         0 100% /snap/certbot/1514
/dev/loop2                           101888   101888         0 100% /snap/core/11798
/dev/loop3                            56832    56832         0 100% /snap/core18/2246
/dev/loop5                           101888   101888         0 100% /snap/core/11993
/dev/loop1                            43264    43264         0 100% /snap/certbot/1582
/dev/loop4                            56832    56832         0 100% /snap/core18/2253
/dev/loop6                            63360    63360         0 100% /snap/core20/1169
/dev/loop7                            63360    63360         0 100% /snap/core20/1242
/dev/loop8                            68864    68864         0 100% /snap/lxd/21835
/dev/loop9                            68864    68864         0 100% /snap/lxd/21803
/dev/loop10                           43264    43264         0 100% /snap/snapd/14066
/dev/loop11                           33280    33280         0 100% /snap/snapd/13640
overlay                            20511312 13904556   5541796  100% /var/lib/docker/overlay2/da64ff848efb6299c0bf7627c50c421e0947319ef2596c258399f342e559b383/merged
overlay                            20511312 13904556   5541796  100% /var/lib/docker/overlay2/09cfe85dd979c85260bdd647552d6acd8f83307aad7413c683d283c1004b16fa/merged
overlay                            20511312 13904556   5541796  100% /var/lib/docker/overlay2/61580194be23a521fd078a49d8cb09c52849f3ba07d81eec5debfff97070b0fc/merged
overlay                            20511312 13904556   5541796  100% /var/lib/docker/overlay2/01c0b7d976051fddd1b18ae4e7a48145531b566947a5a3780f3152e2995d334e/merged
tmpfs                                708084        0    708084   0% /run/user/0
```

I have many different folders in / var / lib / docker / overlay2, including 121656ed95701 ....... with different dates, even as of last November, each one takes up a lot of space.
How can I clean here?

**Comment by ioppermann** [comment]
The `.ts` files are the actual video files needed for streaming. When they are very large (what size do they have?), then the stream has a very high bitrate. What are the specs of your stream?

In order not to store the stream on the disk, you can consider using a tmpfs that stores the files in RAM.
https://datarhei.github.io/restreamer/docs/guides-sdcard.html

**Comment by arcadiush** [comment]
These .ts files are created when we press the "pause" button on the player.
Depending on the time, the longer the "pause" button is pressed, the larger the file is generated. The largest one had 8 GB

Is it possible to disable the possibility of pressing the 'pause' button and thus generating these files?
How to disable the menu in the player?

What is the benefit of installing the "tmp / hls" folder in RAM? Won't it block my memory?

**Comment by ioppermann** [comment]
Pressing the pause button has no influence on the creation of these files. They are not created by the player but by the nginx-rtmp module.

The incoming stream should be split in files of at least 2 seconds of video (these are the `.ts` files). If the keyframe interval of the source stream is longer than 2 seconds, then it is split at each keyframe. If your source stream has a very long keyframe interval, then the `.ts` files will become very large (in combination with a high bitrate).

The benefit of having the `/tmp/hls` folder in RAM is, that this will no wear out an SD card (if you are using an SD card). Yes, it would block this amount of memory.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.
