### ISSUE TITLE
Docker warning - image platform doesn't match host platform

### ISSUE THREAD

**Issue by Baenwort** [datarhei/restreamer#299]
When starting restreamer on a Pi I get:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v6) and no specific platform was requested
3aa7aedf0c3ffd9aa394c9ca15f4bc93f9ce5af9a558d47f4dee15da91b83264
```

The fix can be seen in what pi-hole went through here:

https://github.com/pi-hole/docker-pi-hole/issues/735

The short answer is this is a problem with the cross building process. Docker is now detecting this and flagging the error saying it was built in correctly. To fix it you need to update how you use  `buildx` so that it flags the architecture properly.

**Comment by ioppermann** [comment]
@Baenwort The error message suggests that you are using the wrong image. You should use `datarhei/restreamer-armv7l:latest` instead of `datarhei/restreamer:latest`.

https://datarhei.github.io/restreamer/docs/installation-linux-arm.html

**Comment by Baenwort** [comment]
Hi, I'm using the `datarhei/restreamer-armv6l:latest` as it is a Pi Zero W.

This error occurs with the above image. Per the troubleshooting over in PiHole and other projects this is caused by a change in the latest version of Docker that causes it to flag on images build on other platforms that are using a older build process that doesn't set the flags hoe Docker expects. It used to ignore it and now gives that warning.

The image still works it just throws a warning.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.
