### ISSUE TITLE
Error on building of docker image

### ISSUE THREAD

**Issue by sydro** [datarhei/restreamer#30]
Hi, 
i tried to rebuild a docker image on my pc (amd64 - ubuntu 14.04 - docker 1.13), but it did work.

Log report:

```
npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/andrew-shulgin/node-json-db.git /root/.npm/_git-remotes/git-github-com-andrew-shulgin-no
de-json-db-git-a790c886
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-andrew-shulgin-node-json-db-git-a790c886'...
npm ERR! fatal: remote error: 
npm ERR!   Repository not found.

```

i change in packet.json the node-json-db repository with "git://github.com/Belphemur/node-json-db" and it works again.

**Comment by thangdc94** [comment]
Thank you. It fixed my problem too. They changed `node-json-db` module repo.
