### ISSUE TITLE
the problem of stopping very quickly stops 

### ISSUE THREAD

**Issue by halosalman** [datarhei/restreamer#301]
Hi, I've done the same thing, but after a few seconds the stream stops and the automatic will continue and it stops so soon. What is the solution on Server? I'm working on it to restart the TV channel.
For example
[This Video Click Here ](https://ok.ru/video/3517427747463)

**Comment by ioppermann** [comment]
It looks like that you have a very low and variable framerate. This might cause the problem. Can you configure the source such that it generates a constant framerate of at least 10fps?

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
