### ISSUE TITLE
Good System gone bad

### ISSUE THREAD

**Issue by mickopla** [datarhei/restreamer#303]
I've been running restreamer on a pi 4 for a few months with minor issues but today the stream has begun to start and stop constantly. Would the best way forward be to delete the Docker Container and start again like its a new install???

**Comment by ioppermann** [comment]
You might try to re-install the docker container. Please also check if something with the source stream changed.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket will be closing soon.
