### ISSUE TITLE
JQuery 1.2

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer#304]
Just happened to find that this is running  JQuery 1.2 which has some xss issues. Not sure if you still working on this project. 

MEDIUM
JQuery 1.2 < 3.5.0 Multiple XSS

Description
According to the self-reported version in the script, the version of JQuery hosted on the remote web server is greater than or equal to 1.2 and prior to 3.5.0. It is, therefore, affected by multiple cross site scripting vulnerabilities.

**Comment by jstabenow** [comment]
Thank you very much for your comment. We fixed the function in the Restreamer v2 🚀
Have fun with it.
