### ISSUE TITLE
Turn off menu

### ISSUE THREAD

**Issue by arcadiush** [datarhei/restreamer#305]
After hovering over the player window, it slips out from the bottom (progress bar, pause button, volume, etc.) how to turn it off?

**Comment by ioppermann** [comment]
It should disappear if you stop moving the mouse (while it is hovering the video) or you move it out of the video.

**Comment by arcadiush** [comment]
I know that. but I would like to disable this menu completely, especially when the mouse is moved in this window.

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.

**Comment by svenerbeck** [comment]
Sorry, I was a bit hasty with the closing. We will add this to the feature request list. https://github.com/datarhei/restreamer/discussions/345

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
