### ISSUE TITLE
how I can change hls_segment_filename

### ISSUE THREAD

**Issue by neno76** [datarhei/restreamer#306]
How I can change hls_segment_filename like this tream_%Y%m%d_%s.ts ?
Thanks

**Comment by jstabenow** [comment]
We are currently working on the completion of a new release. Hence the question:
What use case? What is it needed for?

In the current version we use the module NGINX-RTMP. And here are the possible options:
https://github.com/arut/nginx-rtmp-module/wiki/Directives#hls_fragment_naming

Just have a look and change the [nginx.conf](https://github.com/datarhei/restreamer/blob/master/conf/nginx.conf) if you found something suitable.

**Comment by neno76** [comment]
Thanks I need use a external streaming server and pass the fragment with timestamp instead of sequenzial

**Comment by jstabenow** [comment]
Thanks! 
Ok, just for the additional output.

Please use:

```sh
"-strftime 1",
"-hls_segement_filename /tmp/hls/live_%Y%m%d&H%M%S.ts",
```

More about this here:
https://ffmpeg.org/ffmpeg-all.html#hls

**Comment by neno76** [comment]
Thanks! working fine !

**Comment by jstabenow** [comment]
Perfect 👍

**Comment by neno76** [comment]
Sorry... renaming the chucks work fine only local, is possibile that this change don't send that chunks remotely ?
