### ISSUE TITLE
RTSP Feed From Unifi Protect Does Not Work

### ISSUE THREAD

**Issue by varunsridharan** [datarhei/restreamer#307]
I am trying to use restreamer with Unifi protect, but it does not work.

The RTSP link I get from Unifi Protect is `rtsps://10.0.100.4:7441/M3oBdx0AmMnk54pq?enableSrtp` and restreamer works only if the URL ends with a file.

**Comment by jstabenow** [comment]
The problem could be RTSPS and/or SRTP. 
If you want, you can contact us for a test (info@datarhei.com).

**Comment by varunsridharan** [comment]
@jstabenow I am down to work on this if you this will help improve this project. to make it work with RTSPS . and in that case lets start here and make most info public so that others who face the same issue can find more info about it

**Comment by varunsridharan** [comment]
@jstabenow I am down to start anytime. Let me know what kind of info and logs you need.

**Comment by jstabenow** [comment]
None of the above. We need access to the RTSPS camera. Everything else is too costly. 
Again: If you want, you can contact us for a test (info@datarhei.com).

**Comment by OllyKl** [comment]
Had the same issue. This is a Unifi related problem. You can access the rtsp stream on Unifi Protect to get restreamer to work:
Change the protocol to rtsp, change the port to 7447 and cut off everything behind the "?". So, if in Protect the following URL ist shown: rtsps://10.0.100.4:7441/M3oBdx0AmMnk54pq?enableSrtp
change it to rtsp://10.0.100.4:7447/M3oBdx0AmMnk54pq for restreamer. Works fine for me.

**Comment by svenerbeck** [comment]
Thank you @OllyKl 
[electronic high5]
cheerio
Sven
