### ISSUE TITLE
Error: Invalid M3U file, an extended M3U file is required.

### ISSUE THREAD

**Issue by phillipsmn** [datarhei/restreamer#309]
I'm trying to send the HLS stream to an external server (another Docker image on my machine) and I am getting the following error:

> Invalid M3U file, an extended M3U file is required.

I'm basically wanting to send the HLS stream to an xTeVe instance so that I can create a channel in Plex. But, xTeVe is looking for an extended M3U and apparently restreamer is not creating one. Is there something that I can do to configure this? I'd love to be able to restream to TVs running Plex using this means.

I'm running restreamer v0.6.8.

When I put the IP and port and stream the HLS to the xTeVe instance, restream GUI shows that it is streaming. But when I go to set up xTeVe in the GUI, that is when I get the error.

**Comment by jstabenow** [comment]
Thank you very much for your comment. Restreamer v2 includes an HLS [publication service](https://docs.datarhei.com/restreamer/knowledge-base/manual/publications).  
Have fun with it.

**Comment by jaseinny** [comment]
> I'm trying to send the HLS stream to an external server (another Docker image on my machine) and I am getting the following error:
> 
> > Invalid M3U file, an extended M3U file is required.
> 
> I'm basically wanting to send the HLS stream to an xTeVe instance so that I can create a channel in Plex. But, xTeVe is looking for an extended M3U and apparently restreamer is not creating one. Is there something that I can do to configure this? I'd love to be able to restream to TVs running Plex using this means.
> 
> I'm running restreamer v0.6.8.
> 
> When I put the IP and port and stream the HLS to the xTeVe instance, restream GUI shows that it is streaming. But when I go to set up xTeVe in the GUI, that is when I get the error.

Hi there. Did you have any luck in getting this to work? I tried also using the HLS publication service but I'm not sure at how to point it to my Xteve docker in Unraid. It keeps seeing my ip4 address and not my local address as I'm trying to restream from restreamer to xteve on the same server. Is there any guidance on how to fill out the HLS publication service? Thank you

**Comment by FilipStadler** [comment]
> Hi there. Did you have any luck in getting this to work? I tried also using the HLS publication service but I'm not sure at how to point it to my Xteve docker in Unraid. It keeps seeing my ip4 address and not my local address as I'm trying to restream from restreamer to xteve on the same server. Is there any guidance on how to fill out the HLS publication service? Thank you

Have you used localhost or bridged docker ip like 172.18.0.1 I have found more easy to use internal docker ip on the same computer as alternative to the real ip,
