### ISSUE TITLE
Username or Password is invalid Login

### ISSUE THREAD

**Issue by connected9** [datarhei/restreamer#31]
Hello  , 
i just Install restreamer ,  try to login , i got 

`Username or Password is invalid
`
tried this 
admin / datarhei 
same problem ,, 

i tried change it in /conf/live.json which i found it in 

`/var/lib/docker/aufs/mnt/672a9bfeb788119d39d1b82cad007c57168982ab191fbb2ee3bf17f4e8c6bfaa/restreamer/conf/live.json
`
to 

`  "auth": {
        "username": "admin",
        "password": "admin"
`

but same problem , 

any idea ?

THanks

**Comment by sydro** [comment]
You can run docker container with this parameters to change default username and password:

```
-e "RESTREAMER_USERNAME=YOUR-USERNAME" -e "RESTREAMER_PASSWORD=YOUR-PASSWORD"
```

**Comment by connected9** [comment]
sorry . i forget when installation i added username & password .. 

worked 100 % now 

Thanks

**Comment by christophjohannsdotter** [comment]
👍  cool, I'm glad to hear that
