### ISSUE TITLE
 different qualities 

### ISSUE THREAD

**Issue by interiran** [datarhei/restreamer#310]
Please add different qualities like 1080 720 480 to the output

**Comment by Restreamdev** [comment]
yes please add output quailities like master playlist.m3u8

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
