### ISSUE TITLE
Add audio filter volume to stream

### ISSUE THREAD

**Issue by pick-and-mix** [datarhei/restreamer#313]
Is there anyway to edit (I assume) live.json to get -af "volume=6dB" to work.

I have a really quiet stream and i used volumestect and I need to boost the audio by 6db.

I have tried adding it to live.json, but it either hasnt worked or errors out.
Any help would be great.

**Comment by ioppermann** [comment]
You should edit the `audio_codec_aac` and/or `audio_codec_mp3`section in the `live.json`. It might look like this for AAC encoding:

```json
"audio_codec_aac": {
   "outputOptions": [
      "-codec:a aac",
      "-bsf:a aac_adtstoasc",
      "-af volume=6dB",
   ]
},
```

In the UI you have to select AAC encoding for the audio stream.

**Comment by ioppermann** [comment]
How did you transport this modification into the container? Did you build your own image?

You can also simply mount the modified `live.json` in to the official image by adding this option to your docker command, e.g.:

```
docker run ... -v /path/to/your/modified/live.json:/restreamer/conf/live.json ... datarhei/restreamer:latest
```

**Comment by pick-and-mix** [comment]
The way I done it was:
SSH into server and then run:
`sudo docker exec -t -i restreamer /bin/bash`
Installed nano the first time I logged into docker.
`cd /restreamer/conf`
`cp live.json live.json.bck` This is a backup of the original file, in case of problems.
`nano live.json`
Make changes and save.
`exit`
`sudo reboot`

If it doesnt work go back in and run:
`cp live.json.bck live.json`
and reboot

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.

**Comment by svenerbeck** [comment]
Sorry, I was a bit hasty with the closing.  We will add this to the feature request list. https://github.com/datarhei/restreamer/discussions/345

**Comment by jstabenow** [comment]
Hello @pick-and-mix 
The v2.2.0 now supports the volume filter. Here is a overview:
https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-to-use-the-audio-filters

Here it is:
Video Edit > Audio Settings > Audio Encoding (AAC/MP3) > Filter

Cheers

**Comment by svenerbeck** [comment]
💛 If you were satisfied with the support, and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**.
