### ISSUE TITLE
Start and Stop stream at certain times

### ISSUE THREAD

**Issue by mickopla** [datarhei/restreamer#315]
Is there anyway i can set the stream to start and stop at certain times??? Currently i don't run the stream at night so i manually need to stop and restart the next morning. 
Cheers

**Comment by MattWAnderson** [comment]
Depending on what you run it on, you can use a Windows Task, or a cron job.

 Example cron job on linux would be 
docker stop restreamer 
docker start restreamer 

run this at the times you wish for it to happen.

**Comment by mickopla** [comment]
Thanks for that, I'm running on a raspberry pi 4 raspian os

**Comment by svenerbeck** [comment]
Hello,
we added a feature request. https://github.com/datarhei/restreamer/discussions/345
cheerio
Sven
