### ISSUE TITLE
Audio track selection

### ISSUE THREAD

**Issue by istoutjesdijk** [datarhei/restreamer#317]
Is it possible to select a specific audio track or audio language from the source stream?

**Comment by svenerbeck** [comment]
Hey ho istoutjesdijk
Unfortunately not. Not even with the new version. We'll include that as a feature. 
Take a look here: https://github.com/datarhei/restreamer/discussions/345
cheerio
Sven

**Comment by ioppermann** [comment]
Actually, it is possible to choose a specific audio track from the source stream, however, you have to know which audio track to choose because their language (provided that this information is available) is not yet displayed in the list of audio tracks.
