### ISSUE TITLE
Show image, when no stream/stream disconnects

### ISSUE THREAD

**Issue by eustachy84** [datarhei/restreamer#318]
Hello

Is there a possibility to show image, when there is no stream, or stream disconnects? #

**Comment by whig0** [comment]
That would be a really nice feature to keep youtube streams online!

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
