### ISSUE TITLE
Hivision Failed to Play RTSP Stream

### ISSUE THREAD

**Issue by kiteboy** [datarhei/restreamer#32]
Hi 

First time using this app and looks promising
My RTSP stream play fine in VLC and via angelcam for testing purposes using the following for a hikvision
DS-2CD2332-I camera
rtsp://addadadadad:333333333@mydynamicdns:554/video.h264

When I try the same link on restreamer it cant detect the stream
Any advice would be great - this is a bit of a learning curve!!

**Comment by martinwiest** [comment]
Hi,
i got a setup with hikvision and the url you are using should work. I don´t know how your setup looks in details.
Can you test it with the real ip than mydynamicdns in the url? Maybe it´s a problem with DNS

Regards,

Martin

**Comment by kiteboy** [comment]
Tried with my public IP and get the same thing 
Dynamic DNS working fine with other stuff I have running on the server -ie sonarr, radarr etc

Tried using dynamic dns and the following links on a laptop using vlc (connected on same wifi as restreamer)
rtsp://username:pass@hello.ddns.net:554/Streaming/Channels/1
rtsp://username:pass@hello.ddns.net:554/Streaming/Channels/2
rtsp://username:pass@hello.ddns.net:554/video.h264

All work fine and display live stream with no problems

**Comment by martinwiest** [comment]
Do i get it right? You got the restreamer running local and your cam is on an remote place you connect to over dyndns?

**Comment by kiteboy** [comment]
No actually all running locally  - ive tried the internal IP too

Argh god damm it - used the server IP not the camera its detected now using
rtsp://username:pass@hello.ddns.net:554/video.h264

Thanks for the sanity check!

**Comment by christophjohannsdotter** [comment]
Great to hear 👍  Happy Streaming
