### ISSUE TITLE
Is it possible to restream from direct m3u8 URL?

### ISSUE THREAD

**Issue by fuad00** [datarhei/restreamer#320]
I'm getting this issue:
![CleanShot 2022-03-30 at 13 48 47@2x](https://user-images.githubusercontent.com/26776550/160814971-92373103-9991-4adc-9bc0-803e5e97e859.png)

**Comment by FilipStadler** [comment]
If you run more than one than one restreamer the number 2-3 can pull the stream from the first like

http://172.17.0.1:8087/hls/live.stream.m3u8  this way I can have 3 restreamers running where two
of them pulls the same stream the can retransmit to youtube, facebook - I use the internal ip in docker.

**Comment by jstabenow** [comment]
@fuad00 
Please check the new release and close the issue if your problem has been solved. 
Thanks 👍

**Comment by Elize-cel** [comment]
https://player.restream.io/?token=2c8a9196085b4e1c9c25450451f55bd8
