### ISSUE TITLE
Ability to add text overlays

### ISSUE THREAD

**Issue by Countryman98** [datarhei/restreamer#325]
Just wondering if there is going to be the ability to overlay live text onto the live streams (Ay Bottom).
 Currently can add an image but text would be an improvement and something i'd love to see!
Love the software by the way!
Thanks

**Comment by svenerbeck** [comment]
Good hint. I have taken it with us to the list[ feature request](https://github.com/datarhei/restreamer/discussions/345) list.

**Comment by Gsonovb** [comment]
I need this too
My recent DIY surveillance output is mjpg, but there is no time information in the video stream,
When an input interrupt occurs, the video will repeatedly play the last cached content

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
