### ISSUE TITLE
SRT input listener mode howto guide is missing.

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#329]
The new restreamer is so very cool - adding outgoing transmission destinations is cool.
But I how do I add SRT input in mode listener ?

**Comment by jstabenow** [comment]
Thanks! @FilipStadler
We add this to the documentation 👍

**Comment by jstabenow** [comment]
Sorry. It's not working at the moment.

Would that be a solution?
https://github.com/datarhei/restreamer/issues/287

**Comment by FilipStadler** [comment]
I used to do like this with srt and systemd on my raspberry to get srt to rtmp

[Unit]
Description=SRT to  rtmp

Wants=network.target
After=syslog.target network-online.target

[Service]
Type=simple
Restart=always
RestartSec=5s

# Set the ports and passphase and rtmp url key to match
# EnvironmentFile=/etc/default/srt-owncast.conf
# SRT_LISTEN_PORT="1935"
# SRT_PASSPHRASE="Soliasd1daritet"
# RTMP_PUSH_URL="rtmp://127.0.0.1:1935/live/key"

ExecStart=/usr/bin/ffmpeg -re -i "srt://:$SRT_LISTEN_PORT?mode=listener&passphrase=$SRT_PASSPHRASE" -c copy -f flv $RTMP_PUSH_URL

# ExecStart=/usr/bin/ffmpeg -re -i "srt://:1935?mode=listener&passphrase=sillypassword" -c copy -f mpegts srt://127.0.0.1:4001

KillMode=process
NoNewPrivileges=true
User=nobody
Group=nogroup
[Install]
WantedBy=multi-user.target

I did use the restreamer container for rtmp push part to other destination - but  it was slow and the replaced
the restreamer with this https://github.com/ALLATRA-IT/srt-server  and made systemd service files to enable
stream pulling input from the srt https://github.com/ALLATRA-IT/srt-server and it was alot faster but I was missing
the cool GUI that the restreamer have - I am not a programmer but I am really missing the SRT listerner mode
and for input.   I can also pull the srt stream from srt server as it just runs localy and stream to the restreamer.
I have not used the srt rendeuvis mode where listener/caller mode is more like the push and pull part for rtmp.

Anyway using the restreamer for a portable solution conneced to a camlink4K caputure card is possible.
For some strange reason I have to select the audio and later add it as the Audio via ALSA but this because
on the raspberry I also have a Talkback where it makes a SRT connection to a SRT server so its possible
to speak to the camera operator.   I use the https://github.com/ALLATRA-IT/srt-server to make the talkback
service where raspberry just pulls a srt stream.

I will also try the restreamer on a RGB Mini+ videomixer with raspberry and maybe even make it possible
so stream both the program out and the videomixer preview because then I just need to add vpn to
allow app or all ready made software to remotely control the videomixer

One nice thing about the restreamer is that I can add a rtmp server and do srt restream from a gopro or a Mevo camera so I my  raspberry is just running a stream with camlink but also I can add the gopro/mevo input 

Also https://github.com/Eyevinn/toolbox have srt2rtmp solution but its missing the nice gui that restreamer 2.0 have
as this is grea user very friendly solution but the SRT listener mode is really the only thing I am missing.

I hope someone make a container that works and look like the restreamer 2.0 thay may include srt listerner mode.
I really like the restreamer solution as a in between.  Its a nice tool and I run it on a raspberry PI4 to do portable streaming from my own or a local tv station OBS/Vmix and with a battery  - also it would be possible to add SRTLA
https://github.com/BELABOX/srtla  I only do use OMX enconder on the raspberry4 and tobad h265/hvec is not possible.

I look forward to Restreamer 3.0 also and maybe srt listerne mode  then ;)

**Comment by jstabenow** [comment]
Wow, thanks for all the information. We will discuss this and add it to the roadmap 👍

**Comment by jstabenow** [comment]
Hey @FilipStadler 
The v2.2.0 now supports SRT listening (server). Here is a tutorial for OBS via SRT > Restreamer:
https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-to-stream-srt-from-obs

We are looking forward to your feedback.

**Comment by FilipStadler** [comment]
Great - the SRT listener mode is working fine and its usefull.
Both caller and listener mode this really great.
