### ISSUE TITLE
Error with RTSP

### ISSUE THREAD

**Issue by Rmpjunior** [datarhei/restreamer#33]
Hello,
I'm facing a trouble with restreaming of a IP Camera. The RTSP URL is ok(I tested with VLC Player), but when I start the restream on restreamer(I'm using Kitematic and Windows 8), I'm get the following error:
"[25-03-2017 01:37:54.346] [ERROR] Error on stream repeatToLocalNginx: Error: ffmpeg exited with code 1: rtmp://127.0.0.1:1935/hls/live.stream: Invalid argument"

How can I fix this?

**Comment by ofadam** [comment]
I'm having this same issue – did you find a solution?

**Comment by svenerbeck** [comment]
Hey Ho,
which camera are you using?

Cheerio
Sven
