### ISSUE TITLE
Problems with rtmp streaming

### ISSUE THREAD

**Issue by jstabenow** [datarhei/restreamer#330]
Issue:
but now i have problems with rtmp streaming usually i put the address in old version
example
rtmp://address/key
but now nothing happen only i get error :(

History:
https://github.com/datarhei/restreamer/issues/326#issuecomment-1126624438
https://github.com/datarhei/restreamer/issues/326#issuecomment-1126788574
https://github.com/datarhei/restreamer/issues/326#issuecomment-1127001688

-----

[@Inzombie](https://github.com/Inzombie)
Please attach the process report:
https://docs.datarhei.com/restreamer/knowledge-base/manual/process-report

**Comment by Inzombie** [comment]
Attach file from the process report, i replace the url from my source.

**Comment by jstabenow** [comment]
@Inzombie
Thank you for the report. Not everything has been anonymised yet. Sorry. We will fix that.

Did you send the correct process report? This is a pure HLS <- FFmpeg -> HLS process:

```json
{
    "progress": {
        "inputs": [{
                "id": "input_0",
                "address": "http://[anonymized]",
                "index": 0,
                "stream": 0,
                "format": "hls",
                "type": "video",
                "codec": "h264"
            },
            {
                "id": "input_0",
                "address": "http://[anonymized]",
                "index": 0,
                "stream": 1,
                "format": "hls",
                "type": "audio",
                "codec": "aac"
            }
        ],
        "outputs": [{
                "id": "output_0",
                "address": "http://[MemFS]",
                "index": 0,
                "stream": 0,
                "format": "hls",
                "type": "video",
                "codec": "h264"
            },
            {
                "id": "output_0",
                "address": "http://[MemFS]",
                "index": 0,
                "stream": 1,
                "format": "hls",
                "type": "audio",
                "codec": "aac"
            }
        ]
    }
}
```

Feel free to send the report to support@datarhei.com. But please use the Issue-ID as subject.

**Comment by FilipStadler** [comment]
Do you try to stream to a restreamer hidden destination behind cloudflare proxy ?

Maybe you should make a name/destination not proxy behind cloudflare proxy and see how this works.
I also use cloudflare and nginx proxy manager but I use a non proxy name came to push/get stream input.

**Comment by jstabenow** [comment]
The problem is unclear and was discussed by email. 
In the end, it looked like problematic RTMP targets. 

@Inzombie 
If we can help, get back to us or reopen the issue. 
Thanks
