### ISSUE TITLE
 Failed to add an RTSP Stream

### ISSUE THREAD

**Issue by henriquelucas** [datarhei/restreamer#334]
When adding an RTSP Stream I get an error:
_Font verification failed. Please check the address._

I tested the address using VLC and it works there without a problem.

Here's my RTSP:

**rtsp://192.168.0.206:554/cam/realmonitor?channel=1&subtype=0**

**Comment by jstabenow** [comment]
Crazy. I have never seen `Font verification failed. Please check the address` before.

Would you like to say something about the camera manufacturer and the model?

**Comment by henriquelucas** [comment]
In previous versions of Restreamer it worked normally. Here's information about the DVR model and the manufacturer, also a forum link where it shows us which RTSP is for the current model. I'm putting screen prints of RTSP working in a VLC Player.

DVR Intelbras
Model: MHDX 1016
Forum Intelbras: https://forum.intelbras.com.br/viewtopic.php?t=56068

![ss](https://user-images.githubusercontent.com/31218658/169352158-478cd46d-315c-468f-a220-e0f7df9addf7.png)
![ss01](https://user-images.githubusercontent.com/31218658/169352179-cb76d3b0-2a89-4d6a-828c-37fe7cf1e3fe.png)
![ss02](https://user-images.githubusercontent.com/31218658/169352194-f40c074b-6282-4e2f-a8b6-f96e9c737712.png)

**Comment by jstabenow** [comment]
Okay, we have no experience with the manufacturer. For us to help, we would need to be able to connect to your camera. 

If that is possible, write to support@datarhei.com. That would be interesting.

**Comment by henriquelucas** [comment]
Yes, it is possible to send information on how to connect. Via Email.

**Comment by henriquelucas** [comment]
Log
`ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[rtsp @ 0x7faed603a1c0] method OPTIONS failed: 401 Unauthorized
rtsp://admin:Red4815%2540@192.168.0.206:554/cam/realmonitor?channel=1&subtype=0: Server returned 401 Unauthorized (authorization failed)`

**Comment by jstabenow** [comment]
Okay, that looks like a copy+paste error. 

VLC:
rtsp://admin:Red4815@@192.168.0.206:554/cam/realmonitor?channel=1&subtype=0

Log:
rtsp://admin:Red4815%2540@192.168.0.206:554/cam/realmonitor?channel=1&subtype=0

Try:
rtsp://admin:Red4815@192.168.0.206:554/cam/realmonitor?channel=1&subtype=0

And please change the access data. This should not be public ;-)

**Comment by henriquelucas** [comment]
So I tried. The RTSP is correct, but I don't know why when I click on probe the log converts the @ to %2540

**Comment by jstabenow** [comment]
Let's take a look tomorrow. Maybe it is a Unicode problem. 
Or change the credentials and use a password without @.

**Comment by henriquelucas** [comment]
Solved, that's the problem. When changing the password to one that does not include special characters it works just fine. Probably the problem is in the field where you add the password, considering that in the field where you add the RTSP it keeps the character even after generating the log.

**Comment by jstabenow** [comment]
Good to hear 👍  Tomorrow we will check the special character.

**Comment by jstabenow** [comment]
Hey @henriquelucas 
Release v2.1.0 is out now and the escape is fixed. Thanks for your hint 👍

**Comment by jeevadark** [comment]
hey team is there anyone on can help on this ?
ffprobe "rtsp://admin:tlJwpbo6@192.168.60.151/cam/realmonitor?channel=1&subtype=0"
ffprobe version 8.1-3+b1 Copyright (c) 2007-2026 the FFmpeg developers
  built with gcc 15 (Debian 15.2.0-16)
  configuration: --prefix=/usr --extra-version=3+b1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --disable-pocketsphinx --disable-libcaca --disable-libmfx --disable-omx --enable-gnutls --enable-libaom --enable-libass --enable-libbs2b --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libglslang --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-openal --enable-opencl --enable-opengl --disable-sndio --enable-libvpl --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-ladspa --enable-libbluray --enable-libdvdnav --enable-libdvdread --enable-libjack --enable-libjxl --enable-libpulse --enable-librabbitmq --enable-librist --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libx264 --enable-libzmq --enable-libzvbi --enable-lv2 --enable-sdl2 --enable-libplacebo --enable-librav1e --enable-librsvg --enable-shared
  libavutil      60. 26.100 / 60. 26.100
  libavcodec     62. 28.100 / 62. 28.100
  libavformat    62. 12.100 / 62. 12.100
  libavdevice    62.  3.100 / 62.  3.100
  libavfilter    11. 14.100 / 11. 14.100
  libswscale      9.  5.100 /  9.  5.100
  libswresample   6.  3.100 /  6.  3.100
[rtsp @ 0x55cb1b38c180] method DESCRIBE failed: 401 (Unauthorized)
rtsp://admin:tlJwpbo6@192.168.60.151/cam/realmonitor?channel=1&subtype=0: Server returned 401 Unauthorized (authorization failed)
