### ISSUE TITLE
404 when loading

### ISSUE THREAD

**Issue by icarus747** [datarhei/restreamer#335]
Hello,
When following the example from this readme in docker I get the following error. 
```
{"code":404,"message":"File not found","details":["/index.html"]}
```
When exec the container looking in core/ui
```
/core # ls ui/
_player              asset-manifest.json  index.html           logo512.png          robots.txt
_playersite          favicon.ico          logo192.png          manifest.json        static
/core # ls
bin         config      data        mime.types  ui
```
```
/core # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 {run.sh} /bin/sh /core/bin/run.sh
   13 root      0:00 ./bin/core
   90 root      0:00 /bin/sh
   96 root      0:00 ps -ef
```
Not sure what I'm missing.  Running on Ubuntu 18.04.6 LTS, Docker version 20.10.13

**Comment by ioppermann** [comment]
You have to load `/ui` instead of `/`.

**Comment by MattWAnderson** [comment]
confirm same issue, /ui works here on Ubuntu install.

**Comment by icarus747** [comment]
> You have to load `/ui` instead of `/`.

Aw ok that worked, thank you. Was used to the way 0.6.8 worked with index.html in the root web directory.
