### ISSUE TITLE
Typo in Settings on viewing page

### ISSUE THREAD

**Issue by MattWAnderson** [datarhei/restreamer#336]
When viewing the stream in settings title is spelt incorrectly as "Titel:"

**Comment by ioppermann** [comment]
@MattWAnderson Could you please provide a screenshot?

**Comment by MattWAnderson** [comment]
[https://ibb.co/86SgdSc](url)

**Comment by ioppermann** [comment]
This has been fixed in the 2.0.1 release. How to update, see https://docs.datarhei.com/restreamer/installing/update#update-v.2-to-greater-than-2.x
