### ISSUE TITLE
Error 404 JSON in the frontpage index

### ISSUE THREAD

**Issue by CrashOv62** [datarhei/restreamer#337]
hello and thank you for this long-awaited version 2.0!
It turns out that there is an error when I connect to the UI interface: http://myip:8080/ui there is no problem... but when I uncheck the "playsite" and I I connect to the address: http://myip:8080 directly I get a 404 JSON error: {"code":404,"message":"File not found","details":["/index.html "]}
How can I customize this page more easily by putting a text or a logo or a background image....? Is it (or will it be) possible to customize this frontpage via the ui directly? 

thx

**Comment by ioppermann** [comment]
The `/index.html` is taken from the directory that you mount to `/core/data`. There you could place your own `index.html` and any additional files. However, when you activate the Playersite again, the `index.html` will be overwritten.

**Comment by jstabenow** [comment]
Hey @CrashOv62 
Here a [quick guide](https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-to-integrate-a-website)
Thanks for your hint 👍
