### ISSUE TITLE
nginx caching proxy configuration

### ISSUE THREAD

**Issue by sandroshu** [datarhei/restreamer#338]
Hi,

I am trying to set up multiple nginx servers as reverse caching proxy to restreamer 2.0.

So far I did the following. It is working fine as a reverse proxy to restreamer but it does not cache the segments.
I see that in 2.0 there are query strings added to the playlist and playlist items (ts) too.

```
proxy_cache_path /tmp/restreamercache levels=1:2 keys_zone=restreamer_cache:10m max_size=10g inactive=10m use_temp_path=off;

server {
    ...
    location / {
        proxy_pass http://1.2.3.4:8080;
    }
    location ~ \.m3u8$ {
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        proxy_pass http://1.2.3.4:8080;
    }
    location ~ /memfs {
        proxy_cache restreamer_cache;
        proxy_pass http://1.2.3.4:8080;
    }
}
```

My goal is to have multiple nginx servers to cache content from one restreamer instance and clients get contents from the "edge" servers instead of the restreamer instance.
Currently clients can stream from the "edge" servers but not from cache, I can see full bandwidth on the restreamer instance.

I discovered that in VLC the title changes from the edge URL to the restreamer intances URL/<id>/oembed.json

Update: I actually started using my brain and enabled logging plus added proxy_cache_key $scheme$proxy_host$uri; to memfs location. Now I see that there are actual HITS.
I still have no idea where VLC gets that title meta it would be nice to have it set to something custom.

**Comment by ioppermann** [comment]
The query strings are added in order to track how many people are watching the stream. If you have caching edges in front, this number won‘t be reliable anyways. You can deactivate this by setting `sessions.enable` to `false` in the config.json or set the environment variable `CORE_SESSIONS_ENABLE=false`.

**Comment by sandroshu** [comment]
My solution (for now) is the following:

```
location ~ \.m3u8$ {
        access_log     /var/log/apache2/domains/x.hu.log rt_cache;
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        proxy_pass http://stream.x.hu:8080;
}
location ~ /memfs {
        access_log     /var/log/apache2/domains/x.hu.log rt_cache;
        proxy_cache restreamer_cache;
        proxy_cache_key $scheme$proxy_host$uri;
        proxy_ignore_headers X-Accel-Expires;
        proxy_ignore_headers Expires;
        proxy_ignore_headers Cache-Control;
        proxy_pass http://stream.x.hu:8080;
}
```

```
proxy_cache_path /tmp/restreamercache levels=1:2 keys_zone=restreamer_cache:10m max_size=10g inactive=10m use_temp_path=off;
log_format rt_cache '$remote_addr - $upstream_cache_status [$time_local]  '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent"';
```

Viewer count does seem to work well enough so I did not disable it (on a 50 client test it counted 52).

The clients title still reset to http://main.restreamer.instance/id/oembed.json
