### ISSUE TITLE
No USB Devices or Hardware device detected

### ISSUE THREAD

**Issue by cristianr503** [datarhei/restreamer#339]
I'm running Restreamer using Docker on a Windows 10 virtual machine and having trouble seeing any hardware devices. I've verified that the VM host can detect and access my USB camera but Restreamer is not seeing it. Please advise.

![image](https://user-images.githubusercontent.com/8623337/169673907-9dc49d38-b9f8-4ebf-97ed-b7bcd53b82d3.png)

**Comment by cristianr503** [comment]
Update: I found that USB Camera streaming is only available on Linux Docker hosts:
"Your USB camera needs to be v4l (Video4Linux) compliant in order to work with Restreamer. Because of this, USB cameras currently work only with Restreamer on Linux Docker hosts."

Unfortunately, I get the same results on linux :(

I also verified that the Ubuntu host can see my camera but Restreamer does not see it.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8623337/169679860-abecca58-214a-4f3a-b9a5-d55456c1adb2.png">

**Comment by ioppermann** [comment]
Try to add the `—privileged` option to your Restreamer docker command. With this all host devices will be mapped into the container.

**Comment by cristianr503** [comment]
> 

I ran the following:
sudo docker run -d --privileged --restart always --name restreamer -e "RS_USERNAME=admin" -e "RS_PASSWORD=datarhei" -e "RS_MODE=USBCAM" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db --device /dev/video0:/dev/video datarhei/restreamer:latest


Unfortunately, Restreamer is still not detecting any hardware devices..

**Comment by jasunen** [comment]
I have the same issue with docker 20.10.16 on Ubuntu 20.04 PC/AMD64. 

This docker run command works just fine for restreamer 0.6.8 and USB cam with audio, I do not even need to provide --privileged:
`sudo docker run -d --restart always --name restreamer 
 -e "RS_USERNAME=admin" -e "RS_PASSWORD=datarhei" -e "RS_MODE=USBCAM" 
 -p 8080:8080 
 -v /mnt/restreamer/db:/restreamer/db 
 --device /dev/video0:/dev/video 
 datarhei/restreamer:0.6.8`

But with restreamer 2.x:
`sudo docker run -d --restart=always --name restreamer 
 -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data 
 --privileged 
 -p 8080:8080 -p 8181:8181 -p 1935:1935 datarhei/restreamer:latest`

Does not detect any local video device and only gives "Network Source" and "Internal RTMP server" options.
Any ideas?

**Comment by ioppermann** [comment]
@jasunen Your docker command for 2.x is ok. However, you should use for now the Raspberry Pi image (`datarhei/restreamer:rpi-latest`) because the `:latest` image is currently missing the v4l drivers.

**Comment by PerpEternal** [comment]
> @jasunen Your docker command for 2.x is ok. However, you should use for now the Raspberry Pi image (`datarhei/restreamer:rpi-latest`) because the `:latest` image is currently missing the v4l drivers.

When will `datarhei/restreamer:vaapi-latest` support usb camera

**Comment by jstabenow** [comment]
Hey folks,
Release v2.1.0 is out now and V4L2 + VAAPI is fixed. Thanks for your hint 👍
