### ISSUE TITLE
failed to update ingest process - invalid JSON error in 2.0.0

### ISSUE THREAD

**Issue by INDAVO** [datarhei/restreamer#341]
Hi,

first of all, thank you for this next level of restreamer development.
Now, only add native h.265 support without re-encoding and the tool is near to perfection ;)
(Streammedian just recently released a new version of their web player which supports h.265 RTSP playback in the browser (based on java script)  https://streamedian.com/demo/h265/  )

But here is the issue I have with the new version of restreamer 2.0.0:

If you create a new streaming resources and go to the "processing & control" settings page, there is an option for the screenshot interval (set to 60 seconds). I use this feature for a still picture option on my website.
In the recent 0.6.8 version of restreamer it was possible to set this via environment variable to 10 seconds. Now, whatever value I try to set, the error message "Failed to update ingrest process - invalid JSON" appears on the right side (see screenshot).

![Screenshot 2022-05-25 085933](https://user-images.githubusercontent.com/40394932/170202030-e06a8a41-67d7-49ec-a473-11e170eb79c6.png)

By the way, I use restreamer as Docker container on Windows 11 with WSL2.

Thank you.
INDAVO

**Comment by ioppermann** [comment]
Yes, this is a bug. I was able to reproduce it. A fix will be in the next release. For now you should leave this value untouched when you create a new streaming resource.

H.265 support is on our radar.

**Comment by jstabenow** [comment]
Hey @INDAVO 
Release v2.1.0 is out now and the interval is fixed. Thanks for your hint 👍
