### ISSUE TITLE
feature add: Scheduling

### ISSUE THREAD

**Issue by Radixb** [datarhei/restreamer#342]
Thank you for a wonderful product!
I have a feature request - It would be great to be able to set streaming schedules, whether one-time or daily repeat schedules.  Please consider adding this feature in the future.

Many thanks!

Radix

**Comment by MattWAnderson** [comment]
This can be done with Cron Jobs on the system by starting and stopping the docker container(s)

**Comment by CrashOv62** [comment]
Hello,

there has already been a request for this function already made... this concerned Youtube but it is also possible to do this for other broadcasting platforms...

here is the thread:
https://github.com/datarhei/restreamer/issues/237

;)

**Comment by svenerbeck** [comment]
Thank you [CrashOv62](https://github.com/CrashOv62) and [Radixb](https://github.com/Radixb) 
The proposal has been included here as a [feature request ](https://github.com/datarhei/restreamer/discussions/345.)
🤝 cheerio
Sven

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
