### ISSUE TITLE
Windows install errors

### ISSUE THREAD

**Issue by poopyface0931** [datarhei/restreamer#343]
I've just reinstalled Docker and recently rebooted. The Docker 'Getting started' test container installs and runs fine.

I'm having challenges installing Restreamer. I attempt to run the command:

docker run -d --restart=always --name restreamer \
-v /opt/restreamer/config:/core/config \
-v /opt/restreamer/data:/core/data \
-p 8080:8080 -p 8181:8181 -p 1935:1935 \
datarhei/restreamer:latest

I get:

PS C:\Windows\system32> docker run -d --restart=always --name restreamer \
docker: invalid reference format.
See 'docker run --help'.
PS C:\Windows\system32> -v /opt/restreamer/config:/core/config \
-v : The term '-v' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -v /opt/restreamer/config:/core/config \
+ ~~
    + CategoryInfo          : ObjectNotFound: (-v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> -v /opt/restreamer/data:/core/data \
-v : The term '-v' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -v /opt/restreamer/data:/core/data \
+ ~~
    + CategoryInfo          : ObjectNotFound: (-v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> -p 8080:8080 -p 8181:8181 -p 1935:1935 \
-p : The term '-p' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ -p 8080:8080 -p 8181:8181 -p 1935:1935 \
+ ~~
    + CategoryInfo          : ObjectNotFound: (-p:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> datarhei/restreamer:latest

**Comment by ioppermann** [comment]
@poopyface0931 You have to insert the Docker command on a single line into your shell. Instead of copy/paste this

```
docker run -d --restart=always --name restreamer
-v /opt/restreamer/config:/core/config
-v /opt/restreamer/data:/core/data
-p 8080:8080 -p 8181:8181 -p 1935:1935
datarhei/restreamer:latest
```

use this:

```
docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data -p 8080:8080 -p 8181:8181 -p 1935:1935 datarhei/restreamer:latest
```

You also might use Windows style path for the directories you want to mount, e.g. instead of `-v /opt/restreamer/config:/core/config` it should be `-v d:/opt/restreamer/config:/core/config`.

**Comment by poopyface0931** [comment]
The single line worked, thank you!
FYI: the Windows install instructions show this code as a paragraph and not a single line, thus my confusion (I'm not familiar with Linux/CLI environments):
https://docs.datarhei.com/restreamer/installing/windows-macos
