### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by AslanChile** [datarhei/restreamer#346]
Hello
I'm using Restreamer v2 (datarhei-core v16.7.2) behind a web server: Debian11 + Nginx 1.18
Everything works fine  (Restreamer is awesome) but I can't get HTTPS (HTTP works perfect)

I'm using a subdomain with an A record pointed to my server
Ports 8080, 8181 are opened (UFW)
This is my nginx conf (I think here is my problem)

server {
        listen 443 ssl http2;
        server_name s1.mydomain.com;

        location /restreamer/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://localhost:8080;
        }
} server {
        listen 80;
        server_name s1.mydomain.com;

        location /restreamer/ {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://localhost:8080;
        }
}

I will appreciate your help
Thank you

**Comment by ioppermann** [comment]
You have to configure nginx such that it is able to accept HTTPS connections. This is missing the config you provided. Please check the nginx documentation to find out more: https://docs.nginx.com/nginx/admin-guide/security-controls/terminating-ssl-http/

And more information on reverse proxying: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

If your nginx is already doing the HTTPS termination, you don't need to enable HTTPS in Restreamer.

**Comment by AslanChile** [comment]
Thank you @ioppermann 

I got HTTPS from nginx as you said (without enabling in Restreamer) and it worked perfect
Thanks

**Comment by fuad00** [comment]
i'm also proxifying docker traffic for my containers and i get 502 bad gateway error
![CleanShot 2022-06-27 at 17 14 30@2x](https://user-images.githubusercontent.com/26776550/175962468-64f3b9f8-1c23-4966-adea-ecda7bd9d2eb.png)
