### ISSUE TITLE
Grab direct stream or more compatible m3u8

### ISSUE THREAD

**Issue by svenger87** [datarhei/restreamer#348]
I´m trying to lower the WAN bandwitdh usage for digital signage clients.
The signage solution used is the widely common "Samsung MagicInfo". Used at Burger King etc.

When i setup a streaming source in MagicInfo for example with a german news tv channel "Welt" it works pretty flawless with their original m3u8 file > https://w-news2weltcms.akamaized.net/hls/live/2040885/Welt-NextNews/playlist-960.m3u8

When i pass the original source through Restreamer (pass and transcode have the same outcome) i can play the stream in VLC.
But the Samsung MagicInfo clients won´t play it.

Is there any solution to get the m3u8 compatible?
Or grab the direct stream by not using the m3u8?

**Comment by ioppermann** [comment]
Unfortunately, we don't have a MagicInfo to test with. As something to try out, you could mimic the number of HLS chunks and the chunk size of the original stream. In Restreamer in the "Processing & Control" settings adjust the numbers like this:

![image](https://user-images.githubusercontent.com/57445/171847727-a73c523a-996f-4ba8-8414-d0d2b4e4c895.png)

**Comment by jstabenow** [comment]
@svenger87 
If you still have questions, please reopen.
