### ISSUE TITLE
ssl Bring Your Own Certificate

### ISSUE THREAD

**Issue by ftrescue** [datarhei/restreamer#349]
following information on docs my ssl is still not working please can you help with this thanks 
My domain points to server and works brill on http - i have added ssl to the correct folder

**Comment by svenerbeck** [comment]
Here is the tutorial for the datarhei Core. https://github.com/datarhei/core#tls--https

And as a special for you this  step-by-step explanation for Linux. We will update the docs with this example. 

1. **Create the folder structure** for the backup of the Restreamer: 
`mkdir -p /opt/core/config/ssl /opt/core/data`
2. Copy your "my.cert" and "my.key" into the folder /opt/core/config/ssl/.

3. **Start the Restreamer** with the following additional environments.
```
- CORE_TLS_ENABLE=true
- CORE_TLS_AUTO=false
- CORE_TLS_CERTFILE=/core/config/ssl/my.cert
- CORE_TLS_KEYFILE=/core/config/ssl/my.key

```
4. This is your start command
```
docker run -d --name restreamer --restart=always \
-e CORE_TLS_ENABLE=true -e CORE_TLS_AUTO=false -e CORE_TLS_CERTFILE=/core/config/ssl/my.cert -e CORE_TLS_KEYFILE=/core/config/ssl/my.key \
-v /opt/core/config:/core/config -v /opt/core/data:/core/data \
-p 8080:8080 -p 8181:8181 -p 1935:1935 \ datarhei/restreamer:latest
```

**Comment by ftrescue** [comment]
Thanks @svenerbeck  i will give that a go mate
