### ISSUE TITLE
Multiple Outbound RTMP Streams

### ISSUE THREAD

**Issue by teamcoltra** [datarhei/restreamer#35]
I was wondering if I was missing something or you can only setup one RTMP stream? I would like to stream to both Facebook and Twitch at the same time.

**Comment by lhorace** [comment]
I guess this project is a dud :(

**Comment by martinwiest** [comment]
@teamcoltra 
Actually the only way is to start a second docker container with own parameters:

`First container start:

$ docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=admin" -e "RESTREAMER_PASSWORD=verygoodpass" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer-armv7l:latest

Second container start:

$ docker run -d --name restreamer2 --restart always -e "RESTREAMER_USERNAME=admin" -e "RESTREAMER_PASSWORD=verygoodpass" -p 8090:8080 -v /mnt/restreamer/db2:/restreamer/db datarhei/restreamer-armv7l:latest`

**Comment by AdySan** [comment]
@martinwiest kind of related question, the feature list says 

> Multiple Streaming	✓	Works with more than 1 video source

Is the only way to realize this to run multiple docker containers? Or is there actually a way to add a second video source?

**Comment by martinwiest** [comment]
Hello,
with this version the only way to use multiple sources is to run multiple docker containers.
