### ISSUE TITLE
remote Raspicam to Windows

### ISSUE THREAD

**Issue by poopyface0931** [datarhei/restreamer#350]
Restreamer is not seeing the camera on my Raspi. I've confirmed libcamera is working.

**Comment by svenerbeck** [comment]
Hello [poopyface0931](https://github.com/poopyface0931)
Nice to hear from you.

**Keep in mind**
1. Check "raspi config" to activate the Raspicam
2. Don't forget: [--privileged](https://docs.datarhei.com/restreamer/installing/raspberry-pi-arm) 
3. Use the latest Restreamer v 2.1.0

**If it still does not work**
4. Please send your first Docker command to start the Restreamer.

Cheerio
Sven

**Comment by svenerbeck** [comment]
The ticket will be closing soon.

**Comment by poopyface0931** [comment]
Thanks for your reply Sven.

FYI: the option to enable raspicam has been deprecated in the latest version of Raspberry OS. It's now on by default.

Here's the available Restreamer settings presented on my Raspi - note there's no raspicam option:

![restreamer-1](https://user-images.githubusercontent.com/106410268/174463116-85e8662f-cfa4-428e-802d-f10df4f015c0.jpg)

Here's the functioning camera:

![RASPICAM](https://user-images.githubusercontent.com/106410268/174463132-faa02b21-7775-4f03-af22-bfbe4439c6b0.jpg)

**Comment by ioppermann** [comment]
You might first make the Raspi cam available as a Video4Linux device with this command that you execute on the host system `sudo modprobe bcm2835-v4l2`. Afterwards restart the Restreamer container.

**Comment by poopyface0931** [comment]
Tried the Video4Linux command, but still no raspicam shows up.

Additionally, I update using: 
docker pull datarhei/restreamer:latest 
then reboot restreamer, but continue getting a message in Settings saying 'update available'

**Comment by ioppermann** [comment]
Please use the `datarhei/restreamer-rpi:latest` image.

**Comment by poopyface0931** [comment]
How do I select which image to use? Im confused: I update using this command: 
docker pull datarhei/restreamer:latest 
then restart restreamer. Am I not automatically using the latest image after updating?

**Comment by ioppermann** [comment]
You call `docker pull datarhei/restreamer-rpi:latest` instead of `docker pull datarhei/restreamer:latest`. Also in your docker command for running the container you write `datarhei/restreamer-rpi:latest` at the end instead of `datarhei/restreamer:latest`.

**Comment by poopyface0931** [comment]
When I use:
docker pull datarhei/restreamer-rpi:latest 
I receive the following error: 
WARNING: The requested image's platform (linux/arm) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
I'm using arm64v8, which according to your docs requires: 
datarhei/restreamer:latest

**Comment by ioppermann** [comment]
Sorry, my bad 🤦‍♂️ The actual image is `datarhei/restreamer:rpi-latest`. Please try again with this one.

**Comment by poopyface0931** [comment]
Here's what I did:

1. reflashed card with Raspberry OS 64bit;
2. updated + upgraded;
3. installed Docker;
4. sudo docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data -p 8080:8080 -p 8181:8181 -p 1935:1935 --privileged datarhei/restreamer:latest
5. when raspicam did not appear in Restreamer I applied: sudo modprobe bcm2835-v4l2 and restarted Restreamer; same result

I've run these exact steps with and without --privileged with same result. Raspicam is not an option.

I invite you to install 64 bit Raspian + Docker/Restreamer - from scratch - on a v2cam-equipped 4B. I'm not great with Linux/CLI, but I'm not getting any traction. If you can get it to work - from scratch - please tell me how.

![Untitled-1](https://user-images.githubusercontent.com/106410268/175384221-6d0cbb4e-8331-47e5-b31f-98d4a0e8b810.jpg)

Here's my working libcam, captured a minute ago:

![tempFileForShare_20220623-122853](https://user-images.githubusercontent.com/106410268/175384312-3f7e1524-adb8-49df-8c07-55193b68966d.jpg)

**Comment by ioppermann** [comment]
I will try.

**Comment by ioppermann** [comment]
@poopyface0931 I tried the setup you described and was able to capture the stream from the Raspicam. This only worked by enabling the legacy mode for the camera. The latest Raspbian comes with new tools for the camera based on `libcamera` which is not necessarly compatible with video4linux and is currently not supported by ffmpeg.

This is how to enable the legacy mode:

1. Open `/boot/config.txt` in an editor, e.g. `sudo nano /boot/config.txt`
2. Replace the line `camera_auto_detect=1` with `start_x=1` and `gpu_mem=256` on one line each
3. Save the file and exit the editor
4. Reboot the pi

After the pi rebooted you should see the Raspicam option in the UI. Use the `datarhei/restreamer:latest` docker image.

**Comment by poopyface0931** [comment]
Working now, thank you!
