### ISSUE TITLE
Automatic update procedure not working

### ISSUE THREAD

**Issue by CrashOv62** [datarhei/restreamer#351]
Hello,

What is the exact command to update to the new version of restreamer?
I thought it was done automatically via the interface but no, on top of that the links to the update procedure in the language translations don't work so it's impossible to know what the procedure is...
The "automatic" update from the interface is useless... you can't do it automatically via the interface!

Thank you for your clarification on the updates.

;)

**Comment by svenerbeck** [comment]
Hi [CrashOv62](https://github.com/CrashOv62)
You are right, there is no update via the graphical user interface. 

## Workflow
The update works via a new Docker container. **Stop** Docker Container → **Remove** Docker Container → **Pull** the latest Container → **Start** new Docker Container. 

## Here we go on Terminal
Example for Raspberry Pi (Start with hardware support for arm32v7) documented in our [Docs](https://docs.datarhei.com/restreamer/installing/raspberry-pi-arm.)
 
1. Step find out running CONTAINER ID:  
`docker ps`
2. Step stop running CONTAINER with ID
`docker kill ID` 
3. Step to remove stopped CONTAINER
`docker rm ID `
4. Pull latest Restreamer
`docker pull YourNewRestreamerImage`
e.g. for Raspberry Pi: 
`docker pull datarhei/restreamer:rpi-latest`
5. Start fresh docker container with your environments. 
```
docker run -d --restart=always --name restreamer \
-v /opt/restreamer/config:/core/config \
-v /opt/restreamer/data:/core/data \
-p 8080:8080 -p 8181:8181 -p 1935:1935 \
--privileged \
datarhei/restreamer:rpi-latest
```

### Feature List
I will add the update via the GUI as a feature to the feature list. You will find it here: https://github.com/datarhei/restreamer/discussions/345

If you still need help, contact us.  We will close the ticket in a few days. 

[electronic handshake]
🤝 Sven

**Comment by svenerbeck** [comment]
The ticket will be closing soon.
