### ISSUE TITLE
restream existing m3u8 link to instagram live

### ISSUE THREAD

**Issue by bugbounted** [datarhei/restreamer#353]
Hi [datarhei](https://github.com/datarhei),
please help me to restream existing m3u8 link to instagram live ,
waiting for your response
finest regards

**Comment by svenerbeck** [comment]
Hi [elmirarokni](https://github.com/elmirarokni)
Unfortunately, this is not possible directly. Meta does a lot to prevent external video sources. Instagram is a box. But there is a trick. Download the tool from YellowDuck. https://yellowduck.tv

You can use YellowDuck to stream to Instagram via the Publication Service. 
It's free and works very well. The operation is intuitive. If you have problems, contact me. 
Keep in mind that Instagram only allows 60 minutes at a time. 

If you still need help, write in this issue. Otherwise, I will close this in a few days.

Greetings 
Sven

**Comment by Ryce** [comment]
@svenerbeck Is this not a bit strange? A free tool that is *not* open source, where the people behind the tool are not doxxed? Or even undoxxed contactable via Twitter?

I would not be surprised if its a North Korean Trojan Horse or something.

**Comment by svenerbeck** [comment]
Hello Ryce
Honestly - I have no idea. Had quick research. The developer is from Iceland, and the TLD registered in Iceland is in Reykjavík. Thanks for your hint. Always good to see things critically.

Greetings from Switzerland
Sven

[EDIT] https://restream.io/integrations/instagram/
https://medium.com/yellowducktv/setup-obs-with-yellow-duck-8b56497f4b48

It's weird even when others recommend that. I have to agree with you! [/EDIT]

**Comment by Ryce** [comment]
Yeah I saw the TLD info as well. Iceland could be just a dummy address though, there are services that mask your info. I am a bit worried about using them and wanted to see if I can find more info.

I also sent an email to them, but no reply yet

**Comment by svenerbeck** [comment]
Hey ho Ryce
The best thing would be to integrate the function into the Restreamer - then you know what you have! But, to be honest, this function was not requested that often. The prio on Instagram is therefore low.

Cheerio
Sven

[ Note to myself [https://stackoverflow.com/questions/66698335/ffmpeg-stream-to-instagram-via-instafeed-me-or-yellowduck](https://stackoverflow.com/questions/66698335/ffmpeg-stream-to-instagram-via-instafeed-me-or-yellowduck) ]

**Comment by Ryce** [comment]
Wow, thanks for that link @svenerbeck . It's just a RTMP url. Here I thought they would do something a lot more difficult!

**Comment by svenerbeck** [comment]
This FFMPEG function is already implemented in the current Restreamer via a publication service for Instagram. We only need the streaming ID from Insta via an external service. This streaming key is still missing to complete the publication service. It seems to be a secret how to get this ID. We will implement it immediately if you tell us how to get it.
