### ISSUE TITLE
Can't run web interface on windows.

### ISSUE THREAD

**Issue by dwaynarang** [datarhei/restreamer#354]
I installed docker desktop and then kitematic. then I searched for restreamer and created a copy that said it was running. I do get several errors though.

ts=2022-06-05T22:44:02Z level=INFO component="Import" msg="Database import" version="v1"
ts=2022-06-05T22:44:02Z level=INFO component="Import" msg="Checking for database ..." version="v1"
ts=2022-06-05T22:44:02Z level=INFO component="Import" msg="Database doesn't exist and nothing will be imported" database="/core/config/v1.json" version="v1"
ts=2022-06-05T22:44:02Z level=INFO component="Core" application="datarhei-core" branch="master" build="2022-06-03T15:01:03Z" commit="49a8706637d52cf5f5a9394a0c038845bd86b66d" license="Apache License Version 2.0" repository="https://github.com/datarhei/core" version="16.8.0"
ts=2022-06-05T22:44:02Z level=INFO component="HTTP" msg="Server started" address=":8080"

Database doesn't exist and nothing will be imported seems like maybe something big is missing. Never used docker or kitematic so my bad if its an easy config mistake.

**Comment by svenerbeck** [comment]
Hello dwaynarang
Kitematic is deprecated. Please use Docker Desktop instead. Here are the instructions in our docs.  [https://docs.datarhei.com/restreamer/installing/windows-macos](https://docs.datarhei.com/restreamer/installing/windows-macos)

cheerio
Sven

**Comment by svenerbeck** [comment]
The ticket will be closing soon.
