### ISSUE TITLE
8 second delay on stream

### ISSUE THREAD

**Issue by danagain** [datarhei/restreamer#355]
No matter what settings I change, there is always an 8 second delay on the stream. Is there anyway to reduce this ? 
Thanks.

**Comment by jstabenow** [comment]
Currently not. Low latencies (e. g. LL-HLS, CMAF, LL-DASH) are a future topic.

**Comment by danagain** [comment]
No worries, thanks for the response and great project.

**Comment by modemmike** [comment]
I know webRTC is meant to be peer-to-peer but might be worth also investigating, the latency with that is ridiculous at like sub 500ms.
