### ISSUE TITLE
Need help with HTTPS setup

### ISSUE THREAD

**Issue by danagain** [datarhei/restreamer#358]
Hi,

I am stuck trying to get the stream as HTTPS so I can embed into a website. 
I am running the restreamer in a Google compute engine with http and https traffic enabled.

What I have done so far:

1. I have followed the video in the documentation - "How can I use HTTPS with Let's Encrypt". HTTPS has been enabled in the streamer admin UI.
2. Setup a dynamic DNS service and mapped my servers external Ip to a hostname
![image](https://user-images.githubusercontent.com/18300720/172751000-a3a38565-e14a-4dce-8ebb-7e6ad0007e3a.png)
3. Created an apache reverse proxy server in my VM to forward 80 to 8080 and 443 to 8081
![image](https://user-images.githubusercontent.com/18300720/172750943-c55761eb-882b-410f-bba0-f543d83c985f.png)
4. Verified port 443 is open on my server
![image](https://user-images.githubusercontent.com/18300720/172751110-0cce1d5c-f765-4b34-96df-66db3064ec99.png)
5. Verified logs look good
![image](https://user-images.githubusercontent.com/18300720/172751258-e751f5e2-8815-427b-97c8-68091b08e036.png)

At this point when I try and visit the https link in the Embed HTML, I get the following:

![image](https://user-images.githubusercontent.com/18300720/172751446-91661649-a746-4904-878e-6718dda3022e.png)

I have little to no networking background and am finding it difficult to try and debug what is happening and what to do next. Any help will be greatly appreciated.

Regards,
Dan

**Comment by svenerbeck** [comment]
Hello danagain
The documentation for your case is still missing. We will add it relatively soon. Sorry, there are still some gaps in the documentation - this is known to us, and we are continuously working on it.

As an immediate help, you should look for these keywords: 
- **TCP Proxy** if Restreamer should serve the SSL  
- **reverse Proxy** if you want to serve the SSL on your proxy.  

I am sorry that this is still missing in the documents.  😇

We will close the ticket when the manual is available.

Greetings
Sven

**Comment by danagain** [comment]
Thanks!

 I was able to get it all working. I just didn't setup the SSL certificates properly before.

**Comment by svenerbeck** [comment]
Hey Ho Dan
Nice that it still worked out so quickly.
Thanks also for pointing out a gap in the documentation. The tutorial will come. 

If you want, feel free to show us your project. We will 📢 #shoutout the link to promote it. 
We are always happy to see any project with the restreamer.

Have a lovely weekend from datarhei.com
Sven
