### ISSUE TITLE
IOS Problem

### ISSUE THREAD

**Issue by npsolution** [datarhei/restreamer#359]
On some devices they report me continuous anomalies in the video display, the video is not loaded at all or the upload rotation always appears. happens to you too?

**Comment by jstabenow** [comment]
iOS problems are currently not known. Which iOS versions/browsers and devices does this affect?

**Comment by npsolution** [comment]
iPhone 11 and 13 , Broswer Safari
visit the page at https://www.vistalive.it/carpinone-piazza/

**Comment by svenerbeck** [comment]
> iPhone 11 and 13 , Broswer Safari
> visit the page at https://www.vistalive.it/carpinone-piazza/

> Not Found
> The requested URL was not found on this server.

**Comment by npsolution** [comment]
The syte are on transfering hosting, try later, tanks  NP Solution            Di Passarelli Nicola            Mail: ***@***.***            Cel: 351 90 95 953
-------- Messaggio originale --------Da: Sven Erbeck ***@***.***> Data: 13/06/22  09:28  (GMT+01:00) A: datarhei/restreamer ***@***.***> Cc: Nicola Passarelli ***@***.***>, Author ***@***.***> Oggetto: Re: [datarhei/restreamer] IOS Problem (Issue #359) 

iPhone 11 and 13 , Broswer Safari
visit the page at https://www.vistalive.it/carpinone-piazza/


Not Found
The requested URL was not found on this server.

**Comment by jstabenow** [comment]
@npsolution 
iPhone XS, 11, 13 with the latest iOS version works without problems. 

Question: Are all the streams affected or just one? Please check if the process is faulty and if there are dropouts. Maybe the process is cleaned up too fast.

**Comment by jstabenow** [comment]
We see your camera is back:
1. disable autoplay for testing
2. send an address without proxy

Thanks 👍

**Comment by npsolution** [comment]
I have disabled autoplay but still have complaints on ios devices.  I can't figure it out.

**Comment by jstabenow** [comment]
Please send an address without proxy. Then we continue.

**Comment by npsolution** [comment]
https://streaming.vistalive.cloud/memfs/8d0f047b-0eec-4127-b447-2f913782ddc1.m3u8

**Comment by jstabenow** [comment]
```sh
 curl -Li https://streaming.vistalive.cloud/memfs/8d0f047b-0eec-4127-b447-2f913782ddc1.m3u8
HTTP/2 200 
server: openresty
date: Wed, 15 Jun 2022 10:32:21 GMT
content-type: application/vnd.apple.mpegurl
content-length: 130
last-modified: Wed, 15 Jun 2022 10:32:13 GMT
vary: Origin
vary: Accept-Encoding
x-served-by: streaming.vistalive.cloud
```

It's openresty. Again: Please send an address without proxy. Thanks.

**Comment by npsolution** [comment]
what do you mean when you say no proxy?  do you want the rtsp string directly?

**Comment by jstabenow** [comment]
Your setup probably looks like this:
Client -> Openresty (Reverse Proxy) -> Restreamer

And there are too many sources of error. 

That's why we need direct access to the Restreamer without caching/proxy:
Client -> Restreamer

**Comment by npsolution** [comment]
Hi Jan
I'm trying to install restreamer without using nginx proxy manager but I can't get a ssl.
Currently my procedure is as follows:
install restreamer with the following string:

docker run -d --restart = always --name restreamer \
-v / opt / restreamer / config: / core / config \
-v / opt / restreamer / data: / core / data \
-p 80: 8080 -p 443: 8181 -p 1935: 1935 \

after which I add the following ENV:

CORE_TLS_ENABLE = true
CORE_TLS_AUTO = true
CORE_HOST_NAME = mydomain.cloud

**Comment by npsolution** [comment]
I managed to install the certificates and also Client -> restreamer I have problem viewing from ios
At this point I think it depends on the webcams that you set in copy mode have different encodings. As the problem arises, even if randomly only on some cameras, I will do further tests

**Comment by ftrescue** [comment]
@npsolution I don't think its your set up mate i think its there phones as like you know I have an iPhone and its working brill on all your cams -- you could lower the bit rate on the cams this might help mate

**Comment by npsolution** [comment]
Thanks but I think I've solved it, it's a camera coding problem.

**Comment by jstabenow** [comment]
Hey @npsolution 
Sorry, I assumed that all your cameras were having problems on iOS.
So which codec/setting was the problem?

**Comment by npsolution** [comment]
yes, the problem was found on certain ipcamera that had a particular rtsp string.  changing the string i solved.  Thanks for the support anyway.

**Comment by jstabenow** [comment]
All right. Great that you were able to fix it 👍

**Comment by ceesios** [comment]
I found this issue via google and found a solution that works for me;

Under Processing & Control i've set the ext-x version to 7

multiple ios devices can see the stream now, hope this helps someone.

**Comment by brutesque** [comment]
oof. So simple. But that greatly improved the experience in safari. Thanks @ceesios
