### ISSUE TITLE
Default login credentials not working for me 

### ISSUE THREAD

**Issue by chethan566** [datarhei/restreamer#36]
Hi all,

I downloaded debian version of restreamer into my rasbian os on my raspberry pi 3 everything installed smooth, when i was trying to login in the web browser using default credentials it seems to be not working for me. Also i tried resetting the username and password by running docker, but not working.

So I request you to help me in this regards as soon as possible.

Thanks

**Comment by martinwiest** [comment]
How did you do the first start of the docker restreamer container on your pi? Did you follow the instructions for ARM7 on https://datarhei.github.io/restreamer/docs/installation-linux-arm.html ?

**Comment by chethan566** [comment]
Thanks for the quick reply, yes I did the same
and i got the credentials.

**Comment by martinwiest** [comment]
Did you change the line for starting the container from the example:

docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=YOUR-USERNAME" -e "RESTREAMER_PASSWORD=YOUR-PASSWORD" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer-armv7l:latest

to someting with your own credentials like:

docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=chethan566" -e "RESTREAMER_PASSWORD=mykoolpassword" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer-armv7l:latest ?

If you did, do you have free space on your sd-card? Maybe that sounds like a stupid question, but once this was the problem

**Comment by chethan566** [comment]
No i didn't change, i though default login is admin, but later on realized it is YOUR-USERNAME and YOUR-PASSWORD

**Comment by martinwiest** [comment]
Check if there is actually one container running with:

# docker ps 

If there is a container running, stop and remove it:

# docker stop <container-id> && docker remove <container-id>

Run again the docker run cmd with your own credentials and check again in the browser with same user and pass

**Comment by chethan566** [comment]
Now it is working good
Thanks

**Comment by gigisco** [comment]
Hi, i have the same issue on my linux installation.
i start software so;
docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=giuseppe" -e "RESTREAMER_PASSWORD=giuseppe" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer:latest

and when i access to http://localhost:8080 and put info:
admin
datarhei
i get : Username or Password is invalid

How can i fix this?
thanks

**Comment by chethan566** [comment]
Did you change the line for starting the container from the example:

docker run -d --name restreamer --restart always -e
"RESTREAMER_USERNAME=YOUR-USERNAME" -e "RESTREAMER_PASSWORD=YOUR-PASSWORD"
-p 8080:8080 -v /mnt/restreamer/db:/restreamer/db
datarhei/restreamer-armv7l:latest

to someting with your own credentials like:

docker run -d --name restreamer --restart always -e
"RESTREAMER_USERNAME=chethan566"
-e "RESTREAMER_PASSWORD=mykoolpassword" -p 8080:8080 -v
/mnt/restreamer/db:/restreamer/db
datarhei/restreamer-armv7l:latest ?

If you did, do you have free space on your sd-card? Maybe that sounds like
a stupid question, but once this was the problem

On Sep 26, 2017 3:41 PM, "gigisco" <notifications@github.com> wrote:

Hi, i have the same issue on my linux installation.
i start software so;
docker run -d --name restreamer --restart always -e
"RESTREAMER_USERNAME=giuseppe" -e "RESTREAMER_PASSWORD=giuseppe" -p
8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer:latest

and when i access to http://localhost:8080 and put info:
admin
datarhei
i get : Username or Password is invalid

How can i fix this?
thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/datarhei/restreamer/issues/36#issuecomment-332152351>,
or mute the thread

**Comment by jstabenow** [comment]
Hey,
by the env-vars `RESTREAMER_USERNAME` and `RESTREAMER_PASSWORD` you changed the default user/pass credentials to "giuseppe". Your login is now:
**Username:** giuseppe
**Password:** giuseppe

**Comment by gigisco** [comment]
I believe RESTREAMER_USERNAME and RESTREAMER_PASSWORD is for USER interface i want to go in ADMIN pages to change some configuration parameters.

**Comment by jstabenow** [comment]
admin page? there is no special admin page. sorry, but are you sure you be in the right application? ;-)

**Comment by gigisco** [comment]
Sorry, you are right. 
Parameters value are passed in docker run string.

Cheers,
Giuseppe
