### ISSUE TITLE
Unable to reach a domain

### ISSUE THREAD

**Issue by verticalhost** [datarhei/restreamer#360]
Hello , 
I used the link of the video tutorial for let's encrypt. 
It seems to me that nothing happens. 
![image](https://user-images.githubusercontent.com/100486259/172961208-2fbfebe9-103c-4ac0-8a32-e9f937c224f1.png)
I don't know where the problem comes from

**Comment by svenerbeck** [comment]
Bonjour WaffleBoyQc 
Good to hear from you.

You can't do much wrong. Have you forwarded the ports? 

Please [check](https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-use-https-with-lets-encrypt): 
- Don't forget to forward the public port for HTTPS: 443 to your internal Restreamer IP default port: 8181.
- Don't forget to forward the public port for HTTP: 80 to your internal Restreamer IP default port: 8080

**Do not trigger the mechanism too often - Let's Encrypt does not like that. There is a risk that you will be blocked.**

Greetings 
Sven

**Comment by verticalhost** [comment]
So to running my commands line it's should looks like this right ? 

docker run -d --restart=always --name restreamer \
-v /opt/restreamer/config:/core/config \
-v /opt/restreamer/data:/core/data \
-p 80:8080 -p 443:8181 -p 1935:1935 \
datarhei/restreamer:latest

**Comment by verticalhost** [comment]
I fixed by doing this. 
Sorry for taking time. 

Also are you planning to allowed multi user ?

**Comment by svenerbeck** [comment]
Hi WaffleBoyQc
Nice that you still got it running [electronic high5]

For your question about a user management.
You are welcome to make a feature request here: https://github.com/datarhei/restreamer/discussions/345

Have a sunny ☀️ weekend.

Greetings from datarhei
Sven
