### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by ftrescue** [datarhei/restreamer#365]
Hi guys hope you can help I removed the container and then added the code 👍 

```
docker run -d --restart=always --name restreamer \
-v /opt/restreamer/config:/core/config \
-v /opt/restreamer/data:/core/data \
-p 8080:8080 -p 8181:8181 -p 1935:1935 \
datarhei/restreamer:latest
```

but it wont update the program as still says need a update any i dears would help thanks
 -I'm running on ubuntu/Linux
if you need to log on i do have Anydesk  thanks

**Comment by jstabenow** [comment]
Hey @ftrescue 
to update your local image exec `docker pull datarhei/restreamer:latest`.

**Comment by ftrescue** [comment]
> Hey @ftrescue to update your local image exec `docker pull datarhei/restreamer:latest`.
hi @jstabenow 
thats in the code i posted ?

**Comment by jstabenow** [comment]
No, `docker run ...` only loads the image if unavailable locally. 
And `docker pull` updates an existing image.

Please run:
```sh
$ docker pull datarhei/restreamer:latest
$ docker run -d --restart=always --name restreamer \
   -v /opt/restreamer/config:/core/config \
   -v /opt/restreamer/data:/core/data \
   -p 8080:8080 -p 8181:8181 -p 1935:1935 \
   datarhei/restreamer:latest

**Comment by ftrescue** [comment]
@jstabenow your a star mate thank you so much that worked brill :-) so i take it now i will get auto updates saves me learning more about docker hahah

**Comment by svenerbeck** [comment]
⭐ We are pleased about a rating on Google. Your rating helps us to keep the software alive for free. Thank you. [https://g.page/r/CSv68cfIr9l9EBE/review](https://g.page/r/CSv68cfIr9l9EBE/review)
