### ISSUE TITLE
video buffers every 1-2 seconds

### ISSUE THREAD

**Issue by KaptnTobi** [datarhei/restreamer#367]
When I start a RTMP stream the video arrives but buffers every 1-2 seconds. I've already tried to adjust the HLS settings but without success. The RTMP stream is sent directly via a Panasonic AG-CX10. Any ideas for help?

**Comment by svenerbeck** [comment]
Hi @KaptnTobi
Due to HLS there is a basic latency.
At the moment, it is technically not possible to make it faster.
To improve this, there are still some updates to come. 

Cheerio
Sven

**Comment by svenerbeck** [comment]
I just noticed something else... 
Maybe I misunderstood your question? Is it about the latency, or does your video lag every 1 to 2 seconds?

Cool camera by the way :) 

Greetings 
Sven

**Comment by KaptnTobi** [comment]
Hi Sven, thx for your answer. I don't mean the basic latency, this is ok. The video runs smoothly for about 2 seconds and then stops/loads. After another 2 seconds of loading, it runs again, etc. This is how it goes the entire time so that the stream is not viewable due to the dropouts. It runs smoothly on the old Restreamer version. (0.6.8)

**Comment by KaptnTobi** [comment]
Yes it is lagging every 1-2 sec.

Yeah the Camera is very nice! ;D

**Comment by svenerbeck** [comment]
Hey Ho Käptn Tobi

Please send us the "Process Report".
[https://docs.datarhei.com/restreamer/v/de/wissensdatenbank/user-guides/prozess-details](https://docs.datarhei.com/restreamer/v/de/wissensdatenbank/user-guides/prozess-details) 

Greetings
Sven

**Comment by KaptnTobi** [comment]
Hey Sven, here is the process report. I hope he can help.

[220615_report_restreamer.txt](https://github.com/datarhei/restreamer/files/8908955/220615_report_restreamer.txt)

**Comment by svenerbeck** [comment]
Thank you. This helps to find the error.
The processes break down. This can be seen in the log 

> 1655293361
> 1655293057
> 1655293042
> 
>  "address": "rtmp://[anonymized]",
>  "rtmp://[anonymized] Broken pipe"
>  "rtmp://[anonymized] I/O error"


Does the Restreamer in your setup pull the stream, or does your camera push the stream to the Restreamer?

If your camera pushes the video, you can open the address stored in the camera in the VLC and see if the stream is not lagging.

Greetings
Sven

**Comment by svenerbeck** [comment]
Hi @KaptnTobi,
Did that work? We would be happy to receive feedback. 
The ticket will be closing soon.

Greets 
Sven

**Comment by KaptnTobi** [comment]
Hi @svenerbeck,

sorry for the late feedback. I was away for a few days.
The camera push the stream to Restreamer. I have already open the address in VLC and the stream is not lagging.
We are currently using a paid streaming platform and the stream runs smoothly and without lagging.
I also tryed a second camera (same model) and the problem is the same.
In the next step I try to switch an external encoder in between to find a temporary solution.
Other cameras like Osmo Pocket 2 or iPhone (Larix Broadcaster) works fine with Restreamer.

Greets, Tobi
