### ISSUE TITLE
Unable to stream to Youtube 

### ISSUE THREAD

**Issue by jezdd** [datarhei/restreamer#368]
Hi there, 

Love the product, been waiting for the new release and using now using v2.1 installed in a windows docker, installation fine, able to stream local sourced (Unifi cameras) to Twitch out of the box, however we cannot get the streaming to function with Youtube live.

Retreamer logs suggest it is connected and streaming ok but the Youtube side fails both with RMTP and HLS although sometime HLS shows a connection on the Youtube side - there is never ever any video shown.

As far as I can tell this should just work, am I alone is having issues with Youtube?

**Comment by jstabenow** [comment]
Hey @jezdd 
Glad you like the update :partying_face:

So far, there are no known problems with YouTube, and we use it ourselves. 
For us to help, we need the `process debug`:

![Bildschirmfoto 2022-06-15 um 14 16 44](https://user-images.githubusercontent.com/7462030/173825125-fa10a457-d8cd-4f85-9b65-3610da3916d5.png)

Thanks a lot.

**Comment by jezdd** [comment]
Many thanks, see attached, note this is out of the box - we have it streaming a local RTSPS camera to twitch perfectly, I have tried the demo stream to send to Youtube but there is nothing at the Youtube end, simply does not get the feed or connection.  

Using RTMP the Youtube side never sees any stream connection, if I try HLS it tries to connect but with no content.

[report.txt](https://github.com/datarhei/restreamer/files/8918700/report.txt)

**Comment by jezdd** [comment]
Hi there, I think I have found the issue - when setting up the camera in restreamer you must NOT use no audio - Youtube seems to struggle with this, if I repeat the exact same process with silence audio then the stream work well

**Comment by svenerbeck** [comment]
Hi jezdd
Yes, if you don't have audio, you need to enable silence as an audio track for YouTube. Friendly that it works for you now. 
If you like, you can show us your live stream, and we will make a shoutout on Twitter.

💙💚🧡💜 Help datarhei with a rating or review on Google. #feelsgoodtobeloved https://t.co/ZT9pRX1gG7 

Greetings from datarhei.com
