### ISSUE TITLE
Restreamer v2 -copy support

### ISSUE THREAD

**Issue by fluential** [datarhei/restreamer#370]
Hi, v1 had option to copy both audio / video without any transcoding, didn't see this in the v2
I am referring to:
- `-c:a copy`
- `-c:v copy`

**Comment by svenerbeck** [comment]
Hi @fluential 

> * `-c:a copy`
> * `-c:v copy`

Passthrough is the default setting via the wizard. Passthrough is not enabled when encoding is active.

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hi @fluential 
Do you have another question about the topic? The ticket will be closed soon.

Cheerio 
Sven

**Comment by fluential** [comment]
All good, we can close

**Comment by svenerbeck** [comment]
Thank you @fluential 
[electronic high5] 
Sven
