### ISSUE TITLE
Low Latency Mode

### ISSUE THREAD

**Issue by Kieranwest** [datarhei/restreamer#373]
In the previous version of reStreamer I was able to manually edit the nginx config file to reduce the playback latency. I was also able to see more stats on the player itself. Are there any plans to bring back the stats menu along with the ability to decrease the hls times for lower latency playback ? 

I've looked through the container but I really can't seem to find any nginx configs.

**Comment by svenerbeck** [comment]
Hi @Kieranwest 
Decreasing the latency is a to-do and on the roadmap. 
You will find this on the feature request discussion:
https://github.com/datarhei/restreamer/discussions/345

So we still ask for a bit of patience. 

Status is. LHLS is not implemented in FFmpeg. However, if you are a software developer, you are welcome to submit a patch for FFmpeg. 

Greetings
Sven

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
