### ISSUE TITLE
Add audio track

### ISSUE THREAD

**Issue by adrianobarrosmba3** [datarhei/restreamer#375]
I didn't find it in the official documentation, how do you add an mp3 audio to a video stream?

Restreamer v2

**Comment by svenerbeck** [comment]
Hello @adrianobarrosmba3 
Currently, you can only mux audio streams. Single mp3 files are not possible. One solution is to install an Icecast and mux your MP3 into it. Admittedly this is relatively much effort.

Greetings
Sven
