### ISSUE TITLE
Restrict access to m3u8

### ISSUE THREAD

**Issue by giuseppegambino92** [datarhei/restreamer#376]
Hi everyone, I wanted to know if there was a way to protect the m3u8 stream from "outside" access without authorization.
Because it happened to me that from Chrome debugging the video stream was taken and republished on other platforms using my same hls stream.
I would like it to be visible only from the Restreamer Player, embedded in my website.

**Comment by svenerbeck** [comment]
Hi @giuseppegambino92 

good to hear from you.

There are few opportunities there at the moment. Instead, you should **use the Creative Commons license** and choose a minimal license. Your stream is then subject to a license, and unauthorized reuse violates that license.

What you are asking for is a stream protection mechanism with tokens. We have that on the roadmap. But it may take some time. 

Greetings
Sven

[Update. We added your request as official feature request. [Suggestions and feature requests](https://github.com/datarhei/restreamer/discussions/345a)]

**Comment by connaissances** [comment]
Hi @svenerbeck 
Greetings For the day.....!!!!!
Is there any update on m3u8 stream token authorization

**Comment by jstabenow** [comment]
Hey @connaissances 
We are in the planning stage. It might come with the next release. But no guarantee. It's done when it's done ;-)

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
