### ISSUE TITLE
Service to facebook crashes

### ISSUE THREAD

**Issue by ripu** [datarhei/restreamer#377]
Hello,
when I want to start a facebook live, I have to compulsorily restart the service on the platform. 
In a nutshell after fixing the facebook side key, I should simply wait for the signal to come in.
Instead I have to almost every time deactivate the facebook channel and reactivate it in order to see the stream on FB.
I hope this can be helpful

**Comment by svenerbeck** [comment]
Hello ripu
Great to hear from you. 

Please use an audio stream with noise for your video stream to Facebook. Without audio, Facebook probably makes problems. We could reproduce the error without audio as described by you.

You can adjust the audio channel in the video channel settings.

Look at Virtual Audio Source: https://docs.datarhei.com/restreamer/knowledge-base/manual/edit-livestream/sources/audio-settings/virtual-audio-source 

After that, the stream runs immediately.

Thanks for the tip. We will include this in the docs. It is a source of error that should be pointed out.

Cheerio
Sven
