### ISSUE TITLE
Multiple Streaming	✓	Works with more than 1 video source: How?

### ISSUE THREAD

**Issue by AdySan** [datarhei/restreamer#38]
The feature list says this.

> Multiple Streaming	✓	Works with more than 1 video source

However, I cannot find an obvious way to add another video source. Is the only way to run another instance?

**Comment by christophjohannsdotter** [comment]
Thanks for your comment. Currently the only way to run multiple streams is to add multiple instances of the docker image. I think "Multiple Streaming" might mislead, i will discuss changing this sentence :) Tanks
