### ISSUE TITLE
No way to edit or delete a channel

### ISSUE THREAD

**Issue by gerroon** [datarhei/restreamer#380]
Hi,

I added a camera to my system. I want to edit its details but there is no way to edit it the channels thumbnail in the admin section is not clickable , I cant even see a  way to get the video details at all.

Thanks

**Comment by svenerbeck** [comment]
Hi gerroon

Check the [docs](https://docs.datarhei.com/restreamer/knowledge-base/manual/edit-livestream).

## Edit Meta Information
![enter-stream-config-2](https://user-images.githubusercontent.com/12124066/177109322-6667809f-0fd6-451b-9632-acadae172a90.png)

Navigate to: Meta information and edit. Do not forget to save!

![stream-conf-metadata-2](https://user-images.githubusercontent.com/12124066/177109513-cef397ff-8864-48cd-85dc-fd59b0b8cc33.png)

## Delete Channel
Check the 4. The statement "Delete Channel" indicates that the channel will be deleted here.
![stream-conf-general](https://user-images.githubusercontent.com/12124066/177109892-bf44e730-ef09-448e-be01-b411e261b9b6.png)


Cheerio
Sven

**Comment by gerroon** [comment]
Hi

Thanks for the help. I was able to get it after restarting the server and my browser.
