### ISSUE TITLE
Raspicam on Debian Buster

### ISSUE THREAD

**Issue by grumpyprogrammingracoon** [datarhei/restreamer#386]
Hello,

installed Restreamer via Docker on Debian Buster. RaspiCam in found on /dev/video0 and is shown as an available device "mmal service 16.1(/dev/video0)" in restreamer UI. After selecting the Raspicam as Source and clicking "weiter" i get "Die Quelle konnte nicht verifiziert werden. Bitte Adresse prüfen."

**Comment by jstabenow** [comment]
Hey @grumpyprogrammingracoon 
Which Buster version do you use? 32 or 64-bit? And has `gpu_mem` been increased to 256MB?
https://www.raspberrypi.com/documentation/computers/config_txt.html#gpu_mem

**Comment by grumpyprogrammingracoon** [comment]
Solved - forgot the Privileged variable to run the docker
