### ISSUE TITLE
Telegramm stream support

### ISSUE THREAD

**Issue by Alekspom** [datarhei/restreamer#388]
Good time of day. Tell me, are there any plans to add to the publication services the possibility of organizing broadcasts in the Telegram social network? – in connection with the launch of this functionality, the ability to broadcast in this messenger is gaining particular popularity.

**Comment by svenerbeck** [comment]
Hi Alekspom
In the next release, a publication service for Telegram is ready.
Cheerio
Sven

**Comment by Alekspom** [comment]
О! Thank you, great news!

**Comment by svenerbeck** [comment]
<img width="1440" alt="Bildschirmfoto 2022-07-21 um 20 50 39" src="https://user-images.githubusercontent.com/12124066/180293481-b4891821-6f83-4a2b-b9fb-503e82915851.png">
 
👍

**Comment by jstabenow** [comment]
Hey @Alekspom 
It's done. You can find the Telegram service in the current v2.2.0 release.
Cheers.
