### ISSUE TITLE
Cant get Youtube live working

### ISSUE THREAD

**Issue by spannerthumbs** [datarhei/restreamer#389]
Previously used v0.6 but Youtube stream had interruptions so gave up for a while. Now excited to see V2.0 well done datarhei looks very slick. So I am trying again to stream my ocean view. Using Hikvision IP camera and running Docker on Rasp Pi4. In Restreamer Player the stream looks good. 

The Youtube Live integration looks to be so much easier - just paste a key. Fantastic.

But I think iI must be doing something very stupid as I cant get Youtube to see the RTMP stream at all. What am I doing wrong?
Any assistance would be appreciated. log attached.

[Spannerthumbs.txt](https://github.com/datarhei/restreamer/files/9172484/Spannerthumbs.txt)
?

**Comment by jstabenow** [comment]
Hey @spannerthumbs 
It seems to be a network problem. The Restreamer cannot resolve the host "a.rtmp.youtube.com."

Which command did you use to start the Docker container?

**Comment by spannerthumbs** [comment]
Thanks for your help interrogating the logs. 

Sorry I’m not that familiar with Docker and followed an online “how to” to set up Raspian and Docker as a clean install on the rasp pi. Unfortunately I’m not local to it for the next few weeks and although I set up port forwarding so I could see the Restreamer GUI I don’t think I have any other remote access to the pi or docker. 

Regards
Rob 

Rob Furness

Mobile: 07973 200011
Email: ***@***.***

**Comment by jstabenow** [comment]
Ah, crap. Try the following next time:

```sh
docker run -d --restart=always --name restreamer \
   -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data \
   --privileged \
   -p 8080:8080 -p 8181:8181 \
   -p 1935:1935 -p 1936:1936 \
   -p 6000:6000/udp \
   --security-opt seccomp=unconfined \
   datarhei/restreamer:rpi-latest
```

`--security-opt seccomp=unconfined` might solve the network problem.

**Comment by jstabenow** [comment]
@spannerthumbs updates?

**Comment by spannerthumbs** [comment]
Sorry not been back to property since. It may be another few weeks. 

 Have I got it right that I kill the docker process then use the command you suggested and that will restart docker and restreamer in the correct way that will allow YouTube to be reached and ensure that any future power cycle of the Rasp pi will start it correctly automatically? 

I am hopeful and will let you know

Regards
Rob 

Rob Furness

Mobile: 07973 200011
Email: ***@***.***

**Comment by jstabenow** [comment]
I hope so ;-)

**Comment by svenerbeck** [comment]
Hi @spannerthumbs 
We are closing your issue https://github.com/datarhei/restreamer/issues/389.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven

**Comment by sergionaf** [comment]
I have the same problem in v2
Alredy try use these parameter  --security-opt seccomp=unconfined 
Green Status in YouTube Live in Restreamer interface but no transmission received in Youtube
