### ISSUE TITLE
Problem with restreamer + Vivotek VAST Software

### ISSUE THREAD

**Issue by Fenrikus** [datarhei/restreamer#39]
Hello,
I'm facing a trouble with restreaming of a Vivotek VAST Software stream.
Vivotek VAST Software manages multiple IpCams and can stream video from connected cams.
I use connection string rtsp://login:pass@vast.server.ip:3454/Media/Live/Normal/S_B3654504-CAA2-44AF-B178-179408DE22C5?camera=C_2&streamindex=1. When I use VLC to monitor or OBS Software to Youtube restream it’s all good. 
When I use restreamer or other FFmpeg solutions I had a problem.
Some logs:
HypriotOS/armv7: pirate@black-pearl in /mnt/restreamer/db
$ docker exec -i restreamer /bin/sh
ffmpeg -rtsp_transport tcp -i ' rtsp://login:pass@vast.server.ip:3454/Media/Live/Normal/S_B3654504-CAA2-44AF-B178-179408DE22C5?camera=C_2&streamindex=1'  -c copy -f flv /tmp/test.flv
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --prefix=/usr/local --bindir=/usr/local/bin --extra-cflags=-I/usr/local/include --extra-ldflags=-L/usr/local/lib --extra-libs=-ldl --enable-nonfree --enable-gpl --enable-version3 --enable-avresample --enable-libmp3lame --enable-libx264 --enable-openssl --enable-postproc --enable-small --disable-debug --disable-doc --disable-ffserver
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Guessed Channel Layout for  Input Stream #0.1 : mono
Input #0, rtsp, from ' rtsp://vast.server.ip:3454/Media/Live/Normal/S_B3654504-CAA2-44AF-B178-179408DE22C5?camera=C_2&streamindex=1':
  Metadata:
    title           : RTSP server
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: h264, yuvj420p(pc, bt470bg/bt470bg/smpte170m), 1280x720, 29.97 fps, 333.33 tbr, 30k tbn, 59.94 tbc
    Stream #0:1: Audio: pcm_mulaw, 8000 Hz, 1 channels, s16, 64 kb/s
    Stream #0:2: Data: none
[flv @ 0x2f62d40] Codec for stream 0 does not use global headers but container format requires global headers
[flv @ 0x2f62d40] Codec for stream 1 does not use global headers but container format requires global headers
[flv @ 0x2f62d40] Codec for stream 2 does not use global headers but container format requires global headers
Output #0, flv, to '/tmp/test.flv':
  Metadata:
    title           : RTSP server
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuvj420p, 1280x720, q=2-31, 29.97 fps, 333.33 tbr, 1k tbn, 30k tbc
    Stream #0:1: Audio: pcm_mulaw ([8][0][0][0] / 0x0008), 8000 Hz, mono, 64 kb/s
    Stream #0:2: Data: none
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
  Stream #0:2 -> #0:2 (copy)
Press [q] to stop, [?] for help
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 147; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 267; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 387; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 507; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 627; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 834, current: 747; changing to 834. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7147; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:1; previous: 7185, current: 7144; changing to 7185. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7267; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7387; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7507; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7630; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7750; changing to 48597. This may result in incorrect timestamps in the output file.
[flv @ 0x2f62d40] Non-monotonous DTS in output stream 0:0; previous: 48597, current: 7870; changing to 48597. This may result in incorrect timestamps in the output file.

**Comment by strarsis** [comment]
Related issue (web UI)?: https://github.com/datarhei/restreamer/issues/41
