### ISSUE TITLE
Streaming with a Hikvision Camera to Youtube through Restreamer on a Raspberry Pi

### ISSUE THREAD

**Issue by krischan941** [datarhei/restreamer#390]
Hello,
my goal is to receive a rtsp stream (from a Hikvision IP camera) and encode and stream it to youtube. Next monday I can access the camera. Until then I want to setup a Raspberry Pi with restreamer.

So far I installed Raspberry Pi OS 32 bit latest version on a Raspberry Pi 4b 4gb ram. I setup restreamer with docker as described in the manual. Now I set up a virtual source ("Testbild erweitert") to test. I choose FullHD and H264 OpenMax IL Codec. (I can choose between this one and libx264 and V4L2 Memory to Memory). Then a virtual audio source and after saving, it loads the test Video with a very high cpu usage (around 88-95 %). Have you any idea how to reduce this? Thanks in advance.

**Comment by svenerbeck** [comment]
Hi krischan941 
Always good to have a goal. Hikvision works with RTSP H.264. The Streaming URL for Channel 1: rtsp://name:pass@IP:port/Streaming/Channels/101 

OpenMax is the GPU from Raspberry Pi. A good choice and reduces the load on the CPU. Virtual Sources with test patterns are rendered and are surprisingly computationally intensive. Try switching to 720p or using a different test pattern.

With the Hikvision camera, you will have much less load on the system because the process is hardly processing-intensive.

Cheerio from datarhei.com
Sven

PS: If you show us your HIKVISION project there will be a shoutout on social media [electronic high5].

**Comment by krischan941** [comment]
Hi Sven,
thanks for your fast response. That absolutely makes sense now, I didn't know that virtual sources are rendered.

In cooperation with a partner, we installed a camera on a bell tower of our little local church to monitor 24/7 a stork's nest about 165m away. An camera installation directly at the nest was not possible for reasons of nature conservation because the storks already arrived from the south when we planned to do so. The camera signal is sent to our house via antennas and then goes into our network. You can find information and photos of the camera installation on our project website: https://storch.watch/2022/05/16/aufbau-der-kamera/

The project actually runs, but not very stable. You can find a Youtube livestream on the site too: https://storch.watch/storch-live/ 
We've been streaming for almost two weeks now, but unfortunately not constantly. We already run (another) Raspberry Pi 4 (with older Raspbian) and ffmpeg to convert the rtsp to a rtmp stream for Youtube. But it stops working randomly between 12 and 48 hours with different types of "pipe-errors". I could sort out some of them, but I'm in general a bit overwhelmed by the complexity of ffmpeg and find it really complicated to try and understand all the parameters. Although I like it very much. So for that reason and because of the fact that somebody else (technically not too much inclined) needs to take over this project, I looked for alternatives and found Restreamer some days ago, which looks really really appealing and promising! 

I hope then to get a more reliable Livestream with Restreamer. Will see next week! [electronic high5 back]
Thanks
Christian

**Comment by svenerbeck** [comment]
Hello Krischan

Streaming to YouTube is relatively easy with the Restreamer and works reliably. We recommend you leave the streaming parameters on YouTube at the default settings to get stable live streaming.

Thank you for the detailed information about the project. The stream is not broadcasting right now.
📢 Shoutout goes out when the Restreamer is running with the new Hikvision camera. Could you let me know about the ticket here again? 

Greetings
Sven

**Comment by krischan941** [comment]
Hello Sven,
Stream should be back online, but with plain ffmpeg in combination with Cron again for now.

Now I try to setup with Restreamer but am not succesful at the moment. First I setup another SD-card with 64bit Raspberry Pi OS and Restreamer. I try to receive the camera signal and get following errors:

64 bit OS+Restreamer using V4L2 Codec: 
video append of 1003836b failed for segment #1 in playlist 0-07461144-06d5-4877-8685-951dbd975947_var0.m3u8?session=fKxQwCMRS2TTcX2urmMmjJnow

64 bit OS+Restreamer using codec=copy: 
```
`@1658755643 ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers
@1658755643   built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
@1658755643   configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
@1658755643   libavutil      56. 70.100 / 56. 70.100
@1658755643   libavcodec     58.134.100 / 58.134.100
@1658755643   libavformat    58. 76.100 / 58. 76.100
@1658755643   libavdevice    58. 13.100 / 58. 13.100
@1658755643   libavfilter     7.110.100 /  7.110.100
@1658755643   libswscale      5.  9.100 /  5.  9.100
@1658755643   libswresample   3.  9.100 /  3.  9.100
@1658755643   libpostproc    55.  9.100 / 55.  9.100
@1658755644 Input #0, rtsp, from 'rtsp://admin:Kirchturm22%23@192.168.8.105:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1':
@1658755644   Metadata:
@1658755644     title           : Media Presentation
@1658755644   Duration: N/A, start: 0.039000, bitrate: N/A
@1658755644   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 180k tbc
@1658755644 Input #1, lavfi, from 'anullsrc=r=44100:cl=stereo':
@1658755644   Duration: N/A, start: 0.000000, bitrate: 705 kb/s
@1658755644   Stream #1:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
@1658755644 Stream mapping:
@1658755644   Stream #0:0 -> #0:0 (copy)
@1658755644   Stream #1:0 -> #0:1 (pcm_u8 (native) -> aac (native))
@1658755644 Press [q] to stop, [?] for help
@1658755644 Output #0, hls, to 'http://admin:KGwh0enqKqLJYubJ8M@localhost:8080/memfs/07461144-06d5-4877-8685-951dbd975947_var0.m3u8':
@1658755644   Metadata:
@1658755644     title           : http://localhost:8080/07461144-06d5-4877-8685-951dbd975947/oembed.json
@1658755644     service_provider: datarhei-Restreamer
@1658755644     encoder         : Lavf58.76.100
@1658755644   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, q=2-31, 25 fps, 25 tbr, 90k tbn, 90k tbc
@1658755644   Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp, 64 kb/s
@1658755644     Metadata:
@1658755644       encoder         : Lavc58.134.100 aac
@1658755644 [hls       ] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
@1658755644 [mpegts    ] Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
@1658755644 [mpegts    ] first pts and dts value must be set
@1658755644 av_interleaved_write_frame(): Invalid data found when processing input
@1658755644 [hls       ] Opening 'http://admin:KGwh0enqKqLJYubJ8M@localhost:8080/memfs/07461144-06d5-4877-8685-951dbd975947_0001_var0.ts' for writing
@1658755644 [hls       ] Opening 'http://admin:KGwh0enqKqLJYubJ8M@localhost:8080/memfs/07461144-06d5-4877-8685-951dbd975947.m3u8' for writing
@1658755644 [aac       ] Qavg: 50907.137
@1658755644 Conversion failed!`
```

64 bit OS+Restreamer using x264-Codec:
It's receiving the camera signal but with very high CPU usage and only about 15-19 fps (camera sends 25fps and videosetting in Restreamer is 25fps too)

64 bit OS+Restreamer doesn't have OpenMax IL Setting.

Then again with 32bit SD-Card:

32 bit OS+Restreamer using V42L Encoder + h264 (MMAL) Decoder
This is a modal window.video append of 1034840b failed for segment #1 in playlist 0-dd72ea6f-6459-4b3e-b258-ca9a0958dff2_var0.m3u8?session=nW3okwFXHAqdC3VcLhjEye

32 bit OS+Restreamer using V42L Encoder + default Decoder
video append of 834041b failed for segment #1 in playlist 0-dd72ea6f-6459-4b3e-b258-ca9a0958dff2_var0.m3u8?session=efsJ42guGniF2jXgGjYmGm

32bit OS+Restreamer using OpenMax IL Encoder + h64 (MMAL) decoder
> ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers
>   built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
>   configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-omx --enable-omx-rpi --enable-mmal --enable-libv4l2 --enable-v4l2_m2m --enable-alsa --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
>   libavutil      56. 70.100 / 56. 70.100
>   libavcodec     58.134.100 / 58.134.100
>   libavformat    58. 76.100 / 58. 76.100
>   libavdevice    58. 13.100 / 58. 13.100
>   libavfilter     7.110.100 /  7.110.100
>   libswscale      5.  9.100 /  5.  9.100
>   libswresample   3.  9.100 /  3.  9.100
>   libpostproc    55.  9.100 / 55.  9.100
> Input #0, rtsp, from 'rtsp://admin:-----@192.168.8.105:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1':
>   Metadata:
>     title           : Media Presentation
>   Duration: N/A, start: 0.040000, bitrate: N/A
>   Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080, 25 fps, 25 tbr, 90k tbn, 180k tbc
> Input #1, lavfi, from 'anullsrc=r=44100:cl=stereo':
>   Duration: N/A, start: 0.000000, bitrate: 705 kb/s
>   Stream #1:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
> Stream mapping:
>   Stream #0:0 -> #0:0 (h264 (h264_mmal) -> h264 (h264_omx))
>   Stream #1:0 -> #0:1 (pcm_u8 (native) -> aac (native))
> Press [q] to stop, [?] for help
> [h264_mmal @ 0xb66e49e0] Did not get output frame from MMAL.
> Error while decoding stream #0:0: Unknown error occurred
> [h264_omx @ 0xb610b850] Using OMX.broadcom.video_encode
> [h264_omx @ 0xb610b850] err 80001000 (-2147479552) on line 561
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!

32 bit OS+Restreamer using OpenMax IL Encoder + default decoder:
It's receiving the camera signal but with very high CPU usage and only about 15-19 fps (camera sends 25fps and videosetting in Restreamer is 25fps too)

So at the moment I struggle to get a good stream from the Hikvision into Restreamer. It either doesn't work or only with fewer fps and high CPU usage at the moment. I hope the error messages are useful. I'd glad to run the stream with Restreamer.

Greetings
Christian

**Comment by krischan941** [comment]
Ok so in Restreamer if I scroll down so you don't see the (complete) preview it reduces the CPU load and generates relatively stable fps. (On 32 bit Restreamer and OS now).
I want to setup a Teststream to Youtube now but Youtube doesn't get a signal. Here is the console output:

`@1658760615 ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers
@1658760615   built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
@1658760615   configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-omx --enable-omx-rpi --enable-mmal --enable-libv4l2 --enable-v4l2_m2m --enable-alsa --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
@1658760615   libavutil      56. 70.100 / 56. 70.100
@1658760615   libavcodec     58.134.100 / 58.134.100
@1658760615   libavformat    58. 76.100 / 58. 76.100
@1658760615   libavdevice    58. 13.100 / 58. 13.100
@1658760615   libavfilter     7.110.100 /  7.110.100
@1658760615   libswscale      5.  9.100 /  5.  9.100
@1658760615   libswresample   3.  9.100 /  3.  9.100
@1658760615   libpostproc    55.  9.100 / 55.  9.100
@1658760615 [hls       ] Skip ('#EXT-X-VERSION:3')
@1658760615 [hls       ] Opening 'http://admin:g3PJsh3Hq5lz5DWKoc@localhost:8080/memfs/dd72ea6f-6459-4b3e-b258-ca9a0958dff2_var0.m3u8' for reading
@1658760615 [hls       ] Skip ('#EXT-X-VERSION:3')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:19.184+0000')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:21.184+0000')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:23.184+0000')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:25.184+0000')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:27.184+0000')
@1658760615 [hls       ] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-07-25T14:49:29.184+0000')
@1658760615 [hls       ] Opening 'http://admin:g3PJsh3Hq5lz5DWKoc@localhost:8080/memfs/dd72ea6f-6459-4b3e-b258-ca9a0958dff2_0536_var0.ts' for reading
@1658760615 [hls       ] Opening 'http://admin:g3PJsh3Hq5lz5DWKoc@localhost:8080/memfs/dd72ea6f-6459-4b3e-b258-ca9a0958dff2_0537_var0.ts' for reading
@1658760616 Input #0, hls, from 'http://admin:g3PJsh3Hq5lz5DWKoc@localhost:8080/memfs/dd72ea6f-6459-4b3e-b258-ca9a0958dff2.m3u8':
@1658760616   Duration: N/A, start: 843.423222, bitrate: N/A
@1658760616   Program 0 
@1658760616     Metadata:
@1658760616       variant_bitrate : 9081600
@1658760616   Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x1080, 25 fps, 25 tbr, 90k tbn, 180k tbc
@1658760616     Metadata:
@1658760616       variant_bitrate : 9081600
@1658760616   Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp
@1658760616     Metadata:
@1658760616       variant_bitrate : 9081600
@1658760621 [tcp       ] Failed to resolve hostname a.rtmp.youtube.com: Try again
@1658760621 [rtmps     ] Cannot open connection tls://a.rtmp.youtube.com:443
@1658760621 rtmps://a.rtmp.youtube.com/live2/------------: I/O error`

**Comment by svenerbeck** [comment]
Hello krischan941 
Thanks for the details.

It says: "Failed to resolve hostname [a.rtmp.youtube.com](http://a.rtmp.youtube.com/):" 
This indicates network errors.

Maybe Docker has increased security. Please try:

```sh
docker run -d --restart=always --name restreamer \
   -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data \
   --privileged \
   -p 8080:8080 -p 8181:8181 \
   -p 1935:1935 -p 1936:1936 \
   -p 6000:6000/udp \
   --security-opt seccomp=unconfined \
   datarhei/restreamer:rpi-latest
```

`--security-opt seccomp=unconfined` might solve the network problem

## No encoding
Please do not encode. That is senseless because H.264 is already at the start! "Copy" is therefore sufficient. 

## No Unicast
Please use without unicast: 
"rtsp://admin:Kirchturm22%23@192.168.8.105:554/Streaming/Channels/101/" 


Cheerio
Sven

**Comment by svenerbeck** [comment]
**As a small behavioral cue, it is unusual to change the title of a ticket afterward. It would have been a good idea to open a new ticket.**

**Comment by krischan941** [comment]
Hello Sven, thanks for your answer. I'll try tomorrow again and keep you up to date about the progress.
Sorry for inconveniences by renaming the ticket header, next time I'll create a new ticket!
Thanks Christian

**Comment by krischan941** [comment]
Hello Sven, 
now I'm running the stream. But a hidden test stream at first for some days, to see how stable it is and after that to replace the current main stream!
Here is the Link: https://www.youtube.com/watch?v=8gp7SenvCDI

I don't use Unicast anymore,  `--security-opt seccomp=unconfined` solved the nework issue and I don't encode anymore as you suggested.

So the first 15 minutes of streaming Youtube it seems a bit laggy. Youtube alerts continuously between "it's not getting enough data", "no data" and "The transmission quality of the stream is good". 
Maybe you have some pointers to improve quality?

Youtube-Settings are standard, "Stream latency" is set to "normal".

Thanks Christian

**Comment by svenerbeck** [comment]
Hello krischan

Nice that it runs. Then we can do the shoutout tomorrow.

The picture quality has nothing to do with the Restreamer if you don't encode. You have to adjust the settings in the camera. In the picture, you can see that the sharpness setting is way too sharp. 

I would recommend:

## Video and Audio
### Main Stream (Normal)  
/Streaming/Channels/101
- 1920 x 1080P
- Frame rate: Constant
- FPS 24 / 25 
- Max Bitrate: 4096 Kbps
- Video encoding: H.264
- H.264+ OFF
- Profile. Main profile
- I-frame interval: 50
- SVC: Off
- Smooth 50% 

### Third stream 
/Streaming/Channels/103 
- 1920 x 720P
- Frame rate: Constant
- FPS 24 / 25 
- Max Bitrate: 2048 Kbps
- Video encoding: H.264
- H.264+ OFF
- Profile. Main profile
- I-frame interval: 50
- SVC: Off
- Smooth 50% 


## Video
I don't know the camera model, so I can't say anything about the exact image settings because they vary a lot from model to model. But basically, the following applies to Hikvision models: 

In the first step, leave the image settings all at 50% and the one for sharpness at 40% to get a reasonably natural image. Suppose the camera has preset in the image settings. In that case, the day or outdoor profile can provide a good basis for further fine-tuning.

I would set the filter for sharpness to a value between 35 and 42. 

If WDR is used, a value not exceeding 15 should not make the image look unnatural. HLC and BLC can be helpful when looking from a direction with much backlight. But they will keep the sky primarily white, which not everyone likes. So, in general, do without it if a raw video image is desired.

I would turn off Autofocus in your case because the focus is always on the same place - the stork's nest.

In general, clean footage is excellent and beautiful. I would therefore do without a timestamp.

Maybe that can help you.

Cheerio
Sven

PS: YouTube's default settings are excellent for streaming H.264, so I wouldn't recommend changing anything here.

**Comment by krischan941** [comment]
Thank you very much for the great input. I will see if I can tweak something on the camera.
With quality I mean fps in this case. If you look at the trees in the backround, it seems that it doesn't reach 25fps most of the time.
The current main Strem (ffmpeg + Cron) is back online too (on another Raspberry Pi): https://www.youtube.com/watch?v=wtjdq4JO7GA 
So now you can compare both. 
But in general it runs really solid through Restreamer now!
Thanks Christian

**Comment by svenerbeck** [comment]
What model of Hikvision are you using if I may ask.

**Comment by krischan941** [comment]
Shure. In the Web-Interface I found this: Hikvision DS-2DE7A432IW-AEB

**Comment by krischan941** [comment]
The stream got interrupted as I showed up my minimized Chromium with the Youtube-Studio-Tab.
But to this point it was really stable and used only a little CPU!
For now here is the new teststream https://www.youtube.com/watch?v=-FmTXVCBOi8

[Edit] We did a firmware Update of the Hikvision so the last stream got interrupted again. Here is the new teststream: https://www.youtube.com/watch?v=k9XuDnC_5do

**Comment by svenerbeck** [comment]
Hi @krischan941 
The camera is not the cheapest from Hikvision — that is good. 
With the settings I mentioned above, there should be a nice picture. 

## 📢 Shoutout!
As promised the Shoutout for your project. 

[Google](https://www.google.ch/search?q=datarhei&ludocid=9068472601570048555&lpsid=6318765098874705344&source=sh/x/localposts&lsig=AB86z5WYR_I82xEFdMAhs-MMegNC), [Twitter](https://twitter.com/datarhei/status/1552200986839613440?s=20&t=CFi_h_So8ywRTNOzf6muFg), [Mastodon](https://mastodon.social/@datarhei/108718268329279771)

[electronic high5]
Sven

**Comment by krischan941** [comment]
Hello Sven,
thanks for the kudos!
Today I'm not at work, tomorrow I'll launch the Restreamer stream on our main channel :)

[electronic high5]
Christian

**Comment by svenerbeck** [comment]
Hi @krischan941 
Please join our [Discord](https://discord.gg/SHV8RdUM) for further help.

#restreamer-de is in German.

There we can help you more efficiently with the fine adjustments - if necessary.

Bis bald
Sven
