### ISSUE TITLE
Select channel to Playersite

### ISSUE THREAD

**Issue by adampl0** [datarhei/restreamer#392]
Hi 
Is it possible to select individual channels to be displayed on the Playersite ? By default, all channels are displayed, and I would like to select only individual channels

**Comment by svenerbeck** [comment]
Hi @adampl0 
This is not possible at the moment.

I will include your idea as a feature request. Look here: https://github.com/datarhei/restreamer/discussions/345 

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven

**Comment by ioppermann** [comment]
This has been added in the latest release: https://github.com/datarhei/restreamer/releases/tag/v2.12.0
