### ISSUE TITLE
Streaming to Youtube interrupts

### ISSUE THREAD

**Issue by krischan941** [datarhei/restreamer#396]
I streamed to Youtube twice and both times it interrupted without doing it myself. First one after nearly 22h, second after 12h.
The first time I did parallel stream on a other device with same source and destination which didn't fail at the point where Restreamer interrupted. So at least the first time it can't be a network issue.
Both times I got logged out from Restreamer. I hope the logs are useful.

Streaming setup is a Raspberry Pi 4, Raspberry Pi OS 32bit, Restreamer 2.2.0 via Docker
[Logs.zip](https://github.com/datarhei/restreamer/files/9219803/Logs.zip)

**Comment by svenerbeck** [comment]
Hi krischan

You have several Problems. This has nothing to do with the Restreamer, it's setting problems.
Please join our [Discord](https://discord.gg/SHV8RdUM) for further help.

#restreamer-de is in German.

There we can help you more efficiently with the fine adjustments - if necessary.

Thanks for your understanding.

Cheerio
Sven

**Comment by krischan941** [comment]
Okay I see, will join now

**Comment by svenerbeck** [comment]
As we found out together, the source of the problems is not the Restreamer, the Hikvision camera, or YouTube. 

The connection via the point-to-point antennas from the tower to the Restreamer does not have enough power. However, you will get an excellent live stream as soon as the UBNT antennas are green. 

At this point, the support went beyond the Restreamer with a Teamviewer session. If you want to do something good for us, we would be happy about a donation or a new patron, or a backlink/hint to the project.

Feel free to contact us in Discord at any time. 

We will close the ticket.

Cheerio
Sven
