### ISSUE TITLE
Video download / Clipping

### ISSUE THREAD

**Issue by gatorojo** [datarhei/restreamer#399]
Hi, this is to propose a new feature, adding the capability to download the current segments as an mp4 video, with a button next to the snapshot one.

Also, as a follow up to that, the option to trim the timeline and export a portion of that to an mp4.

There could be (train of thoughts) the posibility to upload that clip to youtube or other service directly.

Thanks for the awesome platform!!

**Comment by Pimmetje** [comment]
I have been playing with the idea of the recording. See #381 
For me it would be ideal if we could keep X time in memory and write it to disk in a kind of rolling system.

Let me give a example. I have a camera with a live feed. The system has enough memory for say 60 minutes. Ill allow 60 minutes of live playback directly from memory. As the access time to it is low this is fast and costs little resources. But i still want to keep the recording. So it would be nice to save files of X minutes (where X is less than the amount of memory recording). And every X minutes the data from memory is written to disk (as mp4) or something that does not require reencoding. 
The only downside of this would that in a event of a crash in software/hardware the last X minutes is not written to disk. The plus side of it is that there is little to no resources used to operate the system. If we would bundle the saving as one task the system could even suspend the disk. (This would only be efficient if we would use more than a few hours in memory but still is better to write bigger blocks to a harddisk). 
Those mp4 files could be placed in a public folder. Or a script / webhook / post could be executed when the file was saved. This would allow a very big amount of usecases to be for filled.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
