### ISSUE TITLE
Please provide manual (no docker) installation method

### ISSUE THREAD

**Issue by nodiscc** [datarhei/restreamer#4]
Hi and congrats for the release.

Could you provide an alternate configuration method that doesn't rely on Docker? Many people do not feel comfortable relying on prebuilt docker images or simply do not need virtualization. It would be very appreciated if you could publish an installation method containing

 * required software and versions
 * system and webserver configuration instructions
 * restreamer download and configuration instructions

Thanks in advance

**Comment by svenerbeck** [comment]
Hello nodiscc.
Thank you for your input. 

At the moment we are concentrating on the Docker way. In the future we will show how to install the Datarhei/Restreamer the native way without Docker. It is a lot to compile to get the Restreamer working. For many users it is overstraining to install and configure all these tools we are using. 
It needs some time to write the documentation to support the users with eg. Nginx problems or FFmpeg make problems. There are many pitfalls....

We have decided to start only with Docker to get some experience with the tool it self and the way people use it, too. And we wanted to concentrate on the App and Docker helps us to keep the focus on that. So be patient -  we will present a documented method in the future for sure.

It should be possibel to install the Restreamer at the moment without Docker. But it has not been tested yet PLUS some parts of the Restreamer are at the moment optimized for a Docker installation. 

How ever, if you are using Linux you could see what to do in the Docker configuration file and try replicate it on your system: https://github.com/datarhei/restreamer/blob/master/Dockerfile 

This file is for the Node.js
https://github.com/datarhei/restreamer/blob/master/conf/live.json

This file for NGINX:
https://github.com/datarhei/restreamer/blob/master/conf/nginx.conf

Feel free to write your experience with a native installation. You are welcome if you tell us about the experiences eg. in our [Forum](https://groups.google.com/forum/#!forum/datarhei)

Keep on streaming
Sven

**Comment by nodiscc** [comment]
I am currently running the Apache HTTP server for other purposes. Is it possible to run Restreamer on top of Apache? I don't really want to install and setup another web server just for this application.

Is it required to compile nginx/nodejs/libmp3lame/x264... or could I install them using my distribution's (Debian) prebuilt binary packages?

Another thing to note is that your Dockerfile downloads software sources over insecure plain HTTP. You might want to change that.

**Comment by svenerbeck** [comment]
Hello nodiscc,

The Restreamer needs an RTMP Server which is realized through the NGINX RTMP Module. I am not familiar with an alternative installation through Apache. I think it is not possible as i know. If there is something out there like RTMP over Apache it might be possible. 
 
It is required to compile to be safe that things work as they should. Especially Debian packages are not the newest ones  ...

Thank you for your https download docker build hint. We lost that out of focus. I put it on our internal issues list. We are fixing that till we leave RC.. :+1: 

Keep on streaming!
Sven

**Comment by nodiscc** [comment]
@svenerbeck I gather closing this issue is a way to mark it as `wontfix` ?

AFAIK Apache has no RTMP module, so the only way is to go with nginx. As I said before I really hope there will be a manual installation procedure at some point. Docker is complex and overkill (but I admit it is fine if your app is at the prototype stage)

> It is required to compile to be safe that things work as they should.

So why not define minimum known working versions?

**Comment by svenerbeck** [comment]
Hello nodiscc,
I have to repeat myself, unfortunately: https://github.com/datarhei/restreamer/issues/4#issuecomment-171732530

> At the moment we are concentrating on the Docker way. In the future we will show how to install the Datarhei/Restreamer the native way without Docker. It is a lot to compile to get the Restreamer working. For many users it is overstraining to install and configure all these tools we are using. 
It needs some time to write the documentation to support the users with eg. Nginx problems or FFmpeg make problems. There are many pitfalls....
>
>We have decided to start only with Docker to get some experience with the tool it self and the way people use it, too. And we wanted to concentrate on the App and Docker helps us to keep the focus on that. So be patient - we will present a documented method in the future for sure.

Thank you for your understanding.

Keep on streaming
Sven

**Comment by nodiscc** [comment]
I misunderstood. Thank you.

**Comment by therob3000** [comment]
Over a year later, any update? Still concentrating on monetizing?

**Comment by svenerbeck** [comment]
There is still no native version on the horizon. :) 
Restreamer update is coming... stay tuned.

Keep on streaming
Sven
