### ISSUE TITLE
Feature Request: analytics/statistics

### ISSUE THREAD

**Issue by Fred-DTV** [datarhei/restreamer#403]
Hello hello,

Another feature I would love the see is an analytics site, in which one can see in-depth statistics of a sent stream.

Data that would be nice to know for all channels combined and per channel:
- Total viewers over time
- Average Viewers
- Bitrate over time
- Chat messages over time
- History of recent stream data

**Comment by svenerbeck** [comment]
Hi @DachsbauTV 

Thank you for your message.

This is a logical standard feature and of course on the roadmap. 

Cheerio
Sven

**Comment by Fred-DTV** [comment]
Okay great :) thanks

**Comment by privatesam** [comment]
Yes please - would love this!!!!
