### ISSUE TITLE
How to set video as an image or a video on loop

### ISSUE THREAD

**Issue by Bedrock16** [datarhei/restreamer#404]
Hi,
I want to stream a video on YouTube in loop it's a 2 min video and I am using Network Source in that I have put the url of the video. The problem is after the 2 minutes the stream give error of no video (because the video is only of 2 min) so I want to know how can I keep the video running on loop or just use an image as background.

**Comment by jstabenow** [comment]
Hey @Atharv-Pathak-14 
VoD is not currently supported by the [Restreamer-UI](https://github.com/datarhei/restreamer-ui), which would be an essential requirement.

But if you are a developer and know your way around FFmpeg, you can check here:
[datarhei/core](https://github.com/datarhei/core)

The REST-API can provide all kinds of FFmpeg processes and configurations. So it would be possible.

**Comment by Bedrock16** [comment]
> Hey @Atharv-Pathak-14 VoD is not currently supported by the [Restreamer-UI](https://github.com/datarhei/restreamer-ui), which would be an essential requirement.
> 
> But if you are a developer and know your way around FFmpeg, you can check here: [datarhei/core](https://github.com/datarhei/core)
> 
> The REST-API can provide all kinds of FFmpeg processes and configurations. So it would be possible.

Will definitely try the with the method you specified thanks 👍
