### ISSUE TITLE
srt ingest not possible?

### ISSUE THREAD

**Issue by dvision1979** [datarhei/restreamer#407]
Following this video on your Youtube channel: https://www.youtube.com/watch?v=ATG2bOujuPU

Although the OBS is showing green connection and bitrate, probing the stream in restreamer is not successful.

![image](https://user-images.githubusercontent.com/4688610/187593762-c7f618c9-bbe2-43d7-b3e1-e75d3cf05d99.png)

Could you please advise?
Thank you.

**Comment by jstabenow** [comment]
Hey @danionescu2007 
Can you show your Docker command?

**Comment by danionescu2007** [comment]
> Hey @danionescu2007 
> 
> Can you show your Docker command?

'''

      - RS_SNAPSHOT_INTERVAL=1m
      - CORE_RTMP_ENABLE=true
      #- CORE_RTMP_ENABLE_TLS=true
    restart: unless-stopped

  fblive:
    image: dweomer/stunnel
    container_name: fblive
    expose:
      - 1935
    networks:
      - frontend
    restart: unless-stopped
    environment:
      - STUNNEL_SERVICE=fb-live
      - STUNNEL_CLIENT=yes
      - STUNNEL_ACCEPT=1935
      - STUNNEL_CONNECT=live-api-s.facebook.com:443
      - STUNNEL_VERIFY_CHAIN=NO

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - 8085:80
      - 9443:443
    restart: unless-stopped
    networks:
      - frontend
    environment:
      DOMAINS: restreamer.verasidan.com -> http://restreamer:8080
      STAGE: production
      # DOMAINS: yourdomain.com -> http://restreamer:8080
      # STAGE: production

networks:
  frontend:

'''

**Comment by danionescu2007** [comment]
- RS_SNAPSHOT_INTERVAL=1m
      - CORE_RTMP_ENABLE=true
      #- CORE_RTMP_ENABLE_TLS=true
    restart: unless-stopped

  fblive:
    image: dweomer/stunnel
    container_name: fblive
    expose:
      - 1935
    networks:
      - frontend
    restart: unless-stopped
    environment:
      - STUNNEL_SERVICE=fb-live
      - STUNNEL_CLIENT=yes
      - STUNNEL_ACCEPT=1935
      - STUNNEL_CONNECT=live-api-s.facebook.com:443
      - STUNNEL_VERIFY_CHAIN=NO

  https-portal:
    image: steveltn/https-portal:1
    container_name: https-portal
    ports:
      - 8085:80
      - 9443:443
    restart: unless-stopped
    networks:
      - frontend
    environment:
      DOMAINS: restreamer.verasidan.com -> http://restreamer:8080
      STAGE: production
      # DOMAINS: yourdomain.com -> http://restreamer:8080
      # STAGE: production

networks:
  frontend:

**Comment by danionescu2007** [comment]
version: "3.3"
services:
  restreamer:
    image: datarhei/restreamer:vaapi-latest
    container_name: restreamer
    privileged: true
    ports:
      - 1935:1935
      - 8084:8080
    networks:
      - frontend
    volumes:
      - ./restreamer/db:/restreamer/db
      - ./restreamer/config:/core/config
      - ./restreamer/data:/core/data
    devices:
      - /dev/dri:/dev/dri
    environment:
      - RS_USERNAME=username
      - RS_PASSWORD=password
      - RS_LOGLEVEL=4
      - RS_TIMEZONE=Europe/Bucharest
      - RS_SNAPSHOT_INTERVAL=1m
      - CORE_RTMP_ENABLE=true
      #- CORE_RTMP_ENABLE_TLS=true
    restart: unless-stopped

**Comment by dvision1979** [comment]
'''

version: "3.3"
services:
  restreamer:
    image: datarhei/restreamer:vaapi-latest
    container_name: restreamer
    privileged: true
    ports:
      - 1935:1935
      - 8084:8080
    networks:
      - frontend
    volumes:
      - ./restreamer/db:/restreamer/db
      - ./restreamer/config:/core/config
      - ./restreamer/data:/core/data
    devices:
      - /dev/dri:/dev/dri
    environment:
      - RS_USERNAME=user
      - RS_PASSWORD=password
      - RS_LOGLEVEL=4
      - RS_TIMEZONE=Europe/Bucharest
      - RS_SNAPSHOT_INTERVAL=1m
      - CORE_RTMP_ENABLE=true
      #- CORE_RTMP_ENABLE_TLS=true
    restart: unless-stopped
'''

**Comment by dvision1979** [comment]
Sorry for the messy post. It is the best I can do from my mobile.

**Comment by jstabenow** [comment]
Please add `6000:6000/udp`:

```sh
version: "3.3"
services:
restreamer:
image: datarhei/restreamer:vaapi-latest
container_name: restreamer
privileged: true
ports:
- 1935:1935
- 8084:8080
- 6000:6000/udp
networks:
- frontend
volumes:
- ./restreamer/db:/restreamer/db
- ./restreamer/config:/core/config
- ./restreamer/data:/core/data
devices:
- /dev/dri:/dev/dri
environment:
- RS_USERNAME=user
- RS_PASSWORD=password
- RS_LOGLEVEL=4
- RS_TIMEZONE=Europe/Bucharest
- RS_SNAPSHOT_INTERVAL=1m
- CORE_RTMP_ENABLE=true
#- CORE_RTMP_ENABLE_TLS=true
restart: unless-stopped
```

**Comment by dvision1979** [comment]
My bad, I totally overseen this. Now it is working as designed. Thank you so much.
Are there environment variables foreseen for configuring the SRT server, as per the RTMP one?
Thanks again.

[EDIT]
I checked here https://docs.datarhei.com/restreamer/api/environment-variables, but there does not seem to be any.

**Comment by jstabenow** [comment]
Perfect :-)

SRT and RTMP are configurable via the interface and no longer require `ENV`.

But if you want to use `ENV`, you can find the complete list here:
https://github.com/datarhei/core#environment-variables

**Comment by dvision1979** [comment]
Thank you. Very much appreciated.
