### ISSUE TITLE
How to setup video from MacOS camera? 

### ISSUE THREAD

**Issue by noho501** [datarhei/restreamer#410]
Hi,

I am running Restreamer on the Linode server, I would like to start streaming from my MacOS camera, but no device detected. Could you please advise?

Thanks & best regards

<img width="429" alt="Screen Shot 2022-09-02 at 18 11 28" src="https://user-images.githubusercontent.com/35057759/188127390-fb6b99db-0a13-4ebf-b237-b550f2f20b99.png">

**Comment by jstabenow** [comment]
To do this, you must send your camera to the Restreamer. E.g., via OBS. We could build a browser plugin for it (like YouTube-Live UI) in the long term. But that is not yet on the roadmap.

The Restreamer can access network sources (RTSP, RTMP, SRT, etc.) and local devices (like USB). However, local devices will not be available in any cloud instance ;-)

I hope this information helps you.

**Comment by noho501** [comment]
Hi @jstabenow 

Thanks for your help :)
