### ISSUE TITLE
HTTPS Let's Encrypt Issue

### ISSUE THREAD

**Issue by samiulus** [datarhei/restreamer#412]
I tried to install Let's Encrypt but It doesn't work. I got an error on log. My error message is-

```
ts=2022-09-03T21:39:57Z level=INFO component="Core" application="datarhei-core" license="Apache License Version 2.0" repository="https://github.com/datarhei/core" version="16.9.1"
ts=2022-09-03T21:39:57Z level=INFO component="Let's Encrypt" msg="Acquiring certificate ..." host="cdn2.streamcast.xyz"
ts=2022-09-03T21:40:01Z level=ERROR component="Let's Encrypt" msg="Failed to acquire certificate" error="acme/autocert: unable to satisfy \"https://acme-v02.api.letsencrypt.org/acme/authz-v3/149413948277\" for domain \"cdn2.streamcast.xyz\": no viable challenge type found" host="cdn2.streamcast.xyz"
ts=2022-09-03T21:40:01Z level=WARN component="Core" msg="Continuing with disabled TLS"
ts=2022-09-03T21:40:01Z level=INFO component="HTTP" msg="Server started" address=":8080"
ts=2022-09-03T21:40:01Z level=INFO component="Session" msg="Active" id="HTTP" location="any" peer="any" reference="" type="HTTP"
```

Where is the problem and how can I fix that? I tried 2 different vps with another provider. Same result. Please help me.

Thanks.

**Comment by jstabenow** [comment]
Hey @samiulus 
Have you read this guide?
https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-use-https-with-lets-encrypt

**Comment by samiulus** [comment]
> Hey @samiulus Have you read this guide? https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-use-https-with-lets-encrypt

Yes, I follow this link and do the same settings. Check my log report. Thanks.

**Comment by jstabenow** [comment]
Let's Encrypt was not able to verify the domain:
```sh
ts=2022-09-03T21:40:01Z level=ERROR component="Let's Encrypt" msg="Failed to acquire certificate" error="acme/autocert: unable to satisfy \"https://acme-v02.api.letsencrypt.org/acme/authz-v3/149413948277\" for domain \"cdn2.streamcast.xyz\": no viable challenge type found" host="cdn2.streamcast.xyz"
```

Check whether the domain points to the IP of your VPS and the Restreamer can be reached via `http://cdn2.streamcast.xyz`.
If not, check your DNS entry, your port forwarding / Docker command and your firewall.

**Comment by svenerbeck** [comment]
Hi @samiulus  
We are closing your issue https://github.com/datarhei/restreamer/issues/412.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team

**Comment by Bosutike** [comment]
I am having a similar issue.
After configuring the networking to use  let's encrypt (either with default ports or 80/443), it does not work.
I get this error in the logs:

`ts=2022-10-17T17:29:37Z level=ERROR component="Let's Encrypt" msg="Failed to acquire certificate" error="domain.com: obtaining certificate: [domain.com] Obtain: [domain.com] solving challenge: domain.com: [domain.com] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - 167.172.190.58: Fetching http://domain.com/.well-known/acme-challenge/5bhAXjccV49bco2qtpod2A2007UYV59kF36bQtzx-dw: Connection refused (ca=https://acme-v02.api.letsencrypt.org/directory)" host="domain.com"`

Apparently it can not access "/.well-known/acme-challenge/5bhAXjccV49bco2qtpod2A2007UYV59kF36bQtzx-dw".
Shouldn't this file be generated by restreamer? In this case, can this be a problem related to writing permissions?
