### ISSUE TITLE
Nginx Location

### ISSUE THREAD

**Issue by Kieranwest** [datarhei/restreamer#414]
Does Nginx exist within restreamer v2? 
I'm looking to make some hls changes within the nginx.conf file that helped improve latency in the prior version. 

Thanks

**Comment by svenerbeck** [comment]
Hello @Kieranwest 
Sorry for the high delay. 

There is no Nginx in Restreamer V2. To reduce the latency try the SRT transport. 

[Quick Start: SRT Server with Publication Service for multi-streaming with SRT in datarhei Restreamer](https://youtu.be/xwTdIeTLj_I)

[Quick start: use SRT protocol with OBS and datarhei Restreamer to reduce latency](https://www.youtube.com/watch?v=ATG2bOujuPU)

Cheerio
Sven
