### ISSUE TITLE
Custom DownSampling per platform

### ISSUE THREAD

**Issue by 7ekhed** [datarhei/restreamer#416]
Twitch has very specific bandwidth that they will allow, and I am trying to maximize my visual performance

By streaming in high fidelity to Restreamer, I can stream to YouTube at 1080p 10,000 kbps bitrate, but there appears to be no way to downsample from my 1080p stream to an 864p stream when streaming, let alone streaming just to Twitch. There is a way to change the bandwidth, just not a way to change the resolution.

Is there an option I'm missing or is this something that hasn't been added?

Thanks!

**Comment by 7ekhed** [comment]
69th issue ;) nice

**Comment by svenerbeck** [comment]
Hey Ho @7ekhed 

That's a good feature. We have taken your request to the feature request list.
[💡 Suggestions and feature requests #345](https://github.com/datarhei/restreamer/discussions/345)

Cheerio
Sven

**Comment by Hoerli1337** [comment]
Would also be happy about this function.
Just as an example:
I would like to stream to YouTube in 1440p (Copy), to Twitch in 1080p (Render by Restreamer) and to another platform maybe with 720p (Render by Restreamer).

**Comment by 7ekhed** [comment]
Wow, you guys actually took action on an idea of mine.... That's a first!!!

Thank you SO much for doing this!!

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
