### ISSUE TITLE
Youtube not stream 

### ISSUE THREAD

**Issue by danitus13** [datarhei/restreamer#423]
Sto usando un Orange Pi Debian
E sto mandando in streaming su Youtube una cam reolink 
Quando vado ad abilitare lo streaming su Youtube mi esce questo errore: 

[tcp @ 0xffffaa597a80] Failed to resolve hostname a.rtmp.youtube.com: Name does not resolve
[rtmps @ 0xffffa9b93540] Cannot open connection tls://a.rtmp.youtube.com:443
rtmps://a.rtmp.youtube.com/live2/******* : I/O error

**Comment by jstabenow** [comment]
Please extend the Docker command with the following parameter:
`--security-opt seccomp=unconfined`

**Comment by danitus13** [comment]
Fatto, ma esce sempre lo stesso errore

**Comment by jstabenow** [comment]
Please describe your setup (hardware, operating system) and check whether your computer can reach the address "a.rtmp.youtube.com." And show the Docker command you are using.

**Comment by danitus13** [comment]
> Descrivi la tua configurazione (hardware, sistema operativo) e controlla se il tuo computer può raggiungere l'indirizzo "a.rtmp.youtube.com". E mostra il comando Docker che stai usando.

Questo il comando

```
sudo docker run -d --restart=always --name restreamer    -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data    --privileged    -p 8080:8080 -p 8181:8181    -p 1935:1935 -p 1936:1936    -p 6000:6000/udp    --security-opt seccomp=unconfined    datarhei/restreamer:rpi-latest
9005ce9e7bf5547fe26a6b851d6e90db5acb38fca82435c446339716df433196
```
Hardware: orange pi zero 2
S.O. : debian bullseye

Come faccio a controllare se il mio pc può raggiungere l'indirizzo? Lo inserisco su un browser?

**Comment by jstabenow** [comment]
Please test the following:
```sh
sudo docker kill restreamer
sudo docker rm restreamer
sudo docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data --net=host datarhei/restreamer:latest
```

`:rpi-latest` is not required because your Orange Pi Zero2 uses a different GPU. 

If this does not work, check the address:
```sh
ping a.rtmp.youtube.com
```

**Comment by danitus13** [comment]
Fatto ancora non funziona,
quando faccio il ping mi restituisce:
64 bytes from mil41s04-in-f12.1e100.net (142.250.184.108): icmp_seq=12 ttl=114 time=20.7 ms

ecc...

**Comment by danitus13** [comment]
Ho questo dubbio, potrei sbagliare
Su Youtube url stream è: rtmps://a.rtmps.youtube.com/live2
mentre su restreamer mi restituisce: 
rtmps://a.rtmp.youtube.com/live2/**** : I/O error

non manca una "s a rtmp"?

**Comment by jstabenow** [comment]
It seems that the container has no network access. 

Next try:
```sh
sysctl -w net.ipv4.ip_forward=1
sudo service docker restart
```

**Comment by danitus13** [comment]
> ```shell
> sysctl -w net.ipv4.ip_forward=1
> sudo service docker restart
> ```

nulla

**Comment by jstabenow** [comment]
Do you have a firewall?

Docker tests:
```sh
docker run -it --rm alpine ping 1.1.1.1
docker run -it --rm alpine ping a.rtmps.youtube.com
```

**Comment by danitus13** [comment]
Il primo comando:

```
64 bytes from 1.1.1.1: seq=0 ttl=56 time=15.101 ms
64 bytes from 1.1.1.1: seq=1 ttl=56 time=13.867 ms
64 bytes from 1.1.1.1: seq=2 ttl=56 time=14.073 ms
64 bytes from 1.1.1.1: seq=3 ttl=56 time=14.008 ms
64 bytes from 1.1.1.1: seq=4 ttl=56 time=14.603 ms
64 bytes from 1.1.1.1: seq=5 ttl=56 time=13.950 ms
64 bytes from 1.1.1.1: seq=6 ttl=56 time=14.189 ms
64 bytes from 1.1.1.1: seq=7 ttl=56 time=14.376 ms
64 bytes from 1.1.1.1: seq=8 ttl=56 time=14.397 ms
```
Il secondo 

ping: bad address 'a.rtmps.youtube.com'

**Comment by jstabenow** [comment]
Nice! Next:
```sh
docker run -it --rm --dns 1.1.1.1 alpine ping a.rtmps.youtube.com
```

**Comment by danitus13** [comment]
> ```shell
> docker run -it --rm --dns 1.1.1.1 alpine ping a.rtmps.youtube.com
> ```

questo funziona:

```
64 bytes from 142.250.180.172: seq=0 ttl=113 time=21.641 ms
64 bytes from 142.250.180.172: seq=1 ttl=113 time=21.206 ms
64 bytes from 142.250.180.172: seq=2 ttl=113 time=21.365 ms
64 bytes from 142.250.180.172: seq=3 ttl=113 time=21.681 ms
64 bytes from 142.250.180.172: seq=4 ttl=113 time=21.864 ms
64 bytes from 142.250.180.172: seq=5 ttl=113 time=21.594 ms
64 bytes from 142.250.180.172: seq=6 ttl=113 time=21.527 ms
```

**Comment by jstabenow** [comment]
It's a DNS error:
```sh
sudo docker kill restreamer
sudo docker rm restreamer
sudo docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data --privileged -p 8080:8080 -p 8181:8181 -p 1935:1935 -p 1936:1936 -p 6000:6000/udp --security-opt seccomp=unconfined --dns 1.1.1.1 datarhei/restreamer:rpi-latest
```

**Comment by danitus13** [comment]
> È un errore DNS:
> 
> ```shell
> sudo docker kill restreamer
> sudo docker rm restreamer
> sudo docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data --privileged -p 8080:8080 -p 8181:8181 -p 1935:1935 -p 1936:1936 -p 6000:6000/udp --security-opt seccomp=unconfined --dns 1.1.1.1 datarhei/restreamer:rpi-latest
> ```

Funziona. Grazie mille!

**Comment by jstabenow** [comment]
You are welcome 👍

**Comment by danitus13** [comment]
> You are welcome 👍

Ciao Jstabenow,
ho un nuovo problema purtroppo. 
Dopo qualche ora di srtreaming, youtube si blocca. 
Da restream nessun errore e da Youtube Studio mi dice "connessione buona" 
Ma la diretta è bloccata a ieri sera:

https://www.youtube.com/watch?v=tSjOft4G6JQ

Da cosa può dipendere?

**Comment by jstabenow** [comment]
Disable “low delay” and show the process report if there are still problems:

![Bildschirmfoto 2022-10-06 um 11 05 38](https://user-images.githubusercontent.com/7462030/194272935-fdea4554-288e-4120-a2bd-0529d3a6e980.png)

**Comment by danitus13** [comment]
> Disattiva il "ritardo basso" e mostra il rapporto di processo se ci sono ancora problemi:
> 
> ![Bildschirmfoto 2022-10-06 um 11 05 38](https://user-images.githubusercontent.com/7462030/194272935-fdea4554-288e-4120-a2bd-0529d3a6e980.png)

sorry I had opened another discussion, because I had seen that you had closed this one. You can delete the other.
Now the transmission has resumed. I text for a while and let you know if there are any other problems.
Thank you again.

**Comment by danitus13** [comment]
Ciao Jan, alle 5.02pm si è bloccato nuovamente.


```
"ffmpeg` version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers",
            "  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027",
            "  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-omx --enable-omx-rpi --enable-libv4l2 --enable-v4l2_m2m --enable-alsa --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared",
            "  libavutil      56. 70.100 / 56. 70.100",
            "  libavcodec     58.134.100 / 58.134.100",
            "  libavformat    58. 76.100 / 58. 76.100",
            "  libavdevice    58. 13.100 / 58. 13.100",
            "  libavfilter     7.110.100 /  7.110.100",
            "  libswscale      5.  9.100 /  5.  9.100",
            "  libswresample   3.  9.100 /  3.  9.100",
            "  libpostproc    55.  9.100 / 55.  9.100",
            "[http @ 0xffffafe1de50] HTTP error 404 Not Found",
            "http://[anonymized] Server returned 404 Not Found"
          ],
          "log": [
            [
              "1665052980",
              "ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers"
            ],
            [
              "1665052980",
              "  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027"
            ],
            [
              "1665052980",
              "  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-omx --enable-omx-rpi --enable-libv4l2 --enable-v4l2_m2m --enable-alsa --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared"
            ],
            [
              "1665052980",
              "  libavutil      56. 70.100 / 56. 70.100"
            ],
            [
              "1665052980",
              "  libavcodec     58.134.100 / 58.134.100"
            ],
            [
              "1665052980",
              "  libavformat    58. 76.100 / 58. 76.100"
            ],
            [
              "1665052980",
              "  libavdevice    58. 13.100 / 58. 13.100"
            ],
            [
              "1665052980",
              "  libavfilter     7.110.100 /  7.110.100"
            ],
            [
              "1665052980",
              "  libswscale      5.  9.100 /  5.  9.100"
            ],
            [
              "1665052980",
              "  libswresample   3.  9.100 /  3.  9.100"
            ],
            [
              "1665052980",
              "  libpostproc    55.  9.100 / 55.  9.100"
            ],
            [
              "1665052980",
              "[http @ 0xffffafe1de50] HTTP error 404 Not Found"
            ],
            [
              "1665052980",
              "http://[anonymized] Server returned 404 Not Found"
```
`

**Comment by danitus13** [comment]
> Disattiva il "ritardo basso" e mostra il rapporto di processo se ci sono ancora problemi:
> 
> ![Bildschirmfoto 2022-10-06 um 11 05 38](https://user-images.githubusercontent.com/7462030/194272935-fdea4554-288e-4120-a2bd-0529d3a6e980.png)

Buongiorno Jan,
questa notte si è interrotto nuovamente alle 3.59. Non riavvio nulla, così per capire dov'è il problema. 

Questo il report: 

[report2.txt](https://github.com/datarhei/restreamer/files/9738828/report2.txt)

**Comment by jstabenow** [comment]
Hey @danitus13
Strange. The report is clean. Please activate the "BACKUP STREAM":
<img width="337" alt="Bildschirmfoto 2022-10-08 um 14 14 34" src="https://user-images.githubusercontent.com/7462030/194707050-854264c5-ce5d-42ec-b2d2-dd9339e130d0.png">
Maybe that helps.

**Comment by danitus13** [comment]
> Ehi@danitus13 Strano. Il rapporto è pulito. Si prega di attivare il "BACKUP STREAM": forse questo aiuta. <img alt="Bildschirmfoto 2022-10-08 um 14 14 34" width="337" src="https://user-images.githubusercontent.com/7462030/194707050-854264c5-ce5d-42ec-b2d2-dd9339e130d0.png">

Ho provato, questa notte alle 3.27 si è bloccato nuovamente. Su Youtube lo stream arriva dice "connessione eccellente", su restreamer anche. Ti mando il file di report: 

[report 3.txt](https://github.com/datarhei/restreamer/files/9740970/report.3.txt)

**Comment by jstabenow** [comment]
Maybe you are also affected by this:
https://twitter.com/obsproject/status/1578937361303359489?s=46&t=ggU-awKLPwxHwtVJ_vGwUA

I'll look at the report later.

**Comment by jstabenow** [comment]
Please try:
1. edit channel > Processing & Control > Enable RTMP & disable the "low delay" option
2. select your YouTube publishing service > Source & Control > Switch source to RTMP

I am curious to see if it works better this way. We have no problems.

**Comment by danitus13** [comment]
> Vi preghiamo di provare:
> 
> 1. modifica canale> Elaborazione e controllo> Abilita RTMP e disabilita l'opzione "ritardo basso".
> 2. seleziona il tuo servizio di pubblicazione YouTube > Sorgente e controllo > Cambia sorgente in RTMP
> 
> Sono curioso di vedere se funziona meglio in questo modo. Non abbiamo problemi.

Devo attivare solo RTMP non anche l'RTMPS?

**Comment by jstabenow** [comment]
RTMP.

**Comment by danitus13** [comment]
> RTMP.

Ok abilitato.
Va tutto ok, ma nel report esce questo errore: 

Non-monotonous DTS in output stream 0:0; previous: 11467, current: 11462; changing to 11468. This may result in incorrect timestamps in the output file.

Potrebbe creare dei problemi?

**Comment by jstabenow** [comment]
Not necessarily.

**Comment by danitus13** [comment]
> Not necessarily.

Ciao, sto avendo nuovamente un problema di interruzioni, su un raspberry 3.
Ogni tot di tempo casuale l'inivio dello streaming su Youtube si interrompe (diventa il pallino rosso)
e nonostante c'è la riconnessione attivata, continua ad andare in errore. 
L'unico modo per far riprendere lo streaming è rivviare restreamer. 

Questo è il report:
[report.txt](https://github.com/user-attachments/files/17526421/report.txt)

Soluzioni? 

Grazie
