### ISSUE TITLE
Youtube stops after some time

### ISSUE THREAD

**Issue by danitus13** [datarhei/restreamer#424]
S.O: Orange Pi Debian
Hardware: Orange Pi zero 2

I'm streaming a webcam reolink 24/7. But after some time Youtube blocks the broadcast.
There is no error on Restreamer.
And on Youtube the connection is "good"

Link streaming: https://www.youtube.com/watch?v=tSjOft4G6JQ

Here it is 11.10, but the transmission is blocked at 00.10

**Comment by svenerbeck** [comment]
Hello @danitus13 
Honestly, I don't understand this request. The stream goes through without any problems. We close the ticket.

Cheerio
Sven

**Comment by danitus13** [comment]
> Hello @danitus13 Honestly, I don't understand this request. The stream goes through without any problems. We close the ticket.
> 
> Cheerio Sven

Perchè l'avevo riavviato ieri. Stanotte si è bloccato di nuovo. Questa volta non lo riavvio.
