### ISSUE TITLE
Local server not probing rtmp stream

### ISSUE THREAD

**Issue by riddlenl** [datarhei/restreamer#428]
I'm trying to use the built in RTMP server to get a stream in, however whatever I do, the wizard keeps saying "No live stream was detected. Please check the software that sends the stream."

Tried vMix and OBS both, and they say the stream is incoming.

In the probe logs, I see this:

ffmpeg version 4.4.2-datarhei Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.3.1 (Alpine 10.3.1_git20211027) 20211027
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[tcp @ 0x7f38940f4ec0] Connection to tcp://localhost:443 failed: Address not available
[rtmps @ 0x7f389449ae80] Cannot open connection tls://localhost:443
rtmps://localhost/56180912-0dd3-42bc-b926-6d8697cce356.stream?token=secretserver: Address not available

This is what I see in logging when I start the stream:

ts=2022-10-17T12:32:38Z level=INFO component="Session" msg="Active" id="/56180912-0dd3-42bc-b926-6d8697cce356.stream" location="publish:/56180912-0dd3-42bc-b926-6d8697cce356.stream" peer="MY IP:58620" reference="/56180912-0dd3-42bc-b926-6d8697cce356" type="rtmp"
ts=2022-10-17T12:32:38Z level=DEBUG component="Session" msg="Active" id="/56180912-0dd3-42bc-b926-6d8697cce356.stream" location="publish:/56180912-0dd3-42bc-b926-6d8697cce356.stream" peer="MY IP:58620" reference="/56180912-0dd3-42bc-b926-6d8697cce356" type="rtmp"
ts=2022-10-17T12:32:38Z level=INFO component="RTMP/S" action="START" address=":1935" client="MY IP:58620" path="/56180912-0dd3-42bc-b926-6d8697cce356.stream" who="PUBLISH"
ts=2022-10-17T12:32:38Z level=INFO component="RTMP/S" msg="AAC" action="STREAM" address=":1935" client="MY IP:58620" path="/56180912-0dd3-42bc-b926-6d8697cce356.stream" who="PUBLISH"
ts=2022-10-17T12:32:38Z level=INFO component="RTMP/S" msg="H264" action="STREAM" address=":1935" client="MY IP:58620" path="/56180912-0dd3-42bc-b926-6d8697cce356.stream" who="PUBLISH"
ts=2022-10-17T12:32:38Z level=DEBUG component="HTTPS" address=":8080" client="172.17.0.1" latency_ms=6 method="POST" path="/api/v3/metrics" proto="HTTP/2.0" rx_size_bytes=287 status=200 status_text="OK" tx_size_bytes=471 user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

I have another channel pulling from a remote rtmp stream and that is working

Update 20:30 I unchecked "RTMPS server" in the settings and now it's working correctly.

**Comment by jstabenow** [comment]
Hey @riddlenl
Already fixed [here](https://github.com/datarhei/restreamer-ui/commit/df9ae03900e8b89f03bf35a76a0f5c5dbf63696d). And once again for testing: `datarhei/restreamer:dev`

**Comment by jstabenow** [comment]
Problem is solved in v2.4.x.

💛 If you were satisfied with the support, and we could help you, please [rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review).
