### ISSUE TITLE
How to remove to big logo ;) 

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#431]
**Describe the bug**
How to remove a logo or make it emty - if its to big or bad.
I tried to delete the filename but it did not remove it.

**To Reproduce**
Upload a to big logo  and see how it looks in the player site with chanals.
I goes outside the border.

![image](https://user-images.githubusercontent.com/24371165/196381538-75286af6-2a84-4c0e-b392-9bfff67c2144.png)

**Comment by jstabenow** [comment]
@FilipStadler Thx :-) Working on it.

Todo:
- [x] responsive logo
- [x] option to drop/remove a logo
- [x] fix `player.overlay is not a function` (npm dependency^^)

**Comment by jstabenow** [comment]
@FilipStadler 
“Workaround” for `drop/remove a logo`: Clean up the input field for `Image URL` and save.

**Comment by jstabenow** [comment]
It's inside v2.4.0:

![Bildschirmfoto 2022-11-12 um 15 59 48](https://user-images.githubusercontent.com/7462030/201480176-83d1c032-7c72-42a8-811a-552e945e75c8.png)

Thanks, @FilipStadler 👍
