### ISSUE TITLE
FFMPEG log error 'pkt->duration = 0'

### ISSUE THREAD

**Issue by utilsites** [datarhei/restreamer#433]
Detected the following FFMPEG LOG repeated on Restreamer:
_**"pkt->duration = 0, maybe the hls segment duration will not precise"**_

It seams that the video image has not changing because it was a livestream on still image zone, so the fps was bellow 10.
On iOS 15+ safari the web video player shows the following error:
**_"the media playback was aborted due to a corruption problem pr because the media used features your browser did not support"_**

But if the livestream cam is pointed to a tree that wags with the wind, the fps increases, and the video **starts working again** on iOS.

Do we need to change some Restreamer setting to fix the problem? (Using defaults)

**Smartphone:**
 - Device: iPhone 11
 - OS: iOS 15+
 - Browser:  safari, chrome on iOS

**Additional context**
On Android and Windows it works always.

**Comment by jstabenow** [comment]
Hey @utilsites
My recommendation: Do not use dynamic frame rates and try >= 18 FPS. 
Check if you can switch the camera to CFR (Constant Frame Rate).

Otherwise, specify what kind of camera you are using.

**Comment by utilsites** [comment]
In the cam config app it's set to 25 FPS (check image bellow), so I think it should be constant.
Even so, maybe this can be set/forced using a FFMPEG or Restreamer setting?
The cam is [CamHi PTZ IP ](http://www.ipcam.xin/)

![cam-settings](https://user-images.githubusercontent.com/15893370/196791292-f693d421-25f1-43a4-9f26-5539f764d97b.jpg)

**Comment by jstabenow** [comment]
Uuuh, Hightech :sweat_smile: Unfortunately, I can't help you with the camera. 
So let's try to solve this via the Restreamer. I'll take a look.

**Comment by jstabenow** [comment]
Good morning! 
The `fps_mode` is ready but needs FFmpeg v5, which will come next week.
I'll get back to you as soon as everything is public.

**Comment by utilsites** [comment]
> 

Amazing! Thanks for the change and speed!
I think it's good improvement for Restreamer, as other users may have the same problem, as iOS is always more nitpicking in livestreaming.
Also I thought that Restreamer V2 was using FFmpeg v5, but noticed that is using v4, so I think it will be also a good improvement, to use the latest version of FFmpeg.
It also will be good to be able to set _fps_mode_ from the Restreamer UI web interface, I think that is the case.
I'm waiting for the change.
Thanks

**Comment by utilsites** [comment]
> Good morning! The `fps_mode` is ready but needs FFmpeg v5, which will come next week. I'll get back to you as soon as everything is public.

Hi, any news regarding this improvement?
Best regards.

**Comment by jstabenow** [comment]
Please check our current version (2.4.0).

**Comment by utilsites** [comment]
Nice! Going to test the latest version.
Does it have a new UI setting to set the minimum fps?

**Comment by jstabenow** [comment]
Look here:

![Bildschirmfoto 2022-11-15 um 10 46 38](https://user-images.githubusercontent.com/7462030/201886878-88a5d102-058a-4434-b12c-6cb8311b552f.png)

Channel setup > General > Video settings > Advanced settings > H.264 encoding

**Comment by utilsites** [comment]
Updated to the latest version (2.4.1), configured the encoding setting to "Constant frame rate (CFR)", and now it **works well on iphone with a still image video**!!
And it's good to be processing on the latest ffmpeg version 5.

Thanks a lot! Amazing! @jstabenow 
You deserve a donation, going to make that during this year.

Just a small note, it was difficult to find the setting, because it need to press the "PROBE" button.

**Comment by jstabenow** [comment]
Ah, okay. I'm a little more familiar with the product :sweat_smile:
Glad to hear it's working. But **it works well on iphone with a still image video**?  Is that good?^^ Hope so. 

And you're welcome.

**Comment by utilsites** [comment]
Let me explain better, what was happening, like described above, was that when the images on the camera don't change during some seconds, the FPS goes down a lot, bellow 25, because the image is still during some seconds, so no new frames needed I think. 
It seems like iOS does not like that, or at least with the default specific cam + restreamer configs, so the livrestream didn't work on iOS at least on iOS 15.4+ Safari.
But after putting constant 25 FPS on restreamer new setting, now the livestream  works well on iOS even when the image is still for a few seconds.
