### ISSUE TITLE
Icecast doesn't allow insert data

### ISSUE THREAD

**Issue by MauricioOnetto** [datarhei/restreamer#437]
Hello
I'm using Restreamer behind Nginx (Debian 11)
All works great
I'm restreaming to Facebook, Twitch, Youtube, etc
But when I try to add Icecast it doesn't allow insert data of my server
(address input next to protocol input)
I can select the input but I can't add any text by keyboard neither can't paste data
Thank you

**Comment by svenerbeck** [comment]
If you have an error in the Restreamer, upload the error log file here. Please note that we do not process requests for errors without the log files. [How to get the error report on YouTube.](https://www.youtube.com/watch?v=mZMGrweFCsM)

**Comment by ioppermann** [comment]
Duplicate of #429
