### ISSUE TITLE
adding rtsp feed does not work ...

### ISSUE THREAD

**Issue by jeffd2651** [datarhei/restreamer#44]
Tested the rtsp feed in VLC player as 'Open a Network feed' and it resolves and plays the rtsp from the IP camera yet when I try adding the same feed into Restreamer it simply reports, "Streaming process is initiating. Please wait... " and it just cycles and will not pick up the feed ! :(
Tried both with and without "RTSP over TCP" ticked but same result.
Is there something elemental I'm missing here ??

Tried both ...
rtsp://jeff***xxxxx:xxxxxxxxx@jdan.noip.me:1090/12
and
rtsp://jeff***xxxxx:xxxxxxxxx@192.168.1.190:1090/12 and they both work OK in VLC but neither will add to Restreamer

**Comment by svenerbeck** [comment]
Hello jeffd2651
does your problem still need to be solved?

Cheerio
Sven
