### ISSUE TITLE
Custom RTMP?

### ISSUE THREAD

**Issue by threehappypenguins** [datarhei/restreamer#445]
This may be obvious, but I cannot find the answer. How can I add a custom rtmp address and stream key? For example, if I go to add a Program and choose "RTMP", I can add an rtmp address, but there is no option anywhere to add a stream key.

How can I add both an rtmp address AND stream key together?

**Comment by ioppermann** [comment]
You can simply concatenate them. The stream key is usually the last part of the RTMP address, e.g. `rtmp://stream.example.com/live/[stream key]`.

**Comment by threehappypenguins** [comment]
> You can simply concatenate them. The stream key is usually the last part of the RTMP address, e.g. `rtmp://stream.example.com/live/[stream key]`.

Works perfectly. Thanks!
