### ISSUE TITLE
SRT Vmix

### ISSUE THREAD

**Issue by andersoncgpb1** [datarhei/restreamer#452]
I did all the configuration in Vmix and it didn't work, can someone help me?
[https://ibb.co/pxVrt0s](url)
[https://ibb.co/7bDQpK7](url)
[https://ibb.co/0cTdV7p](url)

**Comment by svenerbeck** [comment]
Hello @andersoncgpb1 
Is that obsolete with the update you wrote in Discord?

Cheerio
Sven

**Comment by wilkerq** [comment]
how to use in vmix? all the ways I tried, no signal arrives

**Comment by andersoncgpb1** [comment]
Yes, I disabled the Windows firewall
