### ISSUE TITLE
ffmpeg: Unrecognized option 'stimeout'. on adding new network source

### ISSUE THREAD

**Issue by redrob** [datarhei/restreamer#462]
On a fresh installation of the latest (v16.11.0) docker image on Ubuntu 18.04.6 LTS. I attempted to add a pull-type network source which happens to be an RTSP URL (rtsp://<IP>:554/s0). I also entered a username and password. When I click 'Probe' to continue I receive an error 'Failed to probe the source. Please check the [probe details]'. Upon inspecting the details I see a ffmpeg error;

Unrecognized option 'stimeout'.
Error splitting the argument list: Option not found

**To Reproduce**
1. NEXT: VIDEO SETUP
2. ADVANCED SETUP
3. Network source
4. Pull Mode
5. URL rtsp://<IP>:554/s0
6. Enter username
7. Enter password
8. Press Probe
9. See Error

**Expected behavior**
ffmpeg version 5.1.2-datarhei Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Unrecognized option 'stimeout'.
Error splitting the argument list: Option not found

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS X 12.6
 - Google Chrome 107.0.5304.87

**Comment by jstabenow** [comment]
Hey @redrob 
It is fixed in v2.4.1. Please update to the latest version.

**Comment by svenerbeck** [comment]
Dear @redrob 
We are closing your issue #462.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team

**Comment by redrob** [comment]
Yes, all is working as expected now on the latest release. Thanks
