### ISSUE TITLE
Unable to add network source after 2.4.0

### ISSUE THREAD

**Issue by Eruthon** [datarhei/restreamer#467]
**Describe the bug**
With v2.3.0 I could add rtsp://*IP*/mpeg4/media.amp for my Axis 211M camera. After the update the GUI succesfully probes the stream, but doesn't let me click NEXT at "Video setup" page, after which the "Audio Setup" page should show up as in v2.3.0. It works with my other newer camera, though.

**To Reproduce**
1. Click on Camera list button
2. Click on '+' to add new source
3. Put in the rtsp://<IP>/mpeg4/media.amp source address
4. Click NEXT and nothing happens

**Expected behavior**
After clicking NEXT at Video setup, I should see Audio setup

**Screenshots**
After clicking nothing happens: 
![image](https://user-images.githubusercontent.com/37985268/202858240-6c0badce-e624-434a-ac8c-4c93ac4c23e7.png)
v2.3.0 shows this:
![image](https://user-images.githubusercontent.com/37985268/202858188-5068165e-6f98-44e7-b0ac-d603d5d15d3d.png)

**Desktop (please complete the following information):**
 - OS restreamer runs on: Debian 11 VM on Proxmox, running with Rancher v2.6 with Kubernetes v1.24.6
 - Browser of my PC: edge, brave
 - Version of restreamer: 2.4.x

**Comment by svenerbeck** [comment]
Hello @Eruthon 
Please update to the latest version v2.4.1 to solve the error.
Cheerio
Sven

**Comment by Eruthon** [comment]
Hi @svenerbeck 
Been there, done that. Didn't help. I've read some issues here that were solved by it, but not mine.

**Comment by svenerbeck** [comment]
Hello @Eruthon 
Thanks for reporting the error. We will fix the bug in one of the following versions. Until then, use the **workaround and switch to the advanced wizard**. We were able to create the video sources. 
![Bildschirm­foto 2022-11-21 um 10 57 29](https://user-images.githubusercontent.com/12124066/203021468-367ceece-6c52-4965-8e0a-55230da28fb5.png)

Cheerio
Sven

**Comment by Eruthon** [comment]
Yep, that works, thx

**Comment by srgzx** [comment]
Same issue here, and the workaround (using advanced mode) works perfectly.  Thank you <3

**Comment by svenerbeck** [comment]
Hello @Eruthon 

We are closing your ticket https://github.com/datarhei/restreamer/issues/467.

This may be due to the following reasons:

- Problem has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
Sven
