### ISSUE TITLE
Send srt stream link from restreamer to watch from VLC player

### ISSUE THREAD

**Issue by Azhdar1990** [datarhei/restreamer#468]
Hello.
First of all thanks for this great project.
When i start to stream srt from OBS i put a link from restreamer which I've installed on docker.
After starting the stream from OBS everything works fine and i see my stream via web player which is included in restream.
But how can i watch my stream from VLC player or send srt link for my friends so they can see the stream?
I will be very pleased if you help me.
Thanks in advance.

**Comment by FilipStadler** [comment]
For some strange reason not all vlc players have inluded support for SRT - my vlc 3.16 on linux have rist but not srt
the link for view should be visible on the Content URL - I dont why SRT its not really in all vlc by now when RIST is.

 - you can also try with the Larix Player https://softvelum.com/player/

**Comment by Azhdar1990** [comment]
But where can I get a link to put in vlc or another player?
I know only one link, which I put into OBS to stream to restreamer server.

**Comment by FilipStadler** [comment]
![srtlink](https://user-images.githubusercontent.com/24371165/202916871-6b533eb1-e742-4f07-859b-7343539dd3ed.png)

If you are running a SRT server...

**Comment by Azhdar1990** [comment]
VLC is support srt.
I've used Content URL in vlc player but it don't play stream.
I have also Vimix server.
I just put a link to the vlc player from Vimix "srt://vimixip:port" and then vlc player starts show stream.
Maybe srt server on restreamer must be configure somehow that vlc start to get stream from it?

**Comment by jstabenow** [comment]
Hey @Azhdar1990 
VLC 3.0.17.3@OSX + Restreamer v2.4.x works. 

1. Copy the SRT URL (@FilipStadler screener)
2. Use them in VLC.

And check the SRT URL:
srt://`address:port`/?mode=caller&transtype=live&streamid=`channelID`,mode:request

**Comment by svenerbeck** [comment]
Hello 

We are closing your ticket https://github.com/datarhei/restreamer/issues/468.

This may be due to the following reasons:

- Problem/inquiry has been solved
- **Ticket remained unanswered by you for a more extended period**
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
