### ISSUE TITLE
Nothing happens when selecting Youtube or any other streaming service

### ISSUE THREAD

**Issue by Martijndutch** [datarhei/restreamer#474]
When I try to publish a stream to e.g. youtube, nothing happens when I click the logo. There seems to be a browser error.

Maybe related, maybe not: I can't get SSL to work. I've entered all the data, forwarded the port and so on, but when trying to connect at 8181 it refuses to connect. 

Environment: Proxmox VM running Ubuntu 20, fresh install with no other software running on the VM. Tried different browsers, chrome, edge, mobile, desktop, incognito etc. Doesn't make a difference

![image](https://user-images.githubusercontent.com/1003284/203572603-749c4d24-4e23-4a84-8aac-8179e0b16e33.png)

[core (2).log](https://github.com/datarhei/restreamer/files/10076482/core.2.log)

**Comment by ioppermann** [comment]
Unfortunatly, I can't reproduce the error with the publication to Youtube.

What is your docker command and please share your "Process report" (https://docs.datarhei.com/restreamer/knowledge-base/manual/process-report) while the stream is connected.

The failing SSL setup is most likely not connected to the error you experience with the publication service.

**Comment by Martijndutch** [comment]
Shoot me. I've stopped/started the stream and then it worked. I've installed a second docker image and can't reproduce it either. Consider it a glitch, closed.
