### ISSUE TITLE
 Sound distortion

### ISSUE THREAD

**Issue by Alekspom** [datarhei/restreamer#475]
In the process of broadcasting, at some point in time, sound distortion begins in the restream stream. Link to example files:
https://disk.yandex.ru/d/vTxN-IySTvjaEQ
(2 fragments are presented: the original stream and the stream after the restreamer).
What could be the problem?

The effect has been tested and confirmed repeatedly.

Thank you for your time!

**Comment by jstabenow** [comment]
Hey @Alekspom 
Please attach the process report. 
Afterward, we'll take a look.

Thx.

**Comment by Alekspom** [comment]
Ок

**Comment by Alekspom** [comment]
@1669882894     7.1             : false
@1669882894     fileSize        : 0
@1669882894     title           : http://see-life.ru:8080/6e202013-9973-4b7a-86da-08935fed0021/oembed.json
@1669882894     encoder         : Lavf59.27.100
@1669882894   Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s
@1669882894   Stream #0:1: Video: h264 (High), yuv420p(tv, progressive), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 6144 kb/s, 50 fps, 50 tbr, 90k tbn
@1669882894 ffmpeg.mapping:{"graphs":[],"mapping":[{"input":{"index":0,"stream":0},"output":{"index":0,"stream":0},"copy":true},{"input":{"index":0,"stream":1},"output":{"index":0,"stream":1},"copy":true}]}
@1669882894 Stream mapping:
@1669882894   Stream #0:0 -> #0:0 (copy)
@1669882894   Stream #0:1 -> #0:1 (copy)
@1669882894 Press [q] to stop, [?] for help
@1669882894 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1148_var0.ts' for writing
@1669882894 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882899 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1149_var0.ts' for writing
@1669882899 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882904 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1150_var0.ts' for writing
@1669882909 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1151_var0.ts' for writing
@1669882909 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882914 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1152_var0.ts' for writing
@1669882914 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1142_var0.ts' for writing
@1669882919 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1153_var0.ts' for writing
@1669882919 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1143_var0.ts' for writing
@1669882919 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882924 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1154_var0.ts' for writing
@1669882924 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1144_var0.ts' for writing
@1669882929 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1155_var0.ts' for writing
@1669882929 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1145_var0.ts' for writing
@1669882929 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882934 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1156_var0.ts' for writing
@1669882934 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1146_var0.ts' for writing
@1669882939 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1157_var0.ts' for writing
@1669882939 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1147_var0.ts' for writing
@1669882939 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882944 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1158_var0.ts' for writing
@1669882944 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1148_var0.ts' for writing
@1669882949 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1159_var0.ts' for writing
@1669882949 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1149_var0.ts' for writing
@1669882949 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882954 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1160_var0.ts' for writing
@1669882954 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1150_var0.ts' for writing
@1669882959 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1161_var0.ts' for writing
@1669882959 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1151_var0.ts' for writing
@1669882959 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882964 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1162_var0.ts' for writing
@1669882964 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1152_var0.ts' for writing
@1669882969 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1163_var0.ts' for writing
@1669882969 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1153_var0.ts' for writing
@1669882969 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021.m3u8' for writing
@1669882974 [hls       ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1164_var0.ts' for writing
@1669882974 [mpegts    ] Opening 'http://admin:6LSFGLdIJNF67QJUEE@localhost:8080/memfs/6e202013-9973-4b7a-86da-08935fed0021_1154_var0.ts' for writing

**Comment by Alekspom** [comment]
https://www.youtube.com/watch?v=GuJ7nwBQLSk

**Comment by Alekspom** [comment]
Music distortion...

**Comment by jstabenow** [comment]
Hey @Alekspom 
We need the real process report:
https://docs.datarhei.com/restreamer/knowledge-base/manual/process-report

Please attach. Thx

**Comment by Alekspom** [comment]
Just moment...

**Comment by Alekspom** [comment]
[report.txt](https://github.com/datarhei/restreamer/files/10130947/report.txt)

**Comment by jstabenow** [comment]
Okay, what can we do?
1. `rtmp://[anonymized] I/O errors` are connection errors. Try to stabilize the source stream. 
2. Enable `AAC` Encoding in the `Advanced Setup Wizard`. It should help with synchronization.
3. If it doesn't work either, enable video encoding and test again.

**Comment by Alekspom** [comment]
Ок, try and test again, thanks!

**Comment by skadiexe** [comment]
same problems with chain
RTMP PULL -- datarhei -- YOUTUBE

even short drop of signal causes audio to interrupt for long time, till the output restart in datarhei

stop and start with good connection often leads to the same result 
i have enabled AAC audio transcoding (source is AAC too)
will check and update

**Comment by skadiexe** [comment]
Enabling transcoding to AAC solves the problem in most cases, but not 100% helps. Sometimes audio  starts to glitch again.

**Comment by grinmusic** [comment]
Hi, I had the same problem. Here's what I found out:
When you create a publication on YouTube, you need to change the source from HLS to RTMP, then the sound will not be distorted.
![Снимок экрана 2023-01-09 155610](https://user-images.githubusercontent.com/122279051/211313115-59d7c79d-4381-4ca6-9abb-c95bc74e923f.jpg)

**Comment by svenerbeck** [comment]
Hello @Alekspom 

We are closing your ticket https://github.com/datarhei/restreamer/issues/475.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
