### ISSUE TITLE
HTML player does not play source from restreamer

### ISSUE THREAD

**Issue by msikorski26** [datarhei/restreamer#476]
HLS source not loading in HTML player

HTML code:
`<video width="600" height="400" controls>
    <source src="url" type="application/x-mpegURL">
</video>`

**Comment by jstabenow** [comment]
Hello @mscodepl 

Please:
1. Please attach the process report
2. Describe where the error occurs

Thx.

**Comment by msikorski26** [comment]
The source of the problem is not the restreamer but that chrome for PC does not support HLS source in <video> HTML5 tags. I close the ticket
