### ISSUE TITLE
video multi quality?

### ISSUE THREAD

**Issue by advphp** [datarhei/restreamer#478]
How can I make more than one video quality?

4K
FHD
HD
SD

**Comment by drboudjelida** [comment]
I am also interested in the answer

**Comment by jstabenow** [comment]
Multiple bitrates are unsupported. But I put it to the [feature requests](https://github.com/datarhei/restreamer/discussions/345).
So follow the list and stay informed 👍

**Comment by msikorski26** [comment]
I too am interested in this function

**Comment by svenerbeck** [comment]
Hello @advphp 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
