### ISSUE TITLE
USB Cam not accessible

### ISSUE THREAD

**Issue by anandbaskaran** [datarhei/restreamer#48]
Hello,

I am trying to steam audio and video from my Mobilus USB camera connected with odroid board. Installation works like a charm. 

However, when I try to start in the USB mode, the sever don't respond at at all :(

**Comment by anandbaskaran** [comment]
From the logs I see that the node server is getting restated frequently without serving the webpage. 

[USBModeLogs.log](https://github.com/datarhei/restreamer/files/1390486/USBModeLogs.log)

**Comment by svenerbeck** [comment]
Hello anandbaskaran
USB is kinda depricated. The focus is on ip video. 
Cheerio
Sven
