### ISSUE TITLE
Bad gateway error

### ISSUE THREAD

**Issue by msikorski26** [datarhei/restreamer#480]
I added the domain to the settings and got something like this:
![image](https://user-images.githubusercontent.com/41286754/204340863-dd4cc715-dfea-4492-aa39-043951aad256.png)

My apache2 configuration:
`<VirtualHost *:80>
  ServerName streams.mscode.pl

  ProxyPass / http://localhost:31000/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
</VirtualHost>

<VirtualHost *:443>
  ServerName streams.mscode.pl
  SSLEngine on
  SSLProxyEngine On
  SSLCertificateFile /etc/letsencrypt/live/streams.mscode.pl/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/streams.mscode.pl/privkey.pem
  Protocols h2 http/1.1
  ProxyPass / https://localhost:31000/
  ProxyPassReverse / https://localhost:31000/
  RewriteEngine on
  RewriteCond %{HTTP:Upgrade} websocket [NC]
  RewriteCond %{HTTP:Connection} upgrade [NC]
</VirtualHost>`

**Comment by ioppermann** [comment]
If you already terminate SSL in your apache, then you don't need to enable it in Restreamer. You simply pass it to http://localhost:31000/. A user from the internet connects via HTTPS to your apache, then apache is accessing Restreamer via HTTP on localhost.

This configuration might be enough (tested it locally):

```
<VirtualHost *:80>
   ServerName streams.mscode.pl

   <Location "/">
      ProxyPass http://localhost:31000/
   </Location>
</VirtualHost>

<VirtualHost *:443>
   ServerName streams.mscode.pl
   SSLEngine on
   SSLProxyEngine On
   SSLCertificateFile /etc/letsencrypt/live/streams.mscode.pl/fullchain.pem
   SSLCertificateKeyFile /etc/letsencrypt/live/streams.mscode.pl/privkey.pem
   Protocols h2 http/1.1

   <Location "/">
      ProxyPass http://localhost:31000/
   </Location>
</VirtualHost>
```

**Comment by msikorski26** [comment]
> 

![image](https://user-images.githubusercontent.com/41286754/204598830-5360c13b-6ea2-4b03-9cea-ef9c33f02adb.png)
still

**Comment by ioppermann** [comment]
What happens if you try to connect to your box directly, i.e. without Cloudflare?

**Comment by svenerbeck** [comment]
Hello @mscodepl 

We are closing your ticket https://github.com/datarhei/restreamer/issues/480.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
