### ISSUE TITLE
srt pour rediffuser sans obs ? avec boitier d'encodage type s2 kiloview

### ISSUE THREAD

**Issue by esquilo444** [datarhei/restreamer#481]
bonjour,

Je veux savoir s'il est possible d'utiliser un autre moyen que l'obs pour envoyer un flux SRT à RESTREAMER ?
Boitier type s2 de chez kiloview.. ou autre.
J'utilise déjà le SRT avec ces boitiers sans aucun problème, mais je n'arrive pas à faire le lien vers RESTREAMER.
Merci d'avance pour votre éclairage.
Chaleureusement

Jérôme

trad 

hello, 

I want to know if it is possible to use other way than obs to send SRT stream to RESTREAMER?
Box type s2 from kiloview .. or other.
I already use the SRT with these boxes without any problem, but I can't link to RESTREAMER.
Thanks in advance for your insight.
Warmly

jerome

**Comment by ioppermann** [comment]
Follow the descriptions for how to use OBS to stream with SRT to Restreamer. Use that same URL for your Kiloview device. You might enter the `streamid` separately. It is part of the URL for OBS as the query parameter `streamid`.

Example: Restreamer provides you this SRT URL:

```
srt://192.168.0.103:6000?mode=caller&transtype=live&streamid=e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc
```

The streamid is `e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc`.

In the Kiloview UI enter the address and port of the Restreamer SRT server, e.g. `192.168.0.103:6000` and select the `caller` mode with transtype `live`. If you configured a passphrase, enter that as well.

**Comment by esquilo444** [comment]
hello,



Thank you very much for the time spent. My stream control room is currently in our bus.

As soon as I can, I'll be looking forward to trying this.

I will keep you posted on my tests.

Once again thank you .



Cordially



jerome


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

________________________________
De : Ingo Oppermann ***@***.***>
Envoyé : Friday, December 30, 2022 6:56:46 AM
À : datarhei/restreamer ***@***.***>
Cc : esquilo444 ***@***.***>; Author ***@***.***>
Objet : Re: [datarhei/restreamer] srt pour rediffuser sans obs ? avec boitier d'encodage type s2 kiloview (Issue #481)


Follow the descriptions for how to use OBS to stream with SRT to Restreamer. Use that same URL for your Kiloview device. You might enter the streamid separately. It is part of the URL for OBS as the query parameter streamid.

Example: Restreamer provides you this SRT URL:

srt://192.168.0.103:6000?mode=caller&transtype=live&streamid=e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc


The streamid is e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc.

In the Kiloview UI enter the address and port of the Restreamer SRT server, e.g. 192.168.0.103:6000 and select the caller mode with transtype live. If you configured a passphrase, enter that as well.

**Comment by esquilo444** [comment]
Hello again,



I already did the test with vmix, before being able to test it with my kiloview box and the result is perfect...

Thanks again for your feedback on the caller url syntax analysis...

Once again a big thank you.



Happy New Year.



Jerome


Envoyé à partir de Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows

De : Ingo ***@***.***>
Envoyé le :vendredi 30 décembre 2022 06:56
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [datarhei/restreamer] srt pour rediffuser sans obs ? avec boitier d'encodage type s2 kiloview (Issue #481)


Follow the descriptions for how to use OBS to stream with SRT to Restreamer. Use that same URL for your Kiloview device. You might enter the streamid separately. It is part of the URL for OBS as the query parameter streamid.

Example: Restreamer provides you this SRT URL:

srt://192.168.0.103:6000?mode=caller&transtype=live&streamid=e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc

The streamid is e5b74c8a-7dae-4d99-b6b7-183af8ab47ed,mode:publish,token:abc.

In the Kiloview UI enter the address and port of the Restreamer SRT server, e.g. 192.168.0.103:6000 and select the caller mode with transtype live. If you configured a passphrase, enter that as well.
