### ISSUE TITLE
Playersite Missing Logo for CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by ve7fet** [datarhei/restreamer#489]
**Describe the bug**
When CC BY-NC-ND 4.0 license is selected, and Playersite is created, logo image on Playersite is broken. 

**To Reproduce**
1. Select CC BY-NC-ND 4.0 license for the stream
2. Create Playersite
3. View playersite, logo for Content License is broken

**Expected behavior**
Display the relevant CC logo for CC BY-NC-ND 4.0.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome/Edge

**Additional context**

From generated /core/data/playersite_<token>.html:

` } else if (license === 'CC BY-NC-SA 4.0') {
                        license_name = 'CC BY-NC-SA 4.0'
                        license_url = 'https://creativecommons.org/licenses/by-nc-sa/4.0/';
                        license_image = 'https://mirrors.creativecommons.org/presskit/buttons/88x31/png/by-nc-sa.png';
} else if (license === 'CC BY-NC-ND 4.0') {
                        license_name = 'CC BY-NC-ND 4.0';
                        license_url = 'https://creativecommons.org/licenses/by-nc-nd/4.0/';
                        license_image = 'https://creativecommons.org/licenses/by-nc-nd/4.0/';`

license_image for CC BY-NC-ND 4.0 is the same as the license_url. CC BY-NC-SA 4.0 above uses a "presskit" image.

**Comment by jstabenow** [comment]
Thanks for your report. Fixed in version 2.5.0.
