### ISSUE TITLE
Forget password

### ISSUE THREAD

**Issue by lck1115** [datarhei/restreamer#491]
I forget the password to login http://ip:8080/ui/
How to reset the password?
Restreamer is deployed in docker.

**Comment by svenerbeck** [comment]
Hello @lck1115 

If you started with this standard environment:

` -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data \`

Look in the /config with your favorite text editor, and you will find your login credentials. 

Cheerio
Sven
