### ISSUE TITLE
High Efficiency Video Coding (HEVC) /  H.265 / MPEG-H Part 2 Support

### ISSUE THREAD

**Issue by troykelly** [datarhei/restreamer#498]
**Is your feature request related to a problem? Please describe.**
I'm unable to pass through HEVC streams, Restreamer insists on conversion to H.264

**Describe the solution you'd like**
I'd like to be able to keep a stream as H.265

**Describe alternatives you've considered**
Removing Restreamer from the pipeline and just using `ffmpeg` - but I do like the UI for restreamer.

**Additional context**
It's been some time since HEVC has been widely adopted, the previous reasons for no support in Restreamer are now no longer valid (SRT input works well)

## Business inquiries
N/A

**Comment by svenerbeck** [comment]
Hello @troykelly 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
