### ISSUE TITLE
Codifica h265

### ISSUE THREAD

**Issue by danitus13** [datarhei/restreamer#499]
Buonasera ho una telecamera reolink Duo 2 che supporta nella visione Nitidia, la codifica h265. 
Sto usando un orangepi 1GB di RAM con debian installato. 
Quando provo a inserire l'RSTP della telecamera, mi chiede la codifica a h264.
Purtroppo l'orangepi non riesce a codificare e la CPU arriva al 95%. 

C'è un modo per poter copiare la codifica della telecamera?

**Comment by svenerbeck** [comment]
Sorry. We only process tickets in English.
