### ISSUE TITLE
Docker images did not work

### ISSUE THREAD

**Issue by bayupermadi** [datarhei/restreamer#50]
Hi, 

I've tried to setup the restreamer in clean docker environment but it seems the application failed to run. Here the steps I do: 

1. Download the docker images, `sudo docker pull datarhei/restreamer:latest  `
2. Run the docker images `docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=YOUR-USERNAME" -e "RESTREAMER_PASSWORD=YOUR-PASSWORD" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer:latest`
3. Check my browser, `http://<server ip>:8080`

Only Nginx is active. It said 502, bad gateway. 

Is there any missed steps from me? 

Thank you very much for the help

**Comment by zovilla** [comment]
Hi, 
I have the same problem.

Message in the Browser:
502 Bad Gateway
nginx/1.9.9

My Server is:
Red Hat Enterprise Linux 7.5-8 x86_64 -in a VM

I did the installgude from https://datarhei.github.io/restreamer/docs/installation-linux-64.html

Any Idea?
Thanks in advance

Help would be nice

**Comment by svenerbeck** [comment]
Hi I'll take a look when I get home tomorrow.

**Comment by martinwiest** [comment]
Hi,

today i did a test with the docker-image for x86_64 on a host with Ubuntu 17.10 "artful" and it works as it should. It's not easy to locate the problem in your setup from remote. It could be a problem in the networklayer between your vm and the host or a running SE-Linux on host/VM witch denies the proper connection to the container. 

Would be nice to know wich kind of virtualisation is used for the Red Hat VM. 

Greetings,
Martin

**Comment by zovilla** [comment]
Hi, thanks for looking at my Problem
@Martinwiest, your hint to SE Linux was a good idea. If I desable the SE Linux, the Loginpage of restreamer is shown.
But now I have no Idea how to config SE Linux with docker. Have to read more about SE Linux (newbie).
If somebody knows how to config SE Linux for restreamer... would be nice =)

Thanks to all.

**Comment by SpootDev** [comment]
Personally I always just turn off SE Linux as it's always a pita to get stuff working with it unless it's simple things like a website, etc, imho.

**Comment by markosc** [comment]
i same error in my Pi 3b+
