### ISSUE TITLE
Use audio from hardware source

### ISSUE THREAD

**Issue by zayigo** [datarhei/restreamer#500]
**Subject of the issue**
I'm trying to use the audio input from my HDMI to USB capture card but I'm unable to find an option for it in the web-gui.

**Your environment**
Docker container running in an unprivileged Proxmox LXC with a bind mount for `/dev/snd` and the correct permissions set

**Steps to reproduce**

1. Ensure that the host system can detect the audio source using `arecord -l` and `arecord -L`
```
root@stream-lxc:~# arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
hw:CARD=MS2109,DEV=0
    MS2109, USB Audio
    Direct hardware device without any conversions
plughw:CARD=MS2109,DEV=0
    MS2109, USB Audio
    Hardware device with all software conversions
default:CARD=MS2109
    MS2109, USB Audio
    Default Audio Device
sysdefault:CARD=MS2109
    MS2109, USB Audio
    Default Audio Device
front:CARD=MS2109,DEV=0
    MS2109, USB Audio
    Front output / input
dsnoop:CARD=MS2109,DEV=0
    MS2109, USB Audio
    Direct sample snooping device
```

```
root@stream-lxc:~# arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: MS2109 [MS2109], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

3. Try to record an audio file with `arecord -d 10 -f S16_LE -c1 --device "plughw:1,0" test.wav`
4. Pass `/dev/snd`  to the container using the `--device` flag
5.  Create or edit an existing stream and try to add an audio source in "General" > "Audio settings"

**Expected behavior**
I should be able to add an audio source from a hardware device, such as a sound card or USB capture card.

**Actual behavior**
The options available to me are limited to "Virtual source" and "Network source"

**Comment by zayigo** [comment]
It seems like ALSA support is completely missing in the base Docker image "[base:alpine-ffmpeg-latest](https://github.com/datarhei/ffmpeg/blob/5.1/Dockerfile.alpine)" and is only present in [the one made for the Raspberry Pi](https://github.com/datarhei/ffmpeg/blob/5.1/Dockerfile.alpine.rpi).

Should this issue be moved to [datarhei/ffmpeg](https://github.com/datarhei/ffmpeg)?

**Comment by lukastaraba** [comment]
any updates on this?

**Comment by reconditeone** [comment]
I'm also experiencing this and would love a resolution

**Comment by jstabenow** [comment]
`ALSA` is now available in all FFmpeg and Restreamer-Dev images.

![Bildschirmfoto 2023-04-25 um 16 45 18](https://user-images.githubusercontent.com/7462030/234314173-0b544a32-0d56-451f-ad0d-960fa41063fd.png)

## For testing:
- datarhei/restreamer:dev (amd64, arm64, armv7)
- datarhei/restreamer:rpi-dev (arm64, armv7)
- datarhei/restreamer:cuda-dev (amd64)
- datarhei/restreamer:vaapi-dev (amd64)

**Comment by reconditeone** [comment]
Switched to dev image and it's working perfectly with my cheap USB HDMI capture card. Thanks much!
