### ISSUE TITLE
Rumble

### ISSUE THREAD

**Issue by mipps71** [datarhei/restreamer#502]
I like to use restreamer for several platforms. Can we add a rumble platform?   I use RTMP and it needs a RTMP and a key code .    thanks

**Comment by svenerbeck** [comment]
Hello @mipps71 

What do you mean:  rumble “platform?“

Do you have the URL?

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello @mipps71 

We have converted the request into a feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

Could find a possibility for streaming with RTMP (https://rumble.com/v12rt2h-how-to-livestream-on-rumble.html and https://rumblefaq.groovehq.com/help/how-to-setup-a-livestream) on rumble. The prospect of implementation is very high. You can already do that with the publication service RTMP.

We are closing this issue.

Cheerio 
Sven
