### ISSUE TITLE
playlist files

### ISSUE THREAD

**Issue by edsonperes** [datarhei/restreamer#505]
it would be very interesting to be able to generate streaming from local files, with a time scheduler, it would be incredible

**Comment by svenerbeck** [comment]
Hello @edsonperes 

Thank you for taking the time to provide your valuable input. Your feaure request has already been added to the official feature request list by another datarhei user. 

We kindly ask you to follow the discussion on this matter at the following link: https://github.com/datarhei/restreamer/discussions/345#discussion-4108562. This will ensure that you stay up-to-date on any progress and will be informed when your requested feature is implemented. Please note that it may take time to implement all the features on the list.

With this, we are now closing this issue.

Best regards,
Sven
