### ISSUE TITLE
New params, cron, auto stary stop ? Possible?

### ISSUE THREAD

**Issue by Ronnon78** [datarhei/restreamer#51]
I have one question. I need to start the restream temporarily. Is it possible to run restream on Youtube through some API, eg using CRON. The second question. Can you set the source and target in the parameter and do some autostart?

**Comment by svenerbeck** [comment]
Hello Ronnon78
To answer your **1st** question short and sweet. Not out of the box.
**2nd** Once the source is set manualy it starts every time you start the docker container.

Hope this helps you a bit out. The question was shamefully long time ago.. Thank you for your patience.

Cheerio
Sven

Cheerio
Sven
