### ISSUE TITLE
Error veth1798043: Failed to query device driver: No such device 

### ISSUE THREAD

**Issue by danitus13** [datarhei/restreamer#510]
SO and Hardware: OrangePi debian 11 bullseye

This code docker install: 

sudo docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data --privileged -p 8080:8080 -p 8181:8181 -p 1935:1935 -p 1936:1936 -p 6000:6000/udp --security-opt seccomp=unconfined --dns 1.1.1.1 datarhei/restreamer:rpi-latest

I've never had any problems, yesterday the light went out, when I restarted, I started having these errors:

veth1798043: Failed to query device driver: No such device
veth1798043: Failed to get link config: No such device

**Comment by jstabenow** [comment]
Hey @danitus13 
Did you update the drivers? Looks like a network error.
