### ISSUE TITLE
Add proxy to request (pull mode)

### ISSUE THREAD

**Issue by lck1115** [datarhei/restreamer#513]
I know FFmpeg supports proxies, -http_proxy http://ip:port/ .
But how to add proxy to resteamer?

**Comment by jstabenow** [comment]
Hey @lck1115 
I will check 👍

**Comment by jstabenow** [comment]
The `http_proxy` option can now be found in the advanced settings:

![Bildschirmfoto 2023-02-23 um 12 25 26](https://user-images.githubusercontent.com/7462030/220893652-cc2d07cc-6611-405a-a2da-07a1ce4ecdfd.png)

Just update to the latest v2.5.0.
