### ISSUE TITLE
Saving RTMP push advanced settings does not save

### ISSUE THREAD

**Issue by whittinghamj** [datarhei/restreamer#518]
Setup a source stream, then add a destination RTMP to push to another RTMP server ...

I set the server as rtmp://server.com:1935/live

I try and set the rtmp_playpath as the 'key' (i think thats right)

Either way, when you click save, the fields dont save the data and hitting save then refreshing the page, the fields are empty again.

**Comment by whittinghamj** [comment]
https://capture.dropbox.com/zKdmobwompuYMZSt

**Comment by ioppermann** [comment]
@whittinghamj This is indeed a bug. I fixed it in the dev branch of the UI. Meanwhile you can simply append the "key" to the URL in the field where you added the server, e.g. `rtmp://server.com:1935/live/key`

Everything after the app (here: `/live`) will be interpreted as rtmp_playpath.

**Comment by jstabenow** [comment]
**Fixed in our Restreamer dev images:**
- datarhei/restreamer:dev (amd64, arm64, armv7)
- datarhei/restreamer:rpi-dev (arm64, armv7)
- datarhei/restreamer:cuda-dev (amd64)
- datarhei/restreamer:vaapi-dev (amd64)

Please feel free to re-open this issue if necessary. Thx.
