### ISSUE TITLE
Fix for Multiple Outputs

### ISSUE THREAD

**Issue by iammenasco** [datarhei/restreamer#52]
Couldn't there be a check to say "take `optionalOutput` and split on ` `. For each output, send it to `Restreamer.addOutput`" and continue onward?

https://github.com/datarhei/restreamer/blob/master/src/classes/Restreamer.js#L304

I'd get a PR going, but I am having no luck building this repo locally. Grunt is having issues. If there is a simple way for me to get this going locally, I'd love to help out or fork.

**Comment by svenerbeck** [comment]
Hello iammenasco,
Thank you for your thoughts. It is one of the most asked features.
We have a way for multiple inputs in our next version.
Until then you can start 2 docker containers and run them simultaneously.

Cheerio
Sven

**Comment by iammenasco** [comment]
Next version? Thats great news! I heard the project was dead?

**Comment by svenerbeck** [comment]
Our programming has bailed us out in the middle of development. We have now found a frontend and backend developers who support us 50% of their time. In the next weeks there should be the first results. Our old developer had only 2-4 hours per week so it was extremely sluggish. 
I'm reviving things up again with the new team from Switzerland. 
Let's go!
Sven

**Comment by iammenasco** [comment]
Woo! I am excited to see the growth of this project again. Feel free to close this issue, as it sounds as though there is a fix in the works.

**Comment by svenerbeck** [comment]
Thank you :)
Greetings from Switzerland
Sven
