### ISSUE TITLE
Can a restreamer connect to an rtsp source stream only when there is a viewer

### ISSUE THREAD

**Issue by Artidv1** [datarhei/restreamer#520]
Can a restreamer connect to an rtsp source stream only when there is a viewer? I do need to prevent unnecessary traffic.

**Comment by svenerbeck** [comment]
Hello Artidv1

Good point! [electronic high5] We have converted the request into a feature request. Follow the discussion 
(https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
