### ISSUE TITLE
Stream to Kick didnt work

### ISSUE THREAD

**Issue by BaluGamingTV** [datarhei/restreamer#523]
**Describe the bug**
Kick ist like Twitch and use RTMPS like Facebook. For that i have take the RTMP v1.0 Part.
But it didnt conect.

**To Reproduce**
1. Go to the point wher add a stream
2. Click on 'RTMP v1.0'
3. Select RTMPS as protoccoll '....'
4. Add URL and Key from kick.com

**Expected behavior**
The stream didnt get pushed. I test it with obs directly and the stream starts.

**Desktop (please complete the following information):**
 - Ubuntu 20.04 Server
 - Chrome

**Smartphone (please complete the following information):**

Another think is that changed the Port of RTMP/S, that OBS cant link to Restreamer 2.0

**Comment by svenerbeck** [comment]
Hello [BaluGamingTV](https://github.com/BaluGamingTV)

It worked for me right away. Could you show me your RTMP URL syntax?

Cheerio
Sven

**Comment by ioppermann** [comment]
As a workaround you can enter this address: `[something].global-contribute.live-video.net/app/[your stream key]`.

Notice the `/app/` in front of the stream key.

**Comment by BaluGamingTV** [comment]
> As a workaround you can enter this address: `[something].global-contribute.live-video.net/app/[your stream key]`.
> 
> Notice the `/app/` in front of the stream key.

DAMN.... with /app/ it has worked and i am feeling realy good.... :D
But wy dont is it in OBS ... or makes OBS this automatic?

When restreamer will be record streams and make it as shedule to stream to any time... it will be awesome :D

Other question... i read about a lizens for restreamer.... i want it :D

**Comment by ioppermann** [comment]
> But wy dont is it in OBS ... or makes OBS this automatic?

That's a quirk of the RTMP protocol and how the URL interpreted. If some parts are missing (here the RTMP app), then the URL gets misinterpreted and during the handshake with the server it receives the wrong information.

A fix for that is already under way.

**Comment by ibrah3m** [comment]
1- select the rtmps 
2- paste the link without the rtmps://
3- put :443/app/ in the end of the url  then but the token
it's gonna work

**Comment by svenerbeck** [comment]
Hello @BaluGamingTV 

We are closing your ticket https://github.com/datarhei/restreamer/issues/523.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

**Comment by MauricioOnetto** [comment]
It worked perfect for me
Even without adding 443 (only choosing rtmps)
Thank you
