### ISSUE TITLE
Can datarhei handle 1000 concurrent connections to video streaming page?

### ISSUE THREAD

**Issue by ougem** [datarhei/restreamer#524]
**Subject of the issue**
I'm wondering how many concurrent connections the restreamer can handle.  I would like to run live streaming from OBS Studio on my website with max 1000 concurrent viewers.

**Your environment**
I don't have the server in production yet, but I would like to know the proper sizing for this.

Thanks

**Comment by ioppermann** [comment]
This is mainly limited by your available bandwidth. If you're doing only restreaming without any encoding then CPU and memory don't have too many requirements.

For the required bandwidth, you have to multiply the bitrate of the stream you're streaming with the number of concurrent viewers.

Example: your stream has a bitrate of 2mbit/s. With 1000 concurrent viewers it will require a bandwidth of 2000mbit/s (or 2gbit/s). Add a margin of 25% on top for protocol overhead (e.g. 2.5gbit/s) and you should be fine.

**Comment by jstabenow** [comment]
Please feel free to re-open this issue if necessary. Thx.
