### ISSUE TITLE
RTSP - Failed to probe the source - latest docker

### ISSUE THREAD

**Issue by Kliwer** [datarhei/restreamer#526]
**Describe the bug**
While trying to add RTSP source I get an error: Failed to probe the source. Please check the [probe details]
**To Reproduce**
1. Install restreamer
2. Go through initial wizard
3. Try to add Network source - RTSP
4. Fill address, username and password
5. Click PROBE
6. Error

**Expected behavior**
Probe finished successfully, get to the next step of the wizard

**Screenshots**
![image](https://user-images.githubusercontent.com/11368153/225759754-f413711f-1faa-45ae-93af-7fd7f0b9fa61.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 110.0.5481.178

**Additional context**
Restreamer installed on Debian 11.

Probe details:
`ffmpeg version 5.1.2-datarhei Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lz -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100`

I was using old version of restreamer without issues, after moving to new server I wanted to check out newest version.

**Comment by jstabenow** [comment]
Hey @Kliwer 
1. check this source: https://demo.datarhei.com/memfs/2f646236-b14d-4242-8b21-54725220dc0c.m3u8
2. if the source works, increase the advanced settings `probesize` and `analyseduration`:
![Bildschirmfoto 2023-03-17 um 14 07 07](https://user-images.githubusercontent.com/7462030/225913233-9314710b-c265-44ae-862b-8a6b170a779c.png)

**Comment by Kliwer** [comment]
Thank you for replying.
That source works - it gets me to the next step.
Increasing those values changes nothing - still the same error.
It is a BCS IP camera. I can play the stream in VLC with no problems.

**Comment by jstabenow** [comment]
Strange. Please run the two docker commands and copy the output here. Hope this helps:

```sh
docker run --interactive --tty --rm datarhei/restreamer:0.6.8 ffmpeg -i rtsp://10.2.48.10:544
```

```
docker run --interactive --tty --rm --entrypoint /usr/bin/ffmpeg datarhei/restreamer:latest -i rtsp://10.2.48.10:544
```

**Comment by Kliwer** [comment]
It seems that it was a routing issue (duplicate IP). Now it works fine.

Both commands returned then and now when it works:
Connection to tcp://10.2.48.10:544?timeout=0 failed: Connection refused
rtsp://10.2.48.10:544: Connection refused
either with username:password@ at front or not.

Thank you for your help.
