### ISSUE TITLE
Restreamer-v2.5.0 - imprint,terms and credit.

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#529]
**Describe the bug**

When I disable share option in the player the imprint, terms and credit does not show popup screen/info
it just reload the page.

If I enable sharing again the other options works again.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chome Version 111.0.5563.64 (Officiel version) (64-bit) and firefox 110.0.1 (64-bit)

**Comment by jstabenow** [comment]
Thanks for your report :star_struck:

The fix has been released in the dev. images:
- datarhei/restreamer:dev
- datarhei/restreamer:rpi-dev
- datarhei/restreamer:cuda-dev
- datarhei/restreamer:vaapi-dev
