### ISSUE TITLE
Installed Kitematic and Restreamer but will not connect to valid RTSP stream

### ISSUE THREAD

**Issue by jeffd2651** [datarhei/restreamer#53]
OK, downloaded the Kitematic interface and enabled the restreamer as per the instructions. However, after entering the valid IP for the camera (rtsp://192.168.1.199:554/onvif1) all that the interface reports is that it is initiating! Tried the same access using my DDNS (rtsp://jdan.noip.me:554/onvif1) also, but similarly does not connect.
What have I done wrong ?!?!?! Thanks

**Comment by svenerbeck** [comment]
Hello jeffd2651
if this issue is still open...

Did you tried another RTSP url eg. without ONFIV.
If you tell me your camera model I will check if RTSP is possible on another URL.

Cheerio
Sven
