### ISSUE TITLE
p2p and mitv streaming protocol

### ISSUE THREAD

**Issue by lck1115** [datarhei/restreamer#532]
Is it possiable to support to restream p2p or mitv streaming protocol?

P2p://generationnexxxt.com:19806/596bc566f5024110b7a9832f4a4e1f86
mitv://fccs.word-tv.com:9906/62596d0a0009c5b313fc0e7cd12205f2

**Comment by ioppermann** [comment]
Couldn't find any information about these protocols. FFmpeg has to support it, otherwise we don't support it.
