### ISSUE TITLE
Stream Initialising ...  NOT!

### ISSUE THREAD

**Issue by jeffd2651** [datarhei/restreamer#54]
Followed the instructions to the letter; entered a valid address for the IP camera RTSP stream and the interface reports, "Streaming Process Is Initiating. Please wait ..." but the problem is, waiting produces nothing !
The rtsp stream is valid as it opens directly in VLC.
Any idea what the problem could be ?????
Thanks

**Comment by svenerbeck** [comment]
Hello Jeffd2651
If this issue is still active. Please tell me the camera model.

Cheerio
Sven
