### ISSUE TITLE
Icecast don't save data

### ISSUE THREAD

**Issue by MauricioOnetto** [datarhei/restreamer#542]
**Describe the bug**
After add all data (user, pass, server, port, mountpoint) and click on save button, cursor change from pointer to "thinking or doing something" but nothing happen.
I've checked the log file and there are nothing related to Icecast and no errors.

**To Reproduce**
You can watch a video where I'm trying to do it
https://drive.google.com/file/d/1AAlw3K8ssKnZWRRl_eDQuKs_fZ023Q4r/view?usp=share_link

I'm using a test user from an Azuracast Server
user: Test
pass: Password123
server: server.radioholistica.com (I tryed using only IP and fail too)
port: 8005
mountpoint: /
Those credentials work perfect on "Butt"

**Expected behavior**
Save credentiales and allow to restream audio to Icecast server

**Screenshots**
Video
https://drive.google.com/file/d/1AAlw3K8ssKnZWRRl_eDQuKs_fZ023Q4r/view?usp=share_link

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 111.0.5563.147 (Build oficial) (64 bits)

Thanks for your great work
I love Datarhei Restreamer

**Comment by jstabenow** [comment]
**Fixed in our Restreamer dev images:**
- datarhei/restreamer:dev (amd64, arm64, armv7)
- datarhei/restreamer:rpi-dev (arm64, armv7)
- datarhei/restreamer:cuda-dev (amd64)
- datarhei/restreamer:vaapi-dev (amd64)

Please feel free to re-open this issue if necessary. Thx.
