### ISSUE TITLE
SSL issue after IP change

### ISSUE THREAD

**Issue by riddlenl** [datarhei/restreamer#549]
The VM with Restreamer got moved to another server with new IP addresses.

Whatever I do, I get SSL errors after it. Any thing I can check?
I unticked the SSL option, ticked it again and it restarted but still the same issue.

This site can’t provide a secure connection
XXXX.XXX.com sent an invalid response.

ERR_SSL_PROTOCOL_ERROR

**Comment by jstabenow** [comment]
The certificate is valid for the domain, not a specific IP.
So check that the domain is pointing to the correct IP with the correct Restreamer and certificate files.

**Comment by riddlenl** [comment]
I know :)

Did a reinstall of Restreamer on a new VM with the same IP and it works. Don't know what was wrong tho

**Comment by jstabenow** [comment]
Crazy and it works for me. Contact us if the error occurs again.
