### ISSUE TITLE
IMPROVEMENT: some ip cam not streaming 400 error

### ISSUE THREAD

**Issue by kiwina** [datarhei/restreamer#55]
Hi nice project, tried it but it dosn't work with my cams but got it to work outside of this project.
here is whats happening.
My Chinese cams expect the CSeq to be the first thing where as ffmpeg puts the headers first if any so you get a 400 error returned from the dvr.
In order to fix this it does require a tiny change before compiling ffmpeg.
in the source of libavformat/rtsp.c 
we need editing the following function
`
rtsp_send_cmd_with_content_async
`
there is the following code
`
    if (headers)
        av_strlcat(buf, headers, sizeof(buf));
    av_strlcatf(buf, sizeof(buf), "CSeq: %d\r\n", rt->seq);
`
all we need is to shift them around
`
    av_strlcatf(buf, sizeof(buf), "CSeq: %d\r\n", rt->seq);
    if (headers)
        av_strlcat(buf, headers, sizeof(buf));
`
this way the CSeq is allways first.
I assume that my dvr dosnt parse the headers but simply assumes the position on where is what.

here a patch https://github.com/kiwina/FFmpeg/commit/71777e69c8f89e5dd558d6925666d85c3fe4e152.patch

**Comment by svenerbeck** [comment]
Thank you kiwina,
I have forwarded the information to the appropriate person. 
We've had problems with the China cameras before. That's the price you don't pay!
Cheerio
Sven
