### ISSUE TITLE
every time need to login plzz fix it

### ISSUE THREAD

**Issue by MANOJJADHAV4000** [datarhei/restreamer#557]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.

**Comment by svenerbeck** [comment]
Hello @manoj4000 

We only work on tickets with error logs to help efficiently. Here you can see how to get the log file: https://www.youtube.com/watch?v=mZMGrweFCsM - Thank you for your understanding.

Cheerio
Sven
