### ISSUE TITLE
Getting image overlay working

### ISSUE THREAD

**Issue by dewman45** [datarhei/restreamer#559]
I can't seem to get the logo working under player edit. I am not familiar with how to enter the file path or what the link entry is next to position. I wasn't able to find too much documentation on it. Am I supposed to have the png file somewhere with the volumes for the container or should I be able to upload it from the file browser?

**Comment by svenerbeck** [comment]
Hello @dewman45 

After looking through your concerns, I noticed that the process in question had been designed to be largely intuitive and self-guided, which has resulted in limited written documentation. The aim is to simplify the user experience, and I understand this may have inadvertently led to some confusion.

Unfortunately, I found it challenging to identify the specific issue you're having based solely on the information provided. If you could give me a more detailed insight into the problem, I would be better positioned to help you further.

In the meantime, I have created a short video that might help you. This video shows the proper steps to follow, and I am confident that it will address most, if not all, of your concerns.

[https://youtu.be/i6dSYg9yPhw](https://youtu.be/i6dSYg9yPhw)

If you need more clarification or help, please do not hesitate to contact us. 

Best Regards,
Sven

**Comment by dewman45** [comment]
So I am still having issues. I understand that I should be able to use upload to add the logo, but that isn't working. I wasn't sure if I misunderstood how it worked. As of right now after trying to upload a PNG, it shows "http://localhost:32773/channels/4abafc8e-9fe4-471c-99e5-fccae3b6991d/logo.png" under the file path. The logo never shows up. I also am not sure what the Link entry is for or if I am supposed to be using that.

Currently [this](https://i.imgur.com/BFvj1ld.png) is what I am seeing once I select the PNG I want to use.

**Comment by dewman45** [comment]
As an additional note I am able to find the PNG in the data files after uploading, but it does not show on the player in any position. Should I be able to see it in the player?

**Comment by svenerbeck** [comment]
Hello @dewman45 

Please show your error logs to help efficiently. Here you can see how to get the log file: [https://www.youtube.com/watch?v=mZMGrweFCsM](https://www.youtube.com/watch?v=mZMGrweFCsM) - Thank you for your understanding.

Cheerio
Sven

**
EDIT: Please send me the logo too. Mail to: support@datarhei.com
**

**Comment by dewman45** [comment]
[report.txt](https://github.com/datarhei/restreamer/files/11500396/report.txt)

This is the process report. Logo has been emailed.

**Comment by dewman45** [comment]
Bumping as I am still having issues

**Comment by dewman45** [comment]
Reopening issue as no response and issue is still present.
