### ISSUE TITLE
RTMP URL with underscore doesn't work

### ISSUE THREAD

**Issue by pmarkun** [datarhei/restreamer#56]
I'm trying to restream the following url:

rtmp://origem_flash.nucleomedia.com.br:1935/cmsp_live/Plenario_1_de_Maio

The start button doesn't work at all, after a lot of try and error I discovered that any urls with _ produces this behavior.

Any hints?

**Comment by svenerbeck** [comment]
Hello pmarkun,If the problem is still current, please do not hesitate to contact us. I'll try to help you promptly.
Regards
