### ISSUE TITLE
RTMP app specification does not work.

### ISSUE THREAD

**Issue by delahn** [datarhei/restreamer#560]
**Subject of the issue**
 Hello, I have a problem with specifying RTMP app. If I leave it blank, everything works, only if I specify "live", for example, the stream does not work

**Your environment**
Raspberry Pi 4 Model B (Docker Container) - Fritz!Box 7560

**Files**
https://youtu.be/XX2qai87vm4
[RTMP app specification does not work.log](https://github.com/datarhei/restreamer/files/11442761/RTMP.app.specification.does.not.work.log)
[core.log](https://github.com/datarhei/restreamer/files/11443821/core.log)

Larix Broadcaster App and similar smartphone apps require the RTMP app. To stream.

Thanks for the help

**Comment by delahn** [comment]
System-Report 
[core.log](https://github.com/datarhei/restreamer/files/11443837/core.log)

**Comment by svenerbeck** [comment]
Nice that the support in Discord worked so well. Have fun streaming!
Greetings from datarhei.com 
Sven
