### ISSUE TITLE
RPi 1 B+ (arm32v6) No web UI access/ Ports Fail to Publish

### ISSUE THREAD

**Issue by exokinetic** [datarhei/restreamer#561]
**Describe the bug**
Installing latest restreamer:rpi-latest 
Raspberry Pi 1 B+ with latest Raspbian Bullseye OS (lite) (headless configuration/ managed via SSH)
-arm32v6 CPU architecture
Latest Docker Standalone 
Portainer Community Edition used for container management
SSH control of RPi via Windows10 laptop using latest version Chrome browser.

Followed installation instructions for latest version of Restreamer (Restreamer 2) for Raspberry Pi

Used this exact string:

docker run -d --restart=always --name restreamer \
   --volume /opt/restreamer/config:/core/config --volume /opt/restreamer/data:/core/data \
   --privileged \
   --security-opt seccomp=unconfined \
   --publish 8080:8080 --publish 8181:8181 \
   --publish 1935:1935 --publish 1936:1936 \
   --publish 6000:6000/udp \
   datarhei/restreamer:rpi-latest
   
Also tried without --priveleged
Also tried without --security-opt seccomp=unconfined 

The container is created and listed as "running" on the Portainer Container manager.

It appears at first that the selected ports are published properly and the container receives an IP address, but after some number of seconds the list of "Published Ports" and the "IP Address" fields in the Portainer details page clear out and show no ports published/ no IP address.

Attempting to access to the browser GUI at http://device-ip:8080/ui results in "This site cant be reached" (ERR_CONNECTION_REFUSED) browser error.

Older version of restreamer works exactly as intended on the same RPi device using this string:

docker run -d --restart always \
     --name restreamer \
     -e "RS_USERNAME=redacted" -e "RS_PASSWORD=redacted" -e "RS_TOKEN=redacted" \
     -p 8080:8080 -p 1935:1935 -v /mnt/restreamer/db:/restreamer/db \
     --tmpfs /tmp/hls \
     datarhei/restreamer-armv6l:latest
     
     
     
I would love to use the new updated version of restreamer, but I cant seem to figure out why its not working/ installing correctly...?

**Comment by svenerbeck** [comment]
Dear @exokinetic,

Thank you for reaching out to us. We want to inform you that the "PI 1, Pi 2, and Pi Zero" requires ARMv6 support, which we do not currently offer and will not in the future. We apologize for any inconvenience this may cause, and we appreciate your understanding in this matter.

Cheerio,
Sven
