### ISSUE TITLE
docs.datarhei.com Installation Compatibility/ Requirements Page Contains Error (ARMv6 support)

### ISSUE THREAD

**Issue by exokinetic** [datarhei/restreamer#562]
Just want to report that the only reason I thought the latest restreamer version would work on my Raspberry Pi 1 with ARMv6 architecture was your own docs website.

https://docs.datarhei.com/restreamer/installing/raspberry-pi-arm

"...

Install and run Restreamer on a Raspberry Pi 3, P 4, **or other devices with an ARMv6**, ARMv7, or ARMv8 CPU in a Docker container.

..."

I sugguest this text; "or other devices with an ARMv6" should be removed from the raspberry-pi-arm installation page if you never plan to support it.

![Raspberry-Pi-ARM-Restreamer-Docs-Correction](https://github.com/datarhei/restreamer/assets/115325279/3b5878c8-5cbd-47e2-bfaf-54305edcca4b)

The deprecated version is thankfully working VERY WELL on my RPi 1.
-Thank you for all the work you have done to provide this incredibly impressive project to all of us!

Looks like its time for an RPi upgrade :)

**Comment by svenerbeck** [comment]
Hello @exokinetic,

Thank you for your comprehensive explanation. Your points are well-taken and warrant our further attention.

Best Regards,
Sven

PS: Sorry, I closed the Issue by mistake. Too little coffee in the morning

**Comment by svenerbeck** [comment]
Dear @exokinetic,

As an additional suggestion, I would recommend considering the utilization of an Okdo Rock. These devices are widely available and have demonstrated reliable performance in many applications.

[https://www.okdo.com/p/okdo-rock-4-model-c-4gb-single-board-computer-starter-kit-with-psu-case-preloaded-linux-os-heat-sink-fan/](https://www.okdo.com/p/okdo-rock-4-model-c-4gb-single-board-computer-starter-kit-with-psu-case-preloaded-linux-os-heat-sink-fan/)

Cheerio — Sven

**Comment by exokinetic** [comment]
Thank you for the recommendation, looking at the Okdo's right now!

**Comment by svenerbeck** [comment]
Hello @exokinetic, 

Raspberry Pis are available again at fair prices. Hooray!

We are closing your ticket https://github.com/datarhei/restreamer/issues/562.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
