### ISSUE TITLE
Support HLS adaptive streaming

### ISSUE THREAD

**Issue by inkas1986** [datarhei/restreamer#567]
Hello, 
Is it possible to add HLS adaptivivr stream in output, if stream in input is HLS with adaptive bitrate?

**Comment by svenerbeck** [comment]
Hello @inkas1986 

At the moment, this feature is not available. However, I'm happy to inform you that it is already on our feature request list. You can follow the ongoing discussion and stay updated on the development of this feature using the following link: [https://github.com/datarhei/restreamer/discussions/345](https://github.com/datarhei/restreamer/discussions/345)

You can follow this part of the discussion to see when your requested feature becomes active.

We want your understanding as implementing new features can take some time. We appreciate your patience and your continued interest in our software.

Given that this feature request is already being tracked, we will close this issue.

Cheerio
Sven
