### ISSUE TITLE
Alternative Network source

### ISSUE THREAD

**Issue by lck1115** [datarhei/restreamer#568]
Is it possiable to add an alternative network source?

The streamer will restream or redirect to the alternative network source automatically when the primary one is down.

**Comment by svenerbeck** [comment]
Hello @lck1115 

At the moment, this feature is not available. However, I'm happy to inform you that it is already on our feature request list. You can follow the ongoing discussion and stay updated on the development of this feature using the following link: [https://github.com/datarhei/restreamer/discussions/345](https://github.com/datarhei/restreamer/discussions/345)

You can follow this discussion to see when your requested feature becomes active.

We would like your understanding as implementing new features can take some time, and we appreciate your patience and continued interest in our software.

Given that this feature request is already being tracked, we will close this issue.

Cheerio
Sven
