### ISSUE TITLE
Raspberry Pi Camera Settings

### ISSUE THREAD

**Issue by mbreslein-thd** [datarhei/restreamer#571]
**Subject of the issue**
Restreamer 0.6.X used to allow configuration of the Raspberry Pi camera using Environment Variables: https://datarhei.github.io/restreamer/docs/guides-raspicam.html

But with the current version this doesn't seem to be the case anymore. Has this been removed or am I missing something?

**Your environment**
Raspbian Buster on a Raspberry Pi 4 with a Raspberry pi Camera Module V2 running datarhei/restreamer:rpi-latest.

**Expected behavior**
I'd like to use the env vars to change some camera settings. Especially RS_RASPICAM_SATURATION and 
RS_RASPICAM_CONTRAST would be interesting.

**Actual behavior**
Nothing happens when I set them. The Container starts normally but the settings are ignored.

**Comment by svenerbeck** [comment]
Hello @mbreslein-thd,

Thank you for reaching out regarding configuring the Raspberry Pi camera using Environment Variables in Restreamer 0.6.X.

I want to inform you that Restreamer 0.6.X is an older version, and we no longer provide support for it. We strongly recommend updating our latest version for the best experience, updated features, and continued support. By updating, you'll also benefit from improved stability, security patches, and the latest enhancements.

Please let us know if you need assistance with the update process or have further questions.

Best regards,
Sven

**Comment by mbreslein-thd** [comment]
Hi,
Maybe my wording is off, but my issue is that there are features I need that 0.6 has but the newer versions don't.
I am running the latest version, that's why I was asking for those features.
