### ISSUE TITLE
PUBLICATION RTMP Address

### ISSUE THREAD

**Issue by lck1115** [datarhei/restreamer#576]
Is there any easy way to change the Publication RTMP address? Or API?

Some platforms change their rtmp address every servel hours or days. I have to change the rtmp address on restreamer manually.
If it can be changed by API, it will be very helpful for me.

**Comment by ioppermann** [comment]
The UI of the Restreamer uses the [datarhei Core API](https://docs.datarhei.com/core/). The Restreamer publications are stored as `process` in the Core. The ID of the process is composed of a prefix, the publication name, and an UUID.

The prefix is `restreamer-ui:egress:`. You'll find the publication name and the UUID in the path when you edit that publication service, e.g. the path is `/0108a05e-eed4-4c19-944d-03ce20e64747/publication/youtube/cf2a7614-8cfa-4f3b-9712-cb129daffe9b`, the publication name is `youtube` and the UUID is `cf2a7614-8cfa-4f3b-9712-cb129daffe9b`.

In the Core API, edit the process config with the ID `restreamer-ui:egress:youtube:cf2a7614-8cfa-4f3b-9712-cb129daffe9b`.

**Disclaimer: do this at your own risk. Any manual changes in the process config may break the functionality of the Restreamer. The only official and supported way to change RTMP address is via the Restreamer.**
