### ISSUE TITLE
Can add platforms kick.com ?

### ISSUE THREAD

**Issue by crewockeez** [datarhei/restreamer#582]
Can add platforms kick.com ?

**Comment by svenerbeck** [comment]
Hello @crewockeez 

There is already a feature request for this. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345) to stay current and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
