### ISSUE TITLE
Don't use rtmp kick.com

### ISSUE THREAD

**Issue by crewockeez** [datarhei/restreamer#583]
**Describe the bug**
don't use rtmp website kick.com. 

Rtmp: rtmps://fa723fc1b171.global-contribute.live-video.net
Key: sk_us-west-2_I02SeEgHl1rk_nrprgob6sL9RKLLyMPoJXQh13PNjGc

I have to go through restream.io and have the restream deliver to kick.com.

**Comment by GADZlLA** [comment]
kick.com Принимает не Rtmp а Rtmps! Для Rtmps нужно доменное имя с сертификатом 
![image](https://github.com/datarhei/restreamer/assets/130315409/ec71506d-661b-4594-8f2d-589a74a59620)
