### ISSUE TITLE
Cuda Version 12

### ISSUE THREAD

**Issue by Tokolosh** [datarhei/restreamer#607]
The lowest current version of nvidia drivers on ubuntu is 525 which uses Cuda Version 12. Nvidia Drivers 515 worked fine but now after a reinstallation of my system i am not able to install 515 anymore as "apt install nvidia-drivers-515" automatically installs 525 with Cuda 12

Could you please provide a Cuda 12 Version?

**Comment by Tokolosh** [comment]
i see the new version is out but still using Cuda 11.4 not 12.2
is it still possible to get a restreamer with cuda 12.2?

Edit: Found a way to get it working on 12

**Comment by maykel535** [comment]
@Tokolosh , how you resolved it? I have cuda 12

I've install in host anfitrion:

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt

And launch docker with runtime nvidia --> --runtime=nvidia

But when I'm going to step --> Video Setup  Hardware Device --> "No input device available
![Captura de pantalla_20240416_000201](https://github.com/datarhei/restreamer/assets/3702872/8689d2cb-4f24-4ad7-8e28-27101e79ac30)
"

Thanks in advanced.
