### ISSUE TITLE
FFMPEG as source

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#61]
Is it possible to use a FFMPEG-style stream as source 
(http://<ip-address>:80/videostream.cgi?user=viewer&pwd=somepassword&rate=0&resolution=-1)?
The ip cam doesn't seem to support RTSP (or is it RTSP?).

**Comment by svenerbeck** [comment]
Hello, you'd have to do some work on the docker container. Out of the box it is unfortunately not planned in the current version of the Restreamer.

If you write an extension we might include it in the next version. You are welcome to send a pull request.

salute 
Sven
