### ISSUE TITLE
Restreamer 2.0 to Facebook

### ISSUE THREAD

**Issue by natzakaria** [datarhei/restreamer#610]
Tried multiple ways to publish to FB either using the Publication or RTMP
I know FB now insist on rtmps

New to Restreamer so if someone would be kind enough to guide

**Comment by svenerbeck** [comment]
Hello @natzakaria,

Thank you for reaching out. Indeed, Facebook requires RTMPS for live streaming. If you're new to Restreamer, we've got a guide that specifically details the steps to stream to Facebook Live using Restreamer. You can find the guide here: [How can I stream to [Facebook Live?](https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-stream-to-facebook-live)

Feel free to review the documentation, and if you have any further questions or encounter any issues, don't hesitate to ask. We're here to help!

Cheerio,
Sven
