### ISSUE TITLE
Decklink Video Input Device

### ISSUE THREAD

**Issue by Sadoharu** [datarhei/restreamer#612]
hi, how can add decklink to the input? By default, it does not find video devices.
![image](https://github.com/datarhei/restreamer/assets/77967977/6e89e318-1afb-45aa-8fc3-457058aa6ec7)
![266227093-f5ec5100-0180-4c23-a824-922bc64d682c](https://github.com/datarhei/restreamer/assets/77967977/b7843933-5e35-4abd-8782-e4282a2e988c)

**Comment by ioppermann** [comment]
decklink devices are not yet supported (see #606). It already has been added to our [feature request list](https://github.com/datarhei/restreamer/discussions/345).

**Comment by zazafree00** [comment]
+1
