### ISSUE TITLE
Ras-Pi Zero 2W with camera

### ISSUE THREAD

**Issue by MattGeale** [datarhei/restreamer#615]
**Subject of the issue**
As subject states, I'm using a Raspberry Pi Zero 2W with a Noir V3 camera. The camera is detected by the raspberry pi itself, but restreamer doesn't like it.

**Your environment**
I cannot seem to get Restreamer to accept the connected camera as a valid hardware device. **Only after spending 2hrs debugging it before creating this post did I find that Restreamer has only been certified for use on Pi 3 A+ and B+ as well as Pi 4 B. So I'm happy to act as a test dummy in this.**. 

The camera is being detected by the Pi Zero and is showing an image after running libcamera-hello (take a look at my lovely white roof while the camera stares directly into a light :P). 
![image](https://github.com/datarhei/restreamer/assets/88370061/c842eb3e-4e57-4108-881f-017b5584e09b)

On the Restreamer front, I need some help telling it that 'hey, the camera is connected as both a Unicam device (/dev/Media3) and ISP device (dev/media0), so don't complain'. Alternatively, what other config I need to do to get the camera to show up. In the following screenshot, I've tried each option and Restreamer doesn't probe successfully; i.e. Failed to probe the source. Please check the probe details. [Pastebin output of libcamera-hello](https://pastebin.com/tnKRDv7y)

Restreamer detects a plethora of devices:
![image](https://github.com/datarhei/restreamer/assets/88370061/c46702c1-eca8-40dd-84a1-475d0dbc19bc)

Eventual goal is to stream the feed to YT which is one of the main things that caught my eye about Restreamer as it can just interface with YT and have the same 'public' link remain unchanged.

**Files**
[Restreamer Process-Report](https://pastebin.com/MgEem1un)
[Publication-Service Process-Report](https://pastebin.com/7q8mzB2x)

**Steps to reproduce**
Attempt to configure a bog-standard instance hardware device.

**Expected behavior**
I would love it if the camera could be detected. :)

**Actual behavior**
The camera is not being detected :(

**Comment by MattGeale** [comment]
Additional output of list-cameras function with libcamera - camera is 100% being located:
![image](https://github.com/datarhei/restreamer/assets/88370061/cd5ae484-bbc8-41ec-8a00-a425961141e2)

**Comment by Lovely-ODV** [comment]
Bonjour,je viens de passer deux jours a comprendre egalement que seul cette carte ne fonctionne pas.Serait il possible de savoir si avec la nouvelle version il y'a une solution?
Merci beaucoup de votre aide pour mon projet ou je souhaite vraiement integre Restreamer qui repond a tous mes besoins contrairement a d'autres
