### ISSUE TITLE
Confused about aarch64 docker and edge docker images!

### ISSUE THREAD

**Issue by kevinshane** [datarhei/restreamer#62]
First very awesome job sir.. but sorry for the very noob question from a noob guy ^_^
- In docker hub I can see the `datarhei/restreamer-edge:0.1.2-aarch64` which updates very often.
- In github wiki homepage it suggests running this command: `docker run -d --name restreamer --restart always -e "RESTREAMER_USERNAME=YOUR-USERNAME" -e "RESTREAMER_PASSWORD=YOUR-PASSWORD" -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer-armv7l:latest`

The question is:
The `datarhei/restreamer-edge` seems like running complete different than the "suggested" way in wiki and the ENV(-e) seems missing the "rtsp" option and the `SNAPSHOT_REFRESH_INTERVAL=60000` as well... So what image should I run when in aarch64 arch?

I've already try the `datarhei/restreamer:0.1.0-aarch64` with port 8080 and seems like working as it should.. but when I try the `datarhei/restreamer-edge:0.1.2-aarch64` I can not see the `rtsp` input in homepage..

Could you please show me the right way to do? Thanks!
Also could you please tell me how to complete disable the `SNAPSHOT_REFRESH_INTERVAL` because the snapshot is being handled by the ip cam side! Thank you so much!!

**Comment by ioppermann** [comment]
In your case, you should use the datarhei/restreamer-aarch64 image. The restreamer-edge is meant to be as target for the external RTMP streaming server (e.g. instead of YouTube), but this is probable not what you want.

Currently it is not possible to disable the snapshot, however you can set it to a very high value.

**Comment by ioppermann** [comment]
v0.1.0 has been released. Just pull the latest datarhei/restreamer-aarch64 docker image. By setting the environment variable `RS_SNAPSHOT_INTERVAL' to `0` you can disable the snapshots (https://datarhei.github.io/restreamer/docs/references-environment-vars.html).

**Comment by kevinshane** [comment]
Thank you sir @ioppermann will test it out and report here!

**Comment by kevinshane** [comment]
@ioppermann hi, the streaming last around 2 hours and die, ffmpeg won't start anymore, any idea?
```
[11-11-2018 04:13:08.297] [INFO ] [    repeatToLocalNginx] Stale connection
[11-11-2018 04:13:08.301] [INFO ] [    repeatToLocalNginx] Stop streaming
[11-11-2018 04:13:08.312] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtsp://192.168.0.120:8554/unicast" in 6000ms
[11-11-2018 04:13:08.314] [ERROR] [              snapshot] Error: ffmpeg exited with code 1:
[11-11-2018 04:13:14.319] [INFO ] [    repeatToLocalNginx] Retry to connect to "rtsp://192.168.0.120:8554/unicast"
[11-11-2018 04:13:14.320] [INFO ] [    repeatToLocalNginx] Start streaming
```

**Comment by ioppermann** [comment]
@kevinshane According to your log, ffmpeg started again pulling the stream from the camera. Or do you refer to the snapshot? What is the brand of your camera?
