### ISSUE TITLE
Setting env var MAXSIZEMBYTES does not limit size of memfs

### ISSUE THREAD

**Issue by myspaghetti** [datarhei/restreamer#620]
**Description**
Setting the environment variable CORE_STORAGE_MEMORY_MAXSIZEMBYTES does not limit the size of memfs.

**Reproduce**
1. Set CORE_STORAGE_MEMORY_MAXSIZEMBYTES to a positive integer. Web GUI settings confirm this is set in ENV.
2. Check or unckeck "Remove the oldest entries if the /memfs is full" (checking this option removes old files but does not limit the size of memfs, which continues to grow as if old files were not removed)
3. Create a channel with a stream stored in memfs that exceeds the MAXSIZEMBYTES, for example a 1Mbps stream that is stored for 500 parts of 2s will exceed a MAXSIZEMBYTES of 100
4. memfs can continue to grow until RAM is full, potentially leading to a system crash
5. On the other hand, not setting CORE_STORAGE_MEMORY_MAXSIZEMBYTES and setting the memfs limit in the config.json file successfully limits the memfs size.

**Expected behavior**
CORE_STORAGE_MEMORY_MAXSIZEMBYTES limits the size of memfs

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Version datarhei-core v16.13.0 (linux/amd64) - plain-fog-2128

**Comment by ioppermann** [comment]
This seems to be a bug. We will look into that. `CORE_STORAGE_MEMORY_MAXSIZEMBYTES` has been deprecated (but should still work). Try the new environment variable `CORE_STORAGE_MEMORY_MAX_SIZE_MBYTES` instead.

**Comment by ioppermann** [comment]
I could confirm that `CORE_STORAGE_MEMORY_MAXSIZEMBYTES` is working correctly. But I found an bug regarding the enabling "Remove the oldest entries" option in the UI. It wasn't respected if this option wasn't enabled at startup.

datarhei/core@c3b63c448050574a95bdbad9bde402158c34e271

What you also might have observed is the overall memory consumption of the container in contrast to the files stored in `/memfs`. If you delete a file from `/memfs` it is not guaranteed that the used memory will be returned to the operating system. Restreamer might keep this memory for itself for later use, such that it doesn't need to reclaim it from the operating system.

You could use the `CORE_DEBUG_MEMORY_LIMIT_MBYTES` environment variable to define a recommendation for the upper limit of memory the whole application should consume. This includes the app itself and the size of the `/memfs`. Then Restreamer tries to keep its memory consumption close to that value. If you observe that the overall memory consumption is far above that value (e.g. at least 100MB) then you set this limit to low and it might impact the performance of Restreamer.

**Comment by myspaghetti** [comment]
Seems like this issue is closed?
