### ISSUE TITLE
Unable to detect webcam on Macbook M1 Pro

### ISSUE THREAD

**Issue by syedmurtaza108** [datarhei/restreamer#621]
**Subject of the issue**
It is not showing my built in camera, therefore unable to proceed further

<img width="605" alt="image" src="https://github.com/datarhei/restreamer/assets/44249868/9d0992de-666c-4410-878b-0103fffe8cbf">

**Your environment**
I run this command on my M1 machine
```
docker run --detach --name core --privileged --volume /Users/syedmurtaza/config:/core/config --volume /Users/syedmurtaza/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest
```

**Comment by ioppermann** [comment]
On MacOS, the built-in camera (and any other camera connected via USB) is only available natively via the Video Toolbox API. Docker is not forwarding these devices into the container and therefore they are not available.

It would work with a native (i.e. without Docker) installation of all required components (ffmpeg, datarhei Core, and RestreamerUI) on MacOS, but this is currently not supported.
