### ISSUE TITLE
{systemd} Trying to get restreamer to restart via systemd upon reboot

### ISSUE THREAD

**Issue by Psilovybin** [datarhei/restreamer#626]
**Subject of the issue**
Adding /etc/systemd/system/core.service

`[Unit]
Description=datarhei Core
After=docker.service
Requires=docker.service

[Service]
TimeoutStartSec=0
Restart=always
ExecStart=/usr/bin/docker run \
  --rm --name core --privileged \
  --security-opt seccomp=unconfined \
  -v /opt/core/config:/core/config \
  -v /opt/core/data:/core/data \
  -p 8080:8080 -p 8181:8181 \
  -p 1935:1935 -p 1936:1936 \
  -p 6000:6000/udp \
  datarhei/core:latest
ExecStop=/usr/bin/docker kill core

[Install]
WantedBy=multi-user.target
`

Upon reboot, in journalctl, I get the error
`docker: Error response from daemon: Conflict. The container name "/core" is already in use by container "b5b2928c6982876d2cfc0b3f50a96181a4a41d879f29d76d5bbce031d4709120". You have to remove (or rename) that container to be able to reuse that name.
Oct 01 14:01:52 sal9000 docker[721]: See 'docker run --help'.
Oct 01 14:01:52 sal9000 systemd[1]: core.service: Main process exited, code=exited, status=125/n/a
Oct 01 14:01:52 sal9000 systemd[1]: core.service: Failed with result 'exit-code'.
`
**Your environment**
Standard Debian 12 server setup with no GUI

**Files**
Posted above, having issues restarting restreamer server after reboot

**Steps to reproduce**
Followed the v2.0 documentation for linux to the letter, even entering in the docker command to start errors out.

`docker run --detach --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest

docker: Error response from daemon: Conflict. The container name "/core" is already in use by container `

**Expected behavior**
Server should start via docker

**Actual behavior**
Just errors out saying the container name is already in use.

**Comment by ioppermann** [comment]
@Psilovybin In order to completely remove the container, the Docker command should contain the `--rm` option. It is included in your `systemd` command and should work accordingly.

The Docker command in the documentation didn't contain the `--rm` option, but I added it now.

**Comment by Psilovybin** [comment]
> @Psilovybin In order to completely remove the container, the Docker command should contain the `--rm` option. It is included in your `systemd` command and should work accordingly.
> 
> The Docker command in the documentation didn't contain the `--rm` option, but I added it now.

awesome.. thank you for your response, I'm rather new to docker, but gain thank you for explaining it.
