### ISSUE TITLE
Show something when the source doesent sent anything

### ISSUE THREAD

**Issue by blxryer** [datarhei/restreamer#627]
Hello,
i want to show a picture or something when the source doesent sent anything. is that possible? because the f.ex. the youtube stream directly stops and behave like its "laging" and i dindent want that to happen.

**Comment by ioppermann** [comment]
@blxryer Thank you for the suggestion. This is already on our feature request list: https://github.com/datarhei/restreamer/discussions/345#discussioncomment-2923875
