### ISSUE TITLE
Where is the Template documentation?

### ISSUE THREAD

**Issue by IanEatsBabies** [datarhei/restreamer#629]
I canne stand the cluttered player page so was happy to see the Template option. Unfortunately there seems to be ZERO documentation, up until the point where it seems you'd rather not have anyone use it.
- NO documentation as far as I can see. There's [this insult](https://docs.datarhei.com/restreamer/knowledge-base/manual/publication-website/template), but that's just rehashing the words found on the interface.
- No examples
- The only template avaiable can neither be downloaded from the interface nor can it be found in the source.

Am I just a fucking idiot?! Where's the documentation?!

Being a template, what variables are expected? What language do we write these templates in?

**Comment by ioppermann** [comment]
We understand your frustration and we assure you that you are not a f*** idiot, because the documentation of the template option was not available.

It is now available at https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-do-i-write-a-template-for-the-publication-website
