### ISSUE TITLE
Ability to embed logo in stream?

### ISSUE THREAD

**Issue by ofadam** [datarhei/restreamer#63]
Is there a way to embed a logo in the stream before sending to YouTube's ingest?

**Comment by ioppermann** [comment]
This would require to re-encode the stream (instead of just forwarding it). Your hardware you're running the restreamer on needs to be powerful enough.

We will consider this for one of the upcoming releases.

**Comment by philipptrenz** [comment]
Wouldn't it be possible to embed a logo as HTML element into the iframe?

**Comment by ioppermann** [comment]
@philipptrenz Yes, this would be one solution, but it requires that the player from the Restreamer is embeded/used. However, if you want to push the stream to Youtube/Twitch/Facebook/... you have to encode it into the video.

**Comment by philipptrenz** [comment]
True, missed that! 
So from my point of view both options should be considered. In my use case I just use the player to embed the stream in a website. For that case a simple png as html image element, separate from the stream, would do it just fine.

**Comment by svenerbeck** [comment]
@ofadam 
This function is now an offical feature request. Image overlay, watermark over an encoding.
You find the list here: https://github.com/datarhei/restreamer/discussions/345

cheerio
Sven

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
