### ISSUE TITLE
HDMI out on Raspberry Pi 4

### ISSUE THREAD

**Issue by os-i-am** [datarhei/restreamer#630]
I'm trying to establish a Raspberry Pi 4 setup in which Restreamer (Docker) catches an RTMP stream (that part works) and redirects it to the HDMI output of the Pi.
The below solution (by @ioppermann on a similar issue) didn't work for me, the addition of `pixel_encoding=2` to the config.txt of the Pi 4 even bricked the Pi boot sequence, so I had to re-flash the SD card.
Is there anything I can do to enable the _Framebuffer_ Publication option? (it is greyed out in the UI and reports 'Incompatible. Check the requirements').

In a perfect world, the Pi would output the incoming RTMP stream (video + audio) to one of the HDMI outs of the Pi without too much of a delay.

Thanks!

Original issue I'm referencing here (since it has been closed in the meantime):

@ioppermann in https://github.com/datarhei/restreamer/issues/387#issuecomment-1189179884
On the Raspberry Pi 4 it's a bit different. There you have to edit the `/boot/config.txt` in order to set the correct resolution:

1. Open `/boot/config.txt` in an editor, e.g. `sudo nano /boot/config.txt`
2. Set `hdmi_force_hotplug=1`
3. Set `hdmi_group=1`
4. Set `hdmi_mode=4` (for 1280x720) or `hdmi_mode=16` (for 1920x1080)
5. Set `hdmi_pixel_encoding=2`
6. At the bottom in the `[pi4]` section, set `dtoverlay=vc4-fkms-v3d`

Reboot the Pi and the docker container. Now you should see the `Framebuffer` publication service, where you select the `/dev/fb0` device and the matching color settings.

**Comment by ioppermann** [comment]
@os-i-am As it turns out, the `hdmi_*` options have been deprecated/removed in the latest Raspbian "bookworm". We recommend to use Raspbian "bullseye". With "bullseye" these instruction still work.

**Comment by svenerbeck** [comment]
Hello @os-i-am 

We are closing your ticket https://github.com/datarhei/restreamer/issues/630.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
