### ISSUE TITLE
H265 

### ISSUE THREAD

**Issue by danitus13** [datarhei/restreamer#631]
I have many 4k cameras that have h265 encoding and not h264. Would I need restreamer to work with h265, as already requested here?

https://github.com/datarhei/restreamer/issues/552

May I know the costs for immediate implementation?

**Comment by hereisderek** [comment]
replied in the linked ticket
https://github.com/datarhei/restreamer/issues/552

fyi

**Comment by svenerbeck** [comment]
Hi @danitus13 ,

Thank you for your message about the H.265 encoding support in our datarhei Restreamer. I'm delighted to confirm that our Restreamer indeed supports H.265 (HEVC) encoded video streams, allowing you to fully utilize your 4K cameras with this encoding.

To assist you further, we have a video demonstration available that showcases how the Restreamer handles H.265 encoded streams. You can view this video here: [How to Use H.265 with datarhei Restreamer](https://www.youtube.com/watch?v=oVCEMUguskA). This should give you a clear overview of the process and the capabilities of our software.

Regarding the costs, there are no additional charges for this feature. 

If you have any more questions or need further assistance, please do not hesitate to contact us.

Cheerio,
Sven

**Comment by danitus13** [comment]
> Hi @danitus13 ,
> 
> Thank you for your message about the H.265 encoding support in our datarhei Restreamer. I'm delighted to confirm that our Restreamer indeed supports H.265 (HEVC) encoded video streams, allowing you to fully utilize your 4K cameras with this encoding.
> 
> To assist you further, we have a video demonstration available that showcases how the Restreamer handles H.265 encoded streams. You can view this video here: [How to Use H.265 with datarhei Restreamer](https://www.youtube.com/watch?v=oVCEMUguskA). This should give you a clear overview of the process and the capabilities of our software.
> 
> Regarding the costs, there are no additional charges for this feature.
> 
> If you have any more questions or need further assistance, please do not hesitate to contact us.
> 
> Cheerio, Sven

Hi, my raspberry doesn't support the transformation from h265 to h264, so I would need direct encoding.
