### ISSUE TITLE
streaming problem with multiple restreamer instance in one docker server

### ISSUE THREAD

**Issue by kosa7** [datarhei/restreamer#64]
Hello,
install docker on Linux kamery 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64
create 4 instance restreamer
[docker_instance.txt](https://github.com/datarhei/restreamer/files/2296326/docker_instance.txt)

Approximately 1 to 2 cameras will stop working in the live view
docker containers are runing, nginx runing, streaming processes runing
example listing individual processes

[docker_ps_aux.txt](https://github.com/datarhei/restreamer/files/2296325/docker_ps_aux.txt)

after restart instance restremer live strem back online to max 1 day, then stop working live stream.

Any sugestion how to repair?
thanks.

**Comment by CAM-TECH** [comment]
what pi do u have? i have this same on pi2, but on pi 3b+ not.

**Comment by kosa7** [comment]
I do not use pi. I use an x86 server with a docker. But it is interesting to have different versions of pi it behaves differently.

**Comment by CAM-TECH** [comment]
Z tego co Widzę jesteś z Polski, stawiałem urządzenie na wielu serwerach, problem odnotowałem na rpi2 na 3 nie, mam w domu na serwerze postawione i też lata od 2 tygodni. Ja bym dodał restart do crona 

01 */24 * * * /etc/init.d/docker restart

**Comment by kosa7** [comment]
use of cron is not the solution. because the interruption between cycles can lead to video malfunction.

**Comment by ioppermann** [comment]
We will investigate this issue. Do your cameras restart inbetween? It can be that the stream from the cameras are having some errors in it which causes the ffmpeg to choke but not to stop.

What cameras do you have?

**Comment by kosa7** [comment]
no cameras do not restart between.
we use dahua cameras, model:IPC-HFW2320R-ZS
the camera did not restart.
I do not know about the errors on the stream camera. Cameras is diferent location connect fiber, no wifi.
I have tried another operating system (CentOs) and the situation is the same. Within 14 days, all 5 cameras stopped working.

**Comment by ioppermann** [comment]
I suspect that the ffmpeg process that ingests the stream from the webcam is getting stale. The used ffmpeg version in the docker image is quite old and ffmpeg may have some bugs that is causing this.

Do you use RTSP over TCP to ingest the stream from the cameras?

I'm currently updating the docker images such that a more recent ffmpeg version will be used.

**Comment by CAM-TECH** [comment]
> I suspect that the ffmpeg process that ingests the stream from the webcam is getting stale. The used ffmpeg version in the docker image is quite old and ffmpeg may have some bugs that is causing this.
> 
> Do you use RTSP over TCP to ingest the stream from the cameras?
> 
> I'm currently updating the docker images such that a more recent ffmpeg version will be used.


when can we expect this update?

**Comment by kosa7** [comment]
> I suspect that the ffmpeg process that ingests the stream from the webcam is getting stale. The used ffmpeg version in the docker image is quite old and ffmpeg may have some bugs that is causing this.
> 
> Do you use RTSP over TCP to ingest the stream from the cameras?
> 
> I'm currently updating the docker images such that a more recent ffmpeg version will be used.

yes, used RTSP over TCP

**Comment by ioppermann** [comment]
I'm planning for November *fingerscrossed*

**Comment by ioppermann** [comment]
v0.1.0 has been released. Please try it out and leave a comment how it works now for you.

**Comment by CAM-TECH** [comment]
did you test youtube route?, it started, but yotube is offline after a while, something is wrong.

**Comment by kosa7** [comment]
> v0.1.0 has been released. Please try it out and leave a comment how it works now for you.

I set up a new version, so I'm going to watch it for a few days and get the result.

in the new version not working parameters for -e "RESTREAMER_USERNAME = login" and -e "RESTREAMER_PASSWORD = password"

**Comment by ioppermann** [comment]
We changed the environment variable prefix to RS_, however the old environment variables work. Only in the case of RESTREAMER_USERNAME and RESTREAMER_PASSWORD I saw that they get overwritten accidentally. It will be fixed in the next release. Please use -e "RS_USERNAME=login" -e "RS_PASSWORD=password" instead.

**Comment by ioppermann** [comment]
@CAM-TECH I tested the Youtube route and had now issues. I will test it for longer. For how long did it work for you? I noticed that Youtube sometimes stops the stream with no apparent reason.

**Comment by CAM-TECH** [comment]
2 devices and two youtube accounts, I click in the rs start broadcast, the YouTube broadcast "run" after a while is offline, the restreamer works, and the YouTube broadcast is not

**Comment by ioppermann** [comment]
Yes, this would be good if you can give me access to one of your cams so I can test it. Did you see any error messages in the Youtube creator studio?

**Comment by CAM-TECH** [comment]
on youtube there are no bugs, the old restreamer works well, the new one is not

**Comment by CAM-TECH** [comment]
send me your email, idk how send here PM

**Comment by ioppermann** [comment]
@CAM-TECH I send a message through the contact form on your website.

**Comment by CAM-TECH** [comment]
Your domain email is .ch? 
send me again,.

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

**Comment by ioppermann** [comment]
@CAM-TECH Yes, that's correct. I sent it again.

**Comment by CAM-TECH** [comment]
with the server is okay, google is not lying and there is still some problem, I do not know what is going on ...

send me an email directly on google

camtechsuwalki@gmail.com

I have a google phrase that the address does not exist again, I trade electronics with Chinese and I have no problems

i try send from google 

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

**Comment by ioppermann** [comment]
@CAM-TECH OK. I sent you the email directly to your google address.

**Comment by kosa7** [comment]
Hi,
after 1 week, all camera works, with no problem. good job.
Thanks.
