### ISSUE TITLE
Update stream title and metadata on connected platforms when going live?

### ISSUE THREAD

**Issue by jdheeter** [datarhei/restreamer#641]
**Is your feature request related to a problem? Please describe.**
restreamer seems to do everything I was looking for except allow you to update the stream description and metadata on the connected platforms when you go live. 
**Describe the solution you'd like**
You should be able to login with your related accounts (Youtube, Twitch, etc..) and then there should be a page where you can change the title and other metadata of the stream which would push that update to the related platforms.

**Comment by ioppermann** [comment]
Thank you the suggestion. This is already on our feature request list (see #573)
