### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by whyauthentic** [datarhei/restreamer#644]
**Is your feature request related to a problem? Please describe.**
Its not so nice when streaming on multiply plattforms and dont having an compressed chat for Overlay and Dock in OBS :D

**Describe the solution you'd like**
An Feature to have an compressed chat for all plattforms :) As Overlay for OBS and as Dock for OBS ;D

**Comment by svenerbeck** [comment]
Hello whyauthentic

We have converted the request into a feature request. Follow the discussion https://github.com/datarhei/restreamer/discussions/345 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
