### ISSUE TITLE
can u add mpd and drm support

### ISSUE THREAD

**Issue by MANOJJADHAV4000** [datarhei/restreamer#653]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.

**Comment by MANOJJADHAV4000** [comment]
plzz add it

**Comment by svenerbeck** [comment]
Hello manoj4000,

Thank you for suggesting adding MPD and DRM support to our software. We always look for ways to enhance our products and appreciate your input.

Please provide us with more details to understand your requirements better and ensure we can evaluate this feature request accurately. 

Specifically, we are interested in knowing:

- Your specific use case for MPD (MPEG-DASH) and DRM (Digital Rights Management) support.
- Any DRM systems or protocols you want to integrate with our software.
- How do you envision this feature improving your streaming setup or workflow?

Your detailed feedback will be invaluable in helping us assess this feature's feasibility and potential implementation. Once we have more information, we can consider it as a [formal feature request](https://github.com/datarhei/restreamer/discussions/345) and provide you with updates on our development roadmap.

Looking forward.

Cheerio,
Sven

**Comment by JustJoostNL** [comment]
Hey @svenerbeck,

While I'm not the creator of this feature request, I'm also interested in this, and will provide answers on the questions (too):

> Your specific use case for MPD (MPEG-DASH) and DRM (Digital Rights Management) support.

Most players do support HLS, but MPD can sometimes have it's advantages over HLS. DRM is useful to protect sensitive content, or to avoid pirating of content.

> Any DRM systems or protocols you want to integrate with our software.

Fairplay and Widevine

>How do you envision this feature improving your streaming setup or workflow?

I think this improves the setup and workflow, because people no longer need something separate that converts the HLS to an MPD stream, and people no longer need to add the DRM manually.

**Comment by svenerbeck** [comment]
Hello  @JustJoostNL,

There is already a DRM feature request. Follow the discussion (https://github.com/datarhei/restreamer/discussions/345#discussion-4108562) to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
