### ISSUE TITLE
RTMPS connection URL includes both the rtmp and rtmps port in it

### ISSUE THREAD

**Issue by MrRubberDucky** [datarhei/restreamer#658]
**Describe the bug**
No idea why this happens but after changing ports from default, the rtmps:// address has both ports in it which just makes OBS experience a tantrum when trying to connect to it. Example `rtmps://site.domain.tld:12002:12003/live/streamkey` instead of just `rtmps://site.domain.tld:12003/live/streamkey` (I set 12003/tcp for rtmps)

If it matters, i'm on Podman and all I've done from installation was change port numbers and redeploy container

I'm not sure if intentional, if it is then sorry for cluttering up issues ^^" but in my testing, it gave me a single port with just stock config

**To Reproduce**
1. Put the container up with Podman or podman-compose
2. Change ports for rtmp to 12002 and for rtmps to 12003
3. Redeploy container so it publishes correct ports (from what i've read podman doesn't allow to edit ports once they're already deployed to a pod so have to redeploy)
4. Start a RTMP connection from wizard and the format will have both ports in it

**Expected behavior**
The `rtmps://` connection url having a single port instead of them both

**Screenshots**
![fresh-instructive-aphid](https://github.com/datarhei/restreamer/assets/79613254/fd928028-7183-4ed2-81b5-1f30fabe356f)

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm, Podman Container (image from docker.io/datarhei/restreamer:latest, deployed using podman-compose)
 - Browser: Firefox 120.0.1
 - Version 2.7.0, v16.13.1 (core)

**Additional context**
If it helps, I save config to my home directory along with the data. I also uh expose the HTTP port and terminate TLS on Caddy that runs on the VPS.

Also here's the log, not sure if it says anything helpful as that's all that it logs really: 
```
ts=2023-12-10T10:06:52Z level=INFO component="Core" application="datarhei-core" arch="linux/amd64" branch="main" build="2023-12-01T16:25:04Z" commit="477e8c6c3248d3701917e4f3c0430042fe2fa173" compiler="go1.20.4" license="Apache License Version 2.0" repository="https://github.com/datarhei/core" version="16.13.1"
ts=2023-12-10T10:06:52Z level=INFO component="Core" msg="Read config file" path="/core/config/config.json"
ts=2023-12-10T10:06:52Z level=INFO component="Process" msg="Created" id="restreamer-ui:ingest:2e647fba-439f-4cf6-93de-e92975c52fbc_snapshot"
ts=2023-12-10T10:06:52Z level=INFO component="Let's Encrypt" msg="Acquiring certificate ..." host="stream.rubberverse.xyz"
ts=2023-12-10T10:06:56Z level=INFO component="Let's Encrypt" msg="Successfully acquired certificate" host="stream.rubberverse.xyz"
ts=2023-12-10T10:06:56Z level=INFO component="HTTPS" msg="Server started" address=":12001"
ts=2023-12-10T10:06:56Z level=INFO component="HTTP" msg="Sidecar server started" address=":12000"
ts=2023-12-10T10:06:56Z level=INFO component="RTMPS" msg="Server started" address=":12003"
ts=2023-12-10T10:06:56Z level=INFO component="RTMP" msg="Server started" address=":12002"
ts=2023-12-10T10:06:56Z level=INFO component="SRT" msg="Server started" address=":12004"
ts=2023-12-10T10:07:11Z level=INFO component="Session" msg="Active" id="HTTP" location="any" peer="any" reference="" type="http"
```

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.

**Comment by ioppermann** [comment]
This bug has been fixed in the `dev` branch of `datarhei/restreamer-ui`.

**Comment by ioppermann** [comment]
This has been fixed in the latest release: https://github.com/datarhei/restreamer/releases/tag/v2.8.0
