### ISSUE TITLE
Autoplay how to modify and access clappr files ?

### ISSUE THREAD

**Issue by flybelgium** [datarhei/restreamer#66]
I would like to activate autoplay when player is loading, i found this issue 
https://github.com/datarhei/restreamer/issues/28

But how to have access to the Clappr Player files through the docker ? I'm in Windows Server 2016 Configuration (docker + hyper v)

If i just add this line on the player.html file, how to overwrite this file with new parameters in restreamer ?
line to be added : autoPlay: true

Thanks

**Comment by ioppermann** [comment]
If you edit the player.html file, then you have to build you own docker image in order to make it work.

In the upcoming release we will incorporate the autoplay option.

**Comment by ioppermann** [comment]
v0.1.0 has been released. Now you can enable autoplay for the embedded player. Have a look at https://datarhei.github.io/restreamer/docs/guides-embedding.html#autoplay
