### ISSUE TITLE
OBS doesnt connect to restreamer

### ISSUE THREAD

**Issue by whyauthentic** [datarhei/restreamer#662]
Hey! 

I tried today to set up a Restreamer Server on my Strato VPS, :D But it didn't work :/

OBS said every time "Can't connect to Server".

Help would be nice :/

Good Day!

**Comment by ioppermann** [comment]
Please check my answer in this issue: https://github.com/datarhei/restreamer/issues/647#issuecomment-1831516718

**Comment by whyauthentic** [comment]
> Please check my answer in this issue: [#647 (comment)](https://github.com/datarhei/restreamer/issues/647#issuecomment-1831516718)

Tried it, but it didn't work

**Comment by whyauthentic** [comment]
Nevermind @ioppermann i fixed it :D Changed the Network in Docker from Bridge to Host ^^

**Comment by whyauthentic** [comment]
Okay, perfekt xD New Problem is there! OBS says Streaming but Restreamer doesnt recognize the stream .-.
