### ISSUE TITLE
stream link with a token

### ISSUE THREAD

**Issue by sara990099** [datarhei/restreamer#666]
when i set the following link in network source, it doesn't work and it returns the following Error.
http://host/test.m3u8?token=--------

Failed to resolve hostname ***.one: Name does not resolve

on Ubuntu server i have run this container:

docker run --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --dns="8.8.8.8"  --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest

I can  resolve the hostname on ubuntu server also i can stream the link via VLC player

**Comment by ioppermann** [comment]
I don't know what VLC is doing with that URL. That URL is missing the host part, so Restreamer (resp. ffmpeg) doesn't know to which host it should connect to.

**Comment by sara990099** [comment]
> I don't know what VLC is doing with that URL. That URL is missing the host part, so Restreamer (resp. ffmpeg) doesn't know to which host it should connect to.

My bad. please check the sample link again
