### ISSUE TITLE
Restream .m3u8

### ISSUE THREAD

**Issue by Jani4ik** [datarhei/restreamer#67]
Is the Restreamer project alive? 
Can you add support for video source m3u8 links in future releases? 
Thank you!

**Comment by ioppermann** [comment]
Yes, Restreamer is alive and streaming from a .m3u8 source will be supported in the upcoming release (probably around mid-November).

**Comment by ioppermann** [comment]
v0.1.0 has been released. Now it's possible to stream from a .m3u8 source.

**Comment by Jani4ik** [comment]
@ioppermann doesn't work for me .m3u8
I try to retransmit the IPTV channel of my provider, I press the "Start" button and nothing happens.

**Comment by ioppermann** [comment]
Which docker image do you use and what is the system you are running it on? It looks like that you don't use yet the latest version.

**Comment by Jani4ik** [comment]
@ioppermann 
![1542123575529](https://user-images.githubusercontent.com/13448816/48424387-32869d80-e76b-11e8-867a-6e52c385c6be.jpg)

**Comment by ioppermann** [comment]
According to the screenshots from yesterday, you're still on an old version.

Did you pull the latest docker image as [described in the documentation](https://datarhei.github.io/restreamer/docs/guides-updates.html#linux).

**Comment by Jani4ik** [comment]
@ioppermann thanks, all worked well! ^-)
