### ISSUE TITLE
Make SRT Stream ID Optional

### ISSUE THREAD

**Issue by JeffThis** [datarhei/restreamer#675]
It seems that Stream ID is currently required for SRT streams, but several broadcast-grade encoders/decoders do not use Stream ID and instead only use IP, Port, and Encryption (optional).  The way it is implemented in these appliances is that each connection gets its own dedicated port assigned, rather than all connections sharing that same port and using Stream ID as a differentiator.

My recommendation to support these appliances would be to allow an optional port-specific configuration for each SRT stream and to make Stream ID optional (requiring EITHER a port assignment OR Stream ID for each SRT stream).

As an example, these are the available SRT streaming parameters on a Haivision Makito encoder:
![image](https://github.com/datarhei/restreamer/assets/134097278/44ab31b9-bfef-4df8-b8d9-f24ea86c4138)

**Comment by ioppermann** [comment]
These broadcast encoders and decoders use still an older version of the SRT protocol that doesn't know about `streamid`.

It might be possible to allow encoders to connect to Restreamer in order to send a stream with only using one port. If you want to connect to a decoder, you might need to use a publication service.

**Comment by ioppermann** [comment]
This feature is now available in the respective dev branches of datarhei/core and datarhei/restreamer-ui.

For the core, SRT server support for SRT handshake v4 has been added. This allows to push streams without a `streamid`. In these cases a `streamid` will be generated which is the `ip:port` of the sending device (datarhei/core@4bffbea48ef4ef32a60288092d6c7e5fb243304d).

In UI the network source has been extended such that it allows you to choose from a list of currently available SRT/RTMP streams in "receive mode" (datarhei/restreamer-ui@d74438e).

**Comment by ioppermann** [comment]
This feature is now available in the lastest [Restreamer release](https://github.com/datarhei/restreamer/releases/tag/v2.8.0).

**Comment by kubo6472** [comment]
Sorry for necroposting, as I mentioned in #889 this still doesn't solve the issue, that the SRT stream won't start without a valid streamID, even if my DSLM doesn't support a) special characters/URL params in the streaming URL and b) streamid as an option/separate field.

**Comment by SerialDestructor** [comment]
Another bump, almost a year later. I ran into the same issue as @kubo6472 (I think?). I have a Sony Alpha series camera, which indeed supports SRT natively.

It does not allow using any parameters in the connection URL, only the host. It refuses to connect if you try. As I wanted to have it working, at least for now, I did a Wireshark dump. Four packets appeared: the initial handshake from the Alpha body mentions SRT version 4. Restreamer replies with a version 5. The handshake (as it seems) restarted with version 5 from the Alpha body.

I don't know if this 'upgrade' thing is in the spec, I didn't have time to dig into it. But that explains why this workaround from @ioppermann doesn't work in this case.

For now, I changed the logic in srt.go to also use IP:PORT if no Stream ID has been sent. If the Alpha body indeed does support v5 (or only mimmicks it, again, I didn't have time to dig deeper), to my understanding, it does not follow the spec.

Anyhow, with this change, it works. It's only cumbersome to re-enter the stream details each time you restart the stream.

I hope this sheds some light on the subject. There needs to be some user friendly fallback logic in this case.

Edit: I think I might have something that could work. 

There could be an option for 'vendor specific quirks'. In this case, Sony Alpha/FX bodies. If this has been chosen, there are three ways to distinguish clients from each other:

- The current method, using the connecting IP and port (the current method, which I explained above, is not ideal)
- A new method, which spawns multiple SRT listeners and a client is tied to a specific port on the host (say ports 6000-6020). In this case, you can even alter the listener logic to bypass things like stream ID only for a specific listener, while the behaviour default adheres to the spec. Also, upon reconnecting, no changes in the UI are needed to resume/restart a stream. I think this is the most clean solution, as it only applies to the host. Also, it will be easier this way to deal with more non-compliant stuff.
- Another method, which maps the encryption secret for a device/streamer to a specific stream. So secret 'aAbBcC12345' could be mapped to (for example) 'noncompliant-srt-stack-1'. This name is persistent across streams and connections. Con: you can not reuse a secret for different clients (but you won't do that anyway... do you?)

I hope this helps!

**Comment by kubo6472** [comment]
Wow, thank you for your work on this. We managed to solve it in the meantime with an inexpensive Chinese encoder that just takes the HDMI feed from the camera. But we have more than one camera, so if this gets turned into a feature, we will definitely consider using the camera body directly.
