### ISSUE TITLE
rtsps network source can't be edited/saved

### ISSUE THREAD

**Issue by martinhoess** [datarhei/restreamer#677]
**Describe the bug**
You can add network sources with rtsp**s** protocol but you can't edit/save them

**To Reproduce**
1. Add new channel
2. Network source
3. Use rtsp**s** address
4. Save
5. Edit Channel
6. Edit rtsp**s** address
7. Try to save changes

**Expected behavior**
Treat rtsp**s** the same way as rtsp
Allow to save changes to channels with rtsp**s** network source

**Screenshots**
![image](https://github.com/datarhei/restreamer/assets/47973549/29f2a7d7-dad7-46c6-b084-762bec784d71)
![image](https://github.com/datarhei/restreamer/assets/47973549/4bcbf63e-8759-4e8d-aedc-a6a6cb5117d7)
![image](https://github.com/datarhei/restreamer/assets/47973549/629140ea-cadf-4c98-b9b9-f8f3ec33206b)
![image](https://github.com/datarhei/restreamer/assets/47973549/82c0ff00-1584-434d-8f92-eb6bd22f2cfe)

**Additional context**
apart from rstp**s** sometimes it would be useful to add/edit a channel even if the (network) source is not available.
In other software, this is sometimes solved by prompting "xyz not available, would you still like to save"

**Comment by mdeeter** [comment]
Confirmed that this update fixed my issue....
![image](https://github.com/datarhei/restreamer/assets/136902/ca37cd8f-95fb-4fd8-a5fe-2e19dac34609)
