### ISSUE TITLE
Audio codecs in cameras

### ISSUE THREAD

**Issue by And63** [datarhei/restreamer#68]
The video is fine.
I have a problem with sound in cameras with G.711 / G.722.1 / G.726 / MP2L2 / PCM audio coding. There is silence instead of sound. If the camera has audio coded in AAC, the sound is normal. How can fix it?

**Comment by ioppermann** [comment]
You can set the environment variable `RS_AUDIO=aac`. This will force encoding the audio track to AAC if it is not already AAC (https://datarhei.github.io/restreamer/docs/references-environment-vars.html#rs_audio)
