### ISSUE TITLE
Can't reach server with rtmps using Easypanel

### ISSUE THREAD

**Issue by utibe-ettebong** [datarhei/restreamer#685]
**Can't reach server with rtmps using Easypanel**
After successfully installing on EasyPanel, setup admin access, enabled rtmps and SSL, the rtmps url used is the url that was added on  EasyPanel. Even after changing the domain in the restreamer settings, it still showed the same url.
when trying to connect with OBS, it says "failed to connect to server". I've tried updating, but still getting the same error.

**Your environment**
EasyPanel on Ubuntu.

**Comment by ioppermann** [comment]
Please reach out to the EasyPanel template developers.
