### ISSUE TITLE
how to rename this file

### ISSUE THREAD

**Issue by sohag1192** [datarhei/restreamer#686]
root@ns:~# docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data -p 8083:8083 -p 8082:8181 -p 1935:1935 -p 1936:1936 -p 3000:6000/udp datarhei/restreamer:latest
docker: Error response from daemon: Conflict. The container name "/restreamer" is already in use by container "c1c34128e596b97ddf75b3872293acecab2703782302bdd50c204ca4ec53dee6". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
root@ns:~# You have to remove (or rename) that container to be able to reuse that name.
-bash: syntax error near unexpected token `('
root@ns:~# docker run --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest
26e2c6da801c006f754bf346b464f8059d86f8dc812f470e47c41a1dc3ecd57f
docker: Error response from daemon: driver failed programming external connectivity on endpoint core (53cf3c4206cbe78131764095f0495ed7de60e3141337057f8ff0aa867a68c452): Bind for 0.0.0.0:8080 failed: port is already allocated.

**Comment by ioppermann** [comment]
You have still a container running with the name "restreamer" that is using the port 8080. Run `docker kill restreamer && docker rm restreamer`. Then you can start a new container with the same name.

**Comment by sohag1192** [comment]
ok , thanks 🥰
