### ISSUE TITLE
Audio Getting out of Sync

### ISSUE THREAD

**Issue by wblake0000** [datarhei/restreamer#69]
I have a raspberry pi 3+ and a PTZ camera with 720p video and G711 audio and reencoding it to AAC but after a few minutes the audio is out of sync with the video.  I verify with the "player" on the restreamer site that the audio and video are out of sync at that stage.  I can open up VLC and play the same RTSP stream and the audio and video are perfectly in sync.  Any thoughts on why the video and audio are out of sync and how I can get them not to go out of sync?

**Comment by ioppermann** [comment]
We experience this with other cameras, too. This is a problem with the reencoding of the audio track. What is your camera model? Does the camera has the possibility to encode the audio in a different format, e.g. MP3 or PCM?

**Comment by And63** [comment]
How I can add parametr “-use_wallclock_as_timestamps 1” to restreamer?

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
