### ISSUE TITLE
Auto start RESTREAMER after rpi4 reboot

### ISSUE THREAD

**Issue by 100karel** [datarhei/restreamer#691]
How to set RPI4 to automatically start RESTREAMER after reboot? Thanks

**Comment by ioppermann** [comment]
In the docker command for Restreamer you have to add the `--restart=always` option. This will cause docker to start Restreamer after you reboot your Pi.

**Comment by 100karel** [comment]
Can you please write the whole command here? When I type this it doesn't work. RESTREAMER does not start itself after restarting.
`docker run --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:rpi-latest --restart=always`

**Comment by ioppermann** [comment]
The `--restart=always` option needs to be befor the docker image name, e.g.:

`docker run --restart=always --detach --rm --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:rpi-latest`

You also have to make sure that Docker itself is also starting automatically after a reboot.

**Comment by 100karel** [comment]
Docker is running after reboot. If I enter the command, it says an error. `docker: Conflicting options: --restart and --rm.
See 'docker run --help'.`

**Comment by 100karel** [comment]
So it is correct `docker run --restart=always --detach --name core --privileged --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:rpi-latest`
This works. Thank you very much for your help.
