### ISSUE TITLE
restreamer stopped work

### ISSUE THREAD

**Issue by CAM-TECH** [datarhei/restreamer#70]
After adding or changing one letter or some small meaningless element, it just stops working ... I changed the favicon restreamer stopped working... wallpaper stoped working or even one name in the translate and it does not work. Can you explain why?

**Comment by ioppermann** [comment]
What operating system do you use? If it uses SELinux, this may cause problems.
What is the command you are starting the restreamer with? `docker run ...`
Wat is the logging output from the restreamer? `docker log [containername]`

**Comment by ioppermann** [comment]
This looks more like you're messing heavily with docker itself and breaking it. This is not a problem caused by the restreamer.

If you want to change something in the restreamer, I recommend that you clone the source code from github, make your changes in a new branch and then build a new docker image.

```
git clone https://github.com/datarhei/restreamer.git
cd restreamer
git checkout -b custom
```

* The background image you'll find in `src/webserver/public/images`.
* The language you can change/add in `src/webserver/public/locales`. There you can simply add a `lang-pl_PL.json` and adjust `src/webserver/public/views/header.html` accordingly. Please consider making a pull request if you want to share a new translation with other users.

After doing your changes, you can build your own docker image:
```
docker build -t restreamer-custom -f Dockerfile-arm64v8 .
```

This will build a docker image for the aarch64 architecture.

**Comment by CAM-TECH** [comment]
I thought about it too, I will try to do it for debian, then I upload picture to docker or github I think it will solve my problem, but I will tell you that previous versions did not have this problem, I have an old version on one ubuntu change and work as soon as I am new on ubuntu immediately stops working after changes:) also something is mixed up.

**Comment by CAM-TECH** [comment]
Build an image from a Dockerfile
root@raspberrypi:/home/pi/restreamer# docker build -t restreamer-custom -f Dockerfile-arm64v8 .
Sending build context to Docker daemon    832kB
Step 1/28 : ARG IMAGE=arm64v8/debian:stretch-slim
Step 2/28 : FROM $IMAGE as builder
 ---> 9cf0daa37223
Step 3/28 : MAINTAINER datarhei <info@datarhei.org>
 ---> Using cache
 ---> 71a4f4c0e9a0
Step 4/28 : ARG LAME_VERSION=3.100
 ---> Using cache
 ---> d887eb12d338
Step 5/28 : ARG X264_VERSION=20180717-2245-stable
 ---> Using cache
 ---> eb0be88b86cc
Step 6/28 : ARG FFMPEG_VERSION=4.1
 ---> Using cache
 ---> 9eb315a10757
Step 7/28 : ARG NGINX_VERSION=1.14.1
 ---> Using cache
 ---> 29ca1d77e5c2
Step 8/28 : ARG NGINXRTMP_VERSION=1.2.1
 ---> Using cache
 ---> 682425d59019
Step 9/28 : ARG NODE_VERSION=10.13.0
 ---> Using cache
 ---> 42104a7b3e81
Step 10/28 : ENV SRC="/usr/local/"     LD_LIBRARY_PATH="/usr/local/lib"     PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
 ---> Using cache
 ---> aa1ded8edc33
Step 11/28 : RUN apt-get update &&     apt-get install -y         pkg-config         curl         libpcre3-dev         libtool         libssl-dev         zlib1g-dev         libasound2-dev         build-essential
 ---> Running in 52a02b9ec417
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update &&     apt-get install -y         pkg-config         curl         libpcre3-dev         libtool         libssl-dev         zlib1g-dev         libasound2-dev         build-essential' returned a non-zero code: 1

**Comment by CAM-TECH** [comment]
after build 

root@Khadas:~/restreamer# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              09fa2c95d5d6        3 minutes ago       702MB
arm64v8/debian      stretch-slim        9cf0daa37223        8 days ago          50.6MB

wtf :P?

**Comment by CAM-TECH** [comment]
I've tried everything, debian, ubuntu, everywhere this problem occurs after changing files, this was not the case in previous versions. On raspberry pi is the same problem as on other devices, the dock does not try even after changing the font. The problem with nginx.


I tried to build my image on all linuxes, the problem is with nginx or it does the image as it will work and it has 700mb ... or 50mb after booting the dock is the same effect as in the case of file substitution, the dock does not start.

**Comment by ioppermann** [comment]
It is important that you build the docker image for aarch64 on a host that
also runs in aarch64 mode, that's why it is saying
"standard_init_linux.go:190: exec user process caused "exec format error""

You can send me your changed files and I will try to build an image from it
(for aarch64)

**Comment by CAM-TECH** [comment]
You have email

**Comment by ioppermann** [comment]
This problem could be solved by properly setting up the docker installation, e.g.:

```
sudo apt-get install docker-ce=18.03.1~ce-0~ubuntu
sudo systemctl enable docker
sudo systemctl start docker

# https://docs.docker.com/install/linux/linux-postinstall/
sudo groupadd docker
sudo usermod -aG docker $USER
```
