### ISSUE TITLE
Hls pull to srt

### ISSUE THREAD

**Issue by LuizStSantos** [datarhei/restreamer#701]
When I use the pull mode "http://ip/live/playlist.m3u8" with SRT output, the signal drops after a while
and it keeps crashing

my ffmpeg output

-c:v:0 h264_nvenc -aspect 16:9 -r:v:0 30 -b:v:0 4500k -maxrate:0 4500k -bufsize:0 4500k -profile:v:0 main -level 41 -delay 0 -ar:0 48000 -b:a:0 128k -c:a:0 aac -master_pl_name playlist.m3u8 -hls_flags append_list+omit_endlist+delete_segments -var_stream_map "v:0,a:0,name:1080p" -hls_segment_filename /usr/share/ffplayout/public/live/stream-%v-%05d.ts /usr/share/ffplayout/public/live/stream_%v.m3u8

Dell Power Edger T110 II server
Processor Intel® Xeon® E3-1220v2 3.10 GHz,
4GB of ECC RAM
SSD 120GB
OS: Debian 12 is already tried with Ubuntu 22.04
Docker version 25.0.3, build 4debf41

It only has Restreamer working on it

**Comment by ioppermann** [comment]
Please post the debug report and process report from Restreamer. Without any error messages it's hard to see what's going wrong.

Your encoding looks good so far. Two things to improve:

1. Add an expliscit GOP size. Usually 2-4 seconds is a good choice for HLS output: `-g:v:0 60`

2. It might be that HLS chunks get deleted before they have been read by Restreamer. Please try these additional options for the HLS muxer in your ffmpeg output: `-start_number 0 -hls_list_size 6 -hls_time 2 -hls_flags append_list+delete_segments+program_date_time+temp_file -hls_delete_threshold 4`
