### ISSUE TITLE
Could not select other audio stream than default one

### ISSUE THREAD

**Issue by AMP-VTV** [datarhei/restreamer#710]
Hi 👋

**Describe the bug**

It's not possible to select an audio stream other than the first one from a multi-audio tracks SRT stream.

**To Reproduce**

1. Edit a channel and click on the edit pencil of the "video settings" panel
2. Probe the SRT input stream
3. Select the video stream and cleck "NEXT:AUDIO"
4. Try to select the second audio stream
5. The selected audio stream stay on the first stream

**Expected behavior**
The second audio stream should be selected.

**Screenshots**

Selecting the 2nd audio stream:
![image](https://github.com/datarhei/restreamer/assets/16701096/a2328509-543c-4460-a895-7727d91911be)

After the selection:
![image](https://github.com/datarhei/restreamer/assets/16701096/b0a052e3-abef-4b33-ba93-2a50181bd142)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : tested on Chrome 123.0.6312.58 and Firefox 123.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone SE (3rd)
 - OS: iOS 17.4
 - Browser : Firefox 123.4 and Safari

**Additional context**
Input source is produced by ffmpeg: here are the streams : 

Output #0, tee, to '[f=mpegts]srt://123.123.123.123:6000?mode=caller&transtype=live&streamid=c400fb67-3729-433d-acf6-bbd1c093768a.stream,mode:publish&passphrase=#######################"':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(top coded first (swapped)), 1920x1080 (0x0) [SAR 1:1 DAR 16:9], q=2-31, 10000 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc60.3.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 10000000/0/10000000 buffer size: 20000000 vbv_delay: N/A
  Stream #0:1: Audio: aac (LC), 48000 Hz, stereo, fltp, delay 1024, 256 kb/s (default)
    Metadata:
      encoder         : Lavc60.3.100 aac
  Stream #0:2: Audio: aac (LC), 48000 Hz, stereo, fltp, delay 1024, 256 kb/s
    Metadata:
      encoder         : Lavc60.3.100 aac

**Comment by ioppermann** [comment]
This has been fixed in the `dev`-branch. You can try it out with the `datarhei/restreamer:dev` docker image.
