### ISSUE TITLE
How to call api prgrammatically without login or with Fixed token

### ISSUE THREAD

**Issue by amira133** [datarhei/restreamer#715]
Hi,
How to call api prgrammatically without login or with Fixed token.
I want to change the settings through another server, but currently, the received token may expire and cause me a lot of problems, is there a way to connect to the api with a fixed token or any other reasonable method?

**Comment by ioppermann** [comment]
You can use the refresh token in order to acquire a new access token. Alternatively you can disable the login in the config (`api.auth.enable: false`), however this is not recommended if your Restreamer is exposed to the public.
