### ISSUE TITLE
FFmpeg Error

### ISSUE THREAD

**Issue by nettraxx** [datarhei/restreamer#725]
**Describe the bug**
ERROR
This version of the UI doesn't support the available FFmpeg binary (6.1.1). The UI requires ^5.1.0. Please use a supported FFmpeg binary.

**To Reproduce**
1. docker ps
2. docker kill f1070d836766
3. docker rm f1070d836766
4. docker ps
5. docker pull datarhei/restreamer:latest
6. docker run -d --restart=always --name restreamer -v /opt/restreamer/config:/core/config -v /opt/restreamer/data:/core/data -p 8080:8080 -p 8181:8181 -p 1935:1935 -p 1936:1936 -p 6000:6000/udp datarhei/restreamer:latest

**Expected behavior**
after updating to the latest restreamer version 

**Screenshots**
[
![restreamer](https://github.com/datarhei/restreamer/assets/21067603/504f3147-2da3-4428-9aa6-accb634f4bc0)
](url)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04 on oracle free cloud
 - Browser chrome
 - Version 122.0.6261.129

**Comment by nettraxx** [comment]
Remedy: simply install FFmpeg

apt install ffmpeg

**Comment by ioppermann** [comment]
Your browser probably had still the old version of the UI in its cache. Emptying the cache should have solved the issue.
