### ISSUE TITLE
(Custom) Audio Configuration gets lost everytime I reconfig video

### ISSUE THREAD

**Issue by Zocker1999NET** [datarhei/restreamer#730]
**Describe the bug**
I have a stream where I receive the video from a webcam, but it has no audio. For testing purposes, I add a looping audio file to the stream. However, everytime after I reconfigure the video stream, the UI preselects "virtual source" and "silence".

**To Reproduce**
1. Configure a stream, video from somewhere but without audio attached, then as audio upload any file for looping it.
2. Save the settings & let Restreamer start that stream.
3. Go back to the settings of that stream.
4. Click on the cogwheel for configuring the video stream & accept taking the stream down
5. Click through the video stream (settings are remembered here) and on "Next: audio" (mind that directly clicking on "Save" is not possible)
6. On the audio page, see that the old settings were not fully remembered.
7. However, after clicking on "Loop" & re-uploading the audio file and clicking on "check", it seems to remember some settings.

**Expected behavior**
I would like it more if the UI would provide me to just keep the audio settings as is, especially as it feels tedious to re-upload the same audio file over & over again.

**Screenshots**

<details>
<summary>Details</summary>

These were the settings before (some data redacted for security reasons):
![grafik](https://github.com/datarhei/restreamer/assets/1645646/7f2abee6-5f64-405c-81f0-0faa42e3e025)

This is the audio configuration page, immediately after clicking on "Next: Audio".
![grafik](https://github.com/datarhei/restreamer/assets/1645646/a6342c9e-92a0-46bf-86b3-d5fd1f61db44)

After selecting "loop" & re-uploading the same loop file, the UI remembered the volume I set (marked with an red arrow):
![grafik](https://github.com/datarhei/restreamer/assets/1645646/1ec352ad-3f42-4fcb-9832-9b843db137a3)

</details>

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version 124

**Comment by ioppermann** [comment]
Yes, this is indeed an annoying bug. We will have a look at it.

**Comment by ioppermann** [comment]
This has been fixed in the latest release.
