### ISSUE TITLE
Docker restreamer enconding nvidia cuda

### ISSUE THREAD

**Issue by mo2o535** [datarhei/restreamer#732]
Hi, before anything, congratulations for this project, I love it!

I like encode video with GPU (nvidia serie 4x) for better performance.

I've run docker with --runtime nvidia parameter and docker boot well.

![Screenshot_20240416_110754](https://github.com/datarhei/restreamer/assets/3490784/80fdfa19-2ac6-400d-921d-428f089856cf)

When launch the docker restreamer:cuda-latest , it works but I can't see the GPU in the video hardware section

![Screenshot_20240416_110636](https://github.com/datarhei/restreamer/assets/3490784/6ee8f01c-7115-471a-a208-6fbd4bda0dbd)

Thanks in advanced.

**Comment by ioppermann** [comment]
In the video setup you are meant to select a video input device (ie. a video4linux device like a USB camera). In a later step you will be asked which encoder you want to use (if the input from video device is not H264). There you can select NVENC, the encoder that will use the GPU. If you switch to the "Advanced setup" you will have more options than in the wizard.

**Comment by maykel535** [comment]
Ok!! Now yes! Many thanks!
