### ISSUE TITLE
Developer/Core API documentation error

### ISSUE THREAD

**Issue by KevinBenjamin** [datarhei/restreamer#738]
**Subject of the issue**
When trying to navigate to the Developer/Core API link in the documentation, the page returns:
An error occurred
Sorry, an unexpected error has occurred. Please try again later.

**Your environment**
Chrome browser 

**Files**
No files

**Steps to reproduce**
Visit https://docs.datarhei.com/restreamer/api/api-and-developer

**Expected behavior**
Documentation displayed

**Actual behavior**
Page returns: An error occurred
Sorry, an unexpected error has occurred. Please try again later.

**Comment by ioppermann** [comment]
Thanks for pointing that out. It seems that there's some issue with gitbook. Please checkout the full docs at https://docs.datarhei.com/core

**Comment by SaganDanteGames** [comment]
@ioppermann How did you fix the error? I have the same problem. When I try to open Gitbook, the same message appears: "Sorry, an unexpected error has occurred. Please try again later."
