### ISSUE TITLE
URL Generation faulty in latest version of Restreamer

### ISSUE THREAD

**Issue by DJGummikuh** [datarhei/restreamer#740]
**Describe the bug**
When setting up a new RTMP Entry, the URL that is displayed where a stream should be directed to (for autodetection of video and such), the URL separates the token=xxxxx with a / where it should be a ?. 
Manually correcting the URL before plugging it into OBS works, but using the URL with / causes it to fail connecting.
Alternatively, in OBS you can ditch the /token=xxxxx part altogether and just enter the token as streamkey.

**To Reproduce**
1. Click on the Camera, then on + to add a channel
2. Enter a Name and Click Next
3. Select RTMP Server and Click Next
4. Check the URL that is provided for the Test, see that it uses / instead of ? for Separation

**Expected behavior**
The URl should use ? for separation between the resource and the token parameter, just as it has been in previous versions (this is a regression)

**Screenshots**
![image](https://github.com/datarhei/restreamer/assets/5188486/a52b61e1-4cc4-46af-9c26-c0babba3b019)

**Desktop (please complete the following information):**
 - OS: Linux, but irrelevant
 - Browser Firefox
 - Version 126.0b3 (64-bit)

**Smartphone (please complete the following information):**
not relevant

**Additional context**
None

## Business inquiries
**We provide support for commercial requirements with professional support, agile software development, and consulting.** If you have a commercial request, be it a bug or a feature enhancement, please contact us directly at support@datarhei.com.
No business inquiry

**Comment by ioppermann** [comment]
This has been fixed in the latest release from yesterday. Do a `docker pull datarhei/restreamer:latest` and restart the container. Also reload the UI in the browser.

**Comment by DJGummikuh** [comment]
Why u so fast? :rofl: 
can be closed, confirmed to work again :D
