### ISSUE TITLE
Stream processing even if no client is connected

### ISSUE THREAD

**Issue by cecchisandrone** [datarhei/restreamer#744]
**Subject of the issue**
Maybe I'm missing something but while using iftop I discovered that even if no client is connected to the playersite there is a constant 2MB/s bandwidth RX utilisation in the server. It is traffic sent from ip cameras to the server. In theory this should only happen if a client is connected and watching the stream, am I wrong?

**Your environment**
Raspberry PI 5 with dockerized datarhei-core v16.14.0 (linux/arm64)

**Comment by ioppermann** [comment]
This is true. Restreamer keeps pulling the stream from the camera even if there's nobody watching.

**Comment by cecchisandrone** [comment]
Is there a way to make this "on demand" to save processing/network resources?

**Comment by ioppermann** [comment]
Currently not. However, it is already on our [feature requests](https://github.com/datarhei/restreamer/discussions/345) list.

**Comment by NicoCaldo** [comment]
Has this feature been implemented?
