### ISSUE TITLE
Stream to multiple stream targets with different options but from the same input stream

### ISSUE THREAD

**Issue by saschafoerster** [datarhei/restreamer#76]
Is there a way to create a service like Restream.io but with Restreamer?

I understood, that you can create multiple dockers, but then the all have different ports, so I have to tell OBS to stream to different targets. I would like to tell OBS just stream to this address, then in restreamer I can orchestrate streams to YouTube, Periscope, etc. all in the perfect transcoding options independently to every network. Thanks for this great tool!

**Comment by ioppermann** [comment]
Hi Sascha

We are working on a new version of the Restreamer which is already in testing. For the current version of the Restreamer we have a feature freeze and will only add bug fixes. Please contact us at open@datarhei.org to discuss what we can do for you.

**Comment by danionescu2007** [comment]
Hello @ioppermann 

How can I get this test version to test it? Is it publicly available.
Thank you.

**Comment by mrpippali** [comment]
Hello @ioppermann

has the new version been released yet?

I'm hunting for something to do exactly this
