### ISSUE TITLE
no Audio when forcing HDMI Raspberry output

### ISSUE THREAD

**Issue by rcstreamer** [datarhei/restreamer#762]
Hi,
I followed the instruction to force HDMI Raspberry output via framebuffer with success but I got no audio :(

In the Frambuffer "source and encoding"  under the Audio section I get No audio in the Codec field and I can't change
Take a look to the img:
[no audio](https://github.com/datarhei/restreamer/assets/160222704/71ff0eab-0aeb-42f1-90c6-452c2f6d6b58)

It's strange with the other plattform I have no problems ...
Cam you help me ?

Best

**Comment by ioppermann** [comment]
The framebuffer publiction service supports only video.
