### ISSUE TITLE
¿alguna forma de poder sacar un panel de estadísticas para saber cuanta gente esta viéndolo?y tener un histórico por meses?

### ISSUE THREAD

**Issue by audiovisualfj** [datarhei/restreamer#764]
estoy probando la aplicación y muy contento con ella en como funciona, pero habría alguna forma de poder sacar un panel de estadísticas la cual nos de quién lo esta viendo y un histórico de varios dias e incluso meses?

Adjunto imagenes de una que estuvimos utilizando para tener una idea.
![ESTADISTIDAS](https://github.com/datarhei/restreamer/assets/166597767/ca90a184-ffdd-4c30-95f8-3e5875b2e7ca)

Muchas gracias.

**Comment by ioppermann** [comment]
Please write in English.
