### ISSUE TITLE
Clappr Stats

### ISSUE THREAD

**Issue by trgcyln** [datarhei/restreamer#77]
Hello,

Is there anyway to include clappr stats plugin into player ?

https://github.com/lucasrodcosta/clappr-nerd-stats

**Comment by ioppermann** [comment]
Hi

Thank you for your suggestion. We will look into that.

**Comment by ioppermann** [comment]
The stats have been added to the embeddable player in the latest release. You can enable the stats with the `stats=1` query parameter: https://datarhei.github.io/restreamer/docs/guides-embedding.html#statistics
