### ISSUE TITLE
On demand streaming

### ISSUE THREAD

**Issue by ofadam** [datarhei/restreamer#79]
Is there a way to have Restreamer only pull from the camera upon player initiation? This would help with bandwidth concerns.

**Comment by ioppermann** [comment]
Hi Adam

This is currently not implemented and not possible to achieve with the current Restreamer. We take it as a feature request.

**Comment by ma0dubois** [comment]
Hi,

Personally, for do this, i remote my docker host with my php application, so i can stop and start my restreamer containers

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback. The ticket is closed.
