### ISSUE TITLE
Add mute support to Clappr player for autoplay on Chrome

### ISSUE THREAD

**Issue by qsolutionsde** [datarhei/restreamer#80]
Chrome's autoplay policy can prevent autoplay (see https://developers.google.com/web/updates/2017/09/autoplay-policy-changes). 

It can be easily resolved (e.g., for IPCams where you mostly don't need audio anyway) by inserting `mute: true` to the Clappr code in `player.html`. Would be great if that could be enabled in a similar way to autoplay.

````js
    var mute= getQueryParam("mute", false);
    if(mute === "1" || mute === "true" || mute=== "yes" || mute === "on") {
        mute= true;
    }
    else {
        mute= false;
    }

    var player = new window.Clappr.Player({
        source: (window.location.protocol == 'https:' ? 'https:' : 'http:') + '//' + window.location.hostname + ':' + window.location.port + '/hls/live.stream.m3u8',
        parentId: '#player',
        baseUrl: '/libs/clappr/dist/',
        poster: 'images/live.jpg?t=' + String(new Date().getTime()),
        mediacontrol: {'seekbar': '#3daa48', 'buttons': '#3daa48'},
        height: '100%',
        width: '100%',
        mute: mute,
        disableCanAutoPlay: true,
        autoPlay: autoplay
    });
````

**Comment by ioppermann** [comment]
Thanks for the input. I added it to the master branch and it will be in the next official release.

**Comment by ioppermann** [comment]
The mute switch for the embeddable player is now included in the latest release.
