### ISSUE TITLE
Playersite website Camera Show Option

### ISSUE THREAD

**Issue by seejm** [datarhei/restreamer#800]
I have about 12 IP cameras running RTSP on my PlayerSite, but I only want to display 8 specific ones. Is there a way to choose which cameras are shown on the PlayerSite? If not, it would be a useful feature to add. You could include a checkbox option for each camera to allow or disallow it on the PlayerSite.

**Comment by ioppermann** [comment]
Thanks for the suggestion and it is already on the feature request list (#392)

**Comment by ioppermann** [comment]
This has been added in the latest release: https://github.com/datarhei/restreamer/releases/tag/v2.12.0
