### ISSUE TITLE
I am adding my audio setting via a network source(HLS) from azuracast and I get the following Probe Failed message... Please Help!

### ISSUE THREAD

**Issue by DarkRen420** [datarhei/restreamer#804]
**Subject of the issue**
Adding Network Source for Audio Source and getting failed probe message.

**Your environment**
I have Azuracast running on my Synology NAS DS225+ using container manager(docker) and Restreamer is also installed and running on my Synology NAS DS225+

**Files**
I do not have files.

**Steps to reproduce**
Using advance setup add loop video source from computer video.mp4 and that works after probe, then save, then audio setup next, and i am using my azuracast HLS HTTP site as the link, then I hit probe and it fails giving me the message below(In the Actual behavior section of this issue). I have looked for ways to set it to an open port but everything I try after probe fails.

**Awesome** ⭐⭐⭐⭐⭐
No Video Issues

**Expected behavior**
It should start broadcasting a looping video and looping playlist using Azuracast HLS HTTP so, I can then add it to YouTube channel and start broadcasting on youtube. I can't get that far cause audio source HLS HTTP fails probe and wont let me save and move to next step.

**Actual behavior**
This is the failed probe message I get when I probe my added network source audio HLS HTTP from Azuracast:

ffmpeg version 6.1.1-datahrei Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --extra-version=datahrei --prefix=/usr/local --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-vaapi --enable-libv4l2 --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-librav1e --disable-ffplay --disable-ffprobe --disable-debug --disable-doc
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[tcp @ 0x55900e11f940] Connection to tcp://azuracast.rendalli.synology.me:443 failed: Connection timed out
[in#0 @ 0x55900e11b480] Error opening input: Connection timed out
Error opening input file https://azuracast.rendalli.synology.me/hls/q105wuer/live.m3u8.
Error opening input files: Connection timed out

PLEASE HELP ME RESOLVE, Thank you!

**Comment by DarkRen420** [comment]
![Screenshot from 2024-08-24 15-51-59](https://github.com/user-attachments/assets/1d09b3cf-361f-4dd8-aeaa-3496dd55b03f)

**Comment by DarkRen420** [comment]
Now i am getting this failed probe:
ffmpeg version 6.1.1-datarhei Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.2.1 (Alpine 13.2.1_git20231014) 20231014
  configuration: --extra-version=datarhei --prefix=/usr --extra-libs='-lpthread -lxml2 -lm -lsupc++ -lstdc++ -lssl -lcrypto -lz -lc -ldl' --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-libv4l2 --enable-v4l2_m2m --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-librav1e --disable-ffplay --disable-debug --disable-doc --disable-shared
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[tcp @ 0x73e622636f00] Connection to tcp://azuracast.rendalli.synology.me:443 failed: Operation timed out
[in#0 @ 0x73e621bc7e40] Error opening input: Operation timed out
Error opening input file https://azuracast.rendalli.synology.me/hls/q105wuer/live.m3u8.
Error opening input files: Operation timed out

**Comment by DarkRen420** [comment]
It's been 11 days, and I have not received any help on my issue. Is there still support for restreamer or no?

**Comment by ioppermann** [comment]
Should the address `https://azuracast.rendalli.synology.me/hls/q105wuer/live.m3u8` be accessible publicly? I can ping the domain, but it's not possible to pull the azuracast stream.

**Comment by DarkRen420** [comment]
yes it is supposed to be publicly accessible, I am using a reverse proxy with my Synology NAS Server and DDNS any suggestions to make it publicly accessible?

**Comment by DarkRen420** [comment]
I tried using https://azuracast.rendalli.synology.me/listen/q105wuer/radio.mp3 but it also gives me the same message.

This is the message it gives me with that stream when I hit probe in Restreamer:

ffmpeg version 6.1.1-datahrei Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --extra-version=datahrei --prefix=/usr/local --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-vaapi --enable-libv4l2 --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-librav1e --disable-ffplay --disable-ffprobe --disable-debug --disable-doc
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[tcp @ 0x55dae9dcc940] Connection to tcp://azuracast.rendalli.synology.me:443 failed: Connection timed out
[in#0 @ 0x55dae9dc8480] Error opening input: Connection timed out
Error opening input file https://azuracast.rendalli.synology.me/listen/q105wuer/radio.mp3.
Error opening input files: Connection timed out

**Comment by ioppermann** [comment]
I can access the `.mp3` URL and listen to the stream. The problem might be that Restreamer runs on the same Synology as the Azuracast. When providing the URL `https://azuracast.rendalli.synology.me/listen/q105wuer/radio.mp3` it actually tries to access itself with the public IP. Please try to replace the domain `azuracast.rendalli.synology.me` with the local IP of the Synology when entering it into Restreamer, e.g. `https://192.168.1.42/listen/q105wuer/radio.mp3` (or whatever the local IP is).

**Comment by DarkRen420** [comment]
ffmpeg version 6.1.1-datahrei Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --extra-version=datahrei --prefix=/usr/local --enable-nonfree --enable-gpl --enable-version3 --enable-postproc --enable-static --enable-openssl --enable-libxml2 --enable-vaapi --enable-libv4l2 --enable-libfreetype --enable-alsa --enable-libsrt --enable-libx264 --enable-libx265 --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libdav1d --enable-librav1e --disable-ffplay --disable-ffprobe --disable-debug --disable-doc
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[tcp @ 0x560629395280] Connection to tcp://SynologyIP failed: Connection timed out
[in#0 @ 0x560629391480] Error opening input: Connection timed out
Error opening input file http://SynologyIP/listen/q105wuer/radio.mp3.
Error opening input files: Connection timed out

I tried what you suggested and get this message after probe. **I blocked out my IP and replaced it with SynologyIP for security reasons** Please help me with this? Am I going to have to use a VM for Restreamer or something like that?

**Comment by DarkRen420** [comment]
I figured it out... I created a vm on my synology NAS, just to run Restreamer, and it works. I am now officially a 24/7 youtube radio DJ. Woohoo! Thanks for your support, it lead me to the ephiany that solved my problem.

You can close this issue... Thanks!

**Comment by ioppermann** [comment]
Great that it works now. Have fun!
