### ISSUE TITLE
 Number of simultaneous SRT viewers

### ISSUE THREAD

**Issue by JonnyTech** [datarhei/restreamer#808]
Hopefully a simple question, but I cannot find anything in the documentation: How many simultaneous client connections can view the SRT stream?

On a local-only Ethernet network with several devices and no other network traffic, I want to stream a SRT source to many connected SRT clients (VLC, ffplay, OBS, etc).

Is there a maximum number of simultaneous connections that the Restreamer supports?

**Comment by ioppermann** [comment]
The number of simultaneous SRT connections is mainly limited by the available bandwidth. The SRT uses some CPU for each connection. Depending on the CPU power of the box where Restreamer is running on, it might be limited by the available CPU.

On a Raspberry Pi 4b you could easily handle 50+ simultaneous SRT connections (not considering the bandwidth).

**Comment by JonnyTech** [comment]
Thank you, I was able to stream to 50 devices with no issue.
