### ISSUE TITLE
Use port 80 and 443 as default port

### ISSUE THREAD

**Issue by astro-com-my** [datarhei/restreamer#811]
Hi, is it possible if i use port 80 and 443 instead of 8080 and 8181 as the port?

**Comment by ioppermann** [comment]
Yes. You can simply modify the port mapping in the docker command accordingly. Instead of `-p 8080:8080 -p 8181:8181` you use `-p 80:8080 -p 443:8181`.

**Comment by astro-com-my** [comment]
> Yes. You can simply modify the port mapping in the docker command accordingly. Instead of `-p 8080:8080 -p 8181:8181` you use `-p 80:8080 -p 443:8181`.

I will try, thanks for the help.
