### ISSUE TITLE
FFmpeg 5 or 7 ?

### ISSUE THREAD

**Issue by gedw99** [datarhei/restreamer#815]
Hey @ioppermann 

what version are you supporting now ? I think its v5 still ?

https://github.com/asticode/go-astiav is up to V7 now btw. Its a decent overlay of ffmpeg with cgo.

**Comment by ioppermann** [comment]
Restreamer is currently using FFmpeg 6.1.1. As soon as 7.1 will be out (probably in a few weeks), we plan to switch to FFmpeg 7.1.

go-astiav is a Go binding to the various `libav*` libraries from FFmpeg. Restreamer (resp. https://github.com/datarhei/core) is not a binding to the libraries, but calls the `ffmpeg` binary via a HTTP API. With this you can use any FFmpeg version that is most suitable to you.

**Comment by ioppermann** [comment]
We're waiting for FFmpeg 7.1

If you're using Windows you can run a Docker container with Linux in it as well.
