### ISSUE TITLE
Overlay  image in youtube stream

### ISSUE THREAD

**Issue by dbradica** [datarhei/restreamer#83]
Is there any ability to embed image/logo to youtube stream?

**Comment by ioppermann** [comment]
Hi

Currently this is not possible. The Restreamer is not re-encoding the stream, it is only forwarding it as-is (audio may get re-encoded depending on the `RS_AUDIO` setting). Re-encoding may require significant CPU/GPU resources.

Re-encoding is planned for the future.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
