### ISSUE TITLE
How do i get a stream key for rtmp server?

### ISSUE THREAD

**Issue by ewczzz** [datarhei/restreamer#842]
-I have 1 pc for everything.
-I'm trying to change OBS for Meld Studio, its a software for streaming on Kick , Twitch, Yt,etc.
-Meld Studio force me, to have a stream key for streaming.

**Comment by ioppermann** [comment]
The streamkey is the last path element of the provided RTMP URL. For example, if Restreamer provided you with this URL: `rtmp://192.168.1.154/live/b8e70b8b-ee0f-4989-be71-0120f32b55a3.stream/foobar` then `foobar` is the stream key.

**Comment by ewczzz** [comment]
Thanks you. It worked.
