### ISSUE TITLE
rtsp h265 stream > restreamer > h264 rtsp

### ISSUE THREAD

**Issue by levski** [datarhei/restreamer#862]
**Subject of the issue**
i'm trying to do exactly what the title says.
just need to transcode the rtsp stream and restream it as an rtsp but can't seem to figure out how to do that.
i got as far as Add Publication > RTSP
can't seem to figure out what to do with the General page. tried some ips on the address section but can't seem to access it with that. i gather this page basically tells restreamer to send the rtsp to the ip address i put in that section.

**Your environment**
docker on debian 12 with nvidia hardware acceleration working

**Files**
![Screenshot from 2024-12-19 05-02-43](https://github.com/user-attachments/assets/d3c951c7-8158-4f76-a33d-1da6b74f6804)
![Screenshot from 2024-12-19 05-02-01](https://github.com/user-attachments/assets/77b42261-eeac-4d79-98d9-22a322ecadef)

**Expected behavior**
am not sure if restreamer supports the use-case i have in mind

**Comment by ioppermann** [comment]
Your specific use-case might not be covered out-of-the-box by Restreamer. Transcoding the H265 stream to H264 is working for you. The publication services are for sending the stream somewhere. This means that the RTSP publication service expects you to send the transcoded stream to some RTSP server, and not that it will start a RTSP server by itself. Restreamer has only a RTMP and SRT server build-in.

**Comment by levski** [comment]
That was what i figured after reading the docs and some googling.Thanks for confirming. I’ll close the thread once i get on my laptop.On Dec 19, 2024, at 7:02 PM, Ingo Oppermann ***@***.***> wrote:﻿
Your specific use-case might not be covered out-of-the-box by Restreamer. Transcoding the H265 stream to H264 is working for you. The publication services are for sending the stream somewhere. This means that the RTSP publication service expects you to send the transcoded stream to some RTSP server, and not that it will start a RTSP server by itself. Restreamer has only a RTMP and SRT server build-in.
