### ISSUE TITLE
Docker logging causing undue wear of SD Card

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [datarhei/restreamer#87]
Hi,

Just worked out that Docker is doing a lot of logging to your SD card by default as well.  This also causes undue wear of SD cards in Raspberrys.

Good idea to change logging.

Either set --log-driver to none (so no logging), or --if syslog is written to a tempfs -- set it to use syslog.

Cmd line either 
```
docker run -d --restart always --name restreamer --log-driver none ..... etc etc
```
or 
```
docker run -d --restart always --name restreamer --log-driver syslog  .... etc etc
```

**Comment by ioppermann** [comment]
Hi

Thanks for the hint. Is this, what Docker is logging, specific to Restreamer? In case you want to silence the log output of Restreamer you can set the environment variable `RS_LOGLEVEL` to `0`.

**Comment by TheOriginalMrWolf** [comment]
No -- it's general docker logging.  Set log-driver to syslog to see in syslog.  You can also check out "docker logs restreamer"

**Comment by ioppermann** [comment]
I will incorporate this as well in the documentation.

**Comment by ioppermann** [comment]
I added an extra page regarding this topic: https://datarhei.github.io/restreamer/docs/guides-sdcard.html
