### ISSUE TITLE
Verify if stream is alive?

### ISSUE THREAD

**Issue by scottgrobinson** [datarhei/restreamer#88]
Hello!

I have a little 'status check' script that checks that my restreamer docker images are up and running. I just look for <title>Restreamer</title> on the correct port via HTTP.

I'd like to try and check the stream is acctually running aswell. Is there any sort of hidden backend API or similar that can confirm that the stream is running? I'd like to avoid having to use a library to pull frames from the m3u8/TS and verifying that a video is there! :)

**Comment by ioppermann** [comment]
Hi

You can check the Restreamer API: https://datarhei.github.io/restreamer/docs/references-http-api.html

This may cover your needs.

**Comment by scottgrobinson** [comment]
Yes :)

I will use the /v1/progresses API to verify current_kbps or similar.

Thanks very much!!
