### ISSUE TITLE
Some kind of protection on player.html

### ISSUE THREAD

**Issue by chwong1** [datarhei/restreamer#89]
Do you have any suggestion on how to protect anonymous user to get the video stream?

**Comment by ioppermann** [comment]
Hi

Currently this is not implemented in Restreamer. For now, you could solve this by having an e.g. nginx in front of Restreamer.

**Comment by ioppermann** [comment]
With the latest version of Restreamer, it is now easier to put it behind a nginx (or any other webserver that allow proxying). The documentation gives some examples: https://datarhei.github.io/restreamer/docs/guides-proxying.html
