### ISSUE TITLE
Possible to get a rtsp stream? 

### ISSUE THREAD

**Issue by rmarinho** [datarhei/restreamer#92]
I was wondering if there was a easy way to get a rtsp stream locally  I could use to hook up to [HomeAssistant camera stream source](https://www.home-assistant.io/components/generic/#stream_source). right now restreamer is working great and a good solution to run on jessie with HOmeAssistant using docker. Using the fixed image also works with HomeAssistant right now, but I would love to integrate the live stream. 

Or anyone can give me some inside how I could set that up.

Thanks

**Comment by ioppermann** [comment]
Hi

It is not possible to pull the stream from Restreamer with RTSP. Only HLS and RTMP (with some additional configuration) are possible. Please try to use HLS URL (http://[address or IP and port of your Restreamer]/hls/live.stream.m3u8) as value for `stream_source` in your Home Assistant.

**Comment by rmarinho** [comment]
thanks, that got the job done. I might need to tweak the config a little bit since everything is running on the raspberry pi and the stream is delayed a bit. 

here's the config I used on homeassistant. 

   ```
 - platform: generic
      name: remoteRPiCam
      still_image_url: !secret rpi_url
      stream_source: !secret rpi_url_stream
      verify_ssl: false


    rpi_url: http://192.168.1.249:8080/images/live.jpg
    rpi_url_stream: http://192.168.1.249:8080/hls/live.stream.m3u8
```

**Comment by ioppermann** [comment]
The delay is probably because of the HLS. It is buffered in the Restreamer for a few seconds.
