### ISSUE TITLE
Restreamer Poor sound quality on RTMP

### ISSUE THREAD

**Issue by oskar601** [datarhei/restreamer#93]
Good day.
I have recently been a raspberry pi 3 b + user. I really liked your program, which I installed as described at https://datarhei.github.io/restreamer/
My problem is that I type "RTSP video source" and everything is fine.
And when I stream to "the optimal source for Youtube RTMP, the sound quality is very bad. Please help. Regards, Oscar

**Comment by ioppermann** [comment]
Hi Oscar

How is the sound quality directly at the RTSP source? If it is bad already there then you have to check if you can improve the quality at the source.

Do you use a specific setting for the `RS_AUDIO` environment variable? By default Restreamer will try to simply copy the audio unmodified. However, if the audio codec is not compatible, it gets re-encoded to AAC with a bitrate of 64k.

**Comment by oskar601** [comment]
Hello.

Please check live now.

http://109.197.168.53:8093/player.html here the sound is ok.

https://www.youtube.com/channel/UCq3PoKsC98SoM4crhXisvjg here the sound is bad - the flow

Yes, I have entered:
docker run -d --restart always \
     --name restreamer \
     -e "RS_USERNAME=..." -e "RS_PASSWORD=..." \
     -e „RS_AUDIO=aac” \
     -p 8080:8093 -v /mnt/restreamer/db:/restreamer/db \
     --tmpfs /tmp/hls \
     datarhei/restreamer-armv7l:latest

Camera settings:
Encode mode AAC
Samplink Frequency 32

As I will give a bitrate of 64k it's not a picture in a restreamer.

greetings...

**Comment by ioppermann** [comment]
HI Oscar

Thanks. This all looks OK. If the sound is OK in the player.html then it should be the same on Youtube. The Restreamer sends the same stream that is used for the player.html unmodified to Youtube. So maybe Youtube is messing something up.

If your camera is already delivering the audio as AAC, then you could set the value for `RS_AUDIO` to `auto`. This will simply copy the audio stream unmodified without re-encoding it.

I checked the links that you provided, but unfortunately it was silent anyways. Is there a schedule when there will be a mass, so there is actually something to hear?

**Comment by oskar601** [comment]
Hello
Holy mass today 03/05/2019 at 4.30 pm Polish time.
On Saturday, the Holy Mass is at 7.00 am and 6.00 pm in the evening

I tried on two YouTube accounts and two computers
and it's the same: double sound, echo.
I set the RS_AUDIO value on the auto and without any improvement.

And if I turn on the same stream through OBS studio, it works correctly.

Any suggestions ? Any hint?
Greetings

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

pt., 3 maj 2019 o 14:45 Ingo Oppermann <notifications@github.com>
napisał(a):

**Comment by ioppermann** [comment]
Can you please reactivate the stream? I wasn't able to fully test all settings.

**Comment by oskar601** [comment]
https://www.youtube.com/user/tvnieglowice
http://192.168.0.10:8093/player.html

**Comment by oskar601** [comment]
http://109.197.168.53:8093/player.html
https://www.youtube.com/user/tvnieglowice

**Comment by oskar601** [comment]
Rather, I'd rather youtube for streaming. Will the restreamer be modified, upgraded to the youtube service?

Regards, Oscar

**Comment by ioppermann** [comment]
Yes, it is the goal to work with Youtube. Others that also stream to Youtube with Restreamer don't report such issues.

It depends on the input data from e.g. an IP camera. If the timestamps that keep audio and video in sync are not very "clean", then it might have some problems. How to address this is under constant investigation.

**Comment by oskar601** [comment]
Ok thank you for help.

**Comment by arni7** [comment]
I have exactly the same problem, it seems to me that the reason is the camera stream I have Dahua and you Oscar?
Arek

**Comment by arni7** [comment]
Interestingly, as the material will be recorded by youtube, then when playing the sound is correct

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
