### ISSUE TITLE
NGINX error with h264 streams

### ISSUE THREAD

**Issue by kevsfastz** [datarhei/restreamer#94]
I am not sure if this is a bug or if I am missing something, but I am having issues streaming from one of my sources. I am able to successfully stream directly from my REOLINK camera with the below RTSP link:
`rtsp://username:password@192.168.0.10:554/h264Preview_01_main`

But when I try to stream the below link from Blue Iris:
`http://username:password@192.168.0.4:81/h264/WC/temp.h264`

I receive the following error:
`[ERROR] [                 NGINX] failed (2: No such file or directory), client: 192.168.0.100, server: , request: "GET /hls/live.stream.m3u8 HTTP/1.1", host: "192.168.0.8:8080", referrer: "http://192.168.0.8:8080/"`

Both addresses stream successfully in VLC. Are there any other logs that I can provide to help troubleshoot?

**Comment by ioppermann** [comment]
Restreamer requires a RTSP, RTMP, or HLS source. Please check the manual if the Blue Iris supports any of those streaming protocols.

Depending on the model of your Blue Iris camera, you might try `http://username:password@192.168.0.4:81/h264/WC/temp.m` or `http://username:password@192.168.0.4:81/h264/WC/temp.m3u8` as source URL.

**Comment by ioppermann** [comment]
You can also try to start Restreamer with `-e RS_LOGLEVEL=4` on the docker command line, e.g. `docker run ... -e RS_LOGLEVEL=4 ...` and to observe the log output for error messages from ffmpeg when you press the "start" button.

**Comment by ioppermann** [comment]
You're welcome.
