### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#95]
Is there a way for being informed when the stream goes down?
YouTube doesn't seem to offer a notification when streaming source doesn't send data anymore.
What would be best practice?

**Comment by ioppermann** [comment]
Restreamer provides an API where you can poll the current state of the incoming and outgoing stream. Have a look at https://datarhei.github.io/restreamer/docs/references-http-api.html

`/v1/states` and/or `/v1/progresses` would be useful in your case. If your Restreamer is running on `http://12.34.56.78:8080/`, then accessing the API would be `http://12.34.56.78:8080/v1/states`.

**Comment by strarsis** [comment]
@ioppermann: It would be even more awesome if pub/sub could be added to the restreamer REST API so a 
little microservice (e.g. nodejs/monitoring script on some port like 9091) can be directly informed so an email / notification can be send?

**Comment by ioppermann** [comment]
Do you mean some kind of webhook that gets notified as soon as a state changes, e.g. by a JSON message?

**Comment by strarsis** [comment]
@ioppermann: Yes! This would remove the polling part.

**Comment by advantix78** [comment]
Per Ora sono riuscito a sviluppare questo oggi pomeriggio,
in questi giorni cercherò di creare un bot telegram che invia notifiche sullo stato.
![dashboard](https://user-images.githubusercontent.com/40419553/78062182-90cb1500-738e-11ea-94ef-99e604e3e027.png)

**Comment by strarsis** [comment]
Translation of post from @advantix78 from Italian to English:

> For Now I was able to develop this afternoon,
> I' m going to try to create a telegram bot these days that sends status notifications.
([deepl.com](https://www.deepl.com/))

**Comment by ioppermann** [comment]
@advantix78 This is awesome! Is it possible that you share it?

**Comment by advantix78** [comment]
Vorrei Finire di configurarlo e poi magari cercherò di condividerlo in modo che tutti lo possano usare.
Ovviamente il mio sistema funziona con appositi presupposti, quindi dovrei implementare con una premessa.
![Annotazione 2020-04-01 123134](https://user-images.githubusercontent.com/40419553/78127629-ce728100-7414-11ea-9336-f3dc40542b5b.png)

**Comment by strarsis** [comment]
Hm, streaming stats for Prometheus and event logs for Logstash would also be nice because I can feed that data into my existing ELK/Monitoring stack.

**Comment by advantix78** [comment]
> @ advantix78 Questo è fantastico! È possibile che tu lo condivida?

DashBoard API Restreamer

Si presuppone di avere un server dove è instalato NodeRed oppure da testare se installarlo
sulla stessa macchina dove è installato Restreamer
che sia esso Raspberry Cloud ecc.

I Nodi sono dei semplici http request code in method GET con URL del server restreamer con finale /API

/v1/ip
/v1/statex
ecc.. ecc..

Dopodichè un nodo change per spostare il msg.payload.xxxxxxxx a msg.payload

seguito da un nodo dashboard che puo essere un semplice testo o un grafico ecc ecc.

Mi risulta complesso al momento fare un tutorial in quanto ho creato questa dashboard
appositamente per il mio caso. il mio server NodeREd si trova a casa su un Orange Pi 0.

Per chi mastica gia Node REd può prendere spunto da questa immagine
![Annotazione 2020-04-05 174600](https://user-images.githubusercontent.com/40419553/78503189-63eb7900-7765-11ea-927a-52f38ab0d52e.png)

**Comment by Pimmetje** [comment]
I am running the dev release. But i have a feeling the API doc (https://docs.datarhei.com/restreamer/api/api-and-developer) are out of sync with the version i am running at least. 
I get a lot of the following responses:
```
{
    "code": 404,
    "message": "Not Found",
    "details": [
        "Not Found"
    ]
}
```

I am looking for a way to get the state of all the streams.. So i can monitor them for issues.

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
