### ISSUE TITLE
Placeholder image/video

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#96]
When a YouTube Livestream is offline for a too long time, YouTube archives the stream and a completely new stream has to be created (which changes the ID/URL and with it all bookmarks and embeds).

Can restreamer send a placeholder (still) image or replacement video while the input stream (camera) is offline so the stream can be kept open? Like "our webcam is down and we are checking it right now" still image?

**Comment by ssamjh** [comment]
👍 Could be really useful!

**Comment by advantix78** [comment]
Seguo questa Funzionalita, molto utile

**Comment by qriff** [comment]
To clarify, Youtube live stream of type Unlisted ("Anyone with the link can view") gets archived soon as the encoder is not receiving a constant flow of data (under 60s). After which the stream URL gets reset, and the viewers need to attain the new URL from you (it is unlisted after all). Currently between popular relaying solutions none provide this functionality and is generally only obtainable by running another OBS Studio as a cloud instance relay (OBS -> OBS -> Youtube vs OBS -> Restreamer -> Youtube) .

https://support.google.com/youtube/answer/9854503

**Comment by svenerbeck** [comment]
Hello 

We have converted the request into a feature request. Follow the discussion  https://github.com/datarhei/restreamer/discussions/345#discussion-4108562 to stay current, and see when your feature becomes active.  

Please appreciate it if we only implement some features, which may take some time. 

We are closing this issue.

Cheerio 
Sven
