### ISSUE TITLE
Restreamer errors out after 24-36 hours 

### ISSUE THREAD

**Issue by kevsfastz** [datarhei/restreamer#97]
I have been using Restreamer for my website for the past few weeks and noticed every 24-36 hours I receive an `Error Code: hls:4`. When I STOP and START the stream it will fix the issue. This happened on the current version 4.0 and the previous version. 

This is the URL I use from Blue Iris:
`http://username:password@192.168.0.4:81/h264/WC/temp.m`

And the logs:
[restreamer logs.txt](https://github.com/datarhei/restreamer/files/3208265/restreamer.logs.txt)

**Comment by ioppermann** [comment]
In the logs I see that the Restreamer is restarting to pull the stream from the camera around line 915 and it tries to reconnect at `21-05-2019 07:30:47.429` and `21-05-2019 07:31:25.500`. This may be the problem as Restreamer should only try once to reconnect. It looks like that the stream is pulled twice at the same time. This would explain why you get the `Error Code: hls:4` error. I will investigate this.

Is your camera automatically restarting e.g. every day or so?

**Comment by kevsfastz** [comment]
I just verified the ReoLink and BueIris settings and nothing is currently configured to restart the camera. Is this something I should enable? 

I will monitor the uptime of the camera to see if it is losing connectivity at any point and cross references with the restreamer logs.

**Comment by kevsfastz** [comment]
Just an update, I have been monitoring the camera and blue iris server and I do not see any correlation with the restreamer logs. I did, however, temporarily resolve this issue by performing a nightly restart on the Ubuntu VM where restreamer is running.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
