### ISSUE TITLE
command for start/stop streaming

### ISSUE THREAD

**Issue by federicobalm** [datarhei/restreamer#98]
Hello!
Is there any way to run the "start / stop" buttons from linux console?.
I can only stop the restramer service with "docker stop stream01", but what I really want to do is stop or start the rtmp transmission, without it being necessary to stop the container service.

there are times I want to stop only the transmission option to an rtmp server but I would like to do it remotely since I have access only by ssh to the host that runs restreamer.

**Comment by ioppermann** [comment]
Hi Federico

Currently there‘s no other way to start or stop a stream than using the web interface or by using the docker run/stop command. I will put it on the feature request list.

**Comment by federicobalm** [comment]
Ok, thank you for your answer. It would be interesting that at least there is a script in phyton or bash to perform this action.
Thanks for the project!

**Comment by federicobalm** [comment]
Ok, thank you for your answer. It would be interesting that at least there is a script in phyton or bash to perform this action.
Thanks for the project!

**Comment by matigumma** [comment]
i made my own litle control panel (html) to start/stop/add/delete restreams (i did it for restreamer-edge)
if you this it is useful i can share it

**Comment by ioppermann** [comment]
@matigumma Yes, this might be useful. Please feel free to share it. Thanks.

**Comment by federicobalm** [comment]
> Hice mi propio panel de control de litle (html) para iniciar / detener / agregar / eliminar retransmisiones (lo hice para restreamer-edge) 
> si crees que esto es útil puedo compartirlo

It would be very interesting to know your panel.

**Comment by matigumma** [comment]
i will give you here a little intro to what i implement,, 
to restreamer-edge image i add (using console) some things...
+php-fpm7
+jq
+curl (dont rememmber if this is included by default)
-
idea:
*html panel
--load / create a list (json) file with name, source, status of each cam 
--with a js call using ajax to modify json list

this status.json is the file that contains the instruction to on/off each cam.

additionally need to run a background script to read this status and execute , that i called 
centinel.sh

while true{
do
foreach (cam in status.json) {
 if (cam.status == on) {
  if (cam.name is in http://127.0.0.1/rtmp-stat.json ) {
  //   its working (here i made some things like log status, take snapshot
   }else{ 
  // camera is not working and try to run the script (play.sh cam.name ) that try to play it again
   }
}else{
  //cam must be turned of...
  // here i implement a kill -9 signal with the pid (i have stored that when ran the play script)
  //logs and other things
}
sleep 120 // 2 mins for me to check status and act again
done

play.sh 

get name pass as arguments 
get cam.source from status.json
exec ffmpeg script with -i cam.source ...
log


this week end will share full code

**Comment by federicobalm** [comment]
Hello, could someone have any progress with a script to start and stop the transmission by rtmp?

**Comment by divx118** [comment]
@federicobalm 
I have added some code to the api to accomplish this https://github.com/datarhei/restreamer/blob/master/src/webserver/controllers/api/v1.js

```javascript
router.get('/stop', (req, res) => {
    const url = require.main.require('./classes/Restreamer').data.addresses.srcAddress;
    const userActions = require.main.require('./classes/Restreamer').data.userActions;

    require.main.require('./classes/Restreamer').data.userActions.repeatToLocalNginx = "stop";
    require.main.require('./classes/Restreamer').writeToDB();
    require.main.require('./classes/Restreamer').stopStream("repeatToLocalNginx");
    require.main.require('./classes/Restreamer').updateState('repeatToLocalNginx', 'disconnected');
    
    res.json({
        'repeat_to_local_nginx': userActions.repeatToLocalNginx
    });
});
router.get('/start', (req, res) => {
    const url = require.main.require('./classes/Restreamer').data.addresses.srcAddress;
    const userActions = require.main.require('./classes/Restreamer').data.userActions;

    require.main.require('./classes/Restreamer').data.userActions.repeatToLocalNginx = "start";
    require.main.require('./classes/Restreamer').writeToDB();  
    require.main.require('./classes/Restreamer').startStream(url,"repeatToLocalNginx",true);
    
    res.json({
        'repeat_to_local_nginx': userActions.repeatToLocalNginx
    });
});
```
Then I use an xmlhttp rquest in my local website to start stop encoding http://myip:port/v1/stop Note that this is a rough method, no checks included if it really starts or stops. Also I use it only on my internal network so I didn't check for any underlying security risks. First time I ever worked with node js, so there can be some things I overlooked.

**Comment by ma0dubois** [comment]
Hi all,

Personally i prefer to use POST for start and stop:

```javascript
router.post('/stop', function (req, res) {
    // update the last submitted user action & write to DB & update the data on Gui
    require.main.require('./classes/Restreamer').updateUserAction('repeatToLocalNginx', 'stop');
    //update the state and stop the signal
    res.end(require.main.require('./classes/Restreamer').stopStream('repeatToLocalNginx'));
});
router.post('/start', function (req, res) {
    // update the last submitted user action & write to DB & update the data on Gui
    require.main.require('./classes/Restreamer').updateUserAction('repeatToLocalNginx', 'start');
    res.end(
        require.main.require('./classes/Restreamer').startStream(
            require.main.require('./classes/Restreamer').data.addresses.srcAddress,
            'repeatToLocalNginx',
            true
        )
    );
});
```

**Comment by divx118** [comment]
@ma0dubois Yes, I agree indeed the best and most logical way is to use post. :)

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.

**Comment by RFDarter** [comment]
> Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀 Have fun with it.

I can not find any documentation on this. Can you point me in the right direction?
Since schedule restreams is not implemented yet i would like to start and stop a restream via the command line
